### ISSUE TITLE
automatic width with body_add_flextable 

### ISSUE THREAD

**Issue by eusebe** [davidgohel/flextable#10]
Hi, 

Perhaps this issue should be reported in the officer repository. Sorry if it is.

With ReporteRs, FlexTable objects were always inserted with a width that do not exceed the width of the docx document. Is it possible to have the same behavior with officer/flextable workflow? 

Example:
```r

library(officer)
ft <- flextable(head(data.frame(cbind(mtcars, mtcars, mtcars))))
doc <- read_docx()
doc <- body_add_flextable(doc, value = ft)
print(doc, target = "test_officer.docx")


library(ReporteRs)
ft <- FlexTable(head(data.frame(cbind(mtcars, mtcars, mtcars))))
doc <- docx()
doc <- addFlexTable(doc, ft)
writeDoc(doc, file = "test2_reporters.docx")
```

Best, 
David
[test_officer.docx](https://github.com/davidgohel/flextable/files/902333/test_officer.docx)
[test_reporters.docx](https://github.com/davidgohel/flextable/files/902332/test_reporters.docx)

**Comment by davidgohel** [comment]
Officer offers is slightly different approach. You can `autofit` or control the width and heights:

https://davidgohel.github.io/flextable/articles/layout.html#cell-widths-and-heights

There are missing functions to get page and margins dimensions, they are coming soon...

**Comment by eusebe** [comment]
Great!
David

**Comment by davidgohel** [comment]
Hi

I have implemented `docx_dim` in `officer`, it returns current page dimensions. From that and by using `flextable::width()` you should be able to fit the flextable to the width of the page. 

I don't have any decent solution to implement `fit_to_windows` function, I am leaving that to the charge of the user for now...

David

**Comment by eusebe** [comment]
Thanks!
What is the unit of the width returned by docx_dim? Inches?

David

**Comment by davidgohel** [comment]
@eusebe It's inch/914400, this is a mistake... I will modify that to get only inches
