### ISSUE TITLE
Problems with horizontal borders if cells are merged

### ISSUE THREAD

**Issue by lcougnaud** [davidgohel/flextable#106]
I noticed some issue to include horizontal border in case the cells are merged.

The line is correctly included if the cells are not merged:
```{r}
data <- data.frame(class = rep(LETTERS[1:4], each = 2), i = 1:8)
ft <- flextable(data) %>% border_remove
ft <- ft %>% hline_bottom(border = fp_border(color = "black"), part = "body") # only include horizontal line at the bottom
```
![flextable_issuehline1](https://user-images.githubusercontent.com/15339154/53418918-1be21a80-39d9-11e9-873d-86ffacdaa986.png)
But the line disappear if the cells of the first column are merged:
```{r}
ft <- ft %>% merge_v(j = 1)
```
![flextable_issuehline2](https://user-images.githubusercontent.com/15339154/53419025-521f9a00-39d9-11e9-85b5-de36a9541321.png)

R version 3.5.1 (2018-07-02)

 Platform: x86_64-pc-linux-gnu (64-bit)

 Running under: Ubuntu 16.04.5 LTS

 Matrix products: default

 BLAS: /usr/lib/libblas/libblas.so.3.6.0

 LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

 * locale:
 LC_ADDRESS=en_GB.UTF-8, LC_COLLATE=en_US.UTF-8, LC_CTYPE=en_US.UTF-8, LC_IDENTIFICATION=en_GB.UTF-8, LC_MEASUREMENT=en_GB.UTF-8, LC_MESSAGES=en_US.UTF-8, LC_MONETARY=en_GB.UTF-8, LC_NAME=en_GB.UTF-8, LC_NUMERIC=C, LC_PAPER=en_GB.UTF-8, LC_TELEPHONE=en_GB.UTF-8, LC_TIME=en_GB.UTF-8

 * attached base packages:
 base, datasets, graphics, grDevices, methods, stats, utils

 * other attached packages:
 bindrcpp_0.2.2, dplyr_0.7.7, flextable_0.5.1, knitr_1.20, magrittr_1.5, officer_0.3.2, pander_0.6.2, plyr_1.8.4, rj_3.0.0-13

 * loaded via a namespace (and not attached):
 assertthat_0.2.0, base64enc_0.1-3, bindr_0.1.1, bookdown_0.7, cli_1.0.1, colorspace_1.3-2, compiler_3.5.1, cowplot_0.9.99, crayon_1.3.4, data.table_1.11.8, digest_0.6.18, evaluate_0.11, fansi_0.4.0, forcats_0.3.0, gdtools_0.1.7, ggplot2_3.1.0, ggrepel_0.8.0, glue_1.3.0, grid_3.5.1, gtable_0.2.0, haven_2.0.0, hms_0.4.2, htmltools_0.3.6, labeling_0.3, lazyeval_0.2.1, magick_2.0, munsell_0.5.0, pillar_1.3.1, pkgconfig_2.0.2, purrr_0.2.5, R6_2.3.0, Rcpp_0.12.19, readr_1.1.1, reshape2_1.4.3, rj.gd_3.0.0-10, rlang_0.3.0.1, rmarkdown_1.11, scales_1.0.0, stringi_1.2.4, stringr_1.3.1, tcltk_3.5.1, tibble_1.4.2, tidyselect_0.2.5, tools_3.5.1, utf8_1.1.4, uuid_0.1-2, viridisLite_0.3.0, xfun_0.3, xml2_1.2.0, xtable_1.8-3, yaml_2.2.0, zip_1.0.0

* Bioconductor (BiocInstaller) version: 1.30.0

**Comment by davidgohel** [comment]
Hi,

Yes, it's a known issue. Before it was always fixed but it has a cost as the computation always happened even when not necessary. Now there is a function for that named `fix_border_issues`. 

The underlying issue is that the border bottom you see is not the last one (the 8th row) but the first one of the group (the 7th row in your example).

```
library(flextable)
library(magrittr)

data <- data.frame(class = rep(LETTERS[1:4], each = 2), i = 1:8)
ft <- flextable(data) %>% border_remove
ft <- ft %>% hline_bottom(border = fp_border(color = "black"), part = "body") # only include horizontal line at the bottom
ft <- ft %>% merge_v(j = 1) %>% fix_border_issues()
ft
```

**Comment by lcougnaud** [comment]
Thanks! This indeed solves my issue.
Sorry, I have just noticed this is actually mentioned in the 'flextable layout' documentation.
