### ISSUE TITLE
It is very easy to add a line break into table cell, why can't add a line break into MSword?

### ISSUE THREAD

**Issue by yvhkgdsk0** [davidgohel/flextable#109]
Hi,
With the flextable version 5.1,I can easily add a line break into a table cell by "\n", why can't use a similar way like "\n" or "\n\r" to add a line break into MS word? [https://github.com/davidgohel/officer/issues/136]
Or just not have the function yet?

Regards,
Qi

**Comment by davidgohel** [comment]
Dear Qi,

That's part of officer API, one paragraph is ending with a carriage return, I don't want to trick the code to change `\n` into new paragraphs. 

In flextable, it was implemented but it has side effects (mainly width and height are wrong and a part of the code is tricked for that which decrease the performances).
