### ISSUE TITLE
enhancement request

### ISSUE THREAD

**Issue by jfrancoiscollin** [davidgohel/flextable#111]
Hello,

un truc qui serait trop bien ce serait de pouvoir faire des bordures doubles avec les tableaux:

 un genre de fp_border(style="solid-double")

La bise! :)

**Comment by davidgohel** [comment]
hello,

Moyen moyen. On verra peut être après. Il faudra ds un premier temps se séparer de tout le cpp dans le code officer. Ensuite, ce sera plus facile d'ajouter ce genre d'options :)
