### ISSUE TITLE
Conditional Formatting not working

### ISSUE THREAD

**Issue by PJReidy** [davidgohel/flextable#112]
Hi David,

I am trying to conditionally format my flextable so that if any figure in the 'Variance' column is below 0 (eg. -23, -54), it will be color red. But it won't work.

Here's my code:
library(flextable)
library(officer)
library(magrittr)
myft <- color(myft, ~ Variance < 0, ~ Variance , color = "red")

Can you please advise as I don't want to use another table cause I love flextable!!

Thanks,

Paul

**Comment by davidgohel** [comment]
Hi, 

I can't reproduce your example. The following is working as expected:

```
library(flextable)
library(magrittr)

data.frame(Variance = rnorm(10)) %>% 
  flextable() %>% 
  color(~ Variance < 0, ~ Variance , color = "red")
```
<img width="121" alt="Capture d’écran 2019-03-24 à 11 45 35" src="https://user-images.githubusercontent.com/4331618/54878252-5d27e780-4e2a-11e9-95ae-b50f573151a4.png">


I will reopen the issue if necessary.

KR
David

**Comment by PJReidy** [comment]
That’s fantastic! It works great. Thanks David
