### ISSUE TITLE
Superscript when output to MS Word

### ISSUE THREAD

**Issue by vovoch** [davidgohel/flextable#113]
It is very easy to do superscript in SAS in [headers/footnotes](http://support.sas.com/kb/24/046.html) or in [a dataset](https://communities.sas.com/t5/SAS-Procedures/Superscript-or-Subscript-in-SAS-dataset/td-p/158183). And it is very useful feature in clinical reporting! Unfortunately, I cannot find it in R. Is it possible in the **flextable** package?

**Comment by davidgohel** [comment]
yes

See https://davidgohel.github.io/flextable/articles/format.html#content-format-functions

and search the keyword "superscript"

KR
David

**Comment by davidgohel** [comment]
@vovoch just added a new function `sup` and `sub` to ease that, I will document that soon
