### ISSUE TITLE
Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html, : internal error: Huge input lookup [1]

### ISSUE THREAD

**Issue by davidgohel** [davidgohel/flextable#114]
@VamsiGundaba commented on [Tue Mar 26 2019](https://github.com/davidgohel/ggiraph/issues/130)

I am new to r programming.
I am getting this error only if the file has a large number of records.
With a smaller number of records, I don't get any error and can print the output in .docx format.

I am using officer & flextable packages for output. This is the code i am using.

library(officer)
library(flextable)
myft <- regulartable(dataset, col_keys = names(dataset))
my_doc <- body_add_par(my_doc, "", style = "Normal")
my_doc <- body_add_flextable(my_doc, value = myft)
print(my_doc, target = "path/ABC.docx") 
How do I write a docx file from a dataset with a large number of records?

**Comment by davidgohel** [comment]
Hi,

Yes, package `xml2` is used and that indicates you are generating a huge result. flextable is made to create tables for reporting or publication, it is not supposed to be used to generate huge tables.

I hope this make things clearer.

KR
David

**Comment by VamsiGundaba** [comment]
Thanks for your response.

I am facing this issue after r was upgraded from 3.5.0 to 3.5.3.
In the earlier version I have not faced any issue like this and even I can
generate the output with  large number of records.

Did I missed any package to install ?
Please let me know.


Regards
Vamsi

**Comment by davidgohel** [comment]
I don't think this has anything to do with R version (more a package that changed).

How much lines are you generating?

**Comment by VamsiGundaba** [comment]
It is having 2000 lines of data

**Comment by VamsiGundaba** [comment]
Hi,

For example please execute the below code. It willshow the same error as i
mentioned.

ord<-c('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J')
srnum<-c('1' :'1000')
df<-expand.grid(srnum=srnum,ord=ord)
library(officer) library(flextable) myft <- regulartable(df, col_keys =
names(df)) my_doc <- body_add_flextable(my_doc, value = myft) print(my_doc,
target = "path/ABC.docx")

It will generate 10000 records,but unable to print in the .docx format.

Please help me on this.

Regards,
Vamsi

**Comment by davidgohel** [comment]
Then use `rmarkdown` documents, it relies on pandoc and not on xml2. You will be able to generate a table along 295 pages:

```````
---
title: "Untitled"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
ord<-c('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J')
srnum<-c('1' :'1000')
df<-expand.grid(srnum=srnum,ord=ord)
library(officer) 
library(flextable) 
myft <- regulartable(df, col_keys = names(df)) 
myft
```

```````

**Comment by VamsiGundaba** [comment]
Thank you David for your response.!

I have one doubt.
Is it possible to add header & footer in word docx output,I mean it should
repeat in all page's using officer package.

Only for header & footer I have to go to r Markdown. Till today I have
generated all my outputs using officer package.

Actually i am new to r programming and I don't know rMarkdown.
Again I have to start from basics to learn rMarkdown for this header &
footer.

Please clarify me on this issue.

Regards,
Vamsi

**Comment by davidgohel** [comment]
OK

If you are looking for help to learn R, you would be more happy with datacamp or community.rstudio.  This place is dedicated to issues and bugs for flextable. 

KR
David

**Comment by VamsiGundaba** [comment]
I am not looking to learn R,but my question is it possible to add header &
footer in all pages of word document using officer package?

Regards,
Vamsi

**Comment by davidgohel** [comment]
**This place is dedicated to issues and bugs for flextable.**
