### ISSUE TITLE
Up & down arrows for positive & negative numbers

### ISSUE THREAD

**Issue by PJReidy** [davidgohel/flextable#116]
Hi David,
Is there a way to include an up arrow beside a positive percentage and a down arrow for a negative percentage in Flextable? 

Kind regards,

Paul

**Comment by davidgohel** [comment]
Yes, 

Below an example:


```
library(flextable)
library(officer)
dat <- head(iris, n = 10)
dat$Sepal.Length <- scale(dat$Sepal.Length)[, 1]

myft <- flextable(dat)


myft <- compose(myft,
  j = 1, i = ~ Sepal.Length < 0,
  value = as_paragraph(
    as_chunk(Sepal.Length, props = fp_text(color = "red")), " ",
    as_image(src = "~/Downloads/arrow_up.png", width = .25, height = .25)
  ),
  part = "body"
)
myft <- compose(myft,
  j = 1, i = ~ !Sepal.Length < 0,
  value = as_paragraph(
    as_chunk(Sepal.Length, props = fp_text(color = "gray")), " ",
    as_image(src = "~/Downloads/arrow_down.png", width = .25, height = .25)
  ),
  part = "body"
)

autofit(myft)
```


![arrow_down](https://user-images.githubusercontent.com/4331618/56676086-d3379c80-66bd-11e9-9617-791f503a9287.png)
![arrow_up](https://user-images.githubusercontent.com/4331618/56676087-d3379c80-66bd-11e9-8a0d-123640f3f25c.png)



<img width="552" alt="Capture d’écran 2019-04-24 à 18 22 15" src="https://user-images.githubusercontent.com/4331618/56676130-e9455d00-66bd-11e9-9d59-77a53ee97cd3.png">

**Comment by PJReidy** [comment]
Cheers David, that's perfect!

**Comment by PJReidy** [comment]
Hi David,
When I export my tables to PowerPoint using Officer, the arrows disappear again. I'm not sure why, can you please advise? Thanks, Paul
