### ISSUE TITLE
Feature Request: Copy table to clipboard

### ISSUE THREAD

**Issue by steventilston** [davidgohel/flextable#117]
Thanks for all your work on this package.

It would be very helpful to be able to write a Word table to the clipboard, so that it could be pasted directly from RStudio into an existing Word doc or Outlook email.

The idea is this would better support very quick ad hoc work in a business environment (e.g. you get emailed a csv, import it with RStudio, do some quick calcs, and email back a summary table), rather than a more formal project where you're generating a report from scratch etc.

Cheers, Steve

**Comment by davidgohel** [comment]
You're welcome

From what I read, using clipboard from a package would be a problem from CRAN point of view so I am relunctant to go in that direction. BUT you can use `print(ft, preview ="docx")` and `print(ft, preview ="pptx")`. This will pop up a Word or PowerPoint document containing only the table (you can then copy paste the table). 

I know this is not exactly what you asked but this is also possible to send email with flextable inside, read this article (sorry, it's in French): 

https://www.ardata.fr/post/2019/03/04/send-emails-containing-flextable-with-r/


David

**Comment by steventilston** [comment]
Thanks, that's actually very helpful. I can see myself using that a lot!
