### ISSUE TITLE
Complex text

### ISSUE THREAD

**Issue by BabaYara** [davidgohel/flextable#12]
Hi David,

Thank you for the wonderful work on the package. I wanted to ask if you have already implemented a version of the complex text you have in the officer package in the flextable package. I want to insert some greek letters, superscript and other similar characters into specific headings or cells and I cannot seem to figure it out. 

Thanks for the support.

**Comment by davidgohel** [comment]
Hi,

Unicode characters are working well. One important point is that if you choose a font, make sure the font contains the character you want to use (Arial for example has *epsilon*).

 Function `display` will also help to concatenate various formatted text: https://davidgohel.github.io/flextable/articles/format.html#display-function

I will make a section in the doc next week to show how it works.

**Comment by BabaYara** [comment]
Thank you.

**Comment by davidgohel** [comment]
I have improved display function and the documentation 

https://davidgohel.github.io/flextable/articles/format.html#display-function

For specific character, you can use unicode 

David
