### ISSUE TITLE
Hi David,

### ISSUE THREAD

**Issue by PJReidy** [davidgohel/flextable#120]
Hi David,
When I export my tables to PowerPoint using Officer, the arrows disappear again. I'm not sure why, can you please advise? Thanks, Paul

_Originally posted by @PJReidy in https://github.com/davidgohel/flextable/issues/116#issuecomment-489599320_

**Comment by davidgohel** [comment]
Hi

I just updated the doc to explain why you can't have images in flextable when output is PowerPoint: https://davidgohel.github.io/flextable/articles/display.html#limitation-for-powerpoint

If you really need to have this feature in PowerPoint, you could use new function `plot`: https://davidgohel.github.io/flextable/reference/plot.flextable.html

Hope this helps. 

David

**Comment by PJReidy** [comment]
Thanks for getting back to me David.
When I try the plot function, I get this error:
> library(flextable)
> ft <- flextable( head( mtcars ) )
> ft <- autofit(ft)
> if(all( interactive(),
+         require("webshot", quietly = TRUE),
+         require("magick", quietly = TRUE),
+         require("graphics", quietly = TRUE) ) )
+   plot(ft)
Linking to ImageMagick 6.9.9.14
Enabled features: cairo, freetype, fftw, ghostscript, lcms, pango, rsvg, webp
Disabled features: fontconfig, x11
Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' is a list, but does not have components 'x' and 'y'

**Comment by davidgohel** [comment]
Update your package with command `remotes::install_github("davidgohel/flextable")`

**Comment by PJReidy** [comment]
That’s great. Thanks for your help David. P
