### ISSUE TITLE
flextable HTML files do not print in color

### ISSUE THREAD

**Issue by tylerrollinsphd** [davidgohel/flextable#121]
When color coding the background in my flextable (see below) then writing it to HTML the color shows fine in the browser but does not print in color...I have ensured that my browsers are set to print background colors. Any chance of including something that will allow for printable colors from HTML docs?

```
...
myft <- bg(myft, ~ Measure=="Mastery", ~ Measure, bg = "#ffdfb2")
myft <- bg(myft, ~ Measure=="Success", ~ Measure, bg = "#e4f9d4")
myft <- bg(myft, ~ Measure=="Drop", ~ Measure, bg = "#ffb7b2")
```

**Comment by davidgohel** [comment]
Hi,

Please post a reproducible and provide

- [ ] The code that is producing the error, it has to be a minimal reproducible example.
Stackoverflow is providing good explanations about it: https://stackoverflow.com/help/mcve. You can use package `reprex` to help you: http://reprex.tidyverse.org/. The most popular R stackoverflow question is about the subject: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

- [ ] the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example. 

- [ ] you did checked you had the latest version of the package on CRAN (and on github if issue exists with CRAN version).

**Comment by davidgohel** [comment]
```
myft <- flextable(iris)
myft <- bg(myft, ~ Species=="setosa", ~ Species, bg = "#ffdfb2")
myft <- bg(myft, ~ Species=="versicolor", ~ Species, bg = "#e4f9d4")
myft <- bg(myft, ~ Species=="virginica", ~ Species, bg = "#ffb7b2")
plot(myft)
```

![Rplot](https://user-images.githubusercontent.com/4331618/57549612-54508e00-7364-11e9-950f-178fe63e16db.png)

**Comment by tylerrollinsphd** [comment]
Yes what you included is basically what I have. But I am outputting via rmarkdown into an html file and when I try to print the display contents in the html web browser window is sends to the printer but does not include the background color. I will post a reprex with the rmarkdown if you need it..but if you write your example to html and send to a color printer I think you'll see it doesn't print the background colors

**Comment by davidgohel** [comment]
Ah ok,

I can see, thanks. I will have a look, it's a bug

**Comment by davidgohel** [comment]
Hi,
 
I did test from RStudio Viewer where flextable is printed in a web view where there is no bootstrap and it printed with colors. It's not a bug. This is an implemented feature of bootstrap (bootstrap is a CSS theme applied to html documents and is used by most of R Markdown formats, i.e. `rmarkdown::html_document`). In that context, I can't do anything for changing that.

You can find good explanations about why bootstrap implemented that here: https://stackoverflow.com/questions/33410724/bootstrap-print-css-removes-background-color

You can have a try with `pagedown`, it will work (maybe use this one if your goal is to print a document. This is an awesome format). 

David
