### ISSUE TITLE
Define a Template  without any previous dataframe

### ISSUE THREAD

**Issue by kmezhoud** [davidgohel/flextable#122]
Dear David,
Thank you for `flextable`! 
I would like to define `flextable` as template for reporting.
The report will be filled automatically or reactively  after processing.
Here an example of `huxtable`. I prefer using `flextable` to define Templates since I have a complex headers.
Thanks

```r
library(huxtable)
library(dplyr)
headr <- data.frame(Title = c("subTitle1", "subTitle2"), 
                     NULL = c("", "numeric2")) 
body <- data.frame( Description = c("Desc1", "Desc2", "Desc3"),
                    Value = c("vale1", "", "value3"))
merged_hux <- rbind(as_huxtable(headr) %>% add_colnames(),
               as_huxtable(body) %>% add_colnames())
huxtable::align(merged_hux)[1, 1]         <- "center"
merged_hux <- merge_cells(merged_hux,1, 1:2)
bottom_border(merged_hux[c(1,3,4), ])     <- 1
huxtable::bold(merged_hux)[c(1, 4), ]    <- TRUE
merged_hux
```

**Comment by davidgohel** [comment]
Hi, 

I am not expert with huxtable but it seems there is a difference, flextable starts from a data.frame but huxtable can bind data into the table. I don't think I can translate that directly.

This would be one solution with flextable:

```{r}
library(flextable)
body <- data.frame( Description = c("Desc1", "Desc2", "Desc3"),
                    Value = c("vale1", "", "value3"), stringsAsFactors = FALSE)
headr <- data.frame(col_keys = c("Description", "Value"),  
                    line1 = c("subTitle1", ""), 
                    line2 = c("subTitle2", "numeric2"), 
                    line3 = c("Description", "Value"),
                    stringsAsFactors = FALSE) 

your_theme <- function(ft, title){
  ft <- add_header_lines(ft, title, top = TRUE)
  ft <- flextable::align(ft, part = "all", align = "left")
  ft <- flextable::align(ft, i = 1, j = 1, part = "header", align = "center")
  ft <- flextable::bold(ft, i = c(1, 4), bold = TRUE, part = "header")
  ft <- fontsize(ft, size = 16, part = "all")
  ft <- padding(ft, padding = 10, part = "all")
  ft <- flextable::width(ft, width = 2)
  ft
}

ft <- flextable(data = body)
ft <- set_header_df(x = ft, mapping = headr, key = "col_keys")
ft <- your_theme(ft, title = "Title")
ft <- hline(ft, i = c(1, 3, 4), border = officer::fp_border(), part = "header")
ft
```

<img width="349" alt="Capture d’écran 2019-05-12 à 16 03 04" src="https://user-images.githubusercontent.com/4331618/57583306-8af6e780-74cf-11e9-9d54-cd7bb6e0a173.png">


I like `set_header_df` as it is easy to define a table and add the content in one single command. If you don't like `set_header_df`, another option is to use `add_header_row`:

```{r}
library(flextable)
body <- data.frame( Description = c("Desc1", "Desc2", "Desc3"),
                    Value = c("vale1", "", "value3"), stringsAsFactors = FALSE)
base_ft <- flextable(data = body, theme_fun = NULL) %>% 
  add_header_row(values = c("subTitle2", "numeric2"), colwidths = c(1,1), top = TRUE) %>% 
  add_header_row(values = c("subTitle1"), colwidths = 2, top = TRUE) %>% 
  add_header_row(values = c("Title"), colwidths = 2, top = TRUE) %>% 
  fontsize(size = 16, part = "all") %>% padding(padding = 10, part = "all")

base_ft %>% 
  flextable::align( part = "all", align = "left") %>% 
  flextable::align( i = 1, j = 1, part = "header", align = "center") %>% 
  hline(i = c(1, 3, 4), border = officer::fp_border(), part = "header") %>% 
  flextable::bold(i = c(1, 4), bold = TRUE, part = "header") %>% 
  flextable::width(width = 2)
```

<img width="372" alt="Capture d’écran 2019-05-12 à 16 03 11" src="https://user-images.githubusercontent.com/4331618/57583314-977b4000-74cf-11e9-858b-6cf301484288.png">


You can also use theme functions (see `theme_tron_legacy` below) or copy and adapt 
from those theme function.


```{r}
base_ft %>% flextable::theme_tron_legacy() %>% 
  flextable::width(width = 2) %>% 
  flextable::align( i = 1, j = 1, part = "header", align = "center")
```

<img width="351" alt="Capture d’écran 2019-05-12 à 16 04 30" src="https://user-images.githubusercontent.com/4331618/57583321-a7931f80-74cf-11e9-9274-0e1cfacb6b82.png">

You can find some documentation here: https://davidgohel.github.io/flextable/articles/layout.html#manage-headers-and-footers

You can get lot of examples and code sample from https://davidgohel.github.io/flextable/articles/offcran/examples.html

**Comment by kmezhoud** [comment]
@davidgohel Thanks for the quick suggestions. 

**First point**
For the first one, the `Description` and `value` parameters are defined 3 times. 
1. as a `col_keys`  for the `headr` despite that it could be in the `body`,
2. The `colnames`of the `body`, (which for me the right one),
3. and in the `line3` in separate rows.

I tried to understand to concept, and I add a column in the body.
- When I comment line3, It is OK.
- but when I added `col_keys` for the `body`  and remove of from the `headr`... does not work

```r
Error in fix.by(by.y, y) : 'by' must specify a uniquely valid column
```
I commented some lines because the number of rows was changed...

```r
library(flextable)
body <- data.frame( col_keys = c("Description", "Value", "Interpretation"),
                    col1 = c("Desc1", "Desc2", "Desc3"),
                    col2 = c("value1", "", "value3"), 
                    col3 = c("Inter1", "", "Inter3"),
                    stringsAsFactors = FALSE)

headr <- data.frame(col_keys = c("foo","too"),
                    line1 = c("subTitle1", ""), 
                    line2 = c("subTitle2", "numeric2"), 
                    #line3 = c("Description", "Value"),
                    stringsAsFactors = FALSE)

your_theme <- function(ft, title){
  ft <- add_header_lines(ft, title, top = TRUE)
  ft <- flextable::align(ft, part = "all", align = "center")
  ft <- flextable::align(ft, i = 1, j = 1, part = "header", align = "center")
  #ft <- flextable::bold(ft, i = c(1, 4), bold = TRUE, part = "header")
  ft <- fontsize(ft, size = 16, part = "all")
  ft <- padding(ft, padding = 10, part = "all")
  #ft <- flextable::width(ft, width = 2)
  ft
}

ft <- flextable(data = body)
ft <- set_header_df(x = ft, mapping = headr, key = "col_keys")
ft <- your_theme(ft, title = "Title")
#ft <- hline(ft, i = c(1, 3, 4), border = officer::fp_border(), part = "header")
ft
``` 
<img width="328" alt="Screen Shot 2019-05-12 at 21 27 35" src="https://user-images.githubusercontent.com/4458195/57587451-d8d61480-74fc-11e9-8a2b-64ff71afc48e.png">

**Second point**
With `set_header_df` we can not define the `Title` as an argument. We have to add it as a new line separately. 

I thing the second suggestion is simplest. 

What is the difference between `add_header_row` and `add_header_lines`  ?

Thanks,
km

**Comment by davidgohel** [comment]
I made documentation improvements. 

https://davidgohel.github.io/flextable/articles/layout.html#manage-headers-and-footers

1. What is the difference between add_header_row and add_header_lines ?

It's clearer in the doc

2. theme_fun is not known for V0.5.2?

yes, it appeared with 0.5.3

3. For the second suggestion `Description` and `value` are defined as colnames of the body. But during setting layout, they considered as a part of header with

I think the documentation is covering that 

KR
David
