### ISSUE TITLE
Feature idea: generic flextable

### ISSUE THREAD

**Issue by patr1ckm** [davidgohel/flextable#123]
Thanks again for the excellent package, I use it all the time.

One idea I had (inspired from the discussion in #118) is to make `flextable` a generic, and then implement specific methods with relevant defaults for it.

For example, `flextable.data.frame` could be implemented with minimal opinions, as you suggest in #118:

```

# just a prototype

flextable <- function(x, ...) {
  UseMethod("flextable")
}

# extra args (including digits) passed to format for example
flextable.data.frame <- function(x, ...){
... original flextable definition
}

# default method coerces to a data frame
flextable.default <- function(x, ...) {
  flextable.data.frame(as.data.frame(x))
}
```
This would also support `broom::tidy` printing, as e.g. `broom::tidy(m)` outputs a data frame (tbl) with appropriate digits for many models.

Other examples
- A separate method for `summary.lm` objects could include useful defaults for printing linear models (including nice p-value formatting) as you also describe in #118. 
-  a flextable method for `DT` as alluded to in #86 .
- a method for sparklines, as in #1 .

Other package authors could provide their own methods for `flextable`, so they don't all have to be collected here. 

I think it's fair to characterize this feature request as tending toward feature creep. However it seems like you've done a lot of thinking already about how various tables (data frames, model summary output) should be displayed which is really useful. 

Curious to hear your thoughts!

**Comment by davidgohel** [comment]
Hi, 

There is a method named `as_flextable`. It can be used to do this kind of things.

As you said, it's easy to add new methods:

```
library(flextable)

linear.1 <- lm(rating ~ complaints + privileges + learning 
               + raises + critical, data=attitude)
as_flextable(linear.1)
```

<img width="605" alt="Capture d’écran 2019-05-18 à 08 58 44" src="https://user-images.githubusercontent.com/4331618/57965915-2b735e80-794b-11e9-9b41-1f1da8306c16.png">

I'd like to find time (or help?) to release this methods. Would you like to contribute? So far, I have `lm`, `glm`, I'd like to get `gam` and `lme` also. 

I don't really understand the need to cast a DT to flextable. flextable is for tabular reporting and publications, DT is designed to be a dynamic display of tabular data in HTML pages. I fear that people will not understand and ask for filters, sorting and many impossible features :)

For #1, there are two subjects. One to enabling htmlwidgets in HTML flextable. and the other subjects is about minicharts. I hope to find time to work on subj 1 later. For subject 2, there are already few options: https://davidgohel.github.io/flextable/articles/display.html#minibar. It may need few new functions I agree.

**Comment by patr1ckm** [comment]
Ah, how did I miss that? The `as_flextable` generic makes sense. I'd be game to help develop/release some of the functions! Happy to start by testing/releasing any code you already have.

**Comment by davidgohel** [comment]
Hi, sorry for the delay

https://github.com/ardata-fr/fmod

I added only 2 functions for now, one for lm, one for glm. This is a very first draft but feel free to contribute - you will be welcome :)
