### ISSUE TITLE
flextable breaks ggplot2 in shiny app

### ISSUE THREAD

**Issue by AshesITR** [davidgohel/flextable#125]
Rendering a flextable in any shiny app breaks all ggplot2 reactive plots.
Instead of updating the plot, an error is logged in the browser console related to invalid JSON syntax. This error is apparently by the shiny-internal message handler.

### MCVE

Here is a minmal app to illustrate the bug.
For a working app, comment out the `output$flex <- ...` code in server and restart R.
As-is the browser console dumps an error and no output is visible:
![grafik](https://user-images.githubusercontent.com/2363178/58780454-4abfec00-85d9-11e9-9cef-8fafa081c0fb.png)

    library(shiny)
    library(magrittr)
    library(ggplot2)
    
    ui <- fluidPage(
        titlePanel("Flextable repro"),
        sidebarLayout(
            sidebarPanel(
                actionButton("btn", label = "Increment")
            ),
            mainPanel(
                plotOutput("plot"),
                uiOutput("flex")
            )
        )
    )
    
    server <- function(input, output) {
        df <- reactive({
            data.frame(n = as.integer(input$btn))
        })
        output$plot <- renderPlot({
            df() %>% 
                ggplot() +
                geom_col(aes(y = n, x = "N"))
        })
        output$flex <- renderUI({
            df() %>%
                flextable::flextable() %>%
                flextable::htmltools_value()
        })
    }
    
    shinyApp(ui = ui, server = server)

### Session Info

- Session info ------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 os       Windows 7 x64 SP 1          
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  German_Germany.1252         
 ctype    German_Germany.1252         
 tz       Europe/Berlin               
 date     2019-06-03                  

- Packages----------------------------------------------------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.4.4)
 base64enc     0.1-3   2015-07-28 [1] CRAN (R 3.4.0)
 Cairo         1.5-10  2019-03-28 [1] CRAN (R 3.4.4)
 cli           1.1.0   2019-03-19 [1] CRAN (R 3.4.2)
 colorspace    1.4-1   2019-03-18 [1] CRAN (R 3.4.2)
 config        0.3     2018-03-27 [1] CRAN (R 3.4.4)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.4.2)
 data.table    1.12.2  2019-04-07 [1] CRAN (R 3.4.4)
 digest        0.6.19  2019-05-20 [1] CRAN (R 3.4.2)
 dplyr       * 0.8.1   2019-05-14 [1] CRAN (R 3.4.2)
 evaluate      0.14    2019-05-28 [1] CRAN (R 3.4.2)
 flextable     0.5.4   2019-05-14 [1] CRAN (R 3.4.2)
 gdtools       0.1.8   2019-04-02 [1] CRAN (R 3.4.4)
 ggplot2     * 3.1.1   2019-04-07 [1] CRAN (R 3.4.4)
 glue          1.3.1   2019-03-12 [1] CRAN (R 3.4.4)
 gtable        0.3.0   2019-03-25 [1] CRAN (R 3.4.4)
 htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.4.0)
 httpuv        1.5.1   2019-04-05 [1] CRAN (R 3.4.4)
 jsonlite      1.6     2018-12-07 [1] CRAN (R 3.4.4)
 knitr         1.23    2019-05-18 [1] CRAN (R 3.4.2)
 labeling      0.3     2014-08-23 [1] CRAN (R 3.4.0)
 later         0.8.0   2019-02-11 [1] CRAN (R 3.4.4)
 lazyeval      0.2.2   2019-03-15 [1] CRAN (R 3.4.2)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.4.0)
 mime          0.6     2018-10-05 [1] CRAN (R 3.4.4)
 munsell       0.5.0   2018-06-12 [1] CRAN (R 3.4.4)
 officer       0.3.4   2019-04-30 [1] CRAN (R 3.4.2)
 pillar        1.4.1   2019-05-28 [1] CRAN (R 3.4.2)
 pkgconfig     2.0.2   2018-08-16 [1] CRAN (R 3.4.4)
 plyr          1.8.4   2016-06-08 [1] CRAN (R 3.4.0)
 promises      1.0.1   2018-04-13 [1] CRAN (R 3.4.4)
 purrr         0.3.2   2019-03-15 [1] CRAN (R 3.4.2)
 R6            2.4.0   2019-02-14 [1] CRAN (R 3.4.4)
 Rcpp          1.0.1   2019-03-17 [1] CRAN (R 3.4.2)
 rlang         0.3.4   2019-04-07 [1] CRAN (R 3.4.4)
 rmarkdown     1.13    2019-05-22 [1] CRAN (R 3.4.2)
 rstudioapi    0.10    2019-03-19 [1] CRAN (R 3.4.4)
 scales        1.0.0   2018-08-09 [1] CRAN (R 3.4.4)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.4.4)
 shiny       * 1.3.2   2019-04-22 [1] CRAN (R 3.4.4)
 tibble        2.1.2   2019-05-29 [1] CRAN (R 3.4.2)
 tidyselect    0.2.5   2018-10-11 [1] CRAN (R 3.4.4)
 uuid          0.1-2   2015-07-28 [1] CRAN (R 3.4.0)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.4.4)
 xfun          0.7     2019-05-14 [1] CRAN (R 3.4.2)
 xml2          1.2.0   2018-01-24 [1] CRAN (R 3.4.3)
 xtable        1.8-4   2019-04-21 [1] CRAN (R 3.4.4)
 yaml          2.2.0   2018-07-25 [1] CRAN (R 3.4.4)
 zip           2.0.2   2019-05-13 [1] CRAN (R 3.4.2)

**Comment by AshesITR** [comment]
Here's a sessioninfo from R 3.5.3 with the same bug.
I'll try using wireshark to grab a sample of the malformed JSON data.

- Session info -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.3 (2019-03-11)
 os       Windows 7 x64 SP 1          
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  German_Germany.1252         
 ctype    German_Germany.1252         
 tz       Europe/Berlin               
 date     2019-06-04                  

- Packages ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.5.3)
 base64enc     0.1-3   2015-07-28 [1] CRAN (R 3.5.0)
 cli           1.1.0   2019-03-19 [1] CRAN (R 3.5.3)
 colorspace    1.4-1   2019-03-18 [1] CRAN (R 3.5.3)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.1)
 data.table    1.12.2  2019-04-07 [1] CRAN (R 3.5.3)
 digest        0.6.19  2019-05-20 [1] CRAN (R 3.5.3)
 dplyr         0.8.1   2019-05-14 [1] CRAN (R 3.5.3)
 evaluate      0.14    2019-05-28 [1] CRAN (R 3.5.3)
 flextable     0.5.4   2019-05-14 [1] CRAN (R 3.5.3)
 gdtools       0.1.8   2019-04-02 [1] CRAN (R 3.5.3)
 ggplot2     * 3.1.1   2019-04-07 [1] CRAN (R 3.5.3)
 glue          1.3.1   2019-03-12 [1] CRAN (R 3.5.3)
 gtable        0.3.0   2019-03-25 [1] CRAN (R 3.5.3)
 htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.5.1)
 httpuv        1.5.1   2019-04-05 [1] CRAN (R 3.5.3)
 jsonlite      1.6     2018-12-07 [1] CRAN (R 3.5.3)
 knitr         1.23    2019-05-18 [1] CRAN (R 3.5.3)
 labeling      0.3     2014-08-23 [1] CRAN (R 3.5.0)
 later         0.8.0   2019-02-11 [1] CRAN (R 3.5.3)
 lazyeval      0.2.2   2019-03-15 [1] CRAN (R 3.5.3)
 magrittr    * 1.5     2014-11-22 [1] CRAN (R 3.5.1)
 mime          0.6     2018-10-05 [1] CRAN (R 3.5.1)
 munsell       0.5.0   2018-06-12 [1] CRAN (R 3.5.1)
 officer       0.3.4   2019-04-30 [1] CRAN (R 3.5.3)
 pillar        1.4.1   2019-05-28 [1] CRAN (R 3.5.3)
 pkgconfig     2.0.2   2018-08-16 [1] CRAN (R 3.5.1)
 plyr          1.8.4   2016-06-08 [1] CRAN (R 3.5.1)
 promises      1.0.1   2018-04-13 [1] CRAN (R 3.5.1)
 purrr         0.3.2   2019-03-15 [1] CRAN (R 3.5.3)
 R6            2.4.0   2019-02-14 [1] CRAN (R 3.5.3)
 Rcpp          1.0.1   2019-03-17 [1] CRAN (R 3.5.3)
 rlang         0.3.4   2019-04-07 [1] CRAN (R 3.5.3)
 rmarkdown     1.13    2019-05-22 [1] CRAN (R 3.5.3)
 rstudioapi    0.10    2019-03-19 [1] CRAN (R 3.5.3)
 scales        1.0.0   2018-08-09 [1] CRAN (R 3.5.1)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.3)
 shiny       * 1.3.2   2019-04-22 [1] CRAN (R 3.5.3)
 tibble        2.1.2   2019-05-29 [1] CRAN (R 3.5.3)
 tidyselect    0.2.5   2018-10-11 [1] CRAN (R 3.5.3)
 uuid          0.1-2   2015-07-28 [1] CRAN (R 3.5.0)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.1)
 xfun          0.7     2019-05-14 [1] CRAN (R 3.5.3)
 xml2          1.2.0   2018-01-24 [1] CRAN (R 3.5.1)
 xtable        1.8-4   2019-04-21 [1] CRAN (R 3.5.3)
 zip           2.0.2   2019-05-13 [1] CRAN (R 3.5.3)

**Comment by davidgohel** [comment]
thanks

I can reproduce on windows, it happens with IE or Microsoft edge, right?

**Comment by AshesITR** [comment]
I repro'd on Firefox, but I think I found the issue in wireshark:
The plot JSON contains numbers with decimals (e.g. "1.0"). Once a flextable has been rendered, the JSON output gets malformed into "1,0" (note the comma).

Sounds like an issue with shadowing some `format`ish function?

**Comment by davidgohel** [comment]
OK thanks for that. I'll have a look this week

**Comment by AshesITR** [comment]
I continued my root cause analysis a bit:

Shiny serializes the messages with `jsonlite::toJSON(...)` using some custom arguments.
After running the app with a flextable, the option `use_signif = TRUE` used by shiny causes malformed JSON:

    jsonlite::toJSON(1.5, use_signif = T)
    # [1.5] on a fresh session and with use_signif = F
    # [1,5] after running the MVCE

**Comment by AshesITR** [comment]
Here's a MCVE without shiny:

``` r
library(flextable)
Sys.getlocale()
#> [1] "LC_COLLATE=German_Germany.1252;LC_CTYPE=German_Germany.1252;LC_MONETARY=German_Germany.1252;LC_NUMERIC=C;LC_TIME=German_Germany.1252"
df <- data.frame(n = 1)
ft <- flextable(df)
Sys.getlocale()
#> [1] "German_Germany.1252"
```

<sup>Created on 2019-06-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

NB we don't have to render the flextable.
