### ISSUE TITLE
Cannot render RMarkdown to PDF

### ISSUE THREAD

**Issue by everetr** [davidgohel/flextable#126]
Here is a minimal example in RMarkdown:

````Rmd
---
title: "Test"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(flextable)
library(magrittr)

test = data.frame(id = c('a', 'b', 'c'),
                  value = c(1,   2,   3))

test %>%
  flextable::flextable()

```
````

When I try to knit this, I get the following error message:

![image](https://user-images.githubusercontent.com/9023041/58833149-f3a13200-863f-11e9-81cb-9cb1a01d7899.png)

When I run the two chunks individually, it works:

![image](https://user-images.githubusercontent.com/9023041/58833794-63fc8300-8641-11e9-9f17-5764762dbb5a.png)

Using `knitr::kable()` instead, I don't get such an error when knitting:

````
---
title: "Test"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(knitr)
# library(flextable)
library(magrittr)

test = data.frame(id = c('a', 'b', 'c'),
                  value = c(1,   2,   3))

test %>%
  # flextable::flextable()
  knitr::kable(format = 'latex')
```
````
I noticed the error message includes `sprintf("file:///%s", tf)`, which was removed in a recent update (6a277f1). Could they be related? I'm just guessing.

*****

My session info after running both chunks individually in the first example above:

````
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
[1] English_United States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magrittr_1.5    flextable_0.5.4

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1        digest_0.6.19     R6_2.4.0          evaluate_0.14     zip_2.0.2         gdtools_0.1.8     rlang_0.3.4      
 [8] uuid_0.1-2        data.table_1.12.2 xml2_1.2.0        rmarkdown_1.13    tools_3.6.0       officer_0.3.4     xfun_0.7         
[15] yaml_2.2.0        compiler_3.6.0    base64enc_0.1-3   htmltools_0.3.6   knitr_1.23
````

I understand knitr and RMarkdown aren't your packages, so it's fine if you don't want to touch this. I just wanted to document it anyway in case someone down the road comes across this problem. Thank you in advance for any insight.

*****

Edit: For anyone googling the error message, here's the text of the error message to guide you here:

>Error in webshot::webshot(url = sprintf("file://%s", tf), file = tmp, : webshot.js returned failure value: 1 Calls: <Anonymous> ... knit_print.flextable -> in_base_dir -> in_dir -> <Anonymous> Execution halted

**Comment by davidgohel** [comment]
Hi,

Thanks, you're right, the fix you mentioned is supposed to solve that issue. Would it be possible for you to update the package from github (`remotes::install_github("davidgohel/flextable")`) and confirm it is working? 

David

**Comment by davidgohel** [comment]
I did some test and now it's fixed. 

Thanks for reporting it.
