### ISSUE TITLE
Error when setting width

### ISSUE THREAD

**Issue by tammoterhark** [davidgohel/flextable#127]
```
library(flextable)
ft <- flextable(iris)
ft <- width(ft, width = 1)
```

produces: `Error in width(ft, width = 1) : unused argument (width = 1)`

R version:  3.6.0
Flextable version: 0.5.4
Rstudio in Windows 10

**Comment by tammoterhark** [comment]
Also after: `install_github("davidgohel/flextable")`

**Comment by tammoterhark** [comment]
Downgrading to R version 3.5.3 made the error disappear.

**Comment by tammoterhark** [comment]
Additional:

```
ft_dims <- flextable(cs_dimensions_ft) %>%
  theme_vanilla() %>%
  font(fontname = "Ubuntu", part = "all") %>%
  bg(bg = "#dddddd", part = "body") %>%
  width(j = 1:4, width = w_vector)
```

In the previous statement also the font declaration did not work on 3.6.0. It does work on R 3.5.3.

**Comment by davidgohel** [comment]
Please, provide a [`reprex`](https://reprex.tidyverse.org/index.html) or at least the `sessionInfo()` result, this will help me when I will work on the issue.

**Comment by tammoterhark** [comment]
Reprex:
```
library(flextable)
ft <- flextable(iris)
ft <- width(ft, width = 1)
```
produces: `Error in width(ft, width = 1) : unused argument (width = 1)`

R version: 3.6.0
Flextable version: 0.5.4
Rstudio in Windows 10

Cannot reproduce sessionInfo() now, because I downgraded R and am in the middle of preparing report, using Officer and Flextable.

**Comment by davidgohel** [comment]
OK

(note that you can have multiple R versions with Windows. )

I can not reproduce, the same example is passing CRAN checks on windows. All is ok also on appveyor. 

The only thing I can suggest is to use `flextable::width` instead of `width` if the function `width` is also exported by another package loaded in your R session.
