### ISSUE TITLE
Header values are checked strictly

### ISSUE THREAD

**Issue by muranyia** [davidgohel/flextable#13]
While flextable in reportRs supported any value in a column header, this version fails when a column name is made with `data.frame(... , check.names=FALSE)` and contains whitespace, apostrophe, etc.
```
Error in f_list(...) : object 'My syntactically not valid variable name' not found
```
If possible I'd like the old behavior back so that header names are not restricted to syntactically valid variable names.

**Comment by davidgohel** [comment]
Sorry, that's not possible.
