### ISSUE TITLE
Option to remove group label in as_flextable

### ISSUE THREAD

**Issue by MMWeb87** [davidgohel/flextable#131]
The function _as_flextable.grouped_data()_ should have an option to customise how the gruop label is shown, or at least the option to hide the group label. Sometimes the labels are already self-explicatory (at least in my case).

So, I would add an argument to the function and the following condition:

```r
if(!hide_grouplabel){
   z <- compose(z, i = i, j = 1, value = as_paragraph(as_chunk(group),  
      ": ", as_chunk(gnames)))
} else {
   z <- compose(z, i = i, j = 1, value = as_paragraph(as_chunk(gnames)))
}
```

**Comment by davidgohel** [comment]
Agree, you can either submit a PR or I will implement it later (for the next release).

David

**Comment by davidgohel** [comment]
Thanks, I used your suggestion to implement the option.
