### ISSUE TITLE
save_as_image() does not render bold text

### ISSUE THREAD

**Issue by padpadpadpad** [davidgohel/flextable#133]
Hi

Great package. For some reason the webshot method of saving to a png does not render bold text anymore.

It does render bold when using `save_to_html()`.

Any advice welcome. Using the flextable 0.5.5 and webshot 0.5.1 on R 3.5.0 and MacOS 10.14.4. Having the same problem on more recent versions of R though on a friend's machine (also MacOS).

``` r
library(flextable)
#> Warning: package 'flextable' was built under R version 3.5.2
  library(magrittr)
  
  x <- flextable(mtcars) %>%
    bold(i = 1) %>%
    bg(bg = 'white', part = 'all')
  
  save_as_image(x, '~/Desktop/test.png')
  save_as_html(x, '~/Desktop/test.html')
```

<sup>Created on 2019-06-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Here are the png and html files.
![test.png](https://user-images.githubusercontent.com/10220722/60279334-c3744880-98f8-11e9-8a91-c3c295a4bac7.png)

![test.html](https://user-images.githubusercontent.com/10220722/60279638-5a410500-98f9-11e9-84b8-c784eacecf4a.png)
![Screenshot 2019-06-27 at 16 33 27](https://user-images.githubusercontent.com/10220722/60279640-5d3bf580-98f9-11e9-8c30-0129ef374983.png)

**Comment by davidgohel** [comment]
I can reproduce. Thanks for reporting that.

I added fonts in the html doc and it worked as expected... I don't know what caused that change.

**Comment by padpadpadpad** [comment]
Feels a bit strange as webshot just takes screenshots of html files. Hopefully a relatively simple fix.

**Comment by davidgohel** [comment]
This should be *solved* in the dev version. You will need to use package [webshot2](https://github.com/rstudio/webshot2) instead of `webshot` (but it is not on CRAN). 

To use that package, specify argument webshot in `save_as_image`: 

```
# remotes::install_github("rstudio/webshot2")
save_as_image(x, '~/Desktop/test.png', webshot="webshot2")
```
