### ISSUE TITLE
Foot note with images

### ISSUE THREAD

**Issue by ddahora** [davidgohel/flextable#135]
Hello,
I created a table where the cells that had the maximum and minimum values of each row were highlighted respectively with the colors, red and green. I managed to make the table perfectly, but I have a problem to make the caption. With the help of the ionicons package, I made the following code that didn't work.

greensq<-as_png("stop",fill="palegreen",width = .3,height= .3)
redsq <-as_png("stop",fill="lightcoral",width = .3,height= .3)

table1 <- flextable::mk_par(table1,
value = as_paragraph(as_chunk(flextable::as_image(src = greensq),"Minimum rate",
" ",flextable::as_image(src = redsq),"Maximum rate"),part="footer"))

Error in formater(x, ...) : could not find function "formater"

**Comment by davidgohel** [comment]
Thanks
Could you add results of `sessionInfo()` also?

**Comment by ddahora** [comment]
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=Portuguese_Brazil.1252  LC_CTYPE=Portuguese_Brazil.1252    LC_MONETARY=Portuguese_Brazil.1252
[4] LC_NUMERIC=C                       LC_TIME=Portuguese_Brazil.1252    

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ionicons_0.1.1   rmarkdown_1.13   markdown_1.0     pipeR_0.6.1.3    zoo_1.8-6        scales_1.0.0    
 [7] gdata_2.18.0     readxl_1.3.1     knitr_1.23       forcats_0.4.0    stringr_1.4.0    dplyr_0.8.1     
[13] purrr_0.3.2      readr_1.3.1      tidyr_0.8.3      tibble_2.1.3     ggplot2_3.2.0    tidyverse_1.2.1 
[19] kableExtra_1.1.0 magrittr_1.5     officer_0.3.5    flextable_0.5.5 
loaded via a namespace (and not attached):
 [1] gtools_3.8.1      tidyselect_0.2.5  xfun_0.8          reshape2_1.4.3    haven_2.1.0       lattice_0.20-38  
 [7] colorspace_1.4-1  generics_0.0.2    htmltools_0.3.6   viridisLite_0.3.0 base64enc_0.1-3   rlang_0.4.0      
[13] pillar_1.4.1      withr_2.1.2       glue_1.3.1        gdtools_0.1.9     sp_1.3-1          modelr_0.1.4     
[19] uuid_0.1-2        plyr_1.8.4        cellranger_1.1.0  munsell_0.5.0     gtable_0.3.0      rvest_0.3.4      
[25] zip_2.0.2         evaluate_0.14     rsvg_1.3          broom_0.5.2       Rcpp_1.0.1        backports_1.1.4  
[31] webshot_0.5.1     jsonlite_1.6      hms_0.4.2         digest_0.6.19     stringi_1.4.3     rgdal_1.4-4      
[37] cli_1.1.0         tools_3.6.0       lazyeval_0.2.2    crayon_1.3.4      pkgconfig_2.0.2   data.table_1.12.2
[43] xml2_1.2.0        lubridate_1.7.4   assertthat_0.2.1  httr_1.4.0        rstudioapi_0.10   R6_2.4.0         
[49] nlme_3.1-139      compiler_3.6.0

**Comment by davidgohel** [comment]
I was not aware there was users of `ionicons` :)

Without the whole code, I can't exactly reproduce. The following is an example that produces the table that can be seen below.

```
# remotes::install_github("davidgohel/ionicons")
library(magrittr)
library(ionicons)
library(officer)
library(flextable)



table1 <- flextable(head(mtcars))
table1 <- add_footer_lines(table1, values = "however, it will be replaced when using mk_par")

width <- .3
height <- .3

greensq <- as_png("stop", fill = "palegreen", width = round(width * 72), height = round(height * 72))
redsq <- as_png("stop", fill = "lightcoral", width = round(width * 72), height = round(height * 72))

table1 <- flextable::mk_par(
  table1,
  j = 1,
  value = as_paragraph(
    as_image(src = greensq, width, height),
    "Minimum rate", " ",
    as_image(src = redsq, width, height),
    "Maximum rate"
  ),
  part = "footer"
)

table1
```


<img width="689" alt="Capture d’écran 2019-06-27 à 21 54 57" src="https://user-images.githubusercontent.com/4331618/60296357-3b0c9c80-9926-11e9-88e5-95f8d48326c0.png">

**Comment by ddahora** [comment]
Hello,
This worked perfectly! I think "as_chunk" wasn't necessary.
Thanks so much!!
The whole code is below. Maybe, you don't understand much, because many things is in portuguese, I try upload the file, but it wasn't work.

y=ncol(g001_003a)
tabheader1<-names(g001_003a)
tabheader1<-tabheader1[-1]
tabheader2<-substr(tabheader1,1,4)
tabheader3<-substr(tabheader1,6,8)
tabheader<-data.frame(tabheader1,tabheader2,tabheader3)
tabheader<-rbind(data.frame(tabheader1="Brasil, Grandes Regiões e Unidades da Federação",tabheader2="Brasil, Grandes Regiões e Unidades da Federação",tabheader3="Brasil, Grandes Regiões e Unidades da Federação"),tabheader)
tabheader$tabheader1<-as.character(tabheader$tabheader1)
tabheader$tabheader2<-as.character(tabheader$tabheader2)
tabheader$tabheader3<-as.character(tabheader$tabheader3)
g001_003 <- flextable::flextable(g001_003a)
g001_003 <- width(g001_003,j=1, width =1.0)
g001_003 <- width(g001_003,j=2:y, width =.3)
g001_003 <- height(g001_003,height=.12)
g001_003 <- set_header_df(g001_003,mapping=tabheader,key="tabheader1")
g001_003 <- merge_h(g001_003, part = "header")
g001_003 <- merge_v(g001_003, part = "header")
g001_003 <- add_header_lines(g001_003, 
  values = "Taxa de desocupação (%)")
g001_003 <- align(g001_003,align="center",part="all")
g001_003 <- bold(g001_003,j=1,part="body")
g001_003 <- bold(g001_003,part="header")
g001_003 <- font(g001_003,fontname= "calibri", part = "all")
bb <- officer::fp_border(color="white", width = 2)
bp <- officer::fp_border(color="black", width = 2)
bpon <- officer::fp_border(color="black",style ="solid" , width = 2)
g001_003 <- border_outer(g001_003, part="all",border=bp)
g001_003 <- border_inner(g001_003, part="header",border=bp)
g001_003 <- border_inner(g001_003, part="body",border=bpon)
g001_003 <- bg(g001_003,bg="azure3",part="header")
g001_003 <- bg(g001_003,i=c(1,2,10,20,25,29),bg="azure4",part="body")
g001_003 <- fontsize(g001_003,size=8,part="all")
cores <-function(x){
  if (x %in% c(1,2,10,20,25,29)) {
  ifelse(g001_003a[x,-1]==max(g001_003a[x,-1]),"lightcoral",
       ifelse(g001_003a[x,-1]==min(g001_003a[x,-1]),"palegreen","azure4"))}
  else{
  ifelse(g001_003a[x,-1]==max(g001_003a[x,-1]),"lightcoral",
       ifelse(g001_003a[x,-1]==min(g001_003a[x,-1]),"palegreen","white"))}
}

for (z in 1:33){
g001_003 <- bg(g001_003,i=z,j=2:y,bg=cores(z),part="body") 
}
for (z in 2:y)
g001_003 <- g001_003 %>% 
  mk_par(j=z,value=as_paragraph(as_chunk(formatC(g001_003a[,z],digits=1,format="f",decimal.mark=","))))
g001_003<-add_footer_lines(g001_003,"Fonte:Pesquisa Nacional por Amostra de Domicílios Contínua")
qverde<-as_png("stop",fill="palegreen",width = .3,height= .3)
qverm <-as_png("stop",fill="lightcoral",width = .3,height= .3)





width <- .3

height <- .3



qverde <- as_png("stop", fill = "palegreen", width = round(width * 72), height = round(height * 72))

qverm <- as_png("stop", fill = "lightcoral", width = round(width * 72), height = round(height * 72))



g001_003 <- flextable::mk_par(

  g001_003,

  j = 1,

  value = as_paragraph("Fonte:IBGE,Pesquisa Nacional por Amostra de Domicílios Contínua      ",

    flextable::as_image(src = qverde, width, height),

    "Maior taxa da série", " ",

    flextable::as_image(src = qverm, width, height),

    "Menor taxa da série"

  ),

  part = "footer"

)

g001_003 <- fontsize(g001_003,size=8,part="footer")
g001_003 <- font(g001_003,fontname="calibri",part="footer")

g001_003

**Comment by davidgohel** [comment]
thanks for your feedback :)

++
David
