### ISSUE TITLE
htmltools_value() uses fontsize in px instead of pt

### ISSUE THREAD

**Issue by beckni** [davidgohel/flextable#138]
Create a table with a given font size, say 12 pt.
`table <- flextable(data.frame(a = 1)) %>% fontsize(size = 12, part = "all")`

When I convert it to html, the css specifies the font size as 12px instead of 12pt. 
 `htmltools_value(table) %>% print()`

    <div class="tabwid"><table style='border-collapse:collapse;'><thead><tr><td style="width:54px;height:18px;background-color:transparent;vertical-align: middle;transform: rotate(0deg);border-bottom: 2px solid rgba(0, 0, 0, 1.00);border-top: 2px solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;"><p style="margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:2px;padding-top:2px;padding-left:5px;padding-right:5px;background-color:transparent;"><span style="font-family:'Arial';font-size:12px;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(17, 17, 17, 1.00);background-color:transparent;">a</span></p></td></tr></thead><tbody><tr><td style="width:54px;height:18px;background-color:transparent;vertical-align: middle;transform: rotate(0deg);border-bottom: 2px solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;"><p style="margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:2px;padding-top:2px;padding-left:5px;padding-right:5px;background-color:transparent;"><span style="font-family:'Arial';font-size:12px;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(17, 17, 17, 1.00);background-color:transparent;">1.000</span></p></td></tr></tbody></table></div>`

I am using the same table in a powerpoint presentation and web page. The font size is correct in the powerpoint file, but too small on the web page.

Session info:

    R version 3.6.1 (2019-07-05)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 10 x64 (build 15063)

    Matrix products: default

    Random number generation:
     RNG:     Mersenne-Twister 
     Normal:  Inversion 
     Sample:  Rounding 
 
    locale:
    [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    
    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
    [5] LC_TIME=German_Germany.1252    

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] dplyr_0.8.3     flextable_0.5.5

    loaded via a namespace (and not attached):
     [1] Rcpp_1.0.1        rstudioapi_0.10   knitr_1.23        xml2_1.2.0        magrittr_1.5      
    tidyselect_0.2.5  uuid_0.1-2        lattice_0.20-38  
     [9] R6_2.4.0          rlang_0.4.0       tools_3.6.1       grid_3.6.1        data.table_1.12.2 xfun_0.8          
    htmltools_0.3.6   digest_0.6.20    
    [17] assertthat_0.2.1  tibble_2.1.3      crayon_1.3.4      zip_2.0.3         purrr_0.3.2       officer_0.3.5     
    base64enc_0.1-3   glue_1.3.1       
    [25] evaluate_0.14     rmarkdown_1.13    pillar_1.4.2      compiler_3.6.1    gdtools_0.1.9     
    pkgconfig_2.0.2

**Comment by beckni** [comment]
I have created a pull request #139

**Comment by davidgohel** [comment]
It is fixed with https://github.com/davidgohel/flextable/commit/22e020375a997c9f652e9004fdd28c5aaedc000f

Sorry it took that much time.
