### ISSUE TITLE
Borders not set as expected

### ISSUE THREAD

**Issue by muranyia** [davidgohel/flextable#14]
I'm trying to strip all borders from a flextable using `border(my_flextable, border=fp_border(style="none"), part="all")` but it seems to have no effect. When using `border(my_flextable, border=fp_border(style="none"))` the borders of the header are stripped off but the body still has them.

**Comment by Rckrd** [comment]
The example in the documentation shows all borders on the pptx example but without borders on the docx.

    library(officer)
    ft <- flextable(head(mtcars)) %>% 
       theme_zebra() %>% 
       autofit()

    ppt <- read_pptx() %>% 
         add_slide(layout = "Title and Content", master = "Office Theme") %>% 
         ph_with_flextable(value = ft, type = "body") 
         if( interactive() ) print(ppt, target = "test.pptx")

    doc <- read_docx() %>% 
         body_add_flextable(value = ft)
         if( interactive() ) print(doc, target = "test.docx")

**Comment by davidgohel** [comment]
I think a workaround is to use `fp_border(width=0)`

**Comment by davidgohel** [comment]
Issue has been fixed, the fix is in package `officer` (install it from github or wait few days as new release has just been submitted).

**Comment by muranyia** [comment]
Thank you, David!
