### ISSUE TITLE
Zebra formatting by groups, not individual rows

### ISSUE THREAD

**Issue by simon-tarr** [davidgohel/flextable#142]
Hello, this is a question rather than an issue (but I cannot tag it as such). I posted the following question on SO yesterday but have yet to receive a response. I'm posting here on the off-chance that the package dev (or other flextable expert) could help with my question. Rather than type it out again, I link to the original question here: https://stackoverflow.com/questions/57097240/zebra-row-formatting-using-flextable

Thank you very much in advance of any help.

**Comment by davidgohel** [comment]
Sorry, I am off until July the 30. I will answer that when I will be back

**Comment by simon-tarr** [comment]
Thanks for getting back to me @davidgohel, despite being away. Looking forward to a possible solution on your return.

**Comment by davidgohel** [comment]
Sorry for the delay. This feature does not exist but can be done with calls to `bg` function and the row selector argument.
