### ISSUE TITLE
Another way to export a flextable as image

### ISSUE THREAD

**Issue by ddahora** [davidgohel/flextable#144]
Hi,
I have been using flextable for a project in my work. But in my work, the installation of phantomjs is not released, so save_as_image doesn't work. Is there another way to export a flextable object as an image?

Diogo da Hora

**Comment by davidgohel** [comment]
Hi, sorry not for now.

I recommend to try package `crrri` (see an example here: https://github.com/RLesur/crrri#examples).

If crrri is on cran one day, I will probably use it as an  alternative for screenshot. It seems RStudio is also duplicating that project here (https://github.com/rstudio/chromote) so it seems you have multiple options.
