### ISSUE TITLE
autofit + Rmarkdown + knitr --> word

### ISSUE THREAD

**Issue by timsadler1988** [davidgohel/flextable#145]
Hi David,

first of all: flextable is a great tool, I think the best to work with knitr and I use it extensively in reporting!

I discovered an issue, however, an I'm not sure whether its a bug or I'm doing something wrong.

I knit a word document from Rmarkdown with knitr and pandoc and all flextables turn out fine, except, when I use autofit. In some cases, the final word document opens up and everything looks fine up to right where the flextable should be. The document basically ends there, the rest fo the content is not written into the document. Knitr does not throw me an error, however. I have discovered, that it only occurs, when I use autofit and only when a line in the table that should be fitted is longer than the width of a word document. If it is a bug, you might wanna include an error message or a work around, so that lines break in some cases even with autofit. I've I'm just being stupid, I would appreciate, if you could help me out. I have included a code chunk that produces the rror with autofit but works fine w/o (it happens both with and without piping):

```
modelconfigurations[,.(Model,Submodel,DV,IVs,Dataset)] %>%
  flextable %>%
  align_text_col(align = "left", header = TRUE, footer = TRUE) %>%
  padding(padding=0) %>%
  autofit
```

Platform: Windows 10, Word 2016

RStudio:
```
RStudio
Version 1.1.463 – © 2009-2018 RStudio, Inc.
Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) rstudio Safari/538.1 Qt/5.4.1
```

R:
```
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.3                         
year           2019                        
month          03                          
day            11                          
svn rev        76217                       
language       R                           
version.string R version 3.5.3 (2019-03-11)
nickname       Great Truth
```

Knitr-Version: 1.23

Do you need any more information?

**Comment by davidgohel** [comment]
Hi,

Thank you,

Yes, I need the following elements: 

- [ ] The code that is producing the error, it has to be a minimal reproducible example.
Stackoverflow is providing good explanations about it: https://stackoverflow.com/help/mcve. You can use package `reprex` to help you: http://reprex.tidyverse.org/. The most popular R stackoverflow question is about the subject: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

- [ ] the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example.

**Comment by davidgohel** [comment]
(IMO, using reprex package will be the easier way as it will cook all necessary elements for you and copy that to your clipboard)

**Comment by timsadler1988** [comment]
Hi David,

thank you for your quick reply!

reprex looks great, unfortunately I didn't get it to work with my Rmarkdown configuration. I will look into this, when I have a little bit more time. Meanwhile, I have included code for a .Rmd-file with a reproducable example. The Sweave options in RStudio are knitr and pdfLaTex.

Session info:
`
## R version 3.5.3 (2019-03-11)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 17134)
## 
## Matrix products: default
## 
## locale:
## [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
## [3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
## [5] LC_TIME=German_Germany.1252    
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] reprex_0.3.0     kableExtra_1.1.0 knitr_1.23       flextable_0.5.4 
## 
## loaded via a namespace (and not attached):
##  [1] zip_2.0.2         Rcpp_1.0.1        compiler_3.5.3   
##  [4] pillar_1.4.1      base64enc_0.1-3   tools_3.5.3      
##  [7] digest_0.6.19     uuid_0.1-2        evaluate_0.13    
## [10] tibble_2.1.1      viridisLite_0.3.0 pkgconfig_2.0.2  
## [13] rlang_0.4.0       rstudioapi_0.10   yaml_2.2.0       
## [16] xfun_0.7          officer_0.3.4     stringr_1.4.0    
## [19] httr_1.4.0        xml2_1.2.0        fs_1.3.1         
## [22] gdtools_0.1.8     hms_0.4.2         webshot_0.5.1    
## [25] glue_1.3.1        data.table_1.12.2 R6_2.4.0         
## [28] rmarkdown_1.13    readr_1.3.1       magrittr_1.5     
## [31] scales_1.0.0      htmltools_0.3.6   rvest_0.3.4      
## [34] colorspace_1.4-1  stringi_1.4.3     munsell_0.5.0    
## [37] crayon_1.3.4
`

Test.Rmd
`
---
title: "Test"
output: 
  word_document
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
Sys.setenv(RSTUDIO_PANDOC="C:/Users/BAT8449/Application Data/Pandoc") #Change to your pandoc directory!
Sys.getenv("RSTUDIO_PANDOC")
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("flextable")
library("knitr")
library("kableExtra")
library("reprex")
```

# Lorem Ipsum 1

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

```{r, echo = FALSE}
sessionInfo()
```

```{r code, include = F}
data <- structure(list(Model = structure(c(1L, 2L, 3L, 4L, 5L, 1L), .Label = c("1", 
"2", "3", "4", "5", "6", "7", "8", "9"), class = "factor"), Submodel = structure(c(1L, 
1L, 1L, 1L, 1L, 2L), .Label = c("a", "b"), class = "factor"), 
    DV = structure(c(1L, 1L, 1L, 1L, 1L, 2L), .Label = c("dependentvariable1", 
    "dependentvariable2", "dependentvariable3", "dependentvariable4"), class = "factor"), 
    IVs = c("independentvariable1 + independentvariable2 + independentvariable3 + independentvariable4 + independentvariable5 + independentvariable6 + Controls", 
    "independentvariable1 + independentvariable2 + independentvariable3 + independentvariable4 + independentvariable5 + independentvariable6 + independentvariable6:moderator1 + independentvariable1:(moderator2 + moderator3 + moderator4) + Controls", 
    "independentvariable1 + independentvariable2 + independentvariable3 + independentvariable4 + independentvariable5 + independentvariable6 + independentvariable7 + Controls", 
    "independentvariable1 + independentvariable2 + independentvariable3 + independentvariable4 + independentvariable5 + independentvariable6 + independentvariable6:moderator1 + independentvariable1:(moderator2 + moderator3 + moderator4) + independentvariable7 + Controls", 
    "independentvariable1 + independentvariable2 + independentvariable3 + independentvariable4 + independentvariable5 + independentvariable6 + independentvariable6:moderator1 + independentvariable1:(moderator2 + moderator3 + moderator4) + independentvariable7 + independentvariable7:(moderator5 + moderator6) + Controls", 
    "independentvariable1 + independentvariable2 + independentvariable3 + independentvariable4 + independentvariable5 + independentvariable6 + independentvariable7 + Controls"
    ), Dataset = structure(c(1L, 1L, 1L, 1L, 1L, 1L), .Label = c("Dataset1", 
    "Dateset2"), class = "factor"), Data = structure(c(1L, 
    1L, 1L, 1L, 1L, 2L), .Label = c("all", "dependentvariable1 > 0", 
    "Online", "Offline"), class = "factor")), row.names = c(NA, 
-6L), class = c("data.table", "data.frame"))
```

```{r, echo = FALSE, ft.align="left"}
data %>%
  flextable %>%
  align_text_col(align = "left", header = TRUE, footer = TRUE) %>%
  padding(padding=0) %>%
  autofit
```
`

Best
Tim

**Comment by timsadler1988** [comment]
Hi David,

thank you for your quick reply!

reprex looks great, unfortunately I didn't get it to work with my Rmarkdown configuration. I will look into this, when I have a little bit more time. Meanwhile, I have included code for a .Rmd-file with a reproducable example. The Sweave options in RStudio are knitr and pdfLaTex.

Best 
Tim

**Comment by timsadler1988** [comment]
Session info:

## R version 3.5.3 (2019-03-11)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 17134)
## 
## Matrix products: default
## 
## locale:
## [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
## [3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
## [5] LC_TIME=German_Germany.1252    
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] reprex_0.3.0     kableExtra_1.1.0 knitr_1.23       flextable_0.5.4 
## 
## loaded via a namespace (and not attached):
##  [1] zip_2.0.2         Rcpp_1.0.1        compiler_3.5.3   
##  [4] pillar_1.4.1      base64enc_0.1-3   tools_3.5.3      
##  [7] digest_0.6.19     uuid_0.1-2        evaluate_0.13    
## [10] tibble_2.1.1      viridisLite_0.3.0 pkgconfig_2.0.2  
## [13] rlang_0.4.0       rstudioapi_0.10   yaml_2.2.0       
## [16] xfun_0.7          officer_0.3.4     stringr_1.4.0    
## [19] httr_1.4.0        xml2_1.2.0        fs_1.3.1         
## [22] gdtools_0.1.8     hms_0.4.2         webshot_0.5.1    
## [25] glue_1.3.1        data.table_1.12.2 R6_2.4.0         
## [28] rmarkdown_1.13    readr_1.3.1       magrittr_1.5     
## [31] scales_1.0.0      htmltools_0.3.6   rvest_0.3.4      
## [34] colorspace_1.4-1  stringi_1.4.3     munsell_0.5.0    
## [37] crayon_1.3.4

**Comment by timsadler1988** [comment]
Test.Rmd:

---
title: "Test"
output: 
  word_document
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
Sys.setenv(RSTUDIO_PANDOC="C:/Users/BAT8449/Application Data/Pandoc") #Change to your pandoc directory!
Sys.getenv("RSTUDIO_PANDOC")
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("flextable")
library("knitr")
library("kableExtra")
library("reprex")
```

# Lorem Ipsum 1

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

```{r, echo = FALSE}
sessionInfo()
```

```{r code, include = F}
data <- structure(list(Model = structure(c(1L, 2L, 3L, 4L, 5L, 1L), .Label = c("1", 
"2", "3", "4", "5", "6", "7", "8", "9"), class = "factor"), Submodel = structure(c(1L, 
1L, 1L, 1L, 1L, 2L), .Label = c("a", "b"), class = "factor"), 
    DV = structure(c(1L, 1L, 1L, 1L, 1L, 2L), .Label = c("dependentvariable1", 
    "dependentvariable2", "dependentvariable3", "dependentvariable4"), class = "factor"), 
    IVs = c("independentvariable1 + independentvariable2 + independentvariable3 + independentvariable4 + independentvariable5 + independentvariable6 + Controls", 
    "independentvariable1 + independentvariable2 + independentvariable3 + independentvariable4 + independentvariable5 + independentvariable6 + independentvariable6:moderator1 + independentvariable1:(moderator2 + moderator3 + moderator4) + Controls", 
    "independentvariable1 + independentvariable2 + independentvariable3 + independentvariable4 + independentvariable5 + independentvariable6 + independentvariable7 + Controls", 
    "independentvariable1 + independentvariable2 + independentvariable3 + independentvariable4 + independentvariable5 + independentvariable6 + independentvariable6:moderator1 + independentvariable1:(moderator2 + moderator3 + moderator4) + independentvariable7 + Controls", 
    "independentvariable1 + independentvariable2 + independentvariable3 + independentvariable4 + independentvariable5 + independentvariable6 + independentvariable6:moderator1 + independentvariable1:(moderator2 + moderator3 + moderator4) + independentvariable7 + independentvariable7:(moderator5 + moderator6) + Controls", 
    "independentvariable1 + independentvariable2 + independentvariable3 + independentvariable4 + independentvariable5 + independentvariable6 + independentvariable7 + Controls"
    ), Dataset = structure(c(1L, 1L, 1L, 1L, 1L, 1L), .Label = c("Dataset1", 
    "Dateset2"), class = "factor"), Data = structure(c(1L, 
    1L, 1L, 1L, 1L, 2L), .Label = c("all", "dependentvariable1 > 0", 
    "Online", "Offline"), class = "factor")), row.names = c(NA, 
-6L), class = c("data.table", "data.frame"))
```

```{r, echo = FALSE, ft.align="left"}
data %>%
  flextable %>%
  align_text_col(align = "left", header = TRUE, footer = TRUE) %>%
  padding(padding=0) %>%
  autofit
```

**Comment by timsadler1988** [comment]
For Rmarkdown, the code chunks must be wrapped in 

> ```{r, echo = FALSE}
and
> ```

Github throws that out unfortunately

**Comment by timsadler1988** [comment]
For Rmarkdown, the code chunks must be wrapped like here : https://rmarkdown.rstudio.com/lesson-3.html

Unfortunately, Github throws that out

**Comment by davidgohel** [comment]
@timsadler1988 🙏  (I think you can edit your post and see how I modified it to make it display as expected)

**Comment by timsadler1988** [comment]
Yes, thank you, that's how it's supposed to look like

**Comment by davidgohel** [comment]
This is produced with your code but with the latest version of `flextable` and it looks ok

[Untitled.docx](https://github.com/davidgohel/flextable/files/3451202/Untitled.docx)

Could you update flextable and see if it solve the issue? Otherwise, I will have to test that with a Windows machine.

**Comment by timsadler1988** [comment]
I have downloaded the file you just send me, and it looks exactly like the errornously one I created in word. Apparently, the problem does not occur in R, but has to do with pandoc or word itself?

**Comment by davidgohel** [comment]
OK, thanks for the feedback. To summarise (let me know if I miss something): 

- [ ] all ran OK
- [ ] Word is not warning that the doc is corrupted
- [ ] the table is missing

Can you tell me the result of `rmarkdown::pandoc_version()`?

I don't have Word 2016 so I hope this is not where the issue is...

**Comment by timsadler1988** [comment]
Hi David,

yes, that’s correct! pandoc_version says 2.7.2

Von: David Gohel <notifications@github.com>
Gesendet: Mittwoch, 31. Juli 2019 13:37
An: davidgohel/flextable <flextable@noreply.github.com>
Cc: Sadler, Tim <Tim.Sadler@uni-hamburg.de>; Mention <mention@noreply.github.com>
Betreff: Re: [davidgohel/flextable] autofit + Rmarkdown + knitr --> word (#145)


OK, thanks for the feedback. To summarise (let me know if I miss something):

  *   [ ] all ran OK
  *   [ ] Word is not warning that the doc is corrupted
  *   [ ] the table is missing

Can you tell me the result of rmarkdown::pandoc_version()?

I don't have Word 2016 so I hope this is not where the issue is...

**Comment by davidgohel** [comment]
Thanks, mine is `2.5`. I will have a try later with your pandoc version

**Comment by davidgohel** [comment]
OK, I can reproduce on some computers but not with my mac neither with my windows machine... It's ... annoying, I have no diagnostic yet. Sorry, it takes more times than expected

**Comment by davidgohel** [comment]
[test_1.docx](https://github.com/davidgohel/flextable/files/3490076/test_1.docx)

[test_2.docx](https://github.com/davidgohel/flextable/files/3490077/test_2.docx)

**Comment by timsadler1988** [comment]
Hi David,
any news on this issue?

**Comment by davidgohel** [comment]
Not really,

I have no diagnostic yet. I know that it only happens with some Word for Windows. It does not on my computer.

**Comment by davidgohel** [comment]
Finally, I have a solution for your issue. 

I don't know why Word is behaving that way... I implemented an option to enable non-fixed table layout (autofit). You can now use `set_table_properties` and choose real *autofit* algorithm:


````
data %>%
  flextable %>%
  align_text_col(align = "left", header = TRUE, footer = TRUE) %>%
  padding(padding=0) %>%
  set_table_properties(layout = "autofit", width = 1)
````
