### ISSUE TITLE
Remove decimal points from flextable

### ISSUE THREAD

**Issue by PHEjessicaedwards** [davidgohel/flextable#147]
I'm trying to remove the decimal points from the flextable without any luck. Is there a way to do this?

I have tried using colformat_num but it doesnt work: 

```
TT<-flextable(TT)%>%
   autofit()%>%
   set_header_labels(Team_and_Organisation = "Team and Organisation", Total = "Total")%>%
  bold(part = "header")  

TT<-colformat_num(TT, col_keys = "Total", digits = NULL)
```

Please help! Than you.

**Comment by davidgohel** [comment]
Hi,

Thank you,

I need the following elements: 

- [ ] The code that is producing the error, it has to be a minimal reproducible example.
Stackoverflow is providing good explanations about it: https://stackoverflow.com/help/mcve. You can use package `reprex` to help you: http://reprex.tidyverse.org/. The most popular R stackoverflow question is about the subject: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

- [ ] the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example.

**Comment by davidgohel** [comment]
This is documented here: https://davidgohel.github.io/flextable/articles/display.html#simple-functions-for-formatting-content

You should use `digits = 0` instead of `digits = NULL`
