### ISSUE TITLE
Subscript/Superscript, etc.

### ISSUE THREAD

**Issue by timsadler1988** [davidgohel/flextable#149]
Hi David,

I have seen this issue came up already in the past, but I can't quite figure it out. Or maybe it is rather a feature request. You mentioned we can use complex text in flextable with the compose() and as_sub() function. But those functions only work on already defined flextable objects, so really only afterwards, when the table is set up, right? Is it possible to predefine subscript, superscript, etc. already in the data.frame parsed by flextable by any sort of markup? I am creating very large and dynamic tables, where it is rather impractical to edit single cells after the flextable is already rendered.

Thanks for your advice
Tim

**Comment by davidgohel** [comment]
You could store `as_paragraph()` results in a list column of the data.frame, not use it in argument `col_keys` but use it with function `compose`:

```
data <- structure(list(Species = structure(1:3, .Label = c("setosa", 
"versicolor", "virginica"), class = "factor"), col1 = c(5.006, 
5.936, 6.588)), class = "data.frame", row.names = c(NA, -3L))

# do what you need to do here
data$paragraphs <- as_paragraph(as_b("µ"), as_sup(data$Species))


ft <- flextable(data, col_keys = c("Species", "col1"))
ft <- compose(ft, part = "body", j = "Species", value = paragraphs)
ft
```

<img width="128" alt="Capture d’écran 2019-08-27 à 22 57 33" src="https://user-images.githubusercontent.com/4331618/63807483-13ce4d80-c91e-11e9-89bf-d96d9539a114.png">


I am not sure I understand you question, if this is the case, please add a minimal example we can discuss

David

**Comment by timsadler1988** [comment]
Nice, works like a charm - thank you!
