### ISSUE TITLE
Line breaks in cells are ignored

### ISSUE THREAD

**Issue by muranyia** [davidgohel/flextable#15]
Line breaks added as "\n" seem to be ignored in the content of cells.

**Comment by davidgohel** [comment]
yes, they are ignored... 

Next time, please explain better what you want to do and what is the issue. 

Also a short reproducible code helps to help. When I can copy paste a code, it's easier to modify and suggest solutions. 

KR

**Comment by muranyia** [comment]
Example code:
```
ft <- flextable(data.frame(x="A\nB C", y="D"))
ft <- width(ft, width=4)
ft
```
Do you mean that line breaks are deliberately ignored and the will be no way to insert line breaks inside cells?
