### ISSUE TITLE
option to set table row property for exact dimensions

### ISSUE THREAD

**Issue by HJAllen** [davidgohel/flextable#151]
I am trying to use flextable and officer to create labels mimicking word mail merge. All is well except the table cell row height property defaults to "At least" which throws off the specific dimensions required for the label formatting. 

It appears the table row property of interest is w:hRule and should be set to "exact". Snippet from word doc with the appropriate property set:
````
<w:trHeight w:hRule="exact" w:val="720"/>
````
 I'm not sure whether this is something that would be implemented in flextable or officer.

**Comment by HJAllen** [comment]
Simple work around
````
ft <- flextable::flextable(cars)
ft_xml <- gsub("<w:trHeight", '<w:trHeight w:hRule="exact"',
             flextable:::docx_str.flextable(ft))

doc <- officer:::body_add_xml(doc, str = ft_xml, pos = "on")
````

**Comment by davidgohel** [comment]
You are right, thanks for your comment. This is now implemented in the package.
