### ISSUE TITLE
Function as_chunk - spelling error in argument definition, same error elsewhere

### ISSUE THREAD

**Issue by dswpg** [davidgohel/flextable#152]
as_chunk has argument 'formater' - this should be 'formatter'

Error is elsewhere, including internal function 'formater' : (https://github.com/davidgohel/flextable/search?q=formater&unscoped_q=formater)

This would, obviously, be a breaking change.

**Comment by davidgohel** [comment]
Thanks, changing this does not seem to break anything on CRAN (just tried it) - I don't think `as_chunk` is much used by end users so I'll do the change.
