### ISSUE TITLE
including latex formulas in cells

### ISSUE THREAD

**Issue by ChristelSwift** [davidgohel/flextable#161]
hi there,

thank you very much for this great package and documentation, it's really useful.  I was just wondering if there is a way to include latex formulas in the cells?  eg  

$$\mu_0$$

**Comment by davidgohel** [comment]
Hi 

No that's not a feature. If you don't mind not using latex formula, you may be interested by: 

https://davidgohel.github.io/flextable/articles/display.html#sugar-functions-for-complex-formatting

KR
David
