### ISSUE TITLE
Partial match of 'span' to 'spans'

### ISSUE THREAD

**Issue by cucumberry** [davidgohel/flextable#164]
Similar to https://github.com/davidgohel/flextable/issues/87, I get a `Warning: partial match of 'span' to 'spans'` when using `flextable()`.

I've pinned it down to this line: https://github.com/davidgohel/flextable/blob/679917825f6870f67abcc7c3930e736a27aefe07/R/tabpart_format.R#L91

It should presumably say `x$spans$rows` instead.

**Comment by davidgohel** [comment]
Thanks, it's fixed
