### ISSUE TITLE
Merge by hidden column when target is set

### ISSUE THREAD

**Issue by DanChaltiel** [davidgohel/flextable#171]
Hi David,

I'm making a beautiful flextable with merges, but I want to use a hidden column to specify the merging.

Here is an output  example (which obviously does not make any sense):

`flextable(iris) %>% merge_v(j="Species", target="Petal.Width")
`

However, when I actually hid the column `Species` using `col_keys`, it does not work: 

`flextable(iris, col_keys = names(iris)[-5]) %>% merge_v(j="Species", target="Petal.Width")`
> ```
> Error in get_columns_id(x[[part]], j = j) : 
>   invalid columns selection:Species
> ```

Although, `myflextable$body$dataset` indeed contains the `Species` column so this might be achievable.

I think this may be happening inside the `get_columns_id` function. In the specific case of `target` being set in `merge_v`, using `names(x$dataset)` instead of `x$col_keys` may be more relevant and might resolve this issue.

What do you think about it?

PS: I think there is a typo in the help of `merge_v` for argument `j`("used" instead of "use")

**Comment by davidgohel** [comment]
Hi,

First sorry for the delay (I will also review your PR soon). 

Thanks! You are right, flextable should allow that. Your suggestion was good. I added `get_dataset_columns_id` so that dataset columns can also be used. 

`merge_v` can now use values from dataset.
