### ISSUE TITLE
colformat_num() interferes with text column alignment when rendered to word.docx

### ISSUE THREAD

**Issue by datarichard** [davidgohel/flextable#175]
Hi, thanks for the great package - it has saved me countless hours. And I think I found an (obscure but annoying) bug:

When I use colformat_num() function on a flextable object and render the flextable to an MS-Word document (docx), the text columns in the table are no longer left aligned. Using align_text_col() doesn't help. 

Here is a minimum reproducible example:

```
library(dplyr)
library(tibble)
library(tidyr)
library(flextable)
library(officer)

mtcars %>%
  rownames_to_column() %>%
  flextable() %>%
  colformat_num(digits = 0) %>%
  align_text_col() %>%
  autofit() -> ft

doc <- read_docx()
doc <- body_add_flextable(doc, value = ft)
print(doc, target = "example.docx")
```

The code creates a Word file in the current directory ("example.docx"), and when I open it in Word (Microsoft Word for Mac, 16.31), the first column `rowname` is centre-aligned rather than left-aligned as expected.

Hope that helps someone get started,

Rich

>R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.2
>
>Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib
>
>locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8
>
>attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
>
>other attached packages:
[1] officer_0.3.6   flextable_0.5.6 tidyr_0.8.3     tibble_2.1.1   
[5] dplyr_0.8.0.1  
>
>loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1        rstudioapi_0.10   xml2_1.2.0        knitr_1.22       
 [5] magrittr_1.5      tidyselect_0.2.5  uuid_0.1-2        R6_2.4.0         
 [9] rlang_0.4.0       tools_3.6.1       data.table_1.12.2 xfun_0.6         
[13] htmltools_0.3.6   systemfonts_0.1.1 assertthat_0.2.1  digest_0.6.18    
[17] crayon_1.3.4      zip_2.0.4         purrr_0.3.2       base64enc_0.1-3  
[21] evaluate_0.13     glue_1.3.1        rmarkdown_1.12    stringi_1.4.3    
[25] compiler_3.6.1    pillar_1.4.0      gdtools_0.2.1     pkgconfig_2.0.2

**Comment by davidgohel** [comment]
Hi,

This happens because you format a text column with a function made for formatting numeric columns. The column was not centered aligned but was containing spaces. By specifying wich columns should be formatted as numeric, your issue disappear.

```
library(dplyr)
library(tibble)
library(tidyr)
library(flextable)
library(officer)

mtcars %>%
  rownames_to_column() %>%
  flextable() %>%
  colformat_num(j = names(mtcars), digits = 0) %>%
  align_text_col() %>%
  autofit() -> ft

print(ft, preview = "docx")
``` 


<img width="807" alt="Capture d’écran 2020-01-06 à 13 01 37" src="https://user-images.githubusercontent.com/4331618/71816996-ba70ea80-3084-11ea-9937-f7b2296d18e3.png">
