### ISSUE TITLE
merge_v removes everything when a merged cell already exists

### ISSUE THREAD

**Issue by RABxx** [davidgohel/flextable#177]
I have a function that creates a flextable, then merges entire rows to make them like heading rows. I then want to `merge_v` on a column within the resulting flextable, but if it's already been merged horizontally the entire column becomes blank when I use `merge_v`

**Code:**
```
library(flextable)

df <- data.frame(
  X = rep(LETTERS[1:3], c(2, 3, 4)),
  Y = c(NA, '1', NA, '2', '3', NA, '4', '5', '6'),
  Z = rep(c('0.1', '0.05', '0.9'), c(2, 3, 4)),
  stringsAsFactors = F)

ft <- regulartable(df)
ft <- align_text_col(ft, align = 'left')
ft2 <- merge_h_range(ft, j1 = 1, j2 = 3, i = c(1, 3, 6)) # merge certain rows 
ft2 <- bg(ft2, bg = 'grey', j = 1, i = c(1, 3, 6)) # highlight rows to show they are merged

merge_v(ft, j = 'Z') # correctly merges consecutive matching values
merge_v(ft2, j = 'Z') # results in an empty column
```

**Output:**
![image](https://user-images.githubusercontent.com/48337093/72694767-435e4a80-3b8a-11ea-8046-fca2dc9e9812.png)

**Desired effect:**

Is it possible to make `merge_v` ignore the cells that are blank/already merged? I would like the Z values to be merged and centered excluding the top line of each letter section.

**Session Info:**

Using R v3.6.1, RStudio 1.1.456, flextable v0.5.5

**Comment by davidgohel** [comment]
> Is it possible to make merge_v ignore the cells that are blank/already merged? 

No this is not possible. 

> I would like the Z values to be merged and centered excluding the top line of each letter section.

You need to change the way you merge cells then, maybe with `merge_at`

---

PS : you don't need `regulartable` (they are now flextable). (from the manual) Function regulartable is maintained for compatibility with old codes made by users but be aware it produces the same exact object than flextable. I may deprecate this function later.
