### ISSUE TITLE
How to start new line inside cells

### ISSUE THREAD

**Issue by muranyia** [davidgohel/flextable#18]
Following up on #15, I'd like to ask  which is the best way to open new lines inside flextable cells.
I cannot do it using the following methods:
```
ft <- flextable(data.frame(x="A\nB C", y="D"))
ft <- width(ft, width=4)
ft
```
```
ft <- flextable(data.frame(x="A\u000D\u000AB C", y="D"))
ft <- width(ft, width=4)
ft
```
Thank you.

**Comment by davidgohel** [comment]
That's not possible the way you want. You can only have one paragraph in a cell (and a paragraph is a set of text chunk). 

This won't be implemented. 

The only suggestion I have here is to reshape your dataset in a tidy format so that A is on row 1, and "B C" on row 2.

**Comment by muranyia** [comment]
Thank you.
I'm wondering, however, if line breaks in the text could be interpreted as [soft returns](https://word.tips.net/T000170_Understanding_Hard_and_Soft_Returns.html). I think a paragraph can have soft returns within, and it still remains a single paragraph.

**Comment by davidgohel** [comment]
Yes, it is possible, but again, this will not be implemented. Maybe best solution for you is to implement a new package that fits exactly your needs!

**Comment by muranyia** [comment]
Thank you. I will try to find another way.

**Comment by AntoineBrisacier** [comment]
Hi David. I was about to write an issue for the same request. Feed line \n was working in ReporteRs but not with flextable. 
Muranyia, if you had solution to provide me I will be highly interested !
