### ISSUE TITLE
theme_zebra and align

### ISSUE THREAD

**Issue by neuwirthe** [davidgohel/flextable#182]
When using `theme_zebra()` `align` does not work any more, only the defaults are used.
Numeric columns always are right aligned, even when `align` is used to do otherwise.

```{r}
library(tidyverse)
library(flextable)
```

```{r}
my_df <- tibble(
  var1=letters[1:5],
  var2=1:5,
  var3=11:15
)
```

```{r}
my_df %>%
  flextable() %>% 
  align(j=2:3,align="center",part="all")
```

```{r}
my_df %>%
  flextable() %>% 
  align(j=2:3,align="center",part="all") %>% 
  theme_zebra()
```

**Comment by davidgohel** [comment]
As written in the documentation (the getting started section)  https://davidgohel.github.io/flextable/articles/overview.html#getting-started 

> Functions `theme_` are sugar functions whose role is to apply a set of formatting instructions to a flextable. For example, theme_vanilla set specific borders, right align paragraphs and make headers bold.

It is documented that `theme_` functions apply a set of formatting instructions (like alignment) but you are changing the alignment before theming and `theme_zebra ` is overwriting your previous command.

What do you mean by **does not work any more**? Do you want to say that it was working differently before?

**Comment by neuwirthe** [comment]
I meant that after adding theme_zebra alignment is not working any more.

**Comment by neuwirthe** [comment]
Explanation: In `ggplot2`, all the examples add the theme as the very last statement. So I was in the habit of transferring this idiom to `flextable`.

**Comment by davidgohel** [comment]
OK, no this is not the case - although I'd like to provide such a beautiful API one day.

Can I close the issue?
