### ISSUE TITLE
Need to document that

### ISSUE THREAD

**Issue by davidgohel** [davidgohel/flextable#184]
Hi there, I have had the same issue and using officedown has solved this -thanks. Just wondering if you can explain why using this solves the problem and/or point me to where in the documentation I can read more about this? Thanks.

_Originally posted by @alicebyers5 in https://github.com/davidgohel/flextable/issues/168#issuecomment-576719102_

**Comment by davidgohel** [comment]
@alicebyers5 I added a short explanation, hope you will find it useful 

https://davidgohel.github.io/flextable/articles/overview.html#notes-about-rmarkdownword_document

If not, let me know what is not clear enough :)

**Comment by alicebyers5** [comment]
Great, thanks David.
