### ISSUE TITLE
Cannot output minibars in a R Markdown context with Word output format

### ISSUE THREAD

**Issue by datarichard** [davidgohel/flextable#187]
Hi,

I'm having some trouble exporting to a Word doc when I have minibars in my table. When I run the code below, a Word doc (example.docx) is created but Word returns an error message when I try to open it. I can still open it in (MacOs) Pages, so this might be a Word problem or platform specific but I thought I would ask.

Ta, 

Rich

Code to produce the error:

```
---
output: word_document
---

```{r setup, include=FALSE}
library(flextable)
library(officer)
library(officedown)
```

```{r table}
myft <- flextable( head(iris, n = 10 ))

myft <- compose( myft, j = 4,
                 value = as_paragraph(
                   minibar(value = Petal.Width, max = max(Petal.Width))
                 ),
                 part = "body")

autofit(myft)
```

Error produced by Word when I try to open example.docx:

![Screen Shot 2020-02-12 at 8 13 23 pm](https://user-images.githubusercontent.com/28824961/74320273-71732b00-4dd4-11ea-9cf8-fd7db4823623.png)

I have MS Word for Mac version 16.16.19

sessioninfo produces the following output:

> R version 3.6.1 (2019-07-05)
> Platform: x86_64-apple-darwin15.6.0 (64-bit)
> Running under: macOS Catalina 10.15.3
> 
> Matrix products: default
> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] officedown_0.0.5.003 officer_0.3.6        flextable_0.5.7     
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.3        knitr_1.28        xml2_1.2.2        magrittr_1.5      uuid_0.1-2        R6_2.4.1         
>  [7] rlang_0.4.4       stringr_1.4.0     tools_3.6.1       data.table_1.12.6 xfun_0.12         rvg_0.2.3        
> [13] htmltools_0.4.0   systemfonts_0.1.1 yaml_2.2.1        digest_0.6.23     zip_2.0.4         base64enc_0.1-3  
> [19] memoise_1.1.0     evaluate_0.14     rmarkdown_2.1     stringi_1.4.5     compiler_3.6.1    gdtools_0.2.1

**Comment by davidgohel** [comment]
Hi,

Using images in flextable requires package officedown in a R Markdown context with Word output format.

It's documented in the note section: https://davidgohel.github.io/flextable/reference/minibar.html#note but I will add also this information in the vignette.
