### ISSUE TITLE
add_rows error when adding header line to 2 row header

### ISSUE THREAD

**Issue by michielve** [davidgohel/flextable#188]
Hello,

Until recently my code was working perfectly and I could generate flextables without any problems. However, now I run into an error when trying to add a new row to a header.

```

library(flextable)
data <- iris[c(1:3, 51:53, 101:104),]

myft <- flextable(
  head(mtcars), 
  col_keys = c("am", "carb", "gear", "mpg", "drat" ))

typology <- data.frame(
  col_keys = c("am", "carb", "gear", "mpg", "drat" ),
  col_b = c("1", "2", "3", "4","5"),
  col_c = c("a", "b", "c", "d","e"),
  stringsAsFactors = FALSE)

ft <- set_header_df(myft, mapping = typology, key = "col_keys" ) # Setting header with typology
ft <- add_header_lines(ft, top = TRUE, values = 'new row') # Add new row to header
ft 
 ```

This results in the following error:
**Error in x$data[i, j] <- value : 
number of items to replace is not a multiple of replacement length**

The strange thing is that when I only have a header of 1 row the new row gets added. I can't figure out where this error originates but I assume it is with the add_row function.

I have already tested a clean installation of R 3.6.2 and 3.6.1 with the flextable library and the dependencies but still run into this error.

Any help is highly appreciated.

sessionInfo output:

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] flextable_0.5.7

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3        digest_0.6.23     R6_2.4.1          magrittr_1.5      evaluate_0.14     zip_2.0.4         rlang_0.4.4      
 [8] gdtools_0.2.1     uuid_0.1-2        data.table_1.12.8 xml2_1.2.2        rmarkdown_2.1     tools_3.6.2       officer_0.3.6    
[15] xfun_0.12         compiler_3.6.2    systemfonts_0.1.1 base64enc_0.1-3   htmltools_0.4.0   knitr_1.28

**Comment by michielve** [comment]
Update:
Installing the old source 0.5.6.tar.gz solves the issue.

**Comment by davidgohel** [comment]
Hi, thanks for reporting this.

I just pushed a fix - I will submit this version on CRAN soon

**Comment by michielve** [comment]
Perfect thanks!
