### ISSUE TITLE
Error when parsing column names with spaces

### ISSUE THREAD

**Issue by lodderig** [davidgohel/flextable#19]
Using column names with blanks triggers a parsing error.

`library(dplyr)
library(officer)
library(flextable)

ds<-mtcars%>%dplyr::rename(`Number of cylinders`=cyl)

ft<-flextable(ds)
`

> Error in parse(text = x, keep.source = FALSE) : 
>   <text>:1:8: unexpected symbol
> 1: Number of

           ^

**Comment by davidgohel** [comment]
You don't need to rename columns, you should use header functions.

https://davidgohel.github.io/flextable/articles/layout.html#manage-headers

**Comment by davidgohel** [comment]
duplicate of #13
