### ISSUE TITLE
flextable does not work with slidy output

### ISSUE THREAD

**Issue by neuwirthe** [davidgohel/flextable#190]
`flextable` does not work in a slidy presentation

The error message is

```
Error in knit_print.flextable(x, ...) unsupported format for flextable rendering:slidy
```

This is the start of the document
---
title: "slidy"
author: "testing guy"
date: "2/16/2020"
output: slidy_presentation
---

```{r}
library(flextable)
test_df <- data.frame(
  num=1:3,
  char=letters[1:3]
)
flextable(test_df) 
```

**Comment by davidgohel** [comment]
It is possible now with the latest github version
