### ISSUE TITLE
winbuilder cannot install flextable

### ISSUE THREAD

**Issue by depmc232** [davidgohel/flextable#194]
Hi David,

I am writing a package that outputs a flextable as a png. It runs on my mac (after I reinstalled Cairo and gdtools as suggested by [this post](https://stackoverflow.com/questions/48199737/cant-install-flextable). 

Running the package through winbuildr, however, results in this error: 

Error: package or namespace load failed for 'edbuildr' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]): there is no package called 'flextable'

Below is a minimal version of the function which requires flextable in my package:

![image](https://user-images.githubusercontent.com/36750356/75798827-239f7200-5d45-11ea-86c2-55f91d17a6d2.png)

It seems as though this is an issue with loading flextable. How do you recommend I proceed with this package so that it runs successfully on other machines?

**Comment by davidgohel** [comment]
Hi,

flextable is on CRAN and has no error. Did you import the package? Where could I have a look at your package source if available?

**Comment by depmc232** [comment]
The source file is not available, but the attached zip is a copy of the function with help file comments and below is the imports included in our package DESCRIPTION file. 

[Imports: 
    dplyr,
    magrittr,
    openxlsx,
    scales,
    stringr,
    flextable,
    tidyselect (>= 1.0.0)
Encoding: UTF-8
LazyData: true
RoxygenNote: 7.0.2
Suggests: 
    knitr,
    rmarkdown]


[sd_neighbor_table.R.zip](https://github.com/davidgohel/flextable/files/4283393/sd_neighbor_table.R.zip)

**Comment by davidgohel** [comment]
I have no clue why you are facing that. I doubt I can help here, see https://CRAN.R-project.org/package=flextable, flextable is already imported by other packages.

I just launch a test on winbuilder with a dummy example/adaptation, let's wait now... 

A quick comment about your code - at least for the HTML output, this line will cause you issues:

```
  my_table <- flextable::autofit(my_table, add_w = -15.0, add_h = 0.15) ## adjust height and width
```

In your example, this can lead to negative widths and make the table *invisible* as widths are not positive.

**Comment by depmc232** [comment]
great thank you! looking forward to seeing the winbuildr results

**Comment by davidgohel** [comment]
(still no feedback - winbuilder may have issues...)

**Comment by davidgohel** [comment]
OK, I think I did something wrong. I gave away with winbuilder and tried with rhub and ... yes, I can read:

```
* checking package dependencies ... ERROR

Package required but not available: 'flextable'
See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.
```

Digging into the error messages reveal that issue may come from `digest`... 

```
 330#> package 'base64enc' successfully unpacked and MD5 sums checked
 331#> package 'data.table' successfully unpacked and MD5 sums checked
 332#> Error in read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) :
 333#> cannot open the connection
 334#> Calls: ... i.p -> .install.winbinary -> unpackPkgZip -> read.dcf
 335#> In addition: Warning messages:
 336#> downloaded length 0 != reported length 249498
 337#> 1: In download.file(url, destfile, method, mode = "wb", ...) :
 338#> 2: In unzip(zipname, exdir = dest) : error 1 in extracting from zip file
 339#> 3: In read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) :
 340#> cannot open compressed file 'digest/DESCRIPTION', probable reason 'No such file or directory'
 341#> Execution halted
```

I don't really know how to manage that. digest is required by officer, officer is required by flextable. And everything seems ok on CRAN.

Any suggestion is welcome...

**Comment by davidgohel** [comment]
ok, digest is not really useful, it was but it's not anymore (this is related to some cleaning I am actually workng on). 

I just dropped `digest` dependency from officer and will submit to CRAN soon.

Thanks for bringing that to my attention!

(However, it does not explain why digest cannot be installed from winbuilder or rhub...)

**Comment by davidgohel** [comment]
I think it was a temporary issue with CRAN... 

Here are the winbuilder results:

```
* using log directory 'd:/RCompile/CRANguest/R-release/importft.Rcheck'
* using R version 3.6.3 (2020-02-29)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* checking for file 'importft/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'importft' version '0.1.0'
* package encoding: UTF-8
* checking CRAN incoming feasibility ... NOTE
Maintainer: 'David Gohel <david.xxx@xxx.fr>'

New submission
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking serialization versions ... OK
* checking whether package 'importft' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking for future file timestamps ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* loading checks for arch 'i386'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
** checking use of S3 registration ... OK
* loading checks for arch 'x64'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
** checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... [6s] OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking examples ...
** running examples for arch 'i386' ... [2s] OK
** running examples for arch 'x64' ... [2s] OK
* checking PDF version of manual ... OK
* checking for detritus in the temp directory ... OK
* DONE
Status: 1 NOTE
```

**Comment by davidgohel** [comment]
Could you close the issue if you don't meet that issue anymore?
