### ISSUE TITLE
Merging non-empty Cells

### ISSUE THREAD

**Issue by MyKo101** [davidgohel/flextable#195]
The ability to combine multiple cells into a single cell is extremely useful, but the fact that all information of the secondary cells is lost can be irritating. This is no always possible to do before the data is processed.

The example that I'm trying to implement is in regards to footnotes. I have a table which requires quite a few footnotes and presenting them vertically takes up a lot of space. I can run the `merge_at()` function on the footer, `merge_at(x,part="footer")`, but this loses all but the first footnote.

I'm currently running a difficult workaround where I extract `x$footer$content$content$data` and collapse the rows myself, however I'm worried that this might cause an incompatibility at some point with the other elements of `x`, since I'm not collapsing it anywhere else.
#

**Comment by davidgohel** [comment]
Could you provide a minimal reproducible code? 

You should not use internals structures (`x$footer$content$content$data`) unless you really understand how it is working and you accept your code may be broken with new releases.

**Comment by MyKo101** [comment]
That was one of my worries. Particularly since I know it is a complicated structure that I don't fully understand. I found the aspect that contains the actual contents of a cell, and so I collapsed just that bit (since I assumed the `merge_at()` function would essentially ignore any other data in the footer).

Here's the function that I'm using at the minute along with a simple example tibble.

```
collapse_footer <- function(x,sep="; ",footer.height=NULL)
{
  
  #Extract the content part of the footer
  # This is a 2d-list with 1 row for each footnote and
  #     one column for each column in the table
  old.content <- x$footer$content$content$data
    
  #This will replace the previous content
  new.content <- list()
  
  #Create a row in the content frame as a separator for the final footnote section
  sep.content <- old.content[1,1][[1]][1,]
  sep.content$txt <- sep
  sep.content$vertical.align <- NA
  
  #For every row in the old content (i.e. every footnote), apart from the final one
  for(i in 1:(nrow(old.content)-1))
  {
    # bind the old content with the separator
    old.content[i,1][[1]] <- rbind(old.content[i,1][[1]],sep.content)
    
    #We don't need the seperator at the end, so we only do nrow(.) - 1
  }
  
  #rbind the entire first column of the 2d-list
  new.content[[1]] <- do.call(rbind,old.content[,1])
  
  # Adjust the seq_index for the new content
  new.content[[1]]$seq_index <- 1:nrow(new.content[[1]])
  
  #Add in the remaining columns to the new content
  for(i in (2:ncol(old.content))) new.content[[i]] <- old.content[1,i][[1]]
  
  #Turn it into a 2d-list
  dim(new.content) <- c(1,ncol(old.content))
  
  #Set the names to be the same as the original content
  colnames(new.content) <- colnames(old.content)
  
  #Put the new stuff back into the original flextable
  x$footer$content$content$data <- new.content
  
  #merge the entire footer into a single cell
  x <- merge_at(x,part="footer")
  
  #Grab the height of a footer-cell
  if(is.null(footer.height)) footer.height = tail(dim(x)$heights,1)
  
  #Set the height of all footer-cells to 0
  x <- height(x,height=0,part="footer")
  
  #Reset the height of the first row of footer-cells
  x <- height(x,i=1,height=footer.height,part="footer")
  
  x
}

#Create a tibble
x <- tibble(Col = c("Red","Blue","Blue-Green","Yellow"),
       x = sample(100,4),y = sample(100,4)) %>%
  flextable %>%
  footnote(i=1,j=1,value=as_paragraph("Red_Foot"),ref_symbols = "a") %>%
  footnote(i=2:3,j=1,value=as_paragraph("Blue_Foot"),ref_symbols = "b")

#Show footnotes in column formation
x

#Collapse them into a single row
x %>% collapse_footer
```

**Comment by davidgohel** [comment]
Thanks, I understand. I agree this could be really useful.

It's possible with function `compose` but could be difficult to code. I will try to implement a new function or option.

I don't know yet what is the best solution. As a very first rough idea, would you find useful a boolean argument `append=TRUE` in `footnote`?

**Comment by MyKo101** [comment]
Something like that would be ideal for the `footnote()`function.

I think that having an option in `merge_at()` to paste cell contents together, rather than overwrite, would be a useful first step. (more advanced features would be deciding whether merging for 2d arrays would be by row or by column).

Can `compose()` be used to paste together two paragraphs? I'm not too great with your paragraph objects, but think they're a fantastic feature. I think if I knew how to stick two together, I could probably write something up.

Maybe a vignette (or some intuitive functions) for string manipulation within the context of paragraphs would be useful too.

Then the `merge_at()` function could be used in the code for generating the inline `footnote()`

**Comment by davidgohel** [comment]
About the vignette: https://davidgohel.github.io/flextable/articles/display.html#compose-function

I thought it was clear enough...

**Comment by MyKo101** [comment]
it's clear how to concatenate unformatted values but can that also work for cells that already contain paragraphs? Does it work vertically as well as horizontally?

**Comment by davidgohel** [comment]
In short, 

> can that also work for cells that already contain paragraphs? 

No, it will replace existing paragraph. Thanks I will clear that in the vignette.

> Does it work vertically as well as horizontally?

I don't understand what means *working vertically as well as horizontally*. 
`compose(as_paragraph(...))` is vectorized over columns and can handle also external values. So maybe only horizontally, as `dplyr::mutate` or many R functions.  
Compose is generating one paragraph, it's up to the user to compose the paragraph. 

I will try to complete the vignette with answers to your questions. Thanks for your feedback

**Comment by davidgohel** [comment]
I added two notes:

https://github.com/davidgohel/flextable/blob/master/docs/articles/display.html#L794

https://github.com/davidgohel/flextable/blob/master/docs/articles/layout.html#L484
