### ISSUE TITLE
flextable in R Markdown

### ISSUE THREAD

**Issue by AndyKKim** [davidgohel/flextable#199]
Hello David,

Although I do not have extensive experience in flextable, I am a huge fan of the package due to its vast flexibility of table appearance.  

I have a couple of questions about flextable, though.  My main usage of the package is to export the table along with some texts to Word document with RMarkDown.  When exporting to html file, I see that the table comes out as expected.  However, when exporting the table to Word, it seems like there is no control over how to size the height of the table.  I tried different parameters with height(data, height=) function in flextable, but keep getting same table with default spacing of 1.15 in Word.  

My second question is regarding the footnote function with flextable.  Is there anyway I can control the size of the footnote so that it will come out smaller in Word?  It seems like it has a default size of 10 in word and need to make it much smaller.

Thank you so much David!

Andy

**Comment by AndyKKim** [comment]
Hello David,

After going through the closed issues, I was able to tackle the problem with height of each row.  Thank you for adding the functionality to address the issue. :) I still have not figured out how to control the size of the footnote (not footer), though.  Do you have any recommendations?  Thank you!

**Comment by davidgohel** [comment]
Can you share a minimal reproducible code of what you've done so far?

**Comment by AndyKKim** [comment]
Hello David,

Thank you so much for getting back to me so quickly.  So here we go.

---
output:
  word_document: 
    reference_docx: C:/R Office Auto/template.docx
  html_document: default
---

```{r setup, include=FALSE}
library(readxl)
library(scales)
library(flextable)
library(tidyr)
library(data.table)
library(officer)
library(knitr)
```
```{r, echo=FALSE}
stats <- matrix(c('a','b','c',1,2,3,4,5,6),nrow=3,ncol=3) #temporary dataset

ft_table <- stats %>%
  flextable() %>%
  align(j=1,align="left") %>%
  fontsize(size = 10, part='body') %>%
  fontsize(i=1, size = 14, part='body') %>%
  width(j = 1, width = 3.5) %>% 
  width(j = 2, width = 1) %>%
  height(height = 0.2, part='body') %>%
  hrule(rule = 'exact', part = "all") %>%
  footnote(i=2, j=1, value= as_paragraph(c("Some footnote"))
           , ref_symbols=c('1'), part='body')

ft_table
``` 
#End of sample code

So what I want to have the control of is the font size of the footnote "Some footnote" at the bottom of the table.  Normally, font size for footnote in MS Word is 7 but when I knit the table to Word, it always comes out with font size of 10, which requires manual adjustment of the font size in Word.  

Also, I was wondering if you have considered placing the footnote at the bottom of the Word document page instead of below each table.  That is where footnotes are almost always placed.  With R Markdown, they have a legit functionality that places footnotes at the bottom of the document.  If we can combine footnotes from different chunks in R Markdown into one set of footnotes with same font type and size would be ideal.  Of course, that would require huge amount of time and effort as with other packages, I believe.  Thank you so much for looking into this, David!

Andy

**Comment by davidgohel** [comment]
Hum, there is an issue in your code. I had to add `as.data.frame` to make it work.

```
library(flextable)
library(magrittr)

stats <- matrix(c('a','b','c',1,2,3,4,5,6),nrow=3,ncol=3) #temporary dataset

ft_table <- stats %>% as.data.frame() %>% 
  flextable() %>%
  align(j=1,align="left") %>%
  fontsize(size = 10, part='body') %>%
  fontsize(i=1, size = 14, part='body') %>%
  width(j = 1, width = 3.5) %>% 
  width(j = 2, width = 1) %>%
  height(height = 0.2, part='body') %>%
  hrule(rule = 'exact', part = "all") %>%
  footnote(i=2, j=1, value= as_paragraph(c("Some footnote"))
           , ref_symbols=c('1'), part='body') %>% 
  fontsize(i=1, size = 7, part='footer')

print(ft_table, preview = "docx")
```

About the feature request, this is not planned for now, sorry.

**Comment by AndyKKim** [comment]
Thank you so much, David!  Although I did not mention in in my code, I did have as.data.frame in my original code.  However, adding the last line fontsize(i=1, size = 7, part='footer') did the trick.  Thanks!
