### ISSUE TITLE
Could flextable be used to 'update' tables in a word document ?

### ISSUE THREAD

**Issue by behrica** [davidgohel/flextable#2]
My use case is to generate a very complex word document which contains lots of tables (bu as well lots of narrative, picture and others).
250 pages in total ...
So a rather complex _report_.

My user have pain (and pressure) and want autogenerate as much as possible,
because the data changes daily, while they write the dcoument.

We will try to go the markdown/bookdown road for the moment.

In this the most difficult question is, how to generate a word document with 'nice tables'.
(Nice mainly meaning multiple, gouped column headers)

I see three alternatives by now:

1) Using knitr::kable and leave the final formating to be done (once !!) by hand at the very end of the process
2) I managed to use ReporteRs and "as.html()' and the 'webshot' package to convert any Flextable into a png, which could be included as is in the word file
3) Combine markdown and ReportRs in an other way (???)

I looked as well as other solution, like pure ReporteRs, markdown and others but discarded them.

Seeing your package now, and by looking at some documen.xml from a docx file, it seems to me that we are not very far away from a functionality which could replace inside an existing word file,
a xml segment <w:tbl>  ... </w:tbl> with a 'new version' of the xml segment.
You function wm_flextable seems to produce the correct xml already.

Probbaly the question to solve is how to identify, which w:tbl elemnt to replace.
Using a table caption, which is just before the <w:tbl> elemnt could solvve this.

It looks like this:

```
<w:tbl>
      <w:tblPr>
        <w:tblStyle w:val="TableNormal"/>
        <w:tblW w:type="pct" w:w="0.0"/>
        <w:tblLook w:firstRow="1"/>
        <w:tblCaption w:val="Table 1 caption of kable"/>
      </w:tblPr>
      <w:tblGrid/>
```

So I could imagine a function, like:

```
replaceTableAfterCaption(docx,caption,newFt)
```
which searches the document for a matching element <w:tblCaption w:val= ...> and replaces the <w:tbl> node afterwards with the new xml comming from wm_flextable(newFt).

This question is somehow related to https://github.com/davidgohel/ReporteRs/issues/154 .

I see this problem as one of the greatest weaknesses of bookdown, for convincing word users to replace word reports by rmarkdown.
For PDF(=latex) and html output bookdown has nearly 'all needed features', but the current table support in markdown/pandoc is very weak.

If a function like the one above is possible, I could imagine a workflow like this:

1. create rmd files
2. knitr (which writes primtive tables with a unique caption using knitr::kable)
   -> stores as well on disk all FlexTable objects)
3. pandoc to docx (results in all tables present in Word file with (unique) captions) 
4. Post process the word file and replace all tables with the FlexTable objects created before in step 2

Do you think this is realistic ?

**Comment by davidgohel** [comment]
Sorry for the delay, I was off last week and quite busy before...

> 3/ Combine markdown and ReportRs in an other way (???)

Nope. ReporteRs and pandoc are not working together unfortunatly.

> If a function like the one above is possible, I could imagine a workflow like this [...]

It should be technically possible. I am working slowly on a new ReporteRs version that should make that possible - but this is not for now. I will need to complete this package first.

**Comment by davidgohel** [comment]
It's almost a year but now it's possible to use flextable with rmarkdown `word_document` output. 
pandoc > 2.0 is required. This is available on github and soon on cran.
