### ISSUE TITLE
Cannot add footnote

### ISSUE THREAD

**Issue by awcm0n** [davidgohel/flextable#204]
The example code:
`ft <- flextable(head(iris))`
`ft <- footnote( ft, i = 1, j = 1:3,`
`            value = as_paragraph(
              c("This is footnote one",
                "This is footnote two",
                "This is footnote three")
            ),
            ref_symbols = c("a", "b", "c"),
            part = "header")`
`ft <- valign(ft, valign = "bottom", part = "header")`
`ft <- autofit(ft)`

Creates the following error with flextable version 0.5.9:

Error in footnote(ft, i = 1, j = 1:3, value = as_paragraph(c("This is footnote one",  : 
unused arguments (i = 1, j = 1:3, value = as_paragraph(c("This is footnote one", "This is footnote two", "This is footnote three")), ref_symbols = c("a", "b", "c"), part = "header")

**Comment by davidgohel** [comment]
Please, follow instructions that are given when you open a new issue. I am closing the issue as it is not reproducible. Probably a conflict with another footnote function.
