### ISSUE TITLE
Autofit does not work when using `add_header_row`

### ISSUE THREAD

**Issue by DanChaltiel** [davidgohel/flextable#207]
Hi David,

When I use `autofit` on a regular `flextable`, there is no problem and the output is pretty:

```r
library(dplyr)
library(flextable)

iris2=iris %>% mutate(Species=as.character(Species))
iris2[2,2]=6.6666666
iris2[2,5]="setosaaaaaaaaaaaa"
iris2 %>% 
    head(15) %>%  
    flextable %>% 
    autofit
```

However, when I use it after adding a header row, some columns are not with the right width.

```r
iris %>% 
    head(15) %>%  
    flextable %>% 
    add_header_row(values = c("Sepals", "Petals", "Species"), colwidths = c(2,2,1)) %>% 
    autofit
```

Here is my `sessionInfo()`. 

> ```
> R version 3.6.3 (2020-02-29)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 17763)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
> [4] LC_NUMERIC=C                   LC_TIME=French_France.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] flextable_0.5.10 crosstable_0.1.0 expss_0.10.1     forcats_0.5.0    stringr_1.4.0   
>  [6] readr_1.3.1      tidyr_1.0.2      tibble_2.1.3     ggplot2_3.3.0    tidyverse_1.3.0 
> [11] glue_1.3.2       purrr_0.3.3      dplyr_0.8.5      rlang_0.4.5      survival_3.1-11 
> [16] testthat_2.3.2  
> ```

I have the latest version of the github package.

Best regards,
Dan

**Comment by davidgohel** [comment]
Hi Dan,

Can you show me on the image below what is not working? (an ugly red line made with MS Paint is fine if possible)

<img width="467" alt="Capture d’écran 2020-03-29 à 12 33 07" src="https://user-images.githubusercontent.com/4331618/77846971-f023fc00-71b9-11ea-9785-1892a6e8bf93.png">



<img width="402" alt="Capture d’écran 2020-03-29 à 12 33 18" src="https://user-images.githubusercontent.com/4331618/77846974-f4e8b000-71b9-11ea-9731-efe6a3f0540b.png">

Thanks
David

**Comment by davidgohel** [comment]
Note your sessionInfo is weird. You have loaded packages but some packages should also be seen in a part named `loaded via a namespace (and not attached)`

**Comment by DanChaltiel** [comment]
Sorry, this is weird but since I restarted R and RStudio, I cannot reproduce the problem.
My sessioninfo was a bit long so I trimmed out what I thought irrelevant info.
I'll re-open this issue if I'm ever able to reproduce it, otherwise sorry for the false alert.

**Comment by davidgohel** [comment]
Ok, thanks for the feedback

**Comment by DanChaltiel** [comment]
Hi David,

I could reproduce the error: 
![image](https://user-images.githubusercontent.com/15105152/79215160-88251500-7e4b-11ea-9251-417867347f4b.png)

Here is the flextable in RDS format: [bug.zip](https://github.com/davidgohel/flextable/files/4474730/bug.zip)

If you want more info about how this flextable is constructed, it is generated by my package [crosstable](https://github.com/DanChaltiel/crosstable) (a rewrite of [biostat2](https://github.com/eusebe/biostat2)), by [this function](https://github.com/DanChaltiel/crosstable/blob/master/R/cross_to_flextable.R) specifically.

This time, it resists when I restart RStudio.

Here is my session-info:
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                   LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] crosstable_0.1.0 dplyr_0.8.5     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6         lattice_0.20-40      tidyr_1.0.2          png_0.1-7            assertthat_0.2.1    
 [6] digest_0.6.25        R6_2.4.1             backports_1.1.6      acepack_1.4.1        evaluate_0.14       
[11] ggplot2_3.3.0        pillar_1.4.3         gdtools_0.2.2        rlang_0.4.5          uuid_0.1-4          
[16] rstudioapi_0.11      data.table_1.12.8    rpart_4.1-15         Matrix_1.2-18        flextable_0.5.9     
[21] checkmate_2.0.0      rmarkdown_2.1        splines_3.6.3        stringr_1.4.0        foreign_0.8-75      
[26] htmlwidgets_1.5.1    munsell_0.5.0        compiler_3.6.3       xfun_0.12            pkgconfig_2.0.3     
[31] systemfonts_0.1.1    base64enc_0.1-3      htmltools_0.4.0      nnet_7.3-12          tidyselect_1.0.0    
[36] tibble_3.0.0         gridExtra_2.3        htmlTable_1.13.3     Hmisc_4.4-0          matrixStats_0.56.0  
[41] fansi_0.4.1          crayon_1.3.4         grid_3.6.3           gtable_0.3.0         lifecycle_0.2.0.9000
[46] magrittr_1.5         scales_1.1.0         zip_2.0.4            cli_2.0.2            stringi_1.4.6       
[51] latticeExtra_0.6-29  xml2_1.3.1           ellipsis_0.3.0       vctrs_0.2.4          nortest_1.0-4       
[56] Formula_1.2-3        RColorBrewer_1.1-2   tools_3.6.3          forcats_0.5.0        glue_1.4.0          
[61] officer_0.3.8        purrr_0.3.3          expss_0.10.2         jpeg_0.1-8.1         survival_3.1-11     
[66] colorspace_1.4-1     cluster_2.1.0        knitr_1.28    
```

**Comment by davidgohel** [comment]
Awesome package! From what I understand, it's totally possible to get **table one** with your package, isn't it?

Let me know if you need something. I'll do my best to help you (given the context ;) ).  One minor note, you could use `as_flextable.crosstable` instead of `cross_to_flextable`, this is the reason I made available this generic function.  

About the bug, could you update flextable package and let me know if you still have the issue? (`remotes::install_giithub("davidgohel/flextable")`). At the moment, you should get version `0.5.10.004`. 

With this version I get:

<img width="697" alt="Capture d’écran 2020-04-14 à 13 33 34" src="https://user-images.githubusercontent.com/4331618/79220610-975c9080-7e54-11ea-96fd-e5fd8ede5214.png">

**Comment by davidgohel** [comment]
Another note, you could add a call to `valign` to make each value of `label` vertically top aligned

**Comment by DanChaltiel** [comment]
Thanks a lot, I'm very happy that you like it! Yes, it is indeed designed to get **table one** easily. There were other packages but I was not happy with them and I thought `biostat2` lacked the `tidyverse` interface that I like so much. 

I'm quite a beginner in package development, so don't hesitate to tell me if you have any thought or ideas of improvement :-) 

I didn't know about `as_flextable` as I only use `flextable` itself. This may require some refactoring but I'll definitely consider it.

I tried with `flextable` github version and autofit worked very well. Reverting to CRAN version made it reappear so I guess **the problem is solved**, thank you very much.

About `valign`, yes, I shall add an option for the user thanks for the suggestion. But if you want vertically top aligned labels to publish in scientific articles, note that editors usually reject merged-cell tables. Here, you might want to use the `compact` option (or method) that gives the "publishable" output.

**Comment by davidgohel** [comment]
I just had a try, `compact` option is great!

Basically, the change is the following:

```
#' @importFrom flextable as_flextable
as_flextable.crosstable = function(x, auto.fit = TRUE, compact = FALSE, show.test.name = TRUE, 
                              by_header = NULL, keep_id = FALSE,
                              generic.labels=list(id = ".id", variable = "variable", value = "value", 
                                                  total="Total", label = "label", test = "test", effect="effect", ...))
```

and then rename all `crosstable` to `x`
