### ISSUE TITLE
Exclude one or several columns in merge_v()

### ISSUE THREAD

**Issue by fdecarpentier** [davidgohel/flextable#209]
Hi David,

I needed to merge_v() in all the columns except for a few.
I did it this way: 

``` R
library(flextable)
library(tidyverse)

colExclude <- function(DataFrame, colToExclude){
  return(colnames(DataFrame)[!colnames(DataFrame) %in% colToExclude])
}

dat <- data.frame(
  letters1 = c("a", "b", "b", "c"), 
  letters2 = c("d", "e", "b", "b"), 
  letters3 = c("a", "c", "c", "f"), 
  letters4 = c("a", "a", "c", "c"),
  number = 1:4, stringsAsFactors = FALSE )

myft <- flextable(dat) %>%
  merge_v(j = colExclude(dat, c("letters2"))) %>%
  theme_box()
```

Is there a more simple way? Do you find it interresting? 
Thanks for the nice package!

Félix

**Comment by davidgohel** [comment]
No, there is no other *selector* than https://davidgohel.github.io/flextable/articles/selectors.html

But some could be added: `col_exclude`, `col_match`, ...

Let's keep that as an improvement to be done

**Comment by fdecarpentier** [comment]
Yeah I agree it is just a small improvement

**Comment by fdecarpentier** [comment]
Yeah I agree it is just a small improvement

**Comment by davidgohel** [comment]
Hi, I did a small change that enable column exclusions with formula syntax:

``` r
library(flextable)
library(magrittr)

dat <- data.frame(
  letters1 = c("a", "b", "b", "c"), 
  letters2 = c("d", "e", "b", "b"), 
  letters3 = c("a", "c", "c", "f"), 
  letters4 = c("a", "a", "c", "c"),
  number = 1:4, stringsAsFactors = FALSE )

myft <- flextable(dat) %>%
  merge_v(j = ~ . -letters2 -letters4 ) %>%
  theme_box()
plot(myft, webshot = "webshot2")
```

![](https://i.imgur.com/kPC2nvh.png)

<sup>Created on 2020-05-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


I will work later on some more complex selectors but it will require some time.
