### ISSUE TITLE
How can we generate Table number with Caption?

### ISSUE THREAD

**Issue by namkyodai** [davidgohel/flextable#211]
The package seems not to generate the Table number, but only with Caption.
For caption, we can use

ft <- flextable( head( iris ) )
ft <- set_caption(ft, "my caption")
ft

how is about number of table?

**Comment by davidgohel** [comment]
Please follow the guidelines.

<img width="753" alt="Capture d’écran 2020-03-25 à 18 26 37" src="https://user-images.githubusercontent.com/4331618/77566636-3d585300-6ec6-11ea-9f51-b78b019362c9.png">

I supposed you are only talking about Word format. Yes, that's not a feature right now. See other open issues.
