### ISSUE TITLE
some vertical inner lines not showing when using merge_v and theme_box

### ISSUE THREAD

**Issue by reyntjesr** [davidgohel/flextable#212]
Hi,

If I write a pdf file or a microsoft word document something goes wrong with the vertical inner lines when using merge_v and the theme_box theme. Below I created an example file.

```R
#' ---
#' title: "A bug in flextable"
#' author: "Robert"
#' date: '`r format(Sys.Date(), "%d %B, %Y")`'
#' geometry: margin=1cm
#' output:
#'   html_document:
#'      toc: true
#'      highlight: zenburn
#'   pdf_document:
#'     toc: true
#'     number_sections: true
#'     highlight: zenburn
#' documentclass: article
#' classoption: a4paper
#' ---
#'
#+ include = F
library(pander)
library(officer)
library(flextable)
library(tidyverse)

panderOptions('digits', 2)
panderOptions('round', 2)
panderOptions('keep.trailing.zeros', TRUE)
options(Encoding="UTF-8")
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)

df = tibble(col1=rep('a1',12),col2=rep(c('b1','b2','b3'),each=4),
            col3=rep(paste0(rep('c',6),1:6),each=2),col4=1:12)

#' A table with merged rows
#' 
#+ results='asis', echo=FALSE
ft = flextable::flextable(df) %>%
  merge_v(j=c("col1","col2","col3")) %>%
  empty_blanks() %>%
  theme_box() %>%
  autofit()
ft

# rmarkdown::render("./flextableBug.R",output_file="flextableBug.pdf",output_format='pdf_document',encoding="UTF-8")
```
I create a file by running the code below:

```R
rmarkdown::render("./flextableBug.R",output_file="flextableBug.pdf",output_format='pdf_document',encoding="UTF-8")
```
I now have a pdf file with a table but in this table the vertical lines between col1 and col2, and col2 and col3 are missing. 

I also noticed this bug when creating word documents with tables using your officer package.

If I run this code in RStudio and look at the Viewer output or render it tho html output the table is correct.

> sessionInfo()
> R version 3.6.3 (2020-02-29)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 18363)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=Dutch_Netherlands.1252  LC_CTYPE=Dutch_Netherlands.1252    LC_MONETARY=Dutch_Netherlands.1252
> [4] LC_NUMERIC=C                       LC_TIME=Dutch_Netherlands.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] flextable_0.5.9 officer_0.3.8   pander_0.6.3    forcats_0.5.0   stringr_1.4.0   dplyr_0.8.5     purrr_0.3.3    
>  [8] readr_1.3.1     tidyr_1.0.2     tibble_3.0.0    ggplot2_3.3.0   tidyverse_1.3.0
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.4        lubridate_1.7.4   here_0.1          lattice_0.20-38   ps_1.3.2          assertthat_0.2.1 
>  [7] rprojroot_1.3-2   digest_0.6.25     utf8_1.1.4        R6_2.4.1          cellranger_1.1.0  backports_1.1.5  
> [13] reprex_0.3.0      evaluate_0.14     httr_1.4.1        highr_0.8         pillar_1.4.3      gdtools_0.2.1    
> [19] rlang_0.4.5       uuid_0.1-4        readxl_1.3.1      rstudioapi_0.11   data.table_1.12.8 callr_3.4.3      
> [25] rmarkdown_2.1     webshot_0.5.2     tinytex_0.22      munsell_0.5.0     broom_0.5.5       compiler_3.6.3   
> [31] modelr_0.1.6      janitor_1.2.1     xfun_0.12         pkgconfig_2.0.3   systemfonts_0.1.1 base64enc_0.1-3  
> [37] htmltools_0.4.0   tidyselect_1.0.0  fansi_0.4.1       crayon_1.3.4      dbplyr_1.4.2      withr_2.1.2      
> [43] grid_3.6.3        nlme_3.1-144      jsonlite_1.6.1    gtable_0.3.0      lifecycle_0.2.0   DBI_1.1.0        
> [49] magrittr_1.5      scales_1.1.0      zip_2.0.4         cli_2.0.2         stringi_1.4.6     fs_1.3.2         
> [55] xml2_1.2.5        ellipsis_0.3.0    generics_0.0.2    vctrs_0.2.4       openxlsx_4.1.4    tools_3.6.3      
> [61] glue_1.3.2        hms_0.5.3         processx_3.4.2    yaml_2.2.1        colorspace_1.4-1  rvest_0.3.5      
> [67] knitr_1.28        haven_2.2.0     

 

kind regard,
  Robert

**Comment by davidgohel** [comment]
Hi, I think you are in this case: https://davidgohel.github.io/flextable/reference/knit_print.flextable.html#pdf-chunk-options

Could you try to install webshot2 and then in your Rmd, use `knitr::opts_chunk$set(webshot="webshot2")`?

**Comment by reyntjesr** [comment]
Not as fast as you with my reaction, but that was because installation via github was down ;-)

It worked! I now see vertical lines inside the table after I installed webshot2 and added the knitr option. 
Will webshot2 become the default in the future?

**Comment by davidgohel** [comment]
Unfortunately, it needs to be on CRAN to be the default one :(
