### ISSUE TITLE
Can gdtools be moved to from Imports to Suggests?

### ISSUE THREAD

**Issue by ddsjoberg** [davidgohel/flextable#215]
Following up on our chat about installation issues with the gdtools package (https://github.com/ddsjoberg/gtsummary/issues/462). Can gdtools be moved to from `Imports:` to `Suggests:`?

**Comment by davidgohel** [comment]
Hi,

I tried to but for now, it's not possible. I reduced dependencies, but I still need gdtools to compute font metrics (for `autofit`). 

Please, let me know if you still have issues with gdtools and I will re-open that issue. As far as I know, there is no more installation issues.
