### ISSUE TITLE
Troubles with `knit_print.flextable` in `github_document`

### ISSUE THREAD

**Issue by DanChaltiel** [davidgohel/flextable#216]
Hi David,

As you may know, I'm using `flextable` extensively in my package `crosstable`.

Among other things, I use it to render crosstables on my GitHub readme page.

Unfortunately, it seems that flextables are not working perfectly in Rmarkdown when `output: github_document`, as it throws the following error when hitting RStudio's "knit" button:

> ```
> Error in (function (x, ...)  : 
>   unsupported format for flextable rendering:gfm
> Calls: <Anonymous> ... freduce -> withVisible -> <Anonymous> -> <Anonymous>
> Execution halted
> ```

For now, my readme page is using images with `flextable::save_as_image`, but the result is not very satisfying.

Surprisingly, it almost works if you knit it manually in the console (`knitr::knit("test.Rmd")`), you can even Preview the result in Rstudio. However, the output is not that pretty, with extra margin in flextable cells:

![image](https://user-images.githubusercontent.com/15105152/80690047-89eb0b80-8ace-11ea-9148-4fd72d81a56c.png)

Here is an MRE that you could try to knit manually and with RStudio:

```Rmd
---
    output: github_document
---

```{r}
    library(crosstable)
    crosstable(mtcars2, cyl, carb, by=vs) %>% 
    as_flextable(keep_id=TRUE)
`` ` #extra blank space for github markdown, to be removed

```

I'm using `flextable v0.5.10.005`, downloaded from GitHub a minute ago. Here is my whole `session_info`:

> ```
> > sessionInfo()
> R version 3.6.3 (2020-02-29)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 17763)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
> [4] LC_NUMERIC=C                   LC_TIME=French_France.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] crosstable_0.1.0
> 
> loaded via a namespace (and not attached):
>  [1] zip_2.0.4            Rcpp_1.0.4.6         pillar_1.4.3         compiler_3.6.3       forcats_0.5.0       
>  [6] base64enc_0.1-3      tools_3.6.3          uuid_0.1-4           digest_0.6.25        packrat_0.5.0       
> [11] lattice_0.20-40      evaluate_0.14        lifecycle_0.2.0.9000 tibble_3.0.0         checkmate_2.0.0     
> [16] htmlTable_1.13.3     pkgconfig_2.0.3      rlang_0.4.5          Matrix_1.2-18        cli_2.0.2           
> [21] rstudioapi_0.11      xfun_0.13            xml2_1.3.1           officer_0.3.8        dplyr_0.8.5         
> [26] stringr_1.4.0        knitr_1.28           systemfonts_0.1.1    gdtools_0.2.2        vctrs_0.2.4         
> [31] htmlwidgets_1.5.1    grid_3.6.3           nortest_1.0-4        tidyselect_1.0.0     glue_1.4.0          
> [36] data.table_1.12.8    R6_2.4.1             fansi_0.4.1          survival_2.44-1      rmarkdown_2.1       
> [41] foreign_0.8-75       tidyr_1.0.2          purrr_0.3.3          magrittr_1.5         splines_3.6.3       
> [46] backports_1.1.6      ellipsis_0.3.0       htmltools_0.4.0      matrixStats_0.56.0   expss_0.10.2        
> [51] assertthat_0.2.1     flextable_0.5.10.005 stringi_1.4.6        crayon_1.3.4      
> ```

**Comment by davidgohel** [comment]
Hi,

Yes, markdown output is not supported (`unsupported format for flextable rendering:gfm`). 

You can use image with "webshot2":

````````
---
output: github_document
---

```{r include=FALSE}
library(magrittr)
library(flextable)
library(crosstable)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-",
  webshot="webshot2"
)
```

## plot method

> you can get unwanted extra margins, unless you define fig.width and fig.height

```{r 'plot'}
crosstable(mtcars2, cyl, carb, by=vs) %>%
  as_flextable(keep_id=TRUE) %>% 
  plot()
```

## save_as_image method

```{r}
crosstable(mtcars2, cyl, carb, by=vs) %>%
  as_flextable(keep_id=TRUE) %>% 
  save_as_image(path = "example.png")
```

![](example.png)
````````


![webshot](https://user-images.githubusercontent.com/4331618/80693462-5363bf80-8ad3-11ea-8171-10bceff50464.png)

**Comment by DanChaltiel** [comment]
Thanks for your response.

This may turn to a feature request because, after a bit of browsing, it seems that using `knit_print.flextable` gives an HTML table that is almost perfectly printed in markdown.

Therefore, I used `trace(flextable:::knit_print.flextable, edit=TRUE)` to add support for `gfm` by simply adding `html|slidy|gfm` [here](https://github.com/davidgohel/flextable/blob/bff5dce04ecd149d78ca59ebff4cdaad6b708426/R/printers.R#L259).

This also required adding a line to the header:

```yaml
---
    output: github_document
    always_allow_html: true
---
```
Again, the output is only almost perfect, with some extra margin and sometimes missing borders depending on the viewer (RStudio, GitHub), but it still seems like a neat feature to have around.

Would you consider adding some support?

**Comment by davidgohel** [comment]
It seems to me there are different subjects in your point:

1. image size, this is not about flextable, this is about GitHub style that display images with 100% width. flextable `save_as_image` can not change the way png are rendered with on GitHub pages. 
2.  you want to display HTML tables in GitHub README (managed by gfm). As far as I know, it is not possible to add HTML in GitHub pages (issues, README, etc.). That's why packages (flextable, kableExtra, htmlwidgets) don't embed example in the README. Are you sure you did not only test your solution with RStudio HTML viewer?

Can you show me how you will handle that limitation? A flextable like this:

<img width="1315" alt="Capture d’écran 2020-05-01 à 11 38 50" src="https://user-images.githubusercontent.com/4331618/80796771-5e385600-8ba0-11ea-98fc-d642cdfa083c.png">

is displayed in an MD page hosted by GitHub as this:

<img width="676" alt="Capture d’écran 2020-05-01 à 11 34 32" src="https://user-images.githubusercontent.com/4331618/80796789-6b554500-8ba0-11ea-9112-6e22dafbab68.png">

**Comment by davidgohel** [comment]
@DanChaltiel I am closing that issue. I will re open if necessary

**Comment by DanChaltiel** [comment]
No, you are perfectly right, this was GitHub limitation.

HTML tables are understood but styles are not, even inline, so borders cannot be controlled that way. And the GFM way of making borders does not allow fused cells so there seems to be nothing to be done for a full `flextable` compatibility.

I stuck to `save_as_image` and displayed images using HTML tags so I can fix the `height` attribute. I wanted them centered so I even had to put them in a `<p align="center">`. The final output is not perfect but I guess I cannot do better for the moment.

**Comment by DanChaltiel** [comment]
Hi @davidgohel 

Just an update to tell you that I finally had to make this fix in my package for `pkgdown` compatibility, as markdown format is required for the home file.

The file [https://github.com/DanChaltiel/crosstable/blob/master/R/knit_print_debug.R](https://github.com/DanChaltiel/crosstable/blob/master/R/knit_print_debug.R) is the exact copy of the one from your package, except for line 18 where I added `markdown_strict` and `gfm`.

This is used in [index.Rmd](https://github.com/DanChaltiel/crosstable/blob/master/pkgdown/index.Rmd) on line 20, the result being the beautiful `flextables` that you can see on [https://danchaltiel.github.io/crosstable](https://danchaltiel.github.io/crosstable/). I had to add a few lines of CSS ([here](https://github.com/DanChaltiel/crosstable/blob/master/pkgdown/extra.css)) to remove the extra padding though.

Of course, this doesn't change the problem on the GitHub Readme file, where I still have to use images, but it might somehow be a reason to support markdown output after all.
