### ISSUE TITLE
Rendering html or markdown inside the tables

### ISSUE THREAD

**Issue by omarelashkar** [davidgohel/flextable#217]
Hello,
Flextable package is excellent in all aspects except that data text is not easily formating  using html like in kable as no real html get rendered in the tables. Further, there are excellent package called `gt` that has the functions [`fmt_markdown()`](https://gt.rstudio.com/reference/fmt_markdown.html) which can really make life easier by just writing markdown inside table.

I'd really like to see equivalent function in flextable.

**Comment by davidgohel** [comment]
Hello,

Yes, using HTML does make the table impossible to render in pptx or docx. 
You can use function `compose` to compose any paragraph made of text chunk. You can even mix images and text. 

Could you share an example of what you've tried so far? I don't see what you want to achieve, I'd like to see really what you were trying to do with HTML.

Note there is an excellent package `ftExtra` that let you add markdown in flextable: https://cran.r-project.org/web/packages/ftExtra/

**Comment by omarelashkar** [comment]
Thank you for your insight!

I am doing a quiz project where I want to generate reports from an online quiz in shiny. The app basically is getting data from user input, where the student is supposed to write something like formatted paragraphs that might include equation. of course I will use some sort of WYGIWYS text editor and get their answers saved in the database. 
Then, I want to report their answers.

I have used ftExtra. The idea is great however it only supports few markdown notations. Not only that, but it also breaks when I have a string that contains. The idea is to be appraised however. 

Thank you for your time!

**Comment by atusy** [comment]
@omarelashkar 
Please feel free to open an issue for the feature request in https://github.com/atusy/ftExtra, 
although I am not sure if I can support it.

**Comment by davidgohel** [comment]
Sorry, Markdown is not supported by flextable as well as latex equations. To format complex things, use function `compose`
