### ISSUE TITLE
Autofit in Word is making long tables to go out of margins

### ISSUE THREAD

**Issue by artasom** [davidgohel/flextable#219]
I have looked into the documentation but I have been unable to find whether this is an expected behaviour or not, so I think this can be a bug. When printing a table in Word and the text is long and the autofit function is invoked, the table goes beyond the margins of the page.

This is the code to reproduce the behaviour

``` r
library(flextable)

common_text1 <- "This is the text of the "
common_text2 <- " \n column and "
common_text3 <- " line"


df <- data.frame(FirstColumn=character(),
                 SecondColumn=character(), 
                 ThirdColumn=character(),
                 FourthColumn=character(), 
                 FithColumn=character(), 
                 SixthColumn=character(), 
                 stringsAsFactors=FALSE) 

for (line in c("first", "second", "third")) {
  new_vector <- c()
  for (column in c("first", "second", "third")) {
    new_vector <- c(new_vector, c(paste0(common_text1, column, common_text2, line, common_text3)))    
  }
  df[nrow(df) + 1,] = new_vector
}

flextable(df) %>% 
  print(preview = "docx")
#> Error in flextable(df) %>% print(preview = "docx"): could not find function "%>%"

flextable(df) %>% autofit() %>%
  print(preview = "docx")
#> Error in flextable(df) %>% autofit() %>% print(preview = "docx"): could not find function "%>%"
```

<sup>Created on 2020-05-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

And the session info

``` r
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=English_Belgium.1252  LC_CTYPE=English_Belgium.1252    LC_MONETARY=English_Belgium.1252 LC_NUMERIC=C                    
[5] LC_TIME=English_Belgium.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reprex_0.3.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6    ps_1.3.2        digest_0.6.25   R6_2.4.1        evaluate_0.14   rlang_0.4.5     fs_1.4.1        callr_3.4.3    
 [9] whisker_0.4     rmarkdown_2.1   tools_3.6.3     xfun_0.13       compiler_3.6.3  processx_3.4.2  clipr_0.7.0     htmltools_0.4.0
[17] knitr_1.28    
```

With the first table creation, the result obtained is

![image](https://user-images.githubusercontent.com/6305118/81473659-3f6d3b80-9200-11ea-9dda-9a41f446dd1d.png)

With the second one, the table goes beyond the margins

![image](https://user-images.githubusercontent.com/6305118/81473673-56139280-9200-11ea-859f-846d406bfbd5.png)

What I was expecting to get is something like

![image](https://user-images.githubusercontent.com/6305118/81473675-60ce2780-9200-11ea-87b4-e830f8f571a5.png)

That is obtained with the first example and using the Autofit > Autofit to contents option in Word.

Am I doing something wrong?

Than you for your wonderful package!

**Comment by davidgohel** [comment]
Hi,

`autofit` was not my biggest naming idea as users are thinking it is the Word feature. The function documentation has just been updated with this concern.

That said, it seems to me your issue is:

* how to get that *Word autofit* feature
* how to get a table width equals to 100% in a Word document...

I will try to add these feature soon (I don't know yet if possible but it is planned to work on this)

**Comment by artasom** [comment]
Hi,

Thank you for your prompt response. I am never good at naming functions myself... Indeed, what you mention are the functionalities I was looking for. I was able to hack the second one with the code posted at https://stackoverflow.com/questions/57175351/flextable-autofit-in-a-rmarkdown-to-word-doc-causes-table-to-go-outside-page-mar

Again, thank you for the work you do to bring us this great package.

**Comment by davidgohel** [comment]
OK, I have a solution I am happy with! 

Use new function `set_table_properties` and you should get what you want. It works with HTML and Word.

```
library(flextable)
library(magrittr)

common_text1 <- "This is the text of the "
common_text2 <- " \n column and "
common_text3 <- " line"


df <- data.frame(FirstColumn=character(),
                 SecondColumn=character(), 
                 ThirdColumn=character(),
                 FourthColumn=character(), 
                 FithColumn=character(), 
                 SixthColumn=character(), 
                 stringsAsFactors=FALSE) 

for (line in c("first", "second", "third")) {
  new_vector <- c()
  for (column in c("first", "second", "third")) {
    new_vector <- c(new_vector, c(paste0(common_text1, column, common_text2, line, common_text3)))    
  }
  df[nrow(df) + 1,] = new_vector
}

flextable(df) %>% 
  set_table_properties(width = 1, layout = "autofit") %>% 
  print(preview = "docx")
```


<img width="1022" alt="Capture d’écran 2020-05-11 à 00 19 36" src="https://user-images.githubusercontent.com/4331618/81511940-23ab8780-931d-11ea-9bc5-a01a7370769c.png">

**Comment by artasom** [comment]
Thanks a lot!
