### ISSUE TITLE
Column widths have no effect in Firefox/IE

### ISSUE THREAD

**Issue by bescoto** [davidgohel/flextable#22]
The width() function does not seem to affect displayed column widths in the Firefox and Internet Explorer (checked with v45.8.0 and 11.0 respectively).  Chrome (v56.0) works for me however.

Here's a code snippet that illustrates the issue:

```
library(tidyr)
library(flextable)
library(officer)

print(data.frame(a=1:2, b=3:4)
      %>% flextable()
      %>% width(j=1:2, width=1:2))
```

The attached image shows what the table looks like for me on these two browsers.  As you can see, the two columns seem to be about the same size, and small/auto-fit, instead of being 1 and 2 inches respectively.

![flextable width example](https://user-images.githubusercontent.com/296094/28176280-6676e3dc-67bc-11e7-83bb-f0945cfd9e95.png)

BTW, I'm switching over from ReporteRs now, flextable+officer looks like an improvement, just trying to iron out the details.  Oh, and I'm using the github version of flextable.

**Comment by davidgohel** [comment]
Thanks,

I saw that last week but did not find time to correct it yet.

**Comment by bescoto** [comment]
Here's something I noticed, which also provides a workaround.  This is in context of using a Shiny app to display flextable tables:

If instead of using the flextable package's rendertabwid and tabwidOutput functions, if I extract the raw HTML from a flextable object ft using tabwid(ft)$x$html, and then display it using shiny::renderUI and shiny::htmlOutput, I don't see this bug at all.

In fact, I prefer using the more generic renderUI/htmlOutput functions in this case, as it fits better a general framework which is passing html around.

My only suggestion would be to add a documented function like flextable_to_html which wraps around tabwid(ft)$x$html and would be more stable/discoverable.

Thanks,
Ben

PS: in case it wasn't clear what I was talking about with Shiny, here is some code to display a flextable in a browser.  There is some irrelevant crap, but hopefully that doesn't obscure the point.

```
.foo_table_shiny_ui <- shiny::fluidPage(
  shiny::sidebarLayout(
    shiny::sidebarPanel("sidebar", width=2),
    shiny::mainPanel(
             shiny::h2("Exhibit Table"),
             shiny::htmlOutput("table")
           )))

.FooTableShinyServer <- function(ft) {
  ## Return Shiny server to display the given exhibit_table
  ShinyServer <- function(input, output) {
    output$table <- shiny::renderUI(flextable::tabwid(ft)$x$html)
  }
  return(ShinyServer)
}

shiny::shinyApp(ui=.foo_table_shiny_ui,
                server=.FooTableShinyServer(ft))
```

**Comment by davidgohel** [comment]
Can you test the fix please?

**Comment by bescoto** [comment]
Fixed!  In the example I gave, widths seem to be respected now in the versions of Firefox and Internet Explorer that I run.  Thanks!
