### ISSUE TITLE
0.5.10 can not render to word, with error "child process not responding r will terminate it"

### ISSUE THREAD

**Issue by xindyhu** [davidgohel/flextable#221]
I have the same Rmd code that I was able to render to both HTML and word before. 
Then I upgraded my flextable from 0.5.8 to 0.5.10, the HTML render runs fine, but the word render will error out in the middle. The R console shows *#$^$#*!@(#& and then I get a pop-up saying "child process not responding r will terminate it".
I downgraded my flextable from 0.5.10 to 0.5.9 and this has fixed it.
I don't know what changes between 0.5.9 and 0.5.10, any additional info on that front would be helpful.
Thanks!

**Comment by davidgohel** [comment]
Help me to help you :)

When submitting a new issue:

- [ ] Provide the code that is producing the error, it has to be a minimal reproducible example.
Stackoverflow is providing good explanations about it: https://stackoverflow.com/help/mcve. You can use package `reprex` to help you: http://reprex.tidyverse.org/. The most popular R stackoverflow question is about the subject: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

- [ ] Provide the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example. 

- [ ] Make sure you did check you had the latest version of the package on CRAN (and on github if issue exists with CRAN version).

**Comment by xindyhu** [comment]
@davidgohel Thank you for the reply. I couldn't recreate the same error after I upgrade flextable to 0.5.10 and officer to 0.3.11, so I will close this ticket.
