### ISSUE TITLE
as_flextable() method for gt objects

### ISSUE THREAD

**Issue by bwiernik** [davidgohel/flextable#224]
I've had some students express interest in the new `gt` package from the RStudio group: https://gt.rstudio.com/

The package looks like it has a nice interface for constructing tables, but it seems like Office export isn't on their development plan. It would be great if there were an as_flextabl.gt() method to convert a gt object to a flextable for Office output.

**Comment by davidgohel** [comment]
I am not sure, but it seems to me flextable is providing the same functions since few years. Why not just using flextable then?

**Comment by bwiernik** [comment]
The main reason would be interoperability--to be able to produce proper PDF or Office tables using the same script.

**Comment by moleps** [comment]
...or perhaps look into gtsummary which provides good options for exporting to Office via flextable and PDF.

**Comment by davidgohel** [comment]
package huxtable is also providing PDF and office since a long time also!

**Comment by bwiernik** [comment]
Yes, there are many tabling packages. 

The question is about supporting gt given the popularization efforts by RStudio.

**Comment by davidgohel** [comment]
Sorry, I don't think I can spend time creating a tool to turn `gt` objects into `flextable` objects, it's a lot of work and it's possible that `gt` will bring docx/pptx output in the future. 

The users of `flextable` are asking for RTF and PDF output and I prefer to spend time on this before, if I find time :)
