### ISSUE TITLE
lambda function in flextable

### ISSUE THREAD

**Issue by perlatex** [davidgohel/flextable#228]
``` r
library(tidyverse)
library(flextable)

flextable(head(iris, n = 10)) %>%
  color(
    i = ~ Sepal.Length > mean(Sepal.Length),
    j = ~ Sepal.Length,
    color = "orange"
  ) %>%
  color(
    i = ~ Sepal.Width > mean(Sepal.Width),
    j = ~ Sepal.Width,
    color = "orange"
  ) %>%
  color(
    i = ~ Petal.Length > mean(Petal.Length),
    j = ~ Petal.Length,
    color = "orange"
  ) %>%
  color(
    i = ~ Petal.Width > mean(Petal.Width),
    j = ~ Petal.Width,
    color = "orange"
  )
```

Can there be a simpler way ?  such as lambda function for each column.

**Comment by davidgohel** [comment]
Hi,

Yes, color can be a function (see [color manual](https://davidgohel.github.io/flextable/reference/color.html)). The example is using package `scales` but you can create any function, it only has to return a vector of colors:

```
colwise_color_fun <- function(x){
  col <- character(length = length(x))
  col[] <- "transparent"
  col[x > mean(x)] <- "orange"
  col
}
flextable(head(iris, n = 10)) %>%
  color(
    j = 1:4,
    color = deff
  ) 
```


### With you code

<img width="380" alt="Capture d’écran 2020-08-20 à 23 59 15" src="https://user-images.githubusercontent.com/4331618/90830015-2d438300-e341-11ea-8e4c-c61ec676c02f.png">


### With my suggestion

<img width="384" alt="Capture d’écran 2020-08-20 à 23 59 55" src="https://user-images.githubusercontent.com/4331618/90830071-464c3400-e341-11ea-9fe0-45706e578cca.png">



--

Another example with `bg`:

```
library(flextable)
library(magrittr)
library(scales)
library(officer)

cor_matrix <- cor(mtcars)

colourer <- col_numeric(
  palette = c("blue", "wheat", "red"),
  domain = c(-1, 1))

std_border <- fp_border(width = 1, color = "white")
data.frame(rowname = row.names(cor_matrix), stringsAsFactors = FALSE) %>%
  cbind(cor_matrix) %>%
  flextable() %>%
  border_outer(part="all", border = std_border ) %>%
  border_inner_h(border = std_border, part="all") %>%
  border_inner_v(border = std_border, part="all") %>%
  compose(i = 1, j = 1, value = as_paragraph(""), part = "header") %>%
  compose(j = colnames(cor_matrix), value = as_paragraph(""), part = "body") %>%
  bg(j = colnames(cor_matrix), bg = colourer) %>%
  align(align = "center", part = "all") %>%
  height_all(height = .5) %>%
  width(width =  .5)
```

<img width="396" alt="Capture d’écran 2020-08-21 à 00 04 59" src="https://user-images.githubusercontent.com/4331618/90830447-fa4dbf00-e341-11ea-934f-c66babc77438.png">

**Comment by perlatex** [comment]
Thank you for your help, I've learned a lot from your answer.
