### ISSUE TITLE
Merged cell border issue in powerpoint

### ISSUE THREAD

**Issue by bescoto** [davidgohel/flextable#23]
It seems the border properties of merged cells aren't respected when a table is exported in powerpoint.  It looks fine in HTML however.  Here's some example code:

```
library(tidyr)
library(flextable)
library(officer)

ft <- (data.frame(a=1:2, b=3:4)
  %>% flextable()
  %>% border(i=1, j=1:2, part="header",
             border.bottom=fp_border(color="red"))
  %>% merge_at(i=1, j=1:2, part="header"))

pres <- (read_pptx()
  %>% add_slide(layout = "Title and Content", master = "Office Theme")
  %>% ph_with_flextable(value = ft, type = "body")
  %>% print(target="header_underline_example.pptx"))
```

In HTML, the ft flextable looks fine:

![flextable html border](https://user-images.githubusercontent.com/296094/28176496-44379540-67bd-11e7-870c-d94926c9d9f6.png)
 
But the exported "header_underline_example.pptx" has mismatched header borders:

![flextable ppt border](https://user-images.githubusercontent.com/296094/28176665-e3131ef0-67bd-11e7-93d7-0f6d92dc670a.png)

(Note only half of the header bottom border is red.)  I've opened the ppt with Powerpoint 2010 and 2016 with same results.  I'm running the github version of flextable.

Thanks!

**Comment by bescoto** [comment]
I looked a bit more into this by opening a ppt produced by officer/flextable in MS-Powerpoint, editing it manually in Powerpoint to fix the border, and then differencing the resulting XML.  The problem seems to stem from conflicts between the borders of one cell and the overlapping borders of adjacent cells.

For instance, in the original example above, in the Powerpoint produced by flextable/officer, the "3" cell would have a black top border, which overrides the red bottom border of the cell above it.  In order for the border to show up as red, the "3" cell needs to have a red top border.

The same problem shows up in merged cells when the right border of one cell conflicts with the left border of the next cell to the right.  Furthermore, the problem doesn't show up on the table edges, when there are no adjacent cells:
```
ft2 <- (data.frame(a=1:5, b=6:10)
  %>% flextable()
  %>% border(i=1, j=1:2, part="header",
             border.bottom=fp_border(color="red"))
  %>% merge_at(i=1, j=1:2, part="header")
  %>% border(i=2, j=1:2, part="body",
             border.bottom=fp_border(color="red"))
  %>% merge_at(i=2, j=1:2, part="body")
  %>% border(i=4:5, j=1, part="body",
             border.left=fp_border(color="red"))
  %>% border(i=4:5, j=1, part="body",
             border.right=fp_border(color="red"))
  %>% merge_at(i=4:5, j=1, part="body"))

pres2 <- (read_pptx()
  %>% add_slide(layout="Title and Content", master="Office Theme")
  %>% ph_with_flextable(value=ft2, type="body")
  %>% print(target="other tests.pptx"))
```
![more border examples](https://user-images.githubusercontent.com/296094/29943496-4501ff92-8e5f-11e7-89a5-91dba278ba44.png)

There is a pretty easy workaround for flextable users: simply set the relevant borders manually, e.g.:
```
ft_workaround <- (data.frame(a=1:2, b=3:4)
  %>% flextable()
  %>% border(i=1, j=1:2, part="header",
             border.bottom=fp_border(color="red"))
  %>% merge_at(i=1, j=1:2, part="header")
  %>% border(i=1, j=1:2, part="body",
             border.top=fp_border(color="red")))

pres_workaround <- (read_pptx()
  %>% add_slide(layout="Title and Content", master="Office Theme")
  %>% ph_with_flextable(value=ft_workaround, type="body")
  %>% print(target="header_underline_workaround.pptx"))
```
![border-workaround](https://user-images.githubusercontent.com/296094/29943229-5df925a8-8e5e-11e7-920b-1e5484453df8.png)

However, arguably it would be better to handle this inside flextable.  For instance, in the styles.R file, the `border` function could be modified to automatically set any interior border in two places: the specified cells and adjacent cell which shares that border (if any).  I was going to prepare a patch in this direction, but then realized it could mess up other targets (e.g. HTML).  It would also be harder to keep track of table modifications (e.g. added rows/columns).

Perhaps it would be better instead to leave the border function as-is, and have an PPT-specific pass that fixes up conflicting borders before printing.  Or maybe there's another solution, or maybe it's best not to do anything and just have users use the workaround.  Anyway, just reporting my initial findings here.

Thanks,
Ben

**Comment by davidgohel** [comment]
thanks, I already faced that with ReporteRs, your diagnostic is correct. I will work on that when I will have a clean solution.

**Comment by davidgohel** [comment]
Sorry for the delay.

> However, arguably it would be better to handle this inside flextable.

Yes. I did not want to change `border()` behavior for maintenance reasons but I found a way to make it easier. I have implemented new functions that should be used instead of `border()`.

* `hline()`: set bottom borders of one or all parts of a flextable. 
* `hline_top()`: set top border of one or all parts of a flextable. 
* `hline_bottom()`: set bottom border of one or all parts of a flextable. 
* `vline()`: set right borders of one or all parts of a flextable. 
* `vline_left()`: set left border of one or all parts of a flextable.
* `vline_right()`: set right border of one or all parts of a flextable.


```
ft2 <- data.frame(a = 1:5, b = 6:10) %>%
  flextable() %>%
  hline( i = 1, j = 1:2, part = "header", border = fp_border(color = "red") ) %>%
  hline_top( j = 1:2, part = "body", border = fp_border(color = "red") ) %>%
  merge_at(i = 1, j = 1:2, part = "header") %>%
  hline( i = 2, j = 1:2, part = "body", border = fp_border(color = "red") ) %>%
  merge_at(i = 2, j = 1:2, part = "body") %>%
  vline_left( i = 4:5, part = "body", border = fp_border(color = "red") ) %>%
  vline( i = 4:5, j = 1, part = "body", border = fp_border(color = "red") ) %>%
  merge_at(i = 4:5, j = 1, part = "body")
```

<img width="443" alt="capture d ecran 2018-03-05 a 17 57 11" src="https://user-images.githubusercontent.com/4331618/36988272-c37df8ae-209e-11e8-97a2-f32cfa7fa6dc.png">

These new functions are taking care of propagating properties to adjacent cells. 



```
dat <- iris[c(1:5, 51:55, 101:105),]
ft <- regulartable(dat, col_keys = c("Species", "Sepal.Length",  "Sepal.Width", "Petal.Length", "Petal.Width" )) 
ft <- border(x = ft, part="all", border =fp_border(color="transparent"))
ft <- merge_v(ft, j = 1) 
ft <- hline(ft, part="all", border = std_border )
ft <- hline(ft, part="header", i = 1, border = big_border )
ft <- hline(ft, part="body", i = c(5, 10, 15), border = big_border )
ft <- hline_top(ft, part="header", border = big_border )
ft <- vline(ft, part = "all", border = std_border)
ft <- vline_left(ft, part = "all", border = std_border)
ft
```

<img width="492" alt="capture d ecran 2018-03-05 a 18 01 55" src="https://user-images.githubusercontent.com/4331618/36988527-6184398c-209f-11e8-819b-09c806c6d22f.png">

I will probably send that version soon on CRAN.
