### ISSUE TITLE
Newline in headers

### ISSUE THREAD

**Issue by moleps** [davidgohel/flextable#232]
Being able to add a line break in the header and output to word would be sweet. Using \n in the string only results in \n in the word table.

**Comment by davidgohel** [comment]
https://davidgohel.github.io/flextable/articles/display.html#two-lines-in-a-cell

**Comment by davidgohel** [comment]
This is already answer here: 

* #178 
* #56

Can you provide a reprex?

**Comment by moleps** [comment]
Sorry. I was not aware of set_header_labels. I was changing the keys directly in df$header$content$content$keys. 

Works like a charm using set_header_labels. Keep up the good work.

**Comment by davidgohel** [comment]
OK,

Avoid using internals unless you are sure what to do. There also a risk that this structure change and break your scripts. If using only exported/documented functions, you should be safe ;)
