### ISSUE TITLE
Warnings in vignettes/display.html

### ISSUE THREAD

**Issue by niszet** [davidgohel/flextable#235]
Hi,

I noticed that the [vignettes/display.html](https://cran.r-project.org/web/packages/flextable/vignettes/display.html#simple-functions-for-formatting-content) in cran repository has warnings related to `colformat_int` and `colformat_num` (argument of `col_keys`, should use `j` ?).

These are still used in vignettes in `display.Rmd`.

https://github.com/davidgohel/flextable/blob/master/vignettes/display.Rmd#L66

and

https://github.com/davidgohel/flextable/blob/master/vignettes/display.Rmd#L67

Check list is here. But because this is not caused by flextable execution result, I only check the CRAN and issues.

---

- [ ] Provide the code that is producing the error, it has to be a minimal reproducible example.
Stackoverflow is providing good explanations about it: https://stackoverflow.com/help/mcve. You can use package `reprex` to help you: http://reprex.tidyverse.org/. The most popular R stackoverflow question is about the subject: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

- [ ] Provide the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example. 

- [ ] Make sure you did checked you had the latest version of the package on CRAN (and on github if issue exists with CRAN version).

- [ ] Make sure you searched in the *open* and *closed* issues on the github repository.

**Comment by davidgohel** [comment]
Thank you for that.

Sorry for the checklist, it is not relevant here, it is used to frame bug reports.
