### ISSUE TITLE
Possible to have global options for all tables in an .Rmd?

### ISSUE THREAD

**Issue by nstjhp** [davidgohel/flextable#236]
Hi, thanks for the nice package. I have what may be more of a feature request, or I'm not finding what I want easily but would it be possible to be able to set some global options that apply to all tables in e.g. an Rmd file? Which could be set in the 1st chunk for instance.

I find myself repeatedly typing out the likes of `ft %>% set_formatter_type(fmt_double = "%.04f", na_str="NA") %>% theme_booktabs(fontsize=16) %>% etc.` 

Or shall I just make a function similar to

```
myflextable = function(data, ...) {
    x <- flextable(data, ...)
    x <- set_formatter_type(x, fmt_double = "%.04f", na_str="NA")
    x <- theme_booktabs(x, fontsize=16)
    return(x)
}
```

**Comment by davidgohel** [comment]
Yes, you could make a function as in your message. But I guess, it could be good to have (optional) global options about font family, font sizes but also *theme* function. 

Maybe a modest set of options that can be defined with something inspired from `knitr::opts_chunk$set()`? Would you be happy with such a solution?

**Comment by nstjhp** [comment]
Yes 👍 that sounds great. I think anything that could control the appearance of multiple tables is a candidate for being an (optional) global option, and the knitr opts_chunk is what I had in mind.

Thinking further as you mention setting the theme, maybe one (other?) way is that a user could easily adapt your default themes (à la ggplot) and they use their own theme to control the table appearance? I could see that being useful when making reports where all tables should have a certain standard style.

**Comment by davidgohel** [comment]
This is now available. It is documented here:

* https://davidgohel.github.io/flextable/articles/format.html#default-formatting-properties
* https://davidgohel.github.io/flextable/reference/set_flextable_defaults.html

It's now possible to define global settings:

```
library(flextable)
set_flextable_defaults(
  font.family = "Roboto", font.size = 14, font.color = "#111111",
  theme_fun = "theme_vanilla")
qflextable(head(iris))
qflextable(head(mtcars))
```

<img width="732" alt="Capture d’écran 2020-10-21 à 19 23 20" src="https://user-images.githubusercontent.com/4331618/96755396-f6d2c480-13d2-11eb-90c4-bcb2f7a9d71c.png">
<img width="730" alt="Capture d’écran 2020-10-21 à 19 23 41" src="https://user-images.githubusercontent.com/4331618/96755398-f803f180-13d2-11eb-98c0-a3ebcdc3ab29.png">

**Comment by nstjhp** [comment]
Cool thanks. How do you see this best working with being able to set your own theme?

Might it be a good idea to use `set_flextable_defaults(whatever)` as the first line in one's custom theme? Or simpler just to keep this separate i.e. outside of the definition of a custom theme function?

**Comment by davidgohel** [comment]
It's better to use it before theming, as in knitr or `ggplot2::theme_set()`. Theme function can be applied at any moment, `set_flextable_default` will define default font family, size, paragraph padding, etc.

Also, theme function can be defined in these settings, it is the last executed command when a flextable is created.

**Comment by nstjhp** [comment]
I see, thanks very much for your efforts with this package, and this enhancement.
