### ISSUE TITLE
Broken link to image on the website 

### ISSUE THREAD

**Issue by GegznaV** [davidgohel/flextable#238]
There is a broken link of image `fig_formats.png` on https://davidgohel.github.io/flextable/articles/overview.html

![image](https://user-images.githubusercontent.com/12725868/93497120-bc2fc500-f918-11ea-9031-33175381868e.png)

Should https://raw.githubusercontent.com/davidgohel/flextable/master/man/figures/fig_formats.png be used?

![](https://raw.githubusercontent.com/davidgohel/flextable/master/man/figures/fig_formats.png)

**Comment by davidgohel** [comment]
Thanks!

On CRAN vignettes it is ok: https://cran.r-project.org/web/packages/flextable/vignettes/overview.html. 

I think it means I can't use man/figures in vignettes when pkgdown is used...

**Comment by davidgohel** [comment]
thanks, it's fixed
