### ISSUE TITLE
Error in as_flextable

### ISSUE THREAD

**Issue by ttrevisan18** [davidgohel/flextable#239]
Amazing package!!! So easy to use and customize. I think the latest release broke "as_flextable". I had some code that was running without issue and is now throwing an error. I have not updated flextable on my production server and the code runs fine. I am pulling the example code from the documentation and it throws the same error.

The error is 

```
Error in UUIDgenerate(n = nrow(uid), use.time = TRUE) : 
  unused argument (n = nrow(uid))
```

When I run this code I get the error

```
 data_CO2 <- dcast(as.data.table(CO2), 
                               Treatment + conc ~ Type, value.var = "uptake", fun.aggregate = mean)
             # head(data_CO2)
             data_CO2 = as_grouped_data(x = data_CO2, groups = c("Treatment"))
             # head(data_CO2)
             as_flextable( data_CO2 ) %>% 
               bold(j = 1, i = ~ !is.na(Treatment), bold = TRUE, part = "body" ) %>% 
               bold(part = "header", bold = TRUE ) %>% 
               width(width = 1.5)
```

![image](https://user-images.githubusercontent.com/45466366/93503654-62aea280-f8e6-11ea-8cfc-19a9024f787c.png)

**Comment by davidgohel** [comment]
I see, thanks for that.

I forgot to add a minimum version on `uuid`. Could you update the package `uuid` and let me know if it should solve your issue?

**Comment by ttrevisan18** [comment]
That solved the problem. Thanks! To reiterate, really great package! Thanks for all your work!

**Comment by davidgohel** [comment]
Thanks :)
