### ISSUE TITLE
Numeric column names overwrite table contents

### ISSUE THREAD

**Issue by bescoto** [davidgohel/flextable#24]
For instance:
```
flextable::flextable(tibble::tibble(`1`=6:10))
```
looks like this:
![table_with_numeric_title](https://user-images.githubusercontent.com/296094/28502103-a862cd28-6fb0-11e7-9448-a4fd8527f541.png)

This may seem like it's the fault of the tibble package, but I believe plain R also allows for this type of column name, and a normal data.table object leads to the same behavior, e.g.
```
df <- data.frame(a=1:5)
df$`1` <- 6:10
flextable::flextable(df)
```
Cheers,
Ben

**Comment by bescoto** [comment]
Hi David, were you planning on looking at this soon?  If not I might try taking a look.  Thanks, Ben.

**Comment by davidgohel** [comment]
Hi 

No, I am off for few weeks, sorry. 

You can of course... but it seems you want *tidy eval* and IMHO there is a lot of work to do. 

If you only want to manage table headers, you have several ways to manage headers labels, see here: https://davidgohel.github.io/flextable/articles/layout.html#manage-headers

**Comment by bescoto** [comment]
Yes, that link you sent details how to fix the immediate problem, thanks David!

I looked through the code a little bit and see what you mean about tidy eval.  I also did some profiling, because it seems html generation for flextable is significantly slower than ReporteRs.  I think the two issues are related---that there is a lot of non-standard evaluation going on.

I think the flexibility and semantics of flextable are great if you're doing data exploration/analysis, and then making a few custom tables for a paper or webpage.  And I'm sure at least half of the flextable users are using it for that.  However, other users (like me) are using flextable to automate the bulk creation of tables---the table is designed once, and then similar tables are created thousands of times on different data sets when people click on buttons or churn out bulk reports.  The current system is a bit awkward for this, for performance reasons, and because it's overly dynamic (e.g. this bug).

I wonder if it would be possible to design a lower-level object that would be harder for the user to make, but faster and less dynamic.  Perhaps it could be an intermediate result in the compilation of a flextable to html or wml, e.g. flextable -> "rigidtable" -> formatted output.  Users could manually produce a "rigidtable" instead of a flextable if they didn't want the non-standard evaluation stuff.  Hopefully it would be an order of magnitude faster to format a "rigidtable" than a flextable. 

One thing I'm not sure of is how your extensive use of R6 affects the speed.  Your base officer html/wml functions are written in C and should be very speedy, but the use of R6 at a very granular level may limit the amount of vectorization that R can do.  But maybe everything would be fast enough with R6 but without the non-standard eval.

What do you think?

Thanks,
Ben

**Comment by davidgohel** [comment]
Hi

That was roughly the subject of #16 . It's true that options are not used by most of users and the package should provide something simpler and more efficient. As you found out, R6 usage (at the granular level used by flextable) is the guilty. The reason is that (even not efficient) it allows creation of complex tables required by some users, e.g. being able to add a superscript note just after a caption.

However, I have a draft that provides a simpler version of flextable (but no images and no composite formatting within text of a cell). Speed is ok with it and it satisfies 80% of usages I think. 

I will let you know when the branch will be published (but not before 2 weeks - I am on holidays :) )

David

**Comment by bescoto** [comment]
Thanks, I had seen that issue but hadn't read to the bottom.  (Unfortunately I don't know French, but just now I've used Google translate to understand :))

Sorry to keep bothering you on vacation---but thanks for the replies!  Your plans sound very promising and I look forward to testing them out.

**Comment by davidgohel** [comment]
Hi, 

You can try the new Github version. A new function is available: `regulartable` (not sure the naming is perfect...). The function has the same arguments than `flextable`.

This new function does only allows one chunk of text per cell. It is faster than `flextable` and supports all existing functions (except `display`). *invalid* colnames are supported.

**Comment by bescoto** [comment]
Wow, this is stellar David.  The speed increase is incredible (maybe 10x+ as a rough approximation).  It fixes the original bug too, but for me that is minor compared to the speed increase :)

I think it's ok not to support `display` (you could say that's the whole point), but does that impair the ability to set multi-level headings?  For instance:
```
rt <- regulartable(tibble(`1`="a", `2`="b"))
rt <- add_header(rt, top=TRUE, `1`="hello", `2`="goodbye")
```
doesn't seem to work---I get "NA" when the table is displayed, instead of the "hello"/"goodbye" I wanted.  Before I could use `display` to fix up the new header row, but now it's not clear to me how to do it.

Also, there is an issue with quoting now.  For instance, consider:
```
rt <- regulartable(tibble(a="hello <b>world</b>"))
```
The brackets seem to be quoted once too many.

I would actually like an option for contents to be not quoted at all, so that I can add my own custom HTML/XML.  This may seem to be reverting more to flextable territory, but this is the tact taken by, for instance, DT package, which lets power-users customize behavior.  Clearly users must then be careful what they are doing, depending on the output format.

In my use-case, data is stored in an intermediate form between a data frame and a flextable/regulartable.  Then I use your package to make tables like this:
![flextable_example](https://user-images.githubusercontent.com/296094/29754295-c723f450-8b47-11e7-8972-37ab119ae162.png)

I could give up having the units be in a lighter font, but it seems like it should be possible if I can manually code the HTML.  The `display` semantics didn't really help much with this case anyway, as the units and formatting types are all not known at program time, so I had to work-around the lazy evaluation.

As for the name, maybe quicktable to emphasize the speed gain?  Anyway, that's not my department :)  Thanks again for this, these changes seem to really nail it!

**Comment by davidgohel** [comment]
Hi

> I think it's ok not to support display (you could say that's the whole point), but does that impair the ability to set multi-level headings? 

No, that was a bug (just fixed it)...

> as the units and formatting types are all not known at program time

Could you explain more please?

**Comment by bescoto** [comment]
Sorry, I just meant that the formatting isn't hard-coded, but determined at run-time.  Unless I misunderstood flextable's lazy evaluation, this requires a bit of a workaround, like this snippet from my code which labels the units next to a column title:

```
        formatters <- list(
            eval(substitute(
                unit ~ unit_sub,
                list(unit_sub=sprintf("(%s)", sf$main_unit)))),
            eval(substitute(
                title ~ title_sub,
                list(title_sub=sf$title))))
        ftl$ft <- flextable::display(
            ftl$ft, i=1, col_key=ftl$colnames[1],
            pattern="{{title}} {{unit}}",
            formatters=formatters,
            fprops=list(unit=flex_table_props$unit_text,
                        title=flex_table_props$title_text),
            part="header")
```
Because the values aren't hard-coded, I thought I needed to use the eval(substitute(...)) construction to get the evaluation contexts right.

**Comment by davidgohel** [comment]
Thanks for that! I understand. 

`formatters` is a formula (you could `as.formula(sprintf(...))`). 

The `display` function is not easy to use but I don't have better idea on how it should be designed in term of usage. There may be a need for a refactoring of `formatters` argument. 

If you have a suggestion about how you would like to do those specific formatting operations, they are welcome.

**Comment by davidgohel** [comment]
I am closing this issue as the original issue is now solved.

The following article show demo the creation of the table you showed:
 
https://davidgohel.github.io/flextable/articles/examples.html
