### ISSUE TITLE
Enable 'Text Highlight Color' for word/powerpoint

### ISSUE THREAD

**Issue by AudioRebel** [davidgohel/flextable#240]
Many thanks for this great package.

It would be great if flextable could access the 'Text Highlight' feature.
![image](https://user-images.githubusercontent.com/48553354/93593362-45e0a080-f9b4-11ea-9ee0-a8a093ba2c3e.png)

This is a nicer way to highlight parts of the table than setting the background color which fills whole content of the cell.

With 'Text Highlight'
![image](https://user-images.githubusercontent.com/48553354/93594096-84c32600-f9b5-11ea-932a-6676d758fa4d.png)

With background color it doesn't look as nice (it covers the banded rows):
![image](https://user-images.githubusercontent.com/48553354/93594120-8b519d80-f9b5-11ea-91f3-5592fea09820.png)

Many thanks,
Claudio

**Comment by davidgohel** [comment]
I can make a function, that's a good suggestion, thanks

For now, you need to use `compose` and `as_chunk`:

```
library(officer)
library(flextable)
ft <- flextable(head( mtcars, n = 10))
ft <- compose(ft, j = "disp", i = ~ disp > 200,
              value = as_paragraph(as_chunk( formatC(disp, format = "f", digits = 1), props = fp_text(shading.color = "yellow")) )
)
ft <- autofit(ft)
ft
```

<img width="522" alt="Capture d’écran 2020-09-18 à 14 19 06" src="https://user-images.githubusercontent.com/4331618/93596629-eeddca00-f9b9-11ea-9803-55c17e8a2e57.png">

It will be simpler when the function will be implemented.

**Comment by AudioRebel** [comment]
That worked like a charm! Many thanks, CR!

**Comment by davidgohel** [comment]
I have created a new function named `hightlight` (only in dev version for now).

```
my_color_fun <- function(x){
  out <- rep("yellow", length(x))
  out[x < quantile(x, .75)] <- "pink"
  out[x < quantile(x, .50)] <- "wheat"
  out[x < quantile(x, .25)] <- "gray90"
  out
}
ft <- flextable(head( mtcars, n = 10))
ft <- highlight(ft, j = "disp", i = ~ disp > 200, color = "yellow")
ft <- highlight(ft, j = ~ drat + wt + qsec, color = my_color_fun)
ft
```


![fig_highlight_1](https://user-images.githubusercontent.com/4331618/93672278-f381ab80-faa9-11ea-97fd-8b05d4490528.png)

**Comment by AudioRebel** [comment]
Wonderful! Kr, Claudio Rebelo

**Comment by gacolitti** [comment]
Highlight seems to work fine before I insert into a powerpoint. But after I insert flextable into a powerpoint and open it up, I don't see any highlighting.

```
library(tibble)
library(flextable)

ft <- flextable(tibble(x = 53)) %>%
  highlight(i = 1, j = "x", color = "black") 

read_pptx("office-theme.pptx") %>% 
  add_slide(layout = "Title and Content", master = "Office Theme") %>% 
  ph_with(ft, location = ph_location_type(type = "body")) %>% 
  print("test.pptx")
```

**Comment by davidgohel** [comment]
sorry @gacolitti I did not see your message...

**Comment by gacolitti** [comment]
Thanks for reopening this issue. 

I'm using `flextable::bg()` now to color cells, but `highlight()` would be preferable.
