### ISSUE TITLE
Choose more than one background color of row headers added with add_header_row()

### ISSUE THREAD

**Issue by daleericko** [davidgohel/flextable#242]
Hello - 

When adding header rows to a flextable, I am trying to change the background color of each new object added with the values parameter. Currently, the bg() function only allows us to change the entire header background color and does not recognize the column or row when using i or j in bg().  

as an example 
`... %>%  
add_header_row(values = c(1, 2, 3), colwidths= c(2, 2, 2) %>%
bg(j = 1, bg = "red", part = "header")
`

Thank you!

**Comment by davidgohel** [comment]
Hello, please next time provide a fully reproducible example.

I can't reproduce what you  are describing, this is my code:

```
library(flextable)
library(magrittr)

flextable(head(iris)) %>% 
  add_header_row(values = c(1, 2, 3), colwidths= c(2, 2, 1)) %>% 
  bg(j = 1, i =2, bg = "red", part = "header")
```

<img width="401" alt="Capture d’écran 2020-09-30 à 21 51 06" src="https://user-images.githubusercontent.com/4331618/94732812-11cb8f00-0367-11eb-8929-4b0248970670.png">

**Comment by daleericko** [comment]
Hi - 
Will do! Apologies for not including that. 

What you wrote is exactly my situation; however, I would like to make 1 some color, 2 another color, and 3 a different color as well.

**Comment by davidgohel** [comment]
If you don't provide any code, it's difficult to help. I can not reproduce your issue. This is working as expected:

```
library(flextable)
library(magrittr)
library(scales)

colourer <- col_numeric(
  palette = c("white", "red"),
  domain = c(0, 7))
  
set.seed(3)
flextable(head(iris)) %>% 
  add_header_row(values = c(1, 2, 3), colwidths= c(2, 2, 1)) %>% 
  bg(i =2, bg = sample(colours(), size = 5), part = "header") %>% 
  bg(i =1, j = c(1, 3, 5), bg = sample(colours(), size = 3), part = "header") %>% 
  bg(j = 1:2, bg = colourer)
```


<img width="385" alt="Capture d’écran 2020-10-01 à 00 05 22" src="https://user-images.githubusercontent.com/4331618/94744769-d38b9b00-0379-11eb-80d6-561c83923d10.png">

**Comment by daleericko** [comment]
Hi David - 

Thank you again for your response. I found the error on my part was improper use of i and j. 

I appreciate your help very much and apologies if there was a lot of time wasted. 
Cheers!
