### ISSUE TITLE
borders not shown

### ISSUE THREAD

**Issue by PhilP86** [davidgohel/flextable#244]
Hi David,

First I would like to thank you for developping such a useful package.

I have an issue when I want to customize the borders of the different parts of my table (maybe the issue is the same as https://github.com/davidgohel/flextable/issues/241#issue).

It happens that sometimes the border of the footer part is not shown as I would want.

You will find below a reproducible example. The border for the footer is not shown for tab1 but is present for tab2.

Many thanks again,

Philippe

```
library(tidyverse)
library(flextable)
library(officer)

dat <- iris[c(1:2, 51:52, 101:102),]

tab1 <- flextable(dat)%>%
    border_remove() %>%
    add_footer_lines(top = TRUE,values = "TEST") %>%
    border_inner(part = "all", border = fp_border(color="gray",  width = 0.5)) %>%
    border_outer(part = "all", border = fp_border(color="gray",  width = 0.5)) %>%
    border(part = "header", border.bottom = fp_border(color="black", width = 1)) %>%     
    border(part = "footer", border.top = fp_border(color="black", width = 1))
	
tab1	
	
tab2 <- flextable(dat)%>%
    border_remove() %>%
    add_footer_lines(top = TRUE,values = "TEST") %>%
    border_inner(part = "all", border = fp_border(color="gray",  width = 0.5)) %>%
    border_outer(part = "all", border = fp_border(color="gray",  width = 0.5)) %>%
    border(part = "header", border.bottom = fp_border(color="black", width = 1)) %>%     
    border(part = "footer", border.top = fp_border(color="black", width = 3))

tab2
```

**Comment by davidgohel** [comment]
Hello,

Sorry for the delay.

I don't recommend to use `border` as is. You should instead use the functions demonstrated in the documentation:

https://davidgohel.github.io/flextable/articles/format.html#borders-1

i.e.: 

* `hline()`: set bottom borders (inner horizontal)
* `vline()`: set right borders (inner vertical)
* `hline_top()`: set the top border (outer horizontal)
* `hline_bottom()`: set the bottom border (outer horizontal)
* `vline_left()`: set the left border (outer vertical)
* `vline_right()`: set the right border (outer vertical)


So the code for your example would be:

```
library(tidyverse)
library(flextable)
library(officer)

dat <- iris[c(1:2, 51:52, 101:102),]
big_border <- fp_border(color="red", width = 1)

tab1 <- flextable(dat)%>%
  border_remove() %>%
  add_footer_lines(top = TRUE,values = "TEST") %>%
  border_inner(part = "all", border = fp_border(color="gray",  width = 0.5)) %>%
  border_outer(part = "all", border = fp_border(color="gray",  width = 0.5)) %>%
  hline_bottom(part = "header", border = big_border ) %>% 
  hline_bottom(part = "body", border = big_border )

tab1
```

<img width="676" alt="Capture d’écran 2020-10-11 à 14 24 59" src="https://user-images.githubusercontent.com/4331618/95678534-91f6bd80-0bcd-11eb-9645-fa26c71bb0b9.png">

I will work on `border` documentation. I kept this function for backward compatibility, maybe I can defunct it or document better it should be used carefully to avoid overlapping borders (this is what is happening in your case).

**Comment by PhilP86** [comment]
Hi David,

Many thanks for your reply.

However I still get the same behavior when changing a bit your proposal.

It seems the `hline_top(part = "footer", border = big_border)` line is not considered (see example below).
Is it again an overlapping issue ?


Indeed in this simple example I can just use your suggestion `hline_bottom(part = "body", border = big_border )` to get the same results but my intent is more general and to incorporate these lines of code in a customized theme (i.e: draw a big_border at the bottom of the body part only when there is a footer), so I really need to use `hline_top(part = "footer", border = big_border)` instead of `hline_bottom(part = "body", border = big_border )`.

Thank you very much.

Philippe


```
library(tidyverse)
library(flextable)
library(officer)

dat <- iris[c(1:2, 51:52, 101:102),]
big_border <- fp_border(color="red", width = 1)


tab1 <- flextable(dat)%>%
        border_remove() %>%
        add_footer_lines(top = TRUE,values = "TEST") %>%
        border_inner(part = "all", border = fp_border(color="gray",  width = 0.5)) %>%
        border_outer(part = "all", border = fp_border(color="gray",  width = 0.5)) %>%
        hline_bottom(part = "header", border= big_border) %>%     
        hline_top(part = "footer", border = big_border)

tab1

```

**Comment by davidgohel** [comment]
> Is it again an overlapping issue ?

Yes I think - although I am not sure it's not a bug ;). Here there is a conflict, body last line is {gray, 0.5} and footer first line is {red, 1} - the browser decide to display the one of the body (it does not happen with the Word output). See the following:

```
library(tidyverse)
library(flextable)
library(officer)

dat <- iris[c(1:2, 51:52, 101:102),]
big_border <- fp_border(color="red", width = 1)


tab1 <- flextable(dat)%>%
  border_remove() %>%
  add_footer_lines(top = TRUE,values = "TEST") %>%
  border_inner(part = "all", border = fp_border(color="gray",  width = 0.5)) %>%
  border_outer(part = "all", border = fp_border(color="gray",  width = 0.5)) %>%
  hline_bottom(part = "header", border= big_border) %>%     
  hline_bottom(part = "body", border = fp_border(width = 0)) %>%     
  hline_top(part = "footer", border = big_border) 

tab1
```

<img width="678" alt="Capture d’écran 2020-10-11 à 15 49 57" src="https://user-images.githubusercontent.com/4331618/95680366-72659200-0bd9-11eb-9e97-a29f4238e00a.png">

By making the last line void, we can see the red line.

**Comment by PhilP86** [comment]
Yes indeed.

The same conflict appears with the `hline_bottom(part = "header", border= big_border)` line  (body first top line is {gray, 0.5} and header last bottom line is {red, 1}) but does not seem to be impacted as it is correctly drawn.
Is there a way to know the logic/order of drawing to avoid overlap?

Thanks!

Philippe

**Comment by davidgohel** [comment]
I think the border bottom of the previous row is winning against the top border of the current row. 

I need more time to think about this.

David

**Comment by PhilP86** [comment]
Sure, no worries at all David.

Many thanks again for your help and have a nice day.

Philippe

**Comment by davidgohel** [comment]
thanks, you too

**Comment by davidgohel** [comment]
This is now working as expected :)

```
library(tidyverse)
library(flextable)
library(officer)

dat <- iris[c(1:2, 51:52, 101:102),]
big_border <- fp_border(color="red", width = 1)


tab1 <- flextable(dat)%>%
  border_remove() %>%
  add_footer_lines(top = TRUE,values = "TEST") %>%
  border_inner(part = "all", border = fp_border(color="gray",  width = 0.5)) %>%
  border_outer(part = "all", border = fp_border(color="gray",  width = 0.5)) %>%
  hline_bottom(part = "header", border= big_border) %>%     
  hline_top(part = "footer", border = big_border)


tab1
```


<img width="571" alt="Capture d’écran 2020-12-22 à 11 00 06" src="https://user-images.githubusercontent.com/4331618/102875994-e081cd00-4444-11eb-8077-33b6df30888c.png">
