### ISSUE TITLE
`height()` doesn't work as-is, documentation needs to mention `hrule()`

### ISSUE THREAD

**Issue by daattali** [davidgohel/flextable#245]
Using both the latest CRAN version (5.11) and the latest GitHub version: This is the example code in the documentation for `height()`:

```
ftab <- flextable(head(iris))
ft <- height(ftab, height = .3)
```

The output of `ft`  looks identical to `ftab`. I found https://github.com/davidgohel/flextable/issues/213 and in it you mention that `hrule()` must be used to make `rowheight` work, and it seems that if I add `hrule(rule="exact")` then the above works too. Perhaps I'm missing something, but it feels to me that either the `height()` function is broken and needs to work without hrule, or the documentation needs to be updated to mention that `hrule()` is required.

**Comment by davidgohel** [comment]
Yes, it needs a more detailed manual page and at least a mention in the vignettes.

Thanks for reporting that.

**Comment by davidgohel** [comment]
I changed the doc and mention `hrule` + add more information in the vignette (and correct some issues with pkgdown):

https://davidgohel.github.io/flextable/articles/layout.html#adjusts-manually-cell-widths-and-heights-1

https://davidgohel.github.io/flextable/reference/height.html

Let me know if still not clear

**Comment by daattali** [comment]
The new docs are clear!
