### ISSUE TITLE
Changing the value of LC_NUMERIC affects layout in strange ways

### ISSUE THREAD

**Issue by torfason** [davidgohel/flextable#246]
The layout of flextables depends on LC_NUMERIC in ways that it seems it should not, specifically the lines/borders in the tables. An example reproducing this issue follows, coupled with a screenshot of the notebook, to demonstrate the output itself. (The reason one wants to change the value of LC_NUMERIC is to get commas for number formats).

The code:

```r
library(flextable)

Sys.setlocale("LC_NUMERIC","C")
flextable(head(trees))

Sys.setlocale("LC_NUMERIC","nl_NL.UTF-8")
flextable(head(trees))
```

The output:

<img width="526" alt="Screenshot 2020-10-06 at 15 59 40" src="https://user-images.githubusercontent.com/3247510/95227157-4cad4700-07ed-11eb-8a95-fa1cd31b248f.png">

(In the second example, the commas are used for decimal separators, as desired, but the horizontal lines disappear for some reason, which is not desired).

sessionInfo after running the above code:

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.3

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/nl_NL.UTF-8/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] flextable_0.5.11

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5        digest_0.6.25     R6_2.4.1          magrittr_1.5     
 [5] evaluate_0.14     zip_2.1.1         rlang_0.4.7       gdtools_0.2.2    
 [9] uuid_0.1-4        data.table_1.13.0 xml2_1.3.2        rmarkdown_2.4    
[13] tools_4.0.2       officer_0.3.14    xfun_0.18         compiler_4.0.2   
[17] systemfonts_0.3.2 base64enc_0.1-3   htmltools_0.5.0   knitr_1.30         
```

**Comment by davidgohel** [comment]
OK, thanks for reporting that issue

If possible, I'd like to find a solution that does not imply to play with locale.

**Comment by davidgohel** [comment]
It's fixed, thanks (the only solution was to play with locale...)

**Comment by torfason** [comment]
Thanks! I'll install the most recent version and test to make sure it works on my setup as well.

**Comment by torfason** [comment]
I can confirm that this is fixed in the GitHub version (not in CRAN as of now). This triggers several warnings related to locale switching (I guess that was what you were referring to when you said the only solution was to play with locale). Probably the best solution is to try to find ways of configuring the calling code to avoid requiring the use of locale (I know the package that I was using, `modelsummary` has been updated). But good to know that if that is not an option, locale switching can work as a last resort. Thanks!

**Comment by davidgohel** [comment]
I have canceled the fix. I don't think it is good.

Another solution is to define the separators with `colformat_num`:

```
library(magrittr)
library(flextable)

flextable(head(trees)) %>% 
  colformat_num(j = 1:3, decimal.mark = ",", big.mark = " ")
```

<img width="424" alt="Capture d’écran 2020-11-22 à 23 19 45" src="https://user-images.githubusercontent.com/4331618/99918746-3b76b600-2d19-11eb-891d-9769903136e3.png">
