### ISSUE TITLE
Specify page size and layout in `save_as_docx()` function

### ISSUE THREAD

**Issue by dvanic** [davidgohel/flextable#247]
For tables with many columns, it would be great if we could specify the page width and landscape orientation for `flextable::save_as_docx()`, for example:

```
flextable::save_as_docx(
  myflextable, 
  path = "myflextable.docx", 
  page_size = officer::page_size(width = 21/2.54, height = 29.7/2.54, orient = "landscape"))
```

At the moment, tables are exported with a default file width, meaning columns are cut off at both left/right when the document is opened in Word.

**Comment by davidgohel** [comment]
Hello,

Thanks for the suggestion.

**Comment by davidgohel** [comment]
This is now implemented: https://davidgohel.github.io/flextable/reference/save_as_docx.html

Here is an example:

```
library(officer)
library(flextable)

set_flextable_defaults(table.layout = "autofit")

tf <- tempfile(fileext = ".docx")

ft1 <- flextable( head( iris ) )
ft2 <- flextable( head( mtcars ) )

sect_properties <- prop_section(
  page_size = page_size(orient = "landscape",
                        width = 8.3, height = 11.7),
  type = "continuous",
  page_margins = page_mar()
)

save_as_docx(`iris table` = ft1, 
             `mtcars table` = ft2,
             path = tf, 
             pr_section = sect_properties)
```

<img width="1423" alt="Capture d’écran 2020-10-24 à 00 28 35" src="https://user-images.githubusercontent.com/4331618/97059142-f5023000-158f-11eb-8094-7f8a7e91d45b.png">



You will need the dev version for now:

```
remotes::install_github("davidgohel/flextable")
```
