### ISSUE TITLE
insert multiple merged header rows in flextable 

### ISSUE THREAD

**Issue by littlehifive** [davidgohel/flextable#249]
I couldn't seem to find ways in `flextable` to insert rows/merged headers with multiple existing data frames. Is it possible to achieve something like the following instead of presenting each small tables separately:

<img width="426" alt="Screen Shot 2020-10-23 at 2 08 42 PM" src="https://user-images.githubusercontent.com/26876926/97038746-43381480-1539-11eb-9f72-ccd1cc27cf97.png">

Thank you very much!

**Comment by davidgohel** [comment]
Yes, see 

* https://davidgohel.github.io/flextable/articles/offcran/as_flextable.html#groups-as-row-titles
* https://davidgohel.github.io/flextable/reference/as_grouped_data.html

**Comment by littlehifive** [comment]
Thank you so much! That solves my problem.
