### ISSUE TITLE
Syntactically invalid names not allowed as column names

### ISSUE THREAD

**Issue by wdearden208** [davidgohel/flextable#25]
This seems related to #24. Syntactically invalid names are illegal in flextable. For example, 
```
iris %>%
  rename(`Sepal Length` = Sepal.Length) %>%
  head() %>%
  flextable()
```

gives `Error in parse ... unexpected symbol`.

**Comment by davidgohel** [comment]
yes this is the same issue (then I am closing the ticket :))
