### ISSUE TITLE
Extending global options

### ISSUE THREAD

**Issue by Crismoc** [davidgohel/flextable#250]
Extending the request in issue #236, I would like to know if a feature can be considered (or if it's already possible). Thinking in the use of tables for non-English languages with other conventions of decimal separator and big marks, would it be possible to add to `set_flextable_default()` global options for `colformat_num()`?

**Comment by davidgohel** [comment]
Thanks for the suggestion. 

I added new options `digits,decimal.mark,big.mark,na_str` now used as default values by `colformat_xxx()` functions.
