### ISSUE TITLE
set_table_properties(width = 1, layout = "autofit") is not working with Microsoft Word 2010 anymore

### ISSUE THREAD

**Issue by schimari** [davidgohel/flextable#252]
Hi,

I attached an expample Rmd file, which should render the table to 100% width, but it does not anymore. 

If you need more information, please let me know.

[flextable_Rmd.txt](https://github.com/davidgohel/flextable/files/5480926/flextable_Rmd.txt)

[sessionInfo.txt](https://github.com/davidgohel/flextable/files/5480927/sessionInfo.txt)

Additional version information:
flextable 0.5.11
rmarkdown 2.5

**Comment by davidgohel** [comment]
I don't think it has been different since `set_table_properties` has been implemented. 

```
#' @param width value of the preferred width of the table in percent.
```

It's a preferred width and Word 'autofit' layout doesn't need/use 100% of the width in your example, I will make the documentation more detailed on this point.

**Comment by schimari** [comment]
Thank you for your quick response. I think that I missunderstood that point. Now I stick with the 'width' function to tune my tables to 100% width.
