### ISSUE TITLE
How can I remove the table caption generated by `flextable` function when manually recomposing the caption?

### ISSUE THREAD

**Issue by bishun945** [davidgohel/flextable#253]
I have test the demo codes in your [book](https://ardata-fr.github.io/officeverse/officedown-for-word.html#table-caption-linked-to-section-number) partly as follows:
~~~
```{r}
runs <- list(
  run_word_field("STYLEREF 1 \\s"),
  ftext(" - "),
  run_autonum(seq_id = "tab", pre_label = "", post_label = "")
)
```

::: {custom-style="Table Caption"}
Table `r run_bookmark("mtcars", runs)`: Head of mtcars
:::

```{r}
head(mtcars)
```
~~~
That's OK. But when I tried to use `flextable` to build tables for word documents, i.e., the code writen as `flextable::flextable(head(mtcars))`, the word presented two captions.

Just like:
~~~
Table 1 - 1: Head of mtcars
Table 1
~~~

How can I remove `Table 1` in the second line above a `flextable`? Does `flextable` has a parameter like `booktabs` in`knitr::kable`?

Thanks!

**Comment by davidgohel** [comment]
Thanks, you can install flextable from github to get the fix.
