### ISSUE TITLE
Subtotals by group

### ISSUE THREAD

**Issue by daranzolin** [davidgohel/flextable#258]
flextable has been a fantastic help for our Microsoft Word reports. But is there a way to calculate summary subtotals within groups? I perused the articles and NAMESPACE and couldn't find the equivalent of `gt::summary_rows(groups = TRUE, ...)`.

**Comment by tomasjanikds** [comment]
+1 for this feature

**Comment by davidgohel** [comment]
I just add a look at `gt::summary_rows()` 

This feature will not be implemented. The paradigm of flextable is to let users do their calculation as they want (usually with dplyr or data.table) and to let the users then transform that into a flextable. So basically, do any aggregation, add some summary statistics with `rbind()` or `bind_rows()`, eventually sort data and that's it. Also adding that would force using dplyr in the dependencies.


There is also function `add_body()` that can happen data at the end or at the beginning of "body" part with same behavior than `add_header()` and `add_footer()`. There is no function to add data at any row number (when a group is changing in the question). With `add_body()`, you can build a table incrementally.
