### ISSUE TITLE
Function to parse markdown syntax in a `flextable` object

### ISSUE THREAD

**Issue by DaniMori** [davidgohel/flextable#259]
When markdown syntax is included in a `flextable` object, such as `**bold**` or `^superindex^`, the character string is rendered "as is", instead of being parsed and "translated" into the proper format.

Having a function that parses these and creates the corresponding `fpar()` objects would be very handy. Something such as:
https://rdrr.io/cran/ubiquity/man/md_to_officer.html

P.S.: I'm not sure whether this feature request corresponds here or in `officer`. My apologies if it should go there.

**Comment by atusy** [comment]
Are you looking for `ftExtra:: colformat_md`?

- Repo: https://github.com/atusy/ftExtra
- Vignette: https://ftextra.atusy.net/articles/format_columns.html

**Comment by davidgohel** [comment]
I recommend you to use @atusy package.

**Comment by DaniMori** [comment]
Your package is superb @atusy , thanks so much! I can also see it renders LaTeX math, which would be my next feature request, so great on that side too! I'd really love to see this on Cran sometime in the future, if you will.

**Comment by atusy** [comment]
@DaniMori It is already on CRAN

**Comment by DaniMori** [comment]
My fault sorry, I just clicked on the repo link and assumed it wasn't yet. Thanks so much again!
