### ISSUE TITLE
merge_v not merging all columns designated in target when j has multiple columns

### ISSUE THREAD

**Issue by matthewrtate** [davidgohel/flextable#261]
Based on the example below I am looking to merge a set of several columns based only on two volumes (in this case, `lastname` and `firstname`).  The merge_v function appears to support this by way of using j to determine what columns to use to identify identical row values and then target to identify all columns to merge.  The issue seems to be in how j is using two variables as it works when I only use one; the problem is that there are instances when a last name is shared so I need to also use first name.  I also cannot just use merge_v on all of the columns I want to merge because there are some that are shared across people that I do not want to merge.  I can also do repeated merge_v calls where I only include two columns in the target.  Input data and code below:

flextable.csv:
<pre><code>lastname,firstname,team,position,track,tenure,date_end,first,last,average,total
Johnson,Alice,alpha,A,,13.3,NA,1/1/2020,12/31/2020,0.5,2.961703731
Johnson,Alice,beta,A,,13.3,NA,1/1/2020,12/31/2020,0.5,0.139317988
Smith,Bob,alpha,B,,8.3,NA,1/1/2020,12/31/2020,1,13.57574303
Williams,Carol,alpha,C,,3.3,NA,1/1/2020,12/31/2020,1,12.63134696
Brown,Dan,alpha,D,3rd,2.5,2/28/2020,1/1/2020,2/25/2020,0.115,5.573192866
Brown,Dan,gamma,D,3rd,2.5,2/28/2020,1/1/2020,2/25/2020,0.038,NA
Jones,Erin,alpha,D,3rd,2.4,NA,6/1/2020,12/31/2020,0.585,4.59682352
Jones,Erin,beta,D,3rd,2.4,NA,1/1/2020,5/31/2020,0.415,15.98899696
Miller,Frank,alpha,D,2nd,1.8,5/29/2020,1/1/2020,5/28/2020,0.346,18.83721448
Miller,Frank,gamma,D,2nd,1.8,5/29/2020,3/1/2020,5/28/2020,0.061,NA
Davis,Grace,alpha,D,,0.4,NA,8/24/2020,12/31/2020,0.292,0.768426912
Davis,Grace,gamma,D,,0.4,NA,10/1/2020,12/31/2020,0.063,NA
</code></pre>

<pre><code>dt.flextable_test <- as.data.table(read.csv("flextable_test.csv"))
ft.test <- flextable(dt.flextable_test)
</code></pre>

the following two calls appear to yield identical results and only merge columns lastname and firstname
<pre><code>ft.test <- merge_v(ft.test, j = ~ lastname + firstname, target = c('lastname', 'firstname', 'position', 'track', 'tenure', 'date_end'))
ft.test <- merge_v(ft.test, j = c('lastname', 'firstname'), target = c('lastname', 'firstname', 'position', 'track', 'tenure', 'date_end'))</code></pre>

the following works when only lastname is used in j
<pre><code>ft.test <- flextable(dt.flextable_test)
ft.test <- merge_v(ft.test, j = c('lastname'), target = c('lastname', 'firstname', 'position', 'track', 'tenure', 'date_end'))
</code></pre>

the following sequential approach works as well but is inefficient
<pre><code>ft.test <- flextable(dt.flextable_test)
ft.test <- merge_v(ft.test, j = c('lastname', 'firstname'))
ft.test <- merge_v(ft.test, j = c('lastname', 'firstname'), target = c('position', 'track'))
ft.test <- merge_v(ft.test, j = c('lastname', 'firstname'), target = c('tenure', 'date_end'))
</code></pre>

Apologies if I've misinterpreted how to correctly use the merge_v function.

**Comment by davidgohel** [comment]
I have added a new option to enable what you want (it was not possible):

```
library(data.table)
library(flextable)

dt.flextable_test <- as.data.table(read.csv("flextable_test.csv"))
ft.test <- theme_box(flextable(dt.flextable_test))
ft.test <- merge_v(ft.test, 
                   j = c('lastname', 'firstname'), 
                   target = c('lastname', 'firstname', 'position', 'track', 'tenure', 'date_end'),
                   combine = TRUE)
ft.test
```

<img width="1433" alt="Capture d’écran 2020-12-22 à 16 08 38" src="https://user-images.githubusercontent.com/4331618/102903053-1a1bfd80-4470-11eb-8610-329d790c3463.png">


The feature is activated when `combine = TRUE`. You need to install the github version to use that feature for now.
