### ISSUE TITLE
Support crossref with upcoming rmarkdown

### ISSUE THREAD

**Issue by atusy** [davidgohel/flextable#262]
The upcoming **rmarkdown** will use Pandoc's HTML raw attribute instead of preservation tokens (`<!--html_preserve--><!--/html_preserve-->`).
This will break our cross-referencing feature (https://github.com/rstudio/rmarkdown/pull/1965#issuecomment-734857060).
Fortunately, @jjallaire told me the workaround https://github.com/rstudio/rmarkdown/pull/1965#issuecomment-734859914 .

(I'll try to make some time to work on this in December)

**Comment by davidgohel** [comment]
Thanks for letting me know. Don't worry, I'll do it, I am often working on it these days

**Comment by atusy** [comment]
Great. Thanks a lot.

**Comment by davidgohel** [comment]
The changes in https://github.com/davidgohel/flextable/commit/87121cf8dfdba3f1bc3c9124affc5af0368b6122 fix that issue.
