### ISSUE TITLE
Error in inverse.rle(structure(list(lengths = colwidths, values = values),  :    invalid 'rle' structure

### ISSUE THREAD

**Issue by benjaminwnelson** [davidgohel/flextable#263]
Just received the following error when trying to print a data frame to table Error in inverse.rle(structure(list(lengths = colwidths, values = values),  :    invalid 'rle' structure

**Comment by davidgohel** [comment]
I can not reproduce, could you provide a reproducible example with the details of `sessionnfo()`?

**Comment by benjaminwnelson** [comment]
Got it to work! Thanks!
