### ISSUE TITLE
One Footnote with Several "Source" Cells

### ISSUE THREAD

**Issue by kloppen** [davidgohel/flextable#264]
I have an application where I need to annotate several cells with the same footnote, as shown below. These cells are dispersed around the table and are in several rows and several columns.

If all the cells are in the same column, it is possible to select several rows and annotate those cells with one footnote. Similarly, if all the cells are in the same row, it is possible to select several columns and annotate those cells with a single footnote.

However, if you want to add a footnote to cells that are in different rows and columns, the `footnote` function will put the footnote in all combinations if `i` and `j` given. For example if `i=c(1, 6)` and `j=c(3, 4)`, `footnote` puts the footnote in cells `[1, 3]`, `[1, 4]`, `[6, 3]` and `[6, 4]`.

Alternatively, you can add two footnotes separately, but then two footnotes appear in the footer (which is what I've done in the example below).

I'm trying to make my table look like the image below, except that there would only be one line in the footer.

![Rplot](https://user-images.githubusercontent.com/12833793/100582488-5025f180-32b7-11eb-8bed-09e8ef062e0a.png)

I'd be happy to submit a PR to add this feature. I'm opening this issue to allow for discussion before I do so.

I would propose to add a new function called `footnote_multiple` (I'm not completely happy with that name --- open to suggestions) that takes the same arguments as `footnote`, except it would take lists for `i` and `j` (perhaps calling these arguments `i_list` and `j_list` to make the altered functionality more obvious). This new function would create a single footnote that is referenced by cells `i_list[[1]]`, `j_list[[1]]` and `i_list[[2]]`, `j_list[[2]]`, etc.

Unless there is an objection or feedback, I will start working on a PR in the next few days.

**Comment by davidgohel** [comment]
thanks, I will try to find time to review and comment the PR next week

**Comment by kloppen** [comment]
Hi @davidgohel 

I'm wondering if you have had a chance to review PR #265? If so, do you think it's appropriate for inclusion in `flextable`? Is there anything that you'd like me to change about the way that this new functionality is implemented?

**Comment by davidgohel** [comment]
Hi, 

Sorry I did not find time, I am fixing issues and working on a new doc. Let me publish on cran a new release, and then we can work on your PR. I think we need to discuss some points, but it's totally appropriate for inclusion.

**Comment by davidgohel** [comment]
This can be closed as it has been fixed by #401
