### ISSUE TITLE
suffix argument not working in colformat_num()

### ISSUE THREAD

**Issue by hmeleiro** [davidgohel/flextable#266]
I just updated flextable and realised that some of my markdowns outputs changed. In particular I realised that suffix argument was no longer working in colformat_num(). The following code displays no "%" symbols:

```
 dat <- mtcars
 ft <- flextable(head(dat))
 ft <- colformat_num(x = ft,
                     big.mark=",", digits = 2, suffix = "%")
 ft <- autofit(ft)
 ft
```

![example](https://user-images.githubusercontent.com/29704914/100858234-05120700-348e-11eb-9309-f4eecdb9458a.png)

Nice package by the way.

**Comment by davidgohel** [comment]
Thanks, that's unfortunate, I will send a fix to cran next week.

The github version fix the issue:

``` r
library(flextable)

dat <- ggplot2::mpg
ft <- flextable(head(dat))
ft <- colformat_int(x = ft, big.mark=" ", suffix = "[i] ")
ft <- colformat_double(x = ft, big.mark=" ", suffix = "[d] ")
ft <- colformat_char(x = ft, prefix = "[c] ")
ft <- autofit(ft)
ft
```

![](https://i.imgur.com/acQ5r6H.png)

<sup>Created on 2020-12-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by statzg** [comment]
This ist still not working for me with the version 0.6.1. Has this been resolved?

**Comment by davidgohel** [comment]
@statzg yes

**Comment by zilch42** [comment]
Hi, sorry to resurrect this, but in version 0.6.3 colformat_num has been fixed but some of the other simple formatting functions are still broken (colformat_int, colformat_char... I haven't checked them all). Both prefix and suffix are not working

`z <- flextable(head(mtcars))
j <- c("vs", "am", "gear", "carb")
z <- colformat_int(x = z, j = j, prefix = "# ")
z`

![image](https://user-images.githubusercontent.com/39004650/107325270-680cc380-6af9-11eb-9dde-c12765077dc5.png)

**Comment by davidgohel** [comment]
@zilch42 there is no integer in your example...

**Comment by zilch42** [comment]
Ohhhh right I see. Sorry, you are right.
