### ISSUE TITLE
required data.table version

### ISSUE THREAD

**Issue by bhogan-mitre** [davidgohel/flextable#267]
I believe there is a an implied requirement for the `data.table` version that should be explicit in the `DESCRIPTION`.

For example, with `data.table` 1.12.8 installed, I get the following error trying to load `flextable` 0.6.0:
```
> library(flextable)
Error: package or namespace load failed for ‘flextable’:
 object ‘fcase’ is not exported by 'namespace:data.table'
```

Once I updated `data.table` (e.g. to 1.13.2), the error went away.  Checking their [release notes](https://github.com/Rdatatable/data.table/blob/master/NEWS.md), it looks like `fcase` was new as of `data.table` v1.13.0.

**Comment by davidgohel** [comment]
Thank you!
