### ISSUE TITLE
Regulartable quoting

### ISSUE THREAD

**Issue by bescoto** [davidgohel/flextable#27]
Hi David,

Thanks for your help with regulartable.  Just making a new issue for this quoting stuff so it doesn't get lost.

```
flextable::regulartable(tibble(a="hello <b>world</b>"))
```

Results in:

![8-31-2017 10-28-57 am](https://user-images.githubusercontent.com/296094/29931585-46fa90e8-8e37-11e7-86ad-33d5e56bb82f.png)

Looks like the contents are getting double-quoted.

**Comment by davidgohel** [comment]
Hi,

In that case, you need to use `flextable` and `display` function. The API is supposed to provide same result in Word, HTML and PowerPoint. Also if not quoting, the following is not working:

`flextable::regulartable(tibble(a="1 < 2"))`

I will make something specific to HTML later (also for #1).

**Comment by bescoto** [comment]
Sorry for confusing the issue---your
```
flextable::regulartable(tibble(a="1 < 2"))
```
is a better example of what I had in mind.  I just meant that there are two ways you could reasonably go: either allow the HTML to affect the table, or quote it out so the HTML appears literally in the cell.  But in this case neither of those happens.

**Comment by davidgohel** [comment]
right, sorry!

A regression, it is supposed to work...
