### ISSUE TITLE
HTML table caption in flextable 0.6.1

### ISSUE THREAD

**Issue by ndevln** [davidgohel/flextable#270]
Hi David,

I observed a changed table caption behaviour when using flextable 0.6.1.

This code
```
flextable(iris[1,]) %>%
  set_caption("test")

```

resulted for 0.5.11 in:
```
<table>
  <caption>test</caption>
...
</table>
```

With 0.6.1 it results in:
```
<caption>test</caption>
...
<table>
...
</table>
```

In some cases this can lead to the label being displayed to the left of the table (e.g. flexdashboard). 

Is this expected behaviour?

Thanks for everything,
Alex

**Comment by davidgohel** [comment]
Hi

Yes, it is expected.  

Now flextables are rendered in the "shadow dom", this means that the display is protected from CSS properties outside the tables. The problem to manage is that the style of the caption is defined in the CSS of the document. So I had to extract it from the table and put it on top. 

I don't mind changing something to improve this (I agree, it SHOULD be in the table tag), but it seems easier to define the CSS of the caption (like in bookdown for example) than to implement a function to customize them when most of the time they all have to be formatted identically. 

````
caption {
    color: red;
    line-height: 1.5em;
    font-size: 14px;
    text-align: center;
}
````

**Comment by ndevln** [comment]
I had a look at the new code. 

```
knitr::opts_chunk$set(ft.shadow = FALSE)
```

Is all I need. 

This option was really hard to find. I had to work my way back from `html_str()`. I like to be able to change the styling using css, since it is easier to test using the browser developer tools. Else I had to rebuild the Markdown document after every little fontsize change.

**Comment by davidgohel** [comment]
The caption is now back in the table tag. HTML caption style can now be changed with `set_flextable_defaults(extra_css = "caption {color: red;margin-top: 10px;margin-bottom: 10px;text-align: center;}")`
