### ISSUE TITLE
flextable 0.6.0: argument `j` won't accept an empty vector anymore (vs 0.5.11)

### ISSUE THREAD

**Issue by RemPsyc** [davidgohel/flextable#275]
**Edit: Confirmed that the error does not show up in `flextable` version 0.5.11 with:**

```
library(devtools)
install_version("flextable", version = "0.5.11", repos = "http://cran.us.r-project.org")
```

**But appears in version 0.6.0 with:**

```
library(devtools)
install_version("flextable", version = "0.6.0", repos = "http://cran.us.r-project.org")
```

---
I am using `dplyr` inside `flextable` in a custom function used in knitted tutorials and this has been working for the last few months. But recently it has stopped working and started outputting this error:

`Error in col_keys[sapply(x[["body"]]$dataset[col_keys], fun)] : invalid subscript type 'list'`

I thought that it was because I recently transitioned to R version 4.0.3 from 4.0.2, but even after running 4.0.2 in RStudio, I experience the same problem, so I believe it is because I updated `flextable` in the process.

- [x] Provide the code that is producing the error, it has to be a minimal reproducible example.

```
# This works:
library(flextable)
library(dplyr)
flextable(mtcars) %>%
  colformat_num(j = (select(mtcars, mpg) %>% names), digits = 2)

# This doesn't work in flextable 0.6.0 but works in version 0.5.11
flextable(mtcars) %>%
  colformat_num(j = (select(mtcars) %>% names), digits = 2)

Error in col_keys[sapply(x[["body"]]$dataset[col_keys], fun)] : invalid subscript type 'list'
```

The problem seems to be that it now won't accept an empty vector as an argument to `j` while it used to.

Now I've simplified the example enough that the end goal might not seem clear at all (indeed why would one try to feed it an empty vector?). It is part of a much more complicated function that uses conditional formatting. It basically formats all columns not already specified elsewhere in the function with two decimals (through `matches()`). But sometimes there are simply no other columns to format (as all are already accounted for) and this generates the error in version 0.6.0.

- [x] Provide the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example.

```
sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252
[4] LC_NUMERIC=C                    LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_1.0.2         flextable_0.6.2.009

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5        rstudioapi_0.13   magrittr_2.0.1    knitr_1.30        xml2_1.3.2       
 [6] tidyselect_1.1.0  mnormt_2.0.2      uuid_0.1-4        lattice_0.20-41   R6_2.5.0         
[11] rlang_0.4.10      tools_4.0.3       parallel_4.0.3    grid_4.0.3        tmvnsim_1.0-2    
[16] data.table_1.13.6 nlme_3.1-149      xfun_0.20         psych_2.0.12      ellipsis_0.3.1   
[21] htmltools_0.5.0   systemfonts_0.3.2 digest_0.6.27     tibble_3.0.4      lifecycle_0.2.0  
[26] crayon_1.3.4      zip_2.1.1         purrr_0.3.4       officer_0.3.16    base64enc_0.1-3  
[31] vctrs_0.3.6       glue_1.4.2        evaluate_0.14     rmarkdown_2.6     pillar_1.4.7     
[36] compiler_4.0.3    generics_0.1.0    gdtools_0.2.3     pkgconfig_2.0.3  
```

- [x] Make sure you did checked you had the latest version of the package on CRAN (and on github if issue exists with CRAN version).

I tried uninstalling `flextable`, then reinstalling through CRAN, and then also uninstalling and reinstalling through GitHub, same problem.

- [x] Make sure you searched in the *open* and *closed* issues on the github repository.

**Comment by davidgohel** [comment]
Thanks,

I have reduced the issue to something shorter (for example, you don't need to filter numeric column, `colformat_num` does it for you): 

Your use case is: you want to call `colformat_num` with an empty column selection, the function should return the same flextable without any change, but now you got an error starting with `Error in col_keys[sapply(x[["body"]]$dataset[col_keys], fun)]`

```
library(flextable)
test.table <- flextable(head(mtcars))
colformat_num(test.table, j = 1:2)# OK
colformat_num(test.table, j = character(0)) # not OK
```

**Comment by davidgohel** [comment]
ah sorry, I did not see you changed your message. Ignore my previous answer then

**Comment by davidgohel** [comment]
Thanks,

This summarizes the case:

```
library(flextable)
test.table <- flextable(head(mtcars))
colformat_num(test.table, j = 1:2)# OK
colformat_num(test.table, j = character(0)) # not OK
```
