### ISSUE TITLE
please add alignment parameter to ph_with

### ISSUE THREAD

**Issue by 13kay** [davidgohel/flextable#277]
Please add an alignment parameter to ph_with function, same as ph_with.data.frame of officer package.

The following code produces 2 slides, flextable is left-aligned by default, data.frame is center-aligned by default (it can also be adjusted by the alignment parameter)

```
read_pptx() %>% 
  add_slide() %>% 
  ph_with(flextable(head(mtcars, 10)),ph_location_type('body'), alignment='c') %>% 
  add_slide() %>% 
  ph_with(head(mtcars,10), ph_location_type('body')) %>% 
  print('~/flextable.pptx')
```

**Comment by davidgohel** [comment]
`ph_with.data.frame` has no alignment argument.

**Comment by 13kay** [comment]
https://github.com/davidgohel/officer/blob/master/R/ppt_ph_with_methods.R#L309

The ph_with function has an alignment parameter that is used in the ph_with.data.frame function, 
and how can I center the flextable in pptx?

**Comment by davidgohel** [comment]
data.frame are not center-aligned, they are using all the space available in the placeholder. 

Objects flextable have a fixed width (especially in PowerPoint). You can get the dimensions with `flextable_dim`, and then compute how to center this flextable with `slide_size`, finally use `ph_location` to define where it should be rendered

**Comment by davidgohel** [comment]
for your previous comment: 

https://github.com/davidgohel/officer/blob/master/R/ppt_ph_with_methods.R#L302

**Comment by 13kay** [comment]
read the doc，alignment is for columns
thanks for the help
