### ISSUE TITLE
Is it possible to add alignment on decimal

### ISSUE THREAD

**Issue by E4ad** [davidgohel/flextable#278]
Hello David, 
Thanks again for your work on officer and flextable. It's a real pleasure to work with it ! I mostly use it to generate tables for word doc.
I have a request, I would like to know if it's possible to align numbers in collumn on the decimal separator ?

I add this small exemple from word:
![image](https://user-images.githubusercontent.com/53569138/104445018-e462c400-5598-11eb-92fc-32e43e1c8b7c.png)

Thanks in advance,
Jim

**Comment by davidgohel** [comment]
Hello,

I don't know how to do it unless if format is pdf. I think it is only managed correctly by pdf. Did your Word example has been done manually or did you do it via a Word feature?

**Comment by E4ad** [comment]
Hello David,
Thank for your answer. It can be done with a format options, in the tab windows, see my screen shot (paragraph > tab, select decimal and press +)
![image](https://user-images.githubusercontent.com/53569138/104453705-19751380-55a5-11eb-947c-08514ebf43f1.png)

**Comment by davidgohel** [comment]
Thanks, I will have a try.

**Comment by davidgohel** [comment]
It's now available in dev version, see https://github.com/davidgohel/flextable/issues/549#issuecomment-1961765244
