### ISSUE TITLE
Automatically formatting pre-selected texts in a flextable cell.

### ISSUE THREAD

**Issue by DragonflyStats** [davidgohel/flextable#280]
Hi David

I have an interesting problem regarding scientific names for Flora and Fauna.
In addition to their common names, species have scientific names that are correctly written in italics in brackets.

Suppose we have a very simple data frame  - but it may  contain a different selection of species for a different group.

```
thisDF <- data.frame(
  thisGroup = c(1,1,1) ,
  thisText = c("The Eurasian otter (Lutra lutra)",
	"The yellow-winged darter (Sympetrum flaveolum)", 
        "The common bottlenose dolphin (Tursiops truncatus)" )
 ) %>% flextable()
```

Can a way be devised to automatically format any phrase on a key-word list in a particular way

Suppose this is the key word list that the user has to pre-define.

```
Scientific_Name <- c("Lutra lutra","Sympetrum flaveolum","Tursiops truncatus","Anser Anser")
```

The function would work something like this

```
thisDF %>% apply_format (  Scientific_Name, as_i )
```

I realise this might be a tough one - but ecologists would love Love LOVE it

**Comment by atusy** [comment]
An easy way is to manipulate character columns to generate markdown texts (e.g., with dplyr) and turn it into a **flextable** object, and then apply `ftExtra::colformat_md`.


```
library(magrittr)

thisDF <- data.frame(
  thisGroup = c(1,1,1) ,
  thisText = c(
    "The Eurasian otter (Lutra lutra)",
    "The yellow-winged darter (Sympetrum flaveolum)",
    "The common bottlenose dolphin (Tursiops truncatus)"
  )
)

Scientific_Name <- c("Lutra lutra","Sympetrum flaveolum","Tursiops truncatus","Anser Anser")

thisDF %>%
  dplyr::mutate(dplyr::across(
    where(is.character),
    stringr::str_replace_all,
    setNames(paste0('*', Scientific_Name, '*'), Scientific_Name)
  )) %>%
  flextable::flextable() %>%
  ftExtra::colformat_md()
```

BTW, I recommend you to put the code into a code block like

````
```r
library(magrittr)
```
````

It significantly improves readability.

**Comment by DragonflyStats** [comment]
Hi Atusy

This looks very promising. Thanks for your assistance.
I am trying to fix a warning error "``Error: 'across' is not an exported object from 'namespace:dplyr``" on my side.
I am trying to figure out what the clash is - if you spot it before me - I would be very grateful.

**Comment by DragonflyStats** [comment]
Hi there
Thanks for that. That looks very promising indeed. I have to get my R environment upgraded - so I cant try it out yet.
That would be a very good example to use whenever you are doing a talk about this project.
Regards
Kevin

**Comment by atusy** [comment]
@DragonflyStats 

Your welcome. FYI, you can easily omit **tidyverse**.

````r
thisDF <- data.frame(
  thisGroup = c(1,1,1) ,
  thisText = c(
    "The Eurasian otter (Lutra lutra)",
    "The yellow-winged darter (Sympetrum flaveolum)",
    "The common bottlenose dolphin (Tursiops truncatus)"
  )
)

Scientific_Name <- c("Lutra lutra","Sympetrum flaveolum","Tursiops truncatus","Anser Anser")

thisDF$thisText <- gsub(
  sprintf("(%s)", paste(Scientific_Name, collapse = "|")),
  "*\\1*",
  thisDF$thisText
)
ftExtra::colformat_md(flextable::flextable(thisDF))
````

**Comment by davidgohel** [comment]
I am closing the issue as I think @atusy answer it, thanks!
