### ISSUE TITLE
line_spacing does not work with pdf output

### ISSUE THREAD

**Issue by altonrus** [davidgohel/flextable#283]
Thank you for this wonderful package. As the title says, line_spacing does not work when knitting to PDF. It would be wonderful if this could be implemented, and if not then perhaps this should be added to the list of features not implemented on https://davidgohel.github.io/flextable/reference/knit_print.flextable.html.

Minimum reproducible example (remove #'s to run, this works if output changed to word_document or html_document):

```
---
output: pdf_document
---

#```{r t-test, echo=FALSE}
library(flextable)
set_flextable_defaults(fonts_ignore = TRUE)

df <- data.frame(a = c(1,2), b = rep("Long text that takes multiple lines", 2))

t_single <- flextable(df)
t_single <- line_spacing(t_single, space=1,part="all")

t_double <- flextable(df)
t_double <- line_spacing(t_single, space=2,part="all")
#```

Single 

`r t_single`

Double

`r t_double`

```

**Comment by davidgohel** [comment]
Thanks.

There is already a section for that:

https://davidgohel.github.io/flextable/reference/knit_print.flextable.html#pdf-output

I am preparing a new documentation. I will improve these explanations...

**Comment by davidgohel** [comment]
As a workaround, you can use chunk option `ft.tabcolsep` (the default value 8 is wrong and has just changed today to 2) and `ft.arraystretch`. These only apply to latex/pdf output.

**Comment by altonrus** [comment]
Thanks! ft.arraystretch is not a workaround for line spacing however. It impacts the space between the text in a cell and the borders, but not spacing between rows of text within a cell. See reproducible example below.


```
---
output: pdf_document
---

#```{r echo=FALSE}
library(flextable)
set_flextable_defaults(fonts_ignore = TRUE)
ft <- flextable(data.frame(a = c(1,2), b = rep("Long text that takes multiple lines", 2)))

#```

Small 

#```{r ft.arraystretch = 1, echo=FALSE}
library(flextable)
ft

#```

Big

#```{r ft.arraystretch = 10, echo=FALSE}
library(flextable)
ft

#```

```

**Comment by davidgohel** [comment]
Yes, sorry. I misread your question. 

I've added more complete notes: https://ardata-fr.github.io/flextable-book/rendering.html#notes-about-rmarkdownpdf_document

However, I now realize I can add this feature.

**Comment by davidgohel** [comment]
It should be OK now (with the github version).

``````
---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flextable)
set_flextable_defaults(fonts_ignore = TRUE)
```

```{r ft.tabcolsep = 2}
ft <- flextable(
  data.frame(
    a = c(1,2), 
    b = rep("Long text that takes multiple lines", 2)
  )
)

ft <- line_spacing(ft, space = 2, part = "all")

theme_box(ft)
```


``````

<img width="596" alt="Capture d’écran 2021-01-27 à 22 32 45" src="https://user-images.githubusercontent.com/4331618/106057014-9fd63d00-60ef-11eb-8202-e2f1f1ff8639.png">

**Comment by altonrus** [comment]
Yes, it works! You're fast. Merci beaucoup
