### ISSUE TITLE
Adjustable width for background color

### ISSUE THREAD

**Issue by JidduAlexander** [davidgohel/flextable#285]
I love tables where the width of the background colour is adjustable and variable across cells. Such that you can set the background colour to become like a horizontal bar chart for that column. 

I had a look at the flextable data structure and some of your code, but it's out of my league :-)
So I just wanted to suggest this feature in case it excites you and also for the small chance that you might think it's relatively easy to implement.

Thanks for the awesome package, I found it super easy to learn and use!
Jiddu

**Comment by davidgohel** [comment]
Hi, 

could this be what you are looking for?

https://ardata-fr.github.io/flextable-book/cell-content-1.html#minibar

**Comment by JidduAlexander** [comment]
Hi David, That is what I'm looking for. I clearly missed part of the documentation. I had a little struggle here until I realised that purrr::compose was masking flextable::compose :-) The ggplot2 possibilities are incredibly exciting.

**Comment by davidgohel** [comment]
Hi

The documentation is a new documentation, that's why you never saw it before :)

There is another name if to want to avoid that issue with purrr: `flextable::mk_par()`.
