### ISSUE TITLE
Support Setting East Asian Fonts

### ISSUE THREAD

**Issue by madlogos** [davidgohel/flextable#290]
Hi David:

Is it possible to support East-Asian (CJK) fonts in `flextable` and other `officeverse` packages?

MS Office products offer a feature of setting multi-language fonts for East-Asian users. Users can set both CJK fonts and Western language fonts in the setting pane. When opening such a .docx document by a zip extractor, the document.xml file within /word folder is like:

```xml
-<w:body>
    -<w:p w:rsidRDefault="00E74C0E" w:rsidRPr="00E74C0E" w:rsidR="006120A5">
        -<w:pPr>
            -<w:rPr>
                <w:rFonts w:hAnsi="Arial" w:eastAsia="仿宋" w:ascii="Arial"/>
              </w:rPr>
          </w:pPr>
        -<w:r w:rsidRPr="00E74C0E">
            -<w:rPr>
                <w:rFonts w:hAnsi="Arial" w:eastAsia="仿宋" w:ascii="Arial" w:hint="eastAsia"/>
              </w:rPr>
            <w:t>大家好。</w:t>
          </w:r>
        -<w:r w:rsidRPr="00E74C0E">
            -<w:rPr>
                <w:rFonts w:hAnsi="Arial" w:eastAsia="仿宋" w:ascii="Arial" />
              </w:rPr>
              <w:t>Hello world.</w:t>
         </w:r>
     </w:p>
```

You may find that there is a `<w:eastAsia>` tag in it. In this case, the Chinese characters `<w:t>大家好。</w:t>` are rendered in font '仿宋' (a CJK font family).

I know this is not a common requirement for non-CJK users. If this feature could be supported, that'll be highly appreciated.

**Comment by davidgohel** [comment]
It is already possible since the beginning of the project

https://github.com/davidgohel/flextable/blob/master/R/01_fpstruct.R#L572

Next time, please follow the guidelines you deleted when you open that issue. There is no bug explained here and if this is a suggestion, it looks like a solution you think that would solve an issue you did not explain.

**Comment by madlogos** [comment]
Thank you for explanation. Since the source code `family <- sprintf("<w:rFonts w:ascii=\"%s\" w:hAnsi=\"%s\" w:eastAsia=\"%s\" w:cs=\"%s\"/>", x$font.family, x$font.family, x$font.family, x$font.family )` has already taken eastAsia tag into account, is it possible to provide a specific CJK font.family argument in the high-level API? Currently it seems x$font.family covers all.

**Comment by davidgohel** [comment]
How can I help if there is no issue explained?

**Comment by madlogos** [comment]
This is not a bug report but an enhancement suggestion. Let me explain it in the following way which may hopefully be more illustrative.

## 1

Currently we use `set_flextable_defaults()` and `font()` functions to set the font.name. But there is only one value fitting for all. The effect is like configuring the fonts by setting the same West and CJK fonts.

![capture2](https://user-images.githubusercontent.com/7327311/106546929-2bfcc000-6547-11eb-81d8-5ff598e89eb4.PNG)

Programatically, it is doing `<w:rFonts w:hAnsi="黑体" w:eastAsia="黑体" w:ascii="黑体"/>`. But you may find that the rendering effect of CJK fonts for Latin letters is not good.

## 2

On Windows for East Asia, users can set West and CJK fonts differently.

![capture1](https://user-images.githubusercontent.com/7327311/106547058-73834c00-6547-11eb-84db-a2c73ab8bfc1.PNG)

Programatically, it is doing `<w:rFonts w:hAnsi="Times New Roman" w:eastAsia="黑体" w:ascii="Times New Roman"/>`. Simply apply it to a paragraph/table mixing CJK and West characters, MS Word will automatically render them correctly.

## Suggestions

So I would suggest providing a CJK font.name argument in the high-level APIs, such as `font()`, `set_flextable_defaults()`, etc. This argument only wants to take care of <w:eastAsia> tags. Otherwise, I have to either (1) use `font()` function heavily to select CJK and Latin characters respectively, and then assign different fonts, or (2) hack into the final .docx document and replace all the <w:eastAsia> tags.

**Comment by davidgohel** [comment]
OK thanks, I understand. 

I don't know these complexities because I'm used to working with a Latin alphabet and Word does not show these options - I only get one font to choose. 

But could you show a code example that is using heavily `font()`?  This would really help.

I can't figure out this elsewhere than in the header or footer part, body part is most of the time a reflection of the input data.frame. I think function `compose` is really relevant here, at some point, you will need to specify 2 fonts, so why not just creating 2 chunks with `as_chunk`? 

```
compose( 
  x, j = "colj", part = "header",
  value = as_paragraph(
    as_chunk("大家好。", props = fp_text_default(font.family = "仿宋")),
    as_chunk("AaBbCc", props = fp_text_default(font.family = "Arial"))
  )
)
```

**Comment by madlogos** [comment]
Good question. Imagine using `flextable` to generate automated .docx reports, there will be a number of data.frames generated programmatically. If I call `compose()` method to create independent chunks in each cell (there might be a lot of chunks within a single cell if West and CJK characters mix like jam), that will be a lot of extra efforts, and the codes will be difficult to maintain.

If I want to make a table as below:
<img width="421" alt="capture" src="https://user-images.githubusercontent.com/7327311/106628320-a31c6d80-65b4-11eb-9145-a98c49d38ab1.png">
 
Its .xml source code:

<details>

```xml
-<w:tbl>
-<w:tblPr>
<w:tblStyle w:val="a3"/>
<w:tblW w:w="0" w:type="auto"/>
<w:tblLook w:val="04A0" w:noVBand="1" w:noHBand="0" w:lastColumn="0" w:firstColumn="1" w:lastRow="0" w:firstRow="1"/>
</w:tblPr>
-<w:tblGrid>
<w:gridCol w:w="4148"/>
<w:gridCol w:w="4148"/>
</w:tblGrid>
-<w:tr w:rsidTr="009312BA" w14:textId="77777777" w14:paraId="0AA4B423" w:rsidRPr="009312BA" w:rsidR="009312BA">
-<w:tc>
-<w:tcPr>
<w:tcW w:w="4148" w:type="dxa"/>
</w:tcPr>
-<w:p w14:textId="104B85ED" w14:paraId="06D59C0C" w:rsidRPr="009312BA" w:rsidR="009312BA" w:rsidRDefault="009312BA">
-<w:pPr>
-<w:rPr>
<w:rFonts w:hAnsi="Arial" w:eastAsia="仿宋" w:ascii="Arial"/>
<w:sz w:val="28"/>
<w:szCs w:val="32"/>
</w:rPr>
</w:pPr>
-<w:r w:rsidRPr="009312BA">
-<w:rPr>
<w:rFonts w:hAnsi="Arial" w:eastAsia="仿宋" w:ascii="Arial" w:hint="eastAsia" w:cs="微软雅黑"/>
<w:sz w:val="28"/>
<w:szCs w:val="32"/>
</w:rPr>
<w:t>标题Title</w:t>
</w:r>
</w:p>
</w:tc>
-<w:tc>
-<w:tcPr>
<w:tcW w:w="4148" w:type="dxa"/>
</w:tcPr>
-<w:p w14:textId="6CF98DCD" w14:paraId="4BD02192" w:rsidRPr="009312BA" w:rsidR="009312BA" w:rsidRDefault="009312BA">
-<w:pPr>
-<w:rPr>
<w:rFonts w:hAnsi="Arial" w:eastAsia="仿宋" w:ascii="Arial"/>
<w:sz w:val="28"/>
<w:szCs w:val="32"/>
</w:rPr>
</w:pPr>
-<w:r w:rsidRPr="009312BA">
-<w:rPr>
<w:rFonts w:hAnsi="Arial" w:eastAsia="仿宋" w:ascii="Arial" w:hint="eastAsia" w:cs="微软雅黑"/>
<w:sz w:val="28"/>
<w:szCs w:val="32"/>
</w:rPr>
<w:t>内容Content</w:t>
</w:r>
</w:p>
</w:tc>
</w:tr>
-<w:tr w:rsidTr="009312BA" w14:textId="77777777" w14:paraId="3097F0EF" w:rsidRPr="009312BA" w:rsidR="009312BA">
-<w:tc>
-<w:tcPr>
<w:tcW w:w="4148" w:type="dxa"/>
</w:tcPr>
-<w:p w14:textId="0A270D6F" w14:paraId="6B9F4AE0" w:rsidRPr="009312BA" w:rsidR="009312BA" w:rsidRDefault="009312BA">
-<w:pPr>
-<w:rPr>
<w:rFonts w:hAnsi="Arial" w:eastAsia="仿宋" w:ascii="Arial"/>
<w:sz w:val="28"/>
<w:szCs w:val="32"/>
</w:rPr>
</w:pPr>
-<w:r w:rsidRPr="009312BA">
-<w:rPr>
<w:rFonts w:hAnsi="Arial" w:eastAsia="仿宋" w:ascii="Arial" w:hint="eastAsia" w:cs="微软雅黑"/>
<w:sz w:val="28"/>
<w:szCs w:val="32"/>
</w:rPr>
<w:t>微软MS</w:t>
</w:r>
</w:p>
</w:tc>
-<w:tc>
-<w:tcPr>
<w:tcW w:w="4148" w:type="dxa"/>
</w:tcPr>
-<w:p w14:textId="40F82A1B" w14:paraId="59085B00" w:rsidRPr="009312BA" w:rsidR="009312BA" w:rsidRDefault="009312BA">
-<w:pPr>
-<w:rPr>
<w:rFonts w:hAnsi="Arial" w:eastAsia="仿宋" w:ascii="Arial"/>
<w:sz w:val="28"/>
<w:szCs w:val="32"/>
</w:rPr>
</w:pPr>
-<w:r w:rsidRPr="009312BA">
-<w:rPr>
<w:rFonts w:hAnsi="Arial" w:eastAsia="仿宋" w:ascii="Arial" w:hint="eastAsia" w:cs="微软雅黑"/>
<w:sz w:val="28"/>
<w:szCs w:val="32"/>
</w:rPr>
<w:t>无题lorem</w:t>
</w:r>
</w:p>
</w:tc>
</w:tr>
</w:tbl>
```

</details>

R Codes will be 

```r
pacman::p_load(flextable, magrittr)
set_flextable_defaults(font.family="仿宋")
df = data.frame(`标题Title`='微软MS',
                `内容Content`='无题lorem')
ft = df %>% flextable %>% autofit %>% width(width=1) %>% 
    theme_box
ft
```

But the effect:
<img width="202" alt="capture1" src="https://user-images.githubusercontent.com/7327311/106631419-b8df6200-65b7-11eb-8e6c-fbc0670bb897.png">

---

If we have something like

```r
set_flextable_defaults(font.family.cjk="仿宋", font.family="Arial")
```

then the .xml simply replace 

```xml
-<w:rPr>
<w:rFonts w:hAnsi="仿宋" w:eastAsia="仿宋" w:ascii="仿宋" w:hint="eastAsia" w:cs="Arial"/>
<w:sz w:val="28"/>
<w:szCs w:val="32"/>
</w:rPr>
<w:t>标题Title</w:t>
```

with

```xml
-<w:rPr>
<w:rFonts w:hAnsi="Arial" w:eastAsia="仿宋" w:ascii="Arial" w:hint="eastAsia" w:cs="Arial"/>
<w:sz w:val="28"/>
<w:szCs w:val="32"/>
</w:rPr>
<w:t>标题Title</w:t>
```

without worrying about how sophiscated it is inside <w:t></w:t>.

Compare to calling high-level APIs like `compose` multiple times, I think it is more useful to set it once and then have the low-level APIs to do the rest of the work.

**Comment by davidgohel** [comment]
It totally makes sense. I will try to implement that (also for pptx and html, I am not sure if it is possible with latex)

**Comment by madlogos** [comment]
Thank you @davidgohel very much for trying to understand the context. Since you may not have the test environment, if you need my assistance to test your updated code before release, please let me know.

**Comment by davidgohel** [comment]
Hello, 

Thanks again for letting me know about this feature. 

It is available now. See the example below (you can now use `eastasia.family`). 

```
library(magrittr)
library(flextable)

set_flextable_defaults(
  font.family="Arial", 
  cs.family = "Symbol", 
  eastasia.family = "仿宋")

df = data.frame(
  `标题Title`='微软MS',
  `内容Content`='无题lorem',
  stringsAsFactors = FALSE)

ft = df %>% 
  flextable %>% 
  autofit %>% 
  width(width=1) %>% 
  theme_box

save_as_docx(ft, path = "test.docx")
```

<img width="840" alt="Capture d’écran 2021-03-03 à 23 35 24" src="https://user-images.githubusercontent.com/4331618/109884247-f13c9380-7c7c-11eb-97d8-25431ed530a5.png">
<img width="442" alt="Capture d’écran 2021-03-03 à 23 35 43" src="https://user-images.githubusercontent.com/4331618/109884254-f3065700-7c7c-11eb-8138-e8eae78c041e.png">

This option is only for Word output. 

You will need to run the following to try the new version:

```
remotes::install_github("davidgohel/officer")
remotes::install_github("davidgohel/flextable")
```

**Comment by davidgohel** [comment]
@madlogos I am closing the issue as I think it is solved now. Thanks for the suggestion, I think it's a valuable new feature :)
