### ISSUE TITLE
colformat_num() digits option not working since last update

### ISSUE THREAD

**Issue by User1282** [davidgohel/flextable#292]
Hello!

I have noticed that since the last update, the options digits = in `colformat_num()` is not working anymore. I get the following error: _unused argument (digits = 0)_.

If I use it with `colformat_double()`, it works.

Thanks!

**Comment by davidgohel** [comment]
Hello,

I can add a `...` but the argument will be ignored. 

https://davidgohel.github.io/flextable/reference/colformat_num.html

> The function is different from colformat_double() on numeric type columns. The function uses the format() function of R on numeric type columns. So this is normally what you see on the R console most of the time (but scientific mode is disabled, NA are replaced, etc.).

**Comment by intael** [comment]
Hi! It'd be good, if possible, to be more careful with non-backwards compatible changes like this :)

**Comment by davidgohel** [comment]
@intael that's the difficult part. "revdep checks" did not ring any bell... I am open to suggestions if any!

**Comment by davidgohel** [comment]
I added a `...` argument so that your scripts does not fail anymore.
