### ISSUE TITLE
Font settings are not applied to new header lines

### ISSUE THREAD

**Issue by casblaauw** [davidgohel/flextable#295]
## Issue

I've been using flextable in combination with officedown for a while now, and it has been a great experience overall.
One issue I did run into was that newly created header lines don't abide by previously set styling rules, particularly regarding fonts. This happens both when adding header styling manually, using a function like `font()` or `theme_*()`, but also happens with default table styles set in `set_flextable_defaults()`. 
I'm not sure how style application works under the hood in flextable, so I understand if it's not feasible to have the new header line utilise a 'part-wide' style, but at least copying the font style of the line below it, or checking the theme function, would already be a big help. 

## Reprex

```
library(flextable)
library(magrittr)

# Example 1
ftable <- iris %>% head() %>% flextable()
ftable %>%
  font(fontname = 'Brush Script MT', part = 'header') %>%
  add_header_row(values = c('Sepal', 'Petal', " "), colwidths = c(2, 2, 1))

# Example 2
set_flextable_defaults(theme_fun = theme_alafoli)
ftable <- iris %>% head() %>% flextable()
ftable %>%
  add_header(Sepal.Width = 'test')
```

## Session info

> R version 4.0.3 (2020-10-10)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS Catalina 10.15.7
> 
> Matrix products: default
> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] magrittr_2.0.1      flextable_0.6.2.010
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.5        digest_0.6.27     R6_2.5.0          evaluate_0.14     zip_2.1.1         rlang_0.4.10     
>  [7] gdtools_0.2.2     uuid_0.1-4        data.table_1.13.6 xml2_1.3.2        rmarkdown_2.6     tools_4.0.3      
> [13] officer_0.3.16    xfun_0.19         compiler_4.0.3    systemfonts_0.3.2 base64enc_0.1-3   htmltools_0.5.0  
> [19] knitr_1.30 
>

**Comment by davidgohel** [comment]
Thank you for your suggestions. It's something I've been keeping in mind for a long time. 

There has been some work done on the *default values* (?set_flextable_defaults), you could perform formatting actions with the `post_process_html` event function. Below is an example (not perfect but better):

```
library(flextable)
library(magrittr)

my_theme <- function(x){
  x <- font(x, fontname = 'Brush Script MT', part = 'header')
  x
}
set_flextable_defaults(theme_fun = theme_alafoli, post_process_html = my_theme)
# Example 1
ftable <- iris %>% head() %>% flextable()
ftable %>%
  add_header_row(values = c('Sepal', 'Petal', " "), 
                 colwidths = c(2, 2, 1)) %>% 
  align(i = 1, align = "center", part = "header")
```

<img width="594" alt="Capture d’écran 2021-03-06 à 15 12 59" src="https://user-images.githubusercontent.com/4331618/110209762-74810380-7e8e-11eb-9b0a-470f43cc4046.png">

```
# Example 2
ftable <- iris %>% head() %>% flextable()
ftable %>%
  add_header(Sepal.Width = 'test')

```

<img width="597" alt="Capture d’écran 2021-03-06 à 15 12 53" src="https://user-images.githubusercontent.com/4331618/110209787-95e1ef80-7e8e-11eb-8d62-01dc35695c5e.png">


Anyway, I will try to copy the properties of the existing lines as suggested, it will be much more natural for the user.

**Comment by CasBlaauw** [comment]
I didn't know about `post_process_html`, that's good to know! I ended up 'solving' the issue by building a wrapper around `add_header_row` for our specific use case, as we also add additional line styling etc. in one go. 
However, for general use, I do agree that copying the existing lines' properties would be a great solution!
I'd be willing to see if I can add it and contribute to the package as well if you'd prefer, but I'm not sure to what extent you prefer having external users contribute code to the package.

**Comment by Pindar777** [comment]
Intersting solution.
I recently noticed an error related to fonts when using special characters like "ü" in the output

```
   font_T <- "Consolas"
   font_H <- "Corbel"

  ft %>%
        font(fontname = font_T, part = "all") %>%
        font(fontname = font_H, part = "header") %>%
```

The desired fonts are used in general, however, the special characters a shown in "Arial".

**Comment by davidgohel** [comment]
@Pindar777 I don't think it's related to the issue here. I think also you're talking about the HTML output, maybe you could open another issue, don't forget to add a reproducible example and sessionInfo().

**Comment by Pindar777** [comment]
@davidgohel I developed a reproducible example and opened a corresponding issue.

**Comment by davidgohel** [comment]
@casblaauw It should be ok now.

```r
library(flextable)
library(magrittr)

# Example 1
ftable <- iris %>% head() %>% flextable()
ftable %>%
  font(fontname = 'Brush Script MT', part = 'header') %>%
  add_header_row(values = c('Sepal', 'Petal', " "), colwidths = c(2, 2, 1)) %>%
  autofit() 
```
<img width="721" alt="Capture d’écran 2021-11-12 à 21 58 34" src="https://user-images.githubusercontent.com/4331618/141533650-5f33d0cf-63a3-479e-82d7-1d218d53da75.png">
