### ISSUE TITLE
font function not working

### ISSUE THREAD

**Issue by hdallc** [davidgohel/flextable#298]
All of a sudden when use the font function (all other functions work fine) in flextable 0.6.3

_flextable(distributions) %>%
 font(fontname = "Arial")_

I get this error:
**Error in element_text(size = size, color = color, face = face, family = family,  : 
  unused argument (fontname = "Arial")**

I have been using this as a workaround: style(pr_t=fp_text(font.family='Century Gothic')). I have systemfonts installed

> R.version                      
platform       x86_64-apple-darwin17.0     (OS Catalina)
version.string R version 4.0.4 (2021-02-15)
nickname       Lost Library Book

**Comment by davidgohel** [comment]
It looks like you have loaded a package that contains a function `font` but you want to use `flextable::font`... 
`element_text` is a function from `ggplot2` that is not used in flextable.

Please next time follow the guidelines, so that it is possible to reproduce your issue :)
