### ISSUE TITLE
tabwid() arguments width and height no effect

### ISSUE THREAD

**Issue by instantkaffee** [davidgohel/flextable#3]
Below native code embedded in hmtl rmarkdown documents prints nicely. 
Now I want to scale the table in size.
When playing around with parameters width and/or height the knitted html shows no difference compared to native version.

```
flextable(head(mtcars), 
                  col_keys = c("am", "separator", "gear", "mpg", "drat" )) %>% 
  bold(part = "header") %>% 
  style(pr_c = c_b_b(), pr_p = fp_right(padding=2), part = "all" ) %>%
  border(j = ~ separator, border = fp_border(width=0), part = "all") %>%
  merge_v() %>%
  autofit() %>%
  tabwid()
```

**Comment by davidgohel** [comment]
Column widths are managed by function `width` (or `autofit` in your example). 
The width and height of the htmlwidget are unused (I am not sure an htmlwidget is necessary and that will probably change).
