### ISSUE TITLE
indent in flextable cells

### ISSUE THREAD

**Issue by lcougnaud** [davidgohel/flextable#30]
Is there a way to specify an specific indent (e.g. 0.5 inches) in one cell in a flextable?
I am interested to have different levels of indentation in the first column (e.g. to group certain variables).

Thanks in advance for the response

**Comment by davidgohel** [comment]
yes, that's possible with function `padding`.

**Comment by lcougnaud** [comment]
Thanks, maybe it would be useful to specify the unit in the help of the padding function.

**Comment by davidgohel** [comment]
What for? people don't read the doc ;) 

I will do in the next devel run

**Comment by ck2136** [comment]
> yes, that's possible with function `padding`.

Just came here to say Thanks to @lcougnaud for raising the question and @davidgohel for the function!
