### ISSUE TITLE
Internal link not working in Word version

### ISSUE THREAD

**Issue by dmenne** [davidgohel/flextable#301]
I have updated my gist on captions, links and cross-references with different table programs, and added a version for Word output. Most packages don't work with word output, flextable is the big exception. 

Everything works in HTML, but there is a problem with linking to a flextable: See the last two rows (same for Huxtable), this jumps to the begin of the documents instead of the table.

https://gist.github.com/dmenne/f8eb291c9e71a5de44764d442e8bdefd#file-bookdowncrossreference_word-rmd

Thanks for your work!

**Comment by davidgohel** [comment]
Hello, 

Thanks, I thought 
In your example, you are using `\@ref(tab:flexiris)` but no caption is added:
https://gist.github.com/dmenne/f8eb291c9e71a5de44764d442e8bdefd#file-bookdowncrossreference-rmd-L92

If this line is uncommented, everything is fine. (or if you use chunk option `tab.cap` - see chunk options [here](https://ardata-fr.github.io/flextable-book/layout-1.html#captions))

```
ft = set_caption(ft, "Iris with flextable")
```

```
<li>Reference to <code>flextable</code>: Please look at flextable <a href="#tab:flexiris">1.5</a>.</li>
```

Please let me know if I miss something. The caption implementation is quite difficult to implement as there are so many `if` (if bookdow, if word, ...).

**Comment by dmenne** [comment]
Hi,

I tried, but I am a bit confused, maybe this is because I later split the examples into a word and an HTML git.

Everything works for HTML: https://gist.github.com/dmenne/f8eb291c9e71a5de44764d442e8bdefd

The problem is with the word version, 

https://gist.github.com/dmenne/ab32c6ef0d8d927927337f80d6904c6e. I tried to change it as follows, but same result. Could you please re-check?

```{r flexiris, tab.cap="Iris with flextable, caption in chunk label", echo=FALSE, label="flexiris"}
library(flextable)
ft = flextable( head( iris ) )
ft = set_caption(ft, "Iris with flextable")
ft
#flextable( head( iris ) )
```

**Comment by davidgohel** [comment]
yes. In the word_document2 version, you are referring to `\@ref(tab:flexiriscap)` but you set a caption id to value `flexiris`. If using `\@ref(tab:flexiris)`, that's OK

**Comment by dmenne** [comment]
Thanks for correcting that one, I had not noted it. But the problem is further below, in the second last line (and probably related, the last).
```
[Link to flextable](#tab:flexiris), does not work, jumps to begin of document.

```

**Comment by davidgohel** [comment]
I thought this one could not work but now I am wondering if this will work if I insert a bookmark as with `word_document` and `officedown::rdocx_document`. I'll try and let you know (maybe not today)

**Comment by davidgohel** [comment]
It worked. The new version should work as expected with your gist now.

You will need to update from GitHub, and then it should be ok. Could you have a try?

**Comment by dmenne** [comment]
Works. Gist was updated.

Thanks for your great work!
