### ISSUE TITLE
Add a class to shadow hosts

### ISSUE THREAD

**Issue by RLesur** [davidgohel/flextable#302]
Hi David,

In order to resolve https://github.com/rstudio/pagedown/issues/216, it would be a great help if the shadow host elements get a class name:

https://github.com/davidgohel/flextable/blob/ea039f3af462108d27d8215942ab5238e5b78989/R/html_str.R#L70

I'll submit a PR.

**Comment by davidgohel** [comment]
Hi Romain

No problem, do you need a specific class value or any value is OK?

@tvroylandt @RLesur I think it's a good idea to have shadow dom support if possible. Meanwhile, you can use `knitr::opts_chunk$set(ft.shadow	= FALSE)` that is there for pagedown support.

**Comment by RLesur** [comment]
I wasn't aware of the `ft.shadow` option. Thanks a lot for the tip!

**Comment by tvroylandt** [comment]
Thanks David ! This is a really useful option !
