### ISSUE TITLE
save_as_image(webshot = "webshot2") does not overwrite existing .png files

### ISSUE THREAD

**Issue by faaa6** [davidgohel/flextable#304]
Hey,

I'm writing reports where I export updated flextable using render() and a loop.

I used `save_as_image(ft, "ft.png", webshot="webshot")` which worked just fine. I recently changed the layout of the flextable to include bold font and switched from webshot to webshot2 (as advised). However, the webshot2 version does not work, if the .png file already exists. I have some kind of workaround, but it only works sporadically:

`if (file.exists("ft.png")) `
`{`
`file.remove("ft.png")`
`save_as_image(ft, "ft.png", webshot="webshot2")`
`}`
`else`
`{`
`save_as_image(ft, "ft.png", webshot="webshot2")`
`}`

**Comment by davidgohel** [comment]
I can't reproduce, sorry. If you can  provide a reproducible example and a `sessionInfo()` as requested when you open a new issue, I wll be happy to re-open the issue and fix it if possible.

```
library(flextable)
require(webshot2)

cat("zz", file = "myimage.png")

ft <- flextable( head( mtcars ) )
ft <- autofit(ft)
tf <- tempfile(fileext = ".png")
save_as_image(x = ft, path = "myimage.png", webshot = "webshot2")
```
