### ISSUE TITLE
Mini charts in word markdown

### ISSUE THREAD

**Issue by hmeleiro** [davidgohel/flextable#307]
Hello, I don't know if this is a bug or I'm doing something wrong. When I render the following markdown, Microsoft Word cannot open the exported file. It throws an error caused of the mini chart in the flextable. I read this in the documentation:

"This chunk option requires package officedown in a R Markdown context with Word output format."

But I'm not sure what it means. Does it mean I have to load `officerdown` package in the markdown document? or does it mean something else?

Thanks for the package.

`````````
---
title: "Untitled"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(flextable)
library(officedown)

ft <- flextable( head(iris, n = 10 ))

ft <- compose(ft, j = 1,
  value = as_paragraph(
    minibar(value = Sepal.Length, max = max(Sepal.Length))
  ),
  part = "body")

ft <- autofit(ft)
ft
```
`````````

**Comment by davidgohel** [comment]
Hi, sorry for the unclear message. You're right, it needs officedown:

````````

---
title: "Untitled"
output: officedown::rdocx_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(flextable)
library(officedown)

ft <- flextable( head(iris, n = 10 ))

ft <- compose(ft, j = 1,
  value = as_paragraph(
    minibar(value = Sepal.Length, max = max(Sepal.Length))
  ),
  part = "body")

ft <- autofit(ft)
ft
```
````````

**Comment by hmeleiro** [comment]
Oooook, that was it. `officedown::rdocx_document` in the YAML did the job. Thanks for the quick response.
