### ISSUE TITLE
HEX alpha and markdown word documents

### ISSUE THREAD

**Issue by hmeleiro** [davidgohel/flextable#308]
Hello again, I'm trying to export a word document using  `bg()` function to color de background of some cells, but I want to lower the transparency of the color. I'm using the alpha channel of the HEX codes. For example: `#4d936a40`, this changes correctly the transparency of the background color inside Rstudio enviroment but it does nothing when exporting the word document. 

Is this a bug or is this something Microsoft Word cannot do?

Thanks again.

```
---
title: "Untitled"
output: officedown::rdocx_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(flextable)
library(officedown)
library(tidyverse)

ft <- flextable( head(iris, n = 10 )) %>% 
  bg(bg = "#4d936a40")

ft <- autofit(ft)
ft
```

```

**Comment by davidgohel** [comment]
RStudio Viewer is HTML viewer (so you are seeing the HTML output). 

Word does not allow you to apply transparency to table cells or paragraph shading 🤷‍♂️.

**Comment by hmeleiro** [comment]
Ok, I thought that could be the problem. Thanks!
