### ISSUE TITLE
Error with conditional color with scale

### ISSUE THREAD

**Issue by hmeleiro** [davidgohel/flextable#309]
I'm getting an error trying to scale-color the background of some cells using the `i` argument in `bg`. Shouldn't this code work? It works without the `i` argument, but I want to apply differente color scales to the same column. Is this possible?

Thanks

```
ft_2 <- flextable(head(iris))

colourer <- col_numeric(na.color = "white",
                        palette = c("#d90812", "#4d936a"),
                        domain = c(0, 7))
ft_2 %>% 
  bg(i = ~Sepal.Length > 5,
     j = c("Sepal.Length", "Sepal.Width",
           "Petal.Length", "Petal.Width"),
     bg = colourer, part = "body")

```

**Comment by davidgohel** [comment]
Thanks for reporting, it's a bug
