### ISSUE TITLE
Popover Message ala kableExtra

### ISSUE THREAD

**Issue by AudioRebel** [davidgohel/flextable#313]
Thanks for this amazing package!

With kableExtra it is possible to create a popover message when you hover the mouse over a particular cell.

It would be great to have a similar feature in flextable (when the output is html)!
Is that possible?

Kr, Claudio

**Comment by davidgohel** [comment]
Hello,

I like the idea thanks. It's possible with HTML, also maybe possible with Word and PowerPoint. not sure it can be implemented for latex...

It could take time but I'll try to implement the feature

**Comment by davidgohel** [comment]
Sorry, closing the issue. It won't be implemented, 'flextable' will not implement interactive elements. We recommand 'reactable' for this kind of feature.
