### ISSUE TITLE
Warnings about deprecated functions and support for International System of Units.

### ISSUE THREAD

**Issue by erydit** [davidgohel/flextable#315]
Warnings about deprecated functions. Please add them. It seems like a good programming practice. 
For example, after a long break when I used flextable last time, I could not execute my old code, that use "display" function. It took time to understand that "display" was replaced by "compose". The warnings in the style of: "**The function "display()" was deprecated since version x.xx, use "compose()" instead**." can save a lot of time in the future.

**Comment by davidgohel** [comment]
This warning has been there during months maybe a year, function has been deprecated then defunct.

**Comment by davidgohel** [comment]
And the documentation was stating that

**Comment by davidgohel** [comment]
For future users:

Please do not open any issues before searching the documentation. 

You can read the NEWS.md: it summarizes the changes, bug fixes, etc.: https://github.com/davidgohel/flextable/blob/master/NEWS.md

The user documentation is here: https://ardata-fr.github.io/flextable-book/

Some code examples here: https://ardata-fr.github.io/flextable-gallery/gallery/

The manuals are here: https://davidgohel.github.io/flextable/reference/index.html

All of this is available from the README page: https://github.com/davidgohel/flextable#resources
