### ISSUE TITLE
Support for russian image names for Word

### ISSUE THREAD

**Issue by erydit** [davidgohel/flextable#316]
Hello! 
officer is an essential and great package. Not without several annoying flaws, though.

1) Proper work with UTF-8 file names.  When I try to save flextable with images in the cells, and images have cyrillic file names, the Word would fail to open it. It is not a big deal to rename all used files. However, proper support for non-latin file names wil benefit the package.
2) Support for International System of Units. By some reason the whole rmarkdown infrastructure, and officer in particular, ignores the SI units. All sizes are specifies in inches, with no posiibility to use cm, mm, etc. That seems weird, considering that MS Office, has no problems with it.

**Comment by davidgohel** [comment]
> Ok, sorry, I thought that the lack of non-latin filenames support is a known issue. 

I don't understand. Could you explain?

> my current sessionInfo():

You did truncate your `sessionInfo()`

**Comment by davidgohel** [comment]
closed by https://github.com/davidgohel/officer/commit/c0944daf2e0a07697a75f7d537adf59545cc7122 where image treatments are happening now.

until it's on CRAN, you need to update with:

```
remotes::install_github("davidgohel/officer")
remotes::install_github("davidgohel/flextable")
```
