### ISSUE TITLE
Error saving flextable object as image with function save_as_image() 

### ISSUE THREAD

**Issue by asar1245** [davidgohel/flextable#317]
Hello, I am writing here because I tried to export a flextable object as image, but this error has appeared:

"Auto configuration failed
139987164892800:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
139987164892800:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
139987164892800:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
139987164892800:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf

Error in webshot::webshot(html, png, vwidth = 1200, vheight = 350, zoom = 2) : 
  webshot.js returned failure value: 1"

I have installed webshot2 package using the github repo, and phantomjs as suggested by official documentation, but I don't understand what is wrong. 

My R version is 4.1.0, and my SO is Debian 10 buster. 

This is the code I ran:

table <- csn_cent %>%
  flextable() %>%
  autofit() %>% 
  fix_border_issues(part = "all") %>%
  bold(part = "header") %>% 
  align(align = "center", part = "all")  

save_as_image(x = table, path = "Outputs/medidas_cent_2.png")

Thank you in advance for your help and support.

Best regards.

**Comment by davidgohel** [comment]
It seems your installation of phantomjs is not ok

if you want to use webshot2, use `save_as_image(x = table, path = "Outputs/medidas_cent_2.png", webshot = "webshot2")`
