### ISSUE TITLE
Hook for "table caption position" option, similar to `fig.topcaption`

### ISSUE THREAD

**Issue by DaniMori** [davidgohel/flextable#319]
I [asked for this feature in the `knitr` repository](https://github.com/yihui/knitr/issues/1995), but I was addressed to request it for each package I'm interested in. As I'm using the `flextable` package intensively, here is my feature request:

It would be interesting to be able to modify the table caption position from "top" to "bottom", similarly to what fig.topcation=TRUE does for caption figures to allow putting them on top of the figure.

The implementation may be something like

````
```{r tab.bottomcaption=TRUE}```
````

or

````
```{r tab.topcaption=FALSE}```
````

Thanks in advance for considering it!

**Comment by davidgohel** [comment]
Thanks for the suggestion

This will be implemented

**Comment by davidgohel** [comment]
This is now implemented (in github version). Thanks for the suggestion!
