### ISSUE TITLE
How to control digits ？

### ISSUE THREAD

**Issue by xiaochenggushiduo** [davidgohel/flextable#320]
library(flextable)
library(xtable)
x <- 1.12345
y <- 2.12345
dataframe <- data.frame(x+y)
names(dataframe) <- "x+y"
xtable_to_flextable(xtable(dataframe,digits = 3),digits = 3)

![image](https://user-images.githubusercontent.com/23014241/119220271-508f9e80-bb1c-11eb-99c2-8a64499b41ef.png)

**Comment by davidgohel** [comment]
You don't need to use xtable for that. Also `xtable_to_flextable` will be deprecated in favor of `as_flextable`.

Have a look at https://ardata-fr.github.io/flextable-book/cell-content-1.html#simple-formatting-of-cell-content

This should help
