### ISSUE TITLE
Create row titles without the name of the group

### ISSUE THREAD

**Issue by joelnitta** [davidgohel/flextable#323]
[In the example showing how to create row titles](https://ardata-fr.github.io/flextable-book/get-flextable-from-objects.html#groups-as-row-titles), the title of each row automatically has the original column name prepended and separated with a colon. For example, "Treatment: nonchilled" and "Treatment: chilled".

Is it possible to do this and **not** include the column name? So, the row titles in this case would just be "nonchilled" and "chilled".

**Comment by davidgohel** [comment]
Yes, see `?flextable::as_flextable.grouped_data` and argument `hide_grouplabel`

**Comment by joelnitta** [comment]
Thanks for the prompt answer!

I had only looked at `?as_flextable` so I missed the additional documentation for the method...

**Comment by joelnitta** [comment]
Great! Glad my question could help make the package a bit better :)

**Comment by davidgohel** [comment]
Writing doc is an non-ending torture :)
