### ISSUE TITLE
`mk_par` / `compose` not working properly for rendering equations in R 4.1.0

### ISSUE THREAD

**Issue by DaniMori** [davidgohel/flextable#325]
The following reprex:

```lang-r
library(magrittr)
library(flextable)
data.frame(x = "a_1") %>%
  flextable() %>%
  mk_par(value = as_paragraph(as_equation(.)), use_dot = TRUE)
```

works perfectly fine in R 4.0.5. However, in R 4.1.0 everything affected by `mk_par()` is rendered as `NA`.
It seems to only affect the output of `as_equation()`, as the following example renders properly (but as text instead of equation, obviously):

```lang-r
library(magrittr)
library(flextable)
flextable(data.frame(x = "a_1")) %>% mk_par(value = as_paragraph(.), use_dot = TRUE)
```

See example rendered in Markdown:

[flextable_equations.md](https://github.com/davidgohel/flextable/files/6637594/flextable_equations.md)

**Comment by davidgohel** [comment]
Hi 

Could you follow the guidelines and add your `sessionInfo()` also?

I think you did not install equatags for R 4.1.0 but I may be wrong...

**Comment by DaniMori** [comment]
You are absolutely right. Sorry, my bad 😞 

I'd suggest, if you allow me, to include equatags in "Imports", although I understand you may not want to add an additional non-essential dependence.
Otherwise, maybe something in the line of `if (!require(equatags) stop("missing dependency")` could be added to `flextable::as_equation()`, to help spot this problem in the future.
