### ISSUE TITLE
include.column_percent=F in proc_freq leads to error

### ISSUE THREAD

**Issue by anon94041** [davidgohel/flextable#328]
I'd like a table with just counts, no percentages.  For example,

```
library(flextable)
dat <- data.frame(col1=c(1:3), col2=c(4:6))
proc_freq(dat, row="col1", col="col2", 
          include.row_percent = FALSE,  
          include.table_percent = FALSE, 
          include.column_percent = FALSE)
```

If include.column_percent=T OR include.row_percent=T in the above,  the command produces a table.  If both include.column_percent = F and include.row_percent = F, I get 

```
Error in `$<-.data.frame`(`*tmp*`, "Total", value = NA) : 
  replacement has 1 row, data has 0
```

Is this a bug, or am I doing something wrong?

Thanks.

**Comment by davidgohel** [comment]
Thanks for reporting that, it was a bug. It's now fixed (only in github for now)
