### ISSUE TITLE
Unbold function

### ISSUE THREAD

**Issue by njbart** [davidgohel/flextable#331]
It seems there is no function to unbold parts of a table. 

In particular, `theme_zebra` formats table footers in boldface, and to my mind this just doesn't look right at all.

(As an alternative, I wouldn't mind either if `theme_zebra` were changed *not* to format footers in boldface, in which case having an unbold function would become less urgent, at least from my point of view.)

**Comment by davidgohel** [comment]
the function is named `bold`, if the argument is set to FALSE, it will be set as "not bold".

**Comment by njbart** [comment]
I’m sure I must be doing something wrong, but with this example:

```
library(flextable)
ft <- flextable(head(iris))
ft <- footnote(ft,  i = 1, j = 5, value = as_paragraph("The footnote"))
ft <- add_footer_row(ft, values = "The footer row", colwidths = 5)
ft <- bold(ft, bold = FALSE, part = "footer")
theme_zebra(ft)
```

I get this result:

![Screenshot 2021-07-02 at 11 51 36](https://user-images.githubusercontent.com/2765811/124256726-236edc80-db1b-11eb-8797-043e10bf6211.png)

**Comment by davidgohel** [comment]
`theme_zebra` is making footer part as bold. It needs to be called before you *unbold*

```
library(flextable)
ft <- flextable(head(iris))
ft <- footnote(ft,  i = 1, j = 5, value = as_paragraph("The footnote"))
ft <- add_footer_row(ft, values = "The footer row", colwidths = 5)
ft <- theme_zebra(ft)
ft <- bold(ft, bold = FALSE, part = "footer")
```

**Comment by njbart** [comment]
Ah, that explains it. Many thanks.

**Comment by davidgohel** [comment]
I forgot to answer about your comment... 

If you don't like theme_zebra, you can easily use its code, adapt it and create your theme as a simple function of yours. 

I don't mind about the bold footer, if you want to make a PR to change that, it will be welcome!
