### ISSUE TITLE
Text colour from flextable::color not output to Word

### ISSUE THREAD

**Issue by cbailiss** [davidgohel/flextable#335]
Hello

Thanks for a great package.
I may be doing something wrong, but text colours seem to be lost when saving as Word documents.
Is it expected that text colour is not output to Word?

Nothing is mentioned on the following pages that I checked:

- https://davidgohel.github.io/flextable/reference/color.html
- https://davidgohel.github.io/flextable/reference/save_as_docx.html
- https://davidgohel.github.io/flextable/reference/body_add_flextable.html

Example:

```
library(flextable)
df <- data.frame(X=c("a", "b", "c"), Y=c(1, 2, 3))
ft <- flextable::flextable(df, cwidth=0, cheight=0)
ft <- flextable::color(ft, i=2, j=1:2, color="red")
ft
library(officer)
docx <- read_docx()
docx <- body_add_par(docx, "Example Table")
docx <- body_add_flextable(docx, value = ft)
print(docx, target = "example_table_word.docx")
```
On the left below is the table as HTML (in R-Studio) and on the right is the Word document.
The middle row is not red in Word.

![image](https://user-images.githubusercontent.com/11745789/124186148-cbe95600-dab3-11eb-9b8a-cd83d4d0b842.png)

Session info:

R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] officer_0.3.18         flextable_0.6.6        basictabler_1.0.3      pivottabler_1.5.2.9999

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6        xml2_1.3.2        knitr_1.33        magrittr_2.0.1    uuid_0.1-4        tidyselect_1.1.1  R6_2.5.0          rlang_0.4.11      fansi_0.5.0       dplyr_1.0.7      
[11] tools_4.1.0       data.table_1.14.0 xfun_0.24         utf8_1.2.1        htmltools_0.5.1.1 systemfonts_1.0.2 ellipsis_0.3.2    yaml_2.2.1        digest_0.6.27     tibble_3.1.2     
[21] lifecycle_1.0.0   crayon_1.4.1      zip_2.2.0         purrr_0.3.4       base64enc_0.1-3   htmlwidgets_1.5.3 vctrs_0.3.8       evaluate_0.14     glue_1.4.2        rmarkdown_2.9    
[31] compiler_4.1.0    pillar_1.6.1      generics_0.1.0    gdtools_0.2.3     jsonlite_1.7.2    pkgconfig_2.0.3

**Comment by cbailiss** [comment]
Actually, this may be an issue with Word Online (i.e. Microsoft's web version - part of Office 365) which I was using.
I will check with proper Word tomorrow and confirm.

**Comment by cbailiss** [comment]
When I opened the document in the full version of Word, the table doesn't show at all:

![image](https://user-images.githubusercontent.com/11745789/124242334-8ad55e00-db14-11eb-8b8d-30a254f90c19.png)

Word version:

![image](https://user-images.githubusercontent.com/11745789/124242639-dc7de880-db14-11eb-8120-4dd4d164e2e0.png)

![image](https://user-images.githubusercontent.com/11745789/124242557-c3753780-db14-11eb-8910-d61fcf6fdefb.png)

File is attached:

[example_table_word.docx](https://github.com/davidgohel/flextable/files/6753099/example_table_word.docx)

**Comment by davidgohel** [comment]
Hello,

From the manual: `cwidth, cheight`: initial width and height to use for cell sizes in inches.

You asked a table with cell of with 0 and height 0, so you can't see it.

This should help 

```
library(flextable)
df <- data.frame(X=c("a", "b", "c"), Y=c(1, 2, 3))
ft <- flextable::flextable(df)
ft <- flextable::color(ft, i=2, j=1:2, color="red")
ft
library(officer)
docx <- read_docx()
docx <- body_add_flextable(docx, value = ft)
print(docx, target = "example_table_word.docx")
```

**Comment by davidgohel** [comment]
(the HTML implementation can not reduce columns to 0, that's why it's confusing)

**Comment by cbailiss** [comment]
That makes sense.  I was trying to eliminate minimum sizes or predefined sizes - i.e. HTML does a good job of sizing table rows and columns often without the need to specify sizes.  Is there a way to do this for Word as well?  I.e. allow Word to size automatically or do sizes have to be specified for Word?

**Comment by davidgohel** [comment]
yes, see in the documentation about the table sizes:

https://ardata-fr.github.io/flextable-book/layout-1.html#table-sizes

and use `set_table_properties(x, layout = "autofit")`

**Comment by cbailiss** [comment]
Thanks, I was avoiding using set_table_properties(layout=autofit) because it makes the table (in HTML) expand to the full width of the page (which I don't want) unless a table width is specified (which I also don't want since I am aiming for a compact table that is sized to fit the content).
I think I was confusing it with autofit() which sizes the table to the contents but doesn't expand it to the full width of the page.
Thanks for your help.
