### ISSUE TITLE
flextable width and height cannot be resized when writing to powerpoint with officer

### ISSUE THREAD

**Issue by heathyates** [davidgohel/flextable#339]
**Description of Issue**

When I write a flextable to powerpoint slide, I can place a table anywhere I want using `left` and `top` arguments. However, my width and height arguments are completely overwritten or ignored. 

**Attempts to Resolve**

I attempted the following work arounds: 

-  I created a template for a table with pre-arranged size and write a table using ph_label with the argument 
-  I thought about writing a png to file and then resizing the png, but this code cannot be supported in all of my scenarios (because of webhost dependency) 

**Steps to reproduce**

1.  Use sample_powerpoint.pptx that has been provided 
2. Run the following sample code: 

```
  library(reprex)
  library(officer)
  library(magrittr)
  
  # Create a basic header slide to confirm base functionality 
  my_pres <- officer::read_pptx("sample_powerpoint.pptx")
  my_pres <- officer::add_slide(my_pres, layout = "title", master = "primary")
  my_pres <- officer::ph_with(my_pres, value = "Demo Title", location = ph_location(left = 5, top = 2, type = "Title"))
  my_pres <- officer::ph_with(my_pres, value = "Demo Subtitle", location = ph_location_type(type = "subTitle"))
  
  # Create flex table from iris  
  my_table_data <- iris[1:20, ]
  my_table_flex <- my_table_data %>% flextable::flextable()
  
  # Write table to slide 
  my_pres <- officer::add_slide(my_pres, layout = "secondary", master = "primary")
  my_pres <- officer::ph_with(my_pres, 
                              value = my_table_flex, 
                              location = ph_location_template(top = 1, left = 3, width = 6.52, height = 5.20),  #This is what is ignored
                              use_loc_size = F)
  
  
  # Output the slide 
  print(my_pres, target = "sample_output_slide.pptx")
```

**Additional Information**

The following is my session info. This also can be replicated on Windows 10 machine. 
```
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS
```

Thank you for this excellent package and I hope the above information helps you and others in suggesting a solution for me? 

[sample_powerpoint.pptx](https://github.com/davidgohel/officer/files/6852249/sample_powerpoint.pptx)

**Comment by davidgohel** [comment]
The width and height of flextable are managed by flextable not by officer. Please read the documentation here https://ardata-fr.github.io/flextable-book/layout-1.html#table-sizes

width and height will be ignored for flextable

**Comment by heathyates** [comment]
Thanks! Maybe instead of calling this invalid, we could relabel as a close question? I'll edit it as such too. This might benefit future users. Actually, what I ended up using was as follows: 

- flextable() use the argument cwidth and cheight to modify cell sizes in inches 
- width() use j argument to pick a column and width to manual resize it 
- I then used ph_location() with arguments top and left to place the table on the slide 

Works great! Really nice tool you created. I had the same issue with vanilla dataframes with officer actually, but using flextables resolves it. Thanks for making this.

**Comment by davidgohel** [comment]
Hello, I think you should instead center it. See below:

```
library(officer)
library(flextable)
library(magrittr)

my_pres <- read_pptx()
my_table_data <- head(iris) %>% flextable() %>% autofit()

t_s <- flextable_dim(my_table_flex)$widths
s_s <- slide_size(my_pres)$width

left <- (s_s/2) - (t_s/2) 

# Write table to slide 
add_slide(my_pres) %>% 
  ph_with(value = my_table_flex, location = ph_location(left = left, top = 1.5)) %>% 
  print(target = "sample_output_slide.pptx")
```

I like this better because you don't have to show huge font sizes when the table is small. And I think that's what we would do if we were using PowerPoint. 

Maybe you could also play with `fit_to_width`.

----
About your last question

Sorry, it is "invalid" because it's not a bug, it is already documented (https://davidgohel.github.io/flextable/reference/ph_with.flextable.html#note) and the title says "flextable width and height cannot be resized when writing to PowerPoint with officer" and it's not true. Width and height can be resized when writing to PowerPoint (documented here: https://ardata-fr.github.io/flextable-book/rendering.html#powerpoint-or-word-documents-with-officer).

**Comment by heathyates** [comment]
I edited this to reflect the enhanced understanding and to make it useful for folks when in similar use cases or issues. It's an "invalid" question now I guess? :) 

I appreciate your contributions in code. Your suggestion is gladly accepted and I will look forward to giving it a spin. Thanks!

**Comment by davidgohel** [comment]
Exactly, it's an invalid question now :) it's a catch22

I'll add your question and the proposed solution to the doc!
