### ISSUE TITLE
hline above a selected row i within body part

### ISSUE THREAD

**Issue by SchmidtPaul** [davidgohel/flextable#340]
Hi, great package - big fan! Sorry if I've missed it somewhere, but I couldn't find answer to this.

I want a horizontal border **above** a selected row within the body. Unfortunately, the [documentation of `hline()`](https://davidgohel.github.io/flextable/reference/hline.html) reads _"The lines are the bottom borders of selected cells."_ and [`hline_top()`](https://davidgohel.github.io/flextable/reference/hline_top.html) does not have `i =` argument.

Below is a reprex: I have a Total row in the bottom and I want it to have top and bottom borders, but can only make the latter work. 

``` r
library(flextable)
library(tidyverse)
library(summarytools)

iris$Species %>% 
  summarytools::freq() %>% 
  as_tibble(rownames = "Level") %>% 
  flextable() %>% 
  border_remove() %>% 
  hline_top(part = "header", border = fp_border()) %>% 
  hline_bottom(part = "header", border = fp_border()) %>% 
  # ?top border for Level == "Total"? %>% 
  hline(i = ~ Level == "Total", border = fp_border()) %>%
  bold(i = ~ Level == "Total")
```
![image](https://user-images.githubusercontent.com/31928213/126462860-0d7f1ce5-57c6-4c3c-9038-076a8231f33b.png)

I am suspecting that I can create a not-so-elegant workaround, but wanted to ask here first.

**Comment by davidgohel** [comment]
Hi,

I think this Total could be in the footer. 

```
library(flextable)
library(tidyverse)
library(summarytools)

match_before_level <- function(z){
  x <- rep(FALSE, length(z))
  x[which(z == "Total") -1] <- TRUE
  x
}

iris$Species %>% 
  summarytools::freq() %>% 
  as_tibble(rownames = "Level") %>% 
  flextable() %>% 
  border_remove() %>% 
  hline_top(part = "header", border = fp_border()) %>% 
  hline_bottom(part = "header", border = fp_border()) %>% 
  # ?top border for Level == "Total"? %>% 
  hline(i = ~ match_before_level(Level), border = fp_border()) %>%
  bold(i = ~ Level == "Total")

```

I can add some helper functions like this if necessary. Do you have any other cases where you'd like a *sugar* function selector?

**Comment by SchmidtPaul** [comment]
Thanks, that is a nice way of dealing with it. Well, I was intuitively looking for a 

- `hline(..., where = "bottom")` = default
- `hline(..., where = "top")`
- `hline(..., where = "both")`

argument. This could analogously be added to `vline()` as well. Not sure if it's worth your effort to implement it.
I would potentially also use it in that same table to add a dotted line above the `<NA>` row.

**Comment by davidgohel** [comment]
Hi, no, `hline` will always address the bottom line (as in latex). Users had issues managing borders overlapping (the bottom line that can overlap the top line of the next row, for example).

**Comment by SchmidtPaul** [comment]
I see. Thank you again! Just for completeness, this is what I am going with now:

``` r
library(flextable)
library(tidyverse)
library(summarytools)

# helper function for hline()
line_above <- function(col , entry){
  x <- rep(FALSE, length(col))
  x[which(col == entry) -1] <- TRUE
  x
}

iris$Species %>% 
  summarytools::freq() %>% 
  as_tibble(rownames = "Level") %>% 
  flextable() %>% 
  border_remove() %>% 
  hline_top(part = "header", border = fp_border()) %>% 
  hline_bottom(part = "header", border = fp_border()) %>% 
  hline_bottom(part = "body", border = fp_border()) %>%
  # handle Total row if present
  hline(i = ~ line_above(Level, "Total"), border = fp_border()) %>%
  bold(i = ~ Level == "Total")
```
<sup>Created on 2021-07-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
![image](https://user-images.githubusercontent.com/31928213/126493402-a666f19b-7c5c-4634-9f93-75d3e24039c4.png)
