### ISSUE TITLE
Duplicate image printing when images with the same name are added from different directories

### ISSUE THREAD

**Issue by EvPop21** [davidgohel/flextable#342]
I had recently reported an issue on GitHub for duplicate image printing using the "body_add_fpar" function. Thank you so much for looking into that, I tested your new version, and that issue is fixed.

However, I noticed that this same issue is still occurring when I use the "body_add_flextable" and "compose" functions. 

Below is a reproducible example of the issue. 

Thank you very much!
![rlogo](https://user-images.githubusercontent.com/78435554/129397168-d2565db6-7459-43f3-93d0-0787d38e9228.png)
![rlogo](https://user-images.githubusercontent.com/78435554/129397182-5a3cbd74-fa8a-4534-84a9-ebedd3be34cb.png)

```r
library(officer)
library(flextable)

my_doc <- read_docx()
  flex_tab <- flextable(data.frame(matrix("", nrow = 2, ncol = 2)), cwidth = c(4.35, 4.35), theme_fun = NULL)
  flex_tab <- delete_part(flex_tab, part = "header")
  flex_tab <- compose(flex_tab, j = 1, i = 1, value = as_paragraph(as_image(src = "./dir1/rlogo.png", width = 4.35, height = 2.7)))
  my_doc <- body_add_flextable(my_doc, flex_tab, align = "left")
  flex_tab2 <- flextable(data.frame(matrix("", nrow = 2, ncol = 2)), cwidth = c(4.35, 4.35), theme_fun = NULL)
  flex_tab2 <- delete_part(flex_tab2, part = "header")
  flex_tab2 <- compose(flex_tab, j = 1, i = 1, value = as_paragraph(as_image(src = "./dir2/rlogo.png", width = 4.35, height = 2.7)))
  my_doc <- body_add_flextable(my_doc, flex_tab2, align = "left")
  print(my_doc, target = "test_doc.docx")
```

**Comment by davidgohel** [comment]
closed by https://github.com/davidgohel/officer/commit/c0944daf2e0a07697a75f7d537adf59545cc7122 where image treatments are happening now.

until it's on CRAN, you need to update with:

```
remotes::install_github("davidgohel/officer")
remotes::install_github("davidgohel/flextable")
```
