### ISSUE TITLE
Allow markdown in table captions (similar to fig.cap chunk option)

### ISSUE THREAD

**Issue by Aariq** [davidgohel/flextable#345]
The `fig.cap` option allows markdown expressions including formatting and inline equations. It would be nice if this was possible with table captions also.

For example, with fig.cap, this caption is parsed:
````
```{r fig.cap="This is a figure with an inline latex equation ($y=mx+b$) and some markdown (*italics*, ~subscript~, **bold**)"}
plot(iris)
```
````
But the same caption with a flextable and tab.cap is not parsed.

**Comment by davidgohel** [comment]
Thanks, it should be ok with the latest commit. Let me know if I need to reopen the issue.
