### ISSUE TITLE
Rotate don't work with save_as_image

### ISSUE THREAD

**Issue by JJachacz** [davidgohel/flextable#346]
Hello, 

I have a problem with header text rotation.. that's work in rstudio plot area but the rotation disapear when I want to save my table with save_as_image()

`ft <- flextable(mtcars)`
`ft <- rotate(ft, rotation = "tbrl", align = "top", part = "header")`
`ft`
`save_as_image(ft,path="tableau.png")`

thanks
JJ

**Comment by davidgohel** [comment]
Hello, 

You should use package webshot2 then, it can be set (if installed of course) as:

```
library(flextable)
ft <- flextable(mtcars)
ft <- rotate(ft, rotation = "tbrl", align = "top", part = "header")
ft
save_as_image(ft,path="tableau.png", webshot = "webshot2")
```

See `?save_as_image`.

KR
