### ISSUE TITLE
Fig capture that includes the numbered sections 

### ISSUE THREAD

**Issue by AudioRebel** [davidgohel/flextable#349]
Hi David, 
would it be possible to include an option so that the section number is included when numbering figures or tables like bookdown::word_document2. 

Instead of Fig 1, Fig 2, Fig 3 to have have Fig 1.1, Fig 1.2 and Fig 2.1, assuming the third figure is in section 2.

Thanks,
Claudio

**Comment by davidgohel** [comment]
I think you are are not talking about flextable but about officedown. 

This is documented here: https://ardata-fr.github.io/officeverse/officedown-for-word.html#custom-cross-reference
