### ISSUE TITLE
Not work with function anova

### ISSUE THREAD

**Issue by ShuguangSun** [davidgohel/flextable#35]
If I apply flextable to the results from anova directly, it will report error:

```
Error in parse(text = x, keep.source = FALSE) : 
  <text>:1:8: unexpected symbol
1: Resid. Df
           ^
```

**Comment by davidgohel** [comment]
yep, that's probably because you are not using `regulartable` but `flextable` but as there is no reproducible code nor sessionInfo(). I can't help more.
