### ISSUE TITLE
Text wrapping for rotated text

### ISSUE THREAD

**Issue by BenSolomon** [davidgohel/flextable#358]
Thanks for the great package! I have been having trouble getting text wrapping to work on cells that have been rotated and wondering if this is an oversight on my part or a feature that isn't yet implemented and could be requested. Here is an example

```
# Test data
iris_test <- iris %>% 
  head() %>% 
  rename_all(~gsub("\\.", " ",.))  # Makes iris column names two words to allow for wrapping
iris_test
```

Sepal Length<dbl> | Sepal Width<dbl> | Petal Length<dbl> | Petal Width<dbl> | Species<fctr>
-- | -- | -- | -- | --
1 | 5.1 | 3.5 | 1.4 | 0.2 | setosa
2 | 4.9 | 3.0 | 1.4 | 0.2 | setosa
3 | 4.7 | 3.2 | 1.3 | 0.2 | setosa
4 | 4.6 | 3.1 | 1.5 | 0.2 | setosa
5 | 5.0 | 3.6 | 1.4 | 0.2 | setosa
6 | 5.4 | 3.9 | 1.7 | 0.4 | setosa

```
# No rotation, column name text wraps if width too small
qflextable(iris_test) %>% 
  width(width =0.2)
```
![image](https://user-images.githubusercontent.com/8231047/142745367-7026948e-f01b-4102-a81a-e4f1de4783d2.png)

```
# With rotation, cannot get column name text to wrap if height set too small
qflextable(iris_test) %>% 
  rotate(part = "header", rotation = "btlr") %>% 
  width(width =0.2) %>% 
  height(height = 0.2, part = "header") %>% 
  hrule(rule = "exact", part = "header")
```
![image](https://user-images.githubusercontent.com/8231047/142745370-7204293d-247d-4c6f-aef2-fd610d45943e.png)

**Comment by davidgohel** [comment]
I tried to reproduce, and it seems to me all is ok.

`````
library(dplyr)
library(flextable)

# Test data
iris_test <- iris %>% 
  head() %>% 
  rename_all(~gsub("\\.", " ",.))  # Makes iris column names two words to allow for wrapping
iris_test

ft <- flextable(iris_test) %>% 
  rotate(part = "header", rotation = "btlr") %>% 
  width(width =1) %>% 
  height(height = .7, part = "header") %>% 
  hrule(rule = "exact", part = "header")

print(ft, preview = "pptx")
print(ft, preview = "docx")
print(ft, preview = "pdf")
print(ft, preview = "html")
`````

<img width="1680" alt="Capture d’écran 2021-12-19 à 18 52 52" src="https://user-images.githubusercontent.com/4331618/146685393-b0e0c87f-a55b-4442-bddb-5924880279df.png">

The PDF is adapting the column height to fit the text but that's expected as height property is not implemented with latex output (see `?knit_print.flextable`)
