### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by dwall1** [davidgohel/flextable#36]
Hi David, 

I'm having trouble with the installation of flextable. The error I get is 
Error : object 'ph_from_xml_at' is not exported by 'namespace:officer'
ERROR: lazy loading failed for package 'flextable'
* removing 'C:/Users/dwall1/Documents/R/win-library/3.3/flextable'
Error: Command failed (1)

I'm using R v3.3.3. Could this be causing the issue? Thanks

**Comment by davidgohel** [comment]
You should not open a github account for that!

I guess you just have to update `officer`.
