### ISSUE TITLE
digits argument to set_flextable_defaults does not work

### ISSUE THREAD

**Issue by edonnachie** [davidgohel/flextable#360]
If the number of digits is set via the `set_flextable_defaults` function, flextable does not round the table output as expected. It is necessary to apply `colformat_double(digits = X)` to each flextable.

Below (and attached with HTML output) is a reproducable example (Rmd document):

---
title: "Flextable digit test"
output: html_document
---

```{r setup, include=FALSE}
library(magrittr)
library(flextable)
knitr::opts_chunk$set(echo = TRUE)
```

```{r flextable-defaults}
set_flextable_defaults(
  font.size = 10,
  font.color = "blue",
  digits = 1
  )
```

```{r}
# digits = 1 is not respected
mtcars %>% 
  head() %>% 
  flextable()
```

```{r}
# digits = 1 in the colformat_double() is respected
mtcars %>% 
  head() %>% 
  flextable() %>% 
  colformat_double(digits = 1)
```

[digit_test.zip](https://github.com/davidgohel/flextable/files/7587440/digit_test.zip)

**Comment by davidgohel** [comment]
> [...] flextable does not round the table output as expected [...]

Function `colformat_num()` is the default one used for numeric columns. So you should expect (from colformat_num documentation):

> So this is normally what you see on the R console most of the time (but scientific mode is disabled, NA are replaced, etc.).

<img width="1672" alt="Capture d’écran 2021-11-23 à 12 38 59" src="https://user-images.githubusercontent.com/4331618/143017818-4f8fd458-262a-4c7b-95aa-f93e0c4c7f51.png">

**Comment by davidgohel** [comment]
and the default value for digits is reused, so no need to specify it again despite your bug issue. See below:

<img width="985" alt="Capture d’écran 2021-11-23 à 12 46 05" src="https://user-images.githubusercontent.com/4331618/143018801-25ed77ca-3932-4380-b7fc-3f3b53c5ae85.png">

**Comment by edonnachie** [comment]
I still don't understand why colformat_double() is needed to round the numbers. Setting decimal.mark or big.mark in set_flextable_defaults() applies these by default, and I would have expected set_flextable_defaults(digits = 1) to work in the same way.

**Comment by davidgohel** [comment]
`decimal.mark` and `big.mark` are arguments of `colformat_num()`, that's why it handles them but not `digits`. 

The idea is that users generally want to see roughly data how they can be read in the console, that's what do `colformat_num()` and it's the default formatting for numeric columns. If users want another display, they can use `colformat_double()` for doubles or `colformat_int()` for integers.

I will try to make that more clear in the documentation. I just checked and there are references to `digits` that does not explain that.

**Comment by vorpalvorpal** [comment]
I came here to raise the same issue, but found this one. Would it be possible to have an option that specifies which of colformat_num/double/int() to use by default. I see your point that there is a common use case where printing something similar to the console layout is preferable, but there is another common (I think) use case (especially in things like rmarkdown reports), where pretty printing is what the user most frequently wants.
