### ISSUE TITLE
Force flextable size (height and width) overall

### ISSUE THREAD

**Issue by laresbernardo** [davidgohel/flextable#362]
I've been trying to set a specific size (height and width) for a flextable output for hours and don't find the way to do it dynamically. I'm adding flextable table results to a PowerPoint deck using `officer`. I've tried several different ways and non seem to work perfectly for this single simple task. Is it not possible to force the whole table's size?

I have already tried:
- `width` and `height` functions change columns' sizes, not the table. I do need the `autofit` functionality so I can't calculate ncols x X.
- Using officer's `ph_location_type(type = "body")` (nor `_label`, nor `_template`), flextable doesn't follow the size of the object added in the template.
- The [link](https://ardata-fr.github.io/officeverse/officer-for-powerpoint.html#flextable-1) in the `officer` documentation for this topic doesn't work.
- Using `set_table_properties` seems to be quite near but only to reduce size; it doesn't work for larger than 1 sizes.
- `flextable_dim` only gives information but doesn't let you edit.
- When I dump the flextable object into PowerPoint file, I can simply enlarge the object to fit the size I want manually and it renders OK, but shouldn't there be a way to set the size programmatically on fixed sizes?

**Comment by davidgohel** [comment]
I don't believe it is possible without adding a (complex) calculation made by an R function. For now, it does not exist, for now you can **only** control the width by using function `fit_to_width()`.

I will probably work on this (see related SO https://stackoverflow.com/q/70089054/3315962).

I will comment more on this later

**Comment by davidgohel** [comment]
> width and height functions change columns' sizes, not the table. I do need the autofit functionality so I can't calculate ncols x X.

The table size is available with `flextable_dim()`. You can only change column widths or line heights to change the values returned by `flextable_dim()`. `autofit()` change width and height so that all content fits on in line per cell.


> Using officer's ph_location_type(type = "body") (nor _label, nor _template), flextable doesn't follow the size of the object added in the template.

See section *Note* in `?ph_with.flextable`.

> The link in the officer documentation for this topic doesn't work.

OK, it will be updated.

> Using set_table_properties seems to be quite near but only to reduce size; it doesn't work for larger than 1 sizes.

From the documentation. **[...]It has no effect on PowerPoint[...]**


> flextable_dim only gives information but doesn't let you edit.

That's why it's written "Returns the width, height and aspect ratio of a flextable in a named list." in the manual, and not "modify/update"... 

> When I dump the flextable object into PowerPoint file, I can simply enlarge the object to fit the size I want manually and it renders OK, but shouldn't there be a way to set the size programmatically on fixed sizes?

Probably!
