### ISSUE TITLE
tables comparing multiple versions of the data

### ISSUE THREAD

**Issue by clerousset** [davidgohel/flextable#363]
Hi,

For a data.frame of, for instance, an economic forecast like 

| year | sales |
|-|-|
2022 | 1000 |
2023 | 1100 |

If the datas change across time with new inputs/decisions :

| year | sales |
|-|-|
2022 | 1000 |
2023 | 1050 |

then it's very convenient to see easily what have changed with a before/after comparison table :

| year | sales |
|-|-|
2022 | 1000 |
2023 | <s>1100</s>1050 |

The idea is to be able to provide to a table not only a version of the data but a bunch of them and then select two versions to be compared. The program then strikes through the old digits and highlights the changing cells automatically.

Obviously it can be programmated by any user but maybe it deserves to be on the package, it can be a very reassuring tool for any statistician.

Working at the Insee forecast departement, I did a little Shiny app doing this for a particular case and it was pretty successful.

Regards,

**Comment by davidgohel** [comment]
Hi 

Happy to learn that INSEE is using flextable!

This is a nice feature, but I don't think it should go in flextable, it would probably be better in its own package with many options (I like to use git diff on CSV table for example). Comparing data versions is a huge subject, and I don't want flextable to extend its functions to another domain than tabular reporting. 

KR
