### ISSUE TITLE
Force html rendering for new Rmarkdown outputformats

### ISSUE THREAD

**Issue by saptarshiguha** [davidgohel/flextable#364]
Hello,
Thank you for this very flexible package. I have an rmarkdown document with the following preamble

```
output:
  conflr::confluence_document:
```

When using flextable and rendering the document, it seems flextable thinks this is a pdf output because it tries to call phantomjs and in the output i see `\includegraphics[width=8.25in,height=3.75in,keepaspectratio]{create_confluence_from_rmd_files/figure-commonmark/safari-1.png}` 

Is there a way i can force flextables to render to html?

**Comment by saptarshiguha** [comment]
Hello,
It turns out that `rmarkdown.pandoc.to` is set to `commonmark`. Adding `html` to this option forces html render. But for this to also work in confluence, i also need to set `ft.shadow` to FALSE.

One issue, is that color formatting has gone

**Comment by davidgohel** [comment]
Hello,

flextable does not think it is a pdf output. It seems conflr is using `rmarkdown::md_document` - https://github.com/line/conflr/blob/master/R/document.R#L115. 

flextable supports HTML, docx, pptx and pdf outputs. Other formats are using a fallback made of a screenshot made by webshot. 

By forcing to HTML, you are assuming it can be used as HTML, but as you can see, it does not work. Even if you can force HTML, CSS will be ignored.
