### ISSUE TITLE
When caching flextable, latex_dependencies are not added

### ISSUE THREAD

**Issue by rfaelens** [davidgohel/flextable#366]
When enabling caching in RMarkdown, the flextable cached result is used directly. `flextable:::latex_value()` is not called, and flextable dependencies are not added to knitr metadata.

This results in the following error when rendering an Rmd document with flextable:
```
! Undefined control sequence.
l.382 \hhline
             {>{\arrayrulecolor[HTML]{666666}\global\arrayrulewidth=2pt}->{\...

Error: LaTeX failed to compile thesis.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See thesis.log for more info.
```

Could a different mechanism be used to register latex dependencies (e.g. at package load?). If you feel the problem is upstream (how RMarkdown handles caching of knit_metadata), then feel free to close this bug. I will open one with `rmarkdown` instead.

**Comment by davidgohel** [comment]
I see, thanks for letting me know.

What if you add these instructions ? If it works, I can add these in an exported function...

```
  usepackage_latex("fontspec")
  usepackage_latex("multirow")
  usepackage_latex("multicol")
  usepackage_latex("colortbl")
  usepackage_latex("hhline")
  usepackage_latex("longtable")
  usepackage_latex("array")
  usepackage_latex("hyperref")
```

**Comment by rfaelens** [comment]
If I add these into a chunk that is not cached (e.g. `setup`), that works.
If I add these into a chunk that is cached (e.g. the chunk that creates the flextable), they are not included.

**Comment by davidgohel** [comment]
Thanks, then I'll add that with an explanation of where to use this future function (in a non cached chunk)

**Comment by davidgohel** [comment]
You can now use function `add_latex_dep()` to add flextable latex 
dependencies to the knitr session.


``````
---
title: "Untitled"
output: 
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flextable)
add_latex_dep()
```

## R Markdown

```{r cache=TRUE}
qflextable(iris)
```


``````
