### ISSUE TITLE
Iterate over columns

### ISSUE THREAD

**Issue by djfgerber** [davidgohel/flextable#371]
Hi all
Thank you very much for flextable. It simplifies life a lot!
I could not find out from the documentation how I could iterate over columns using several table columns to combine to one columns (this is I believe beyond the possibilites offered by use_dot) and if there is a way to do so (see my stackexchange post: https://stackoverflow.com/questions/70567228/how-to-iterate-over-flextable-columns)?
Any help would be appreciated and if the issue is not in my understanding of flextable then the documentation could maybe improved.
Best dan

**Comment by davidgohel** [comment]
Hi, 

No, there is no such feature in flextable. The way you did is ok to me. You can maybe create a solution that better suits your needs by using package rlang for example.
