### ISSUE TITLE
Feature Request: Underline text

### ISSUE THREAD

**Issue by jzadra** [davidgohel/flextable#373]
It would be great if there was a function to format text with an underline.

My use case is for hyperlinks: the `hyperlink_text()` does not underline, but this is probably a better general addition rather than adding a specific argument to `hyperlink_text()`

**Comment by davidgohel** [comment]
It is already possible by using the argument `props` of the function you are using: `hyperlink_text(..., props = fp_text_default(underlined = TRUE))`

And for the general addition, it's also already possible:

```
library(flextable)
library(magrittr)

qflextable(head(iris)) %>% 
  style(i = 2, j = 3:4, 
        pr_t = fp_text_default(
          underlined = TRUE)
        )

qflextable(head(iris)) %>% 
  mk_par(i = 2, 
        j = 3:4, 
        use_dot = TRUE, 
        value = as_paragraph(
          "something ", 
          as_chunk(., props = fp_text_default(underlined = TRUE)))
        ) %>% 
  autofit()

```

see: 

* function style: https://ardata-fr.github.io/flextable-book/format.html#function-style
* function compose/mk_par: https://ardata-fr.github.io/flextable-book/cell-content-1.html#function-compose
