### ISSUE TITLE
Apply styling to table captions

### ISSUE THREAD

**Issue by thebioengineer** [davidgohel/flextable#375]
When submitting a feature request, please explain the value, describe the situation and be reasonable.

**Not a bug or feature request? If you are looking for help on how to use the 
package correctly, please read the doc first at https://davidgohel.github.io/flextable/. 
You can also visit [Stackoverflow](https://stackoverflow.com/questions/tagged/flextable+r) 
and tag your question with `[flextable]`. We usually read them and answer WHEN possible.**  

For headers, cell contents, and footers you have developed a method for applying styling of the text contents. for example - `as_paragraph`,`as_sub`, `as_chunk`. I was curious if this same process could be applied to the table caption as well? It would be super helpful as right now there is no styling we can apply if you want to add super or subscripting, etc. 

For example, it would be great to be able to do this:

```r

ft <- flextable(head(cars))

ft %>% flextable::set_caption(
  caption = as_paragraph(
    as_chunk("This is the header with"),
    as_sup("superscripting")
  )
)

```

**Comment by Pindar777** [comment]
@thebioengineer Have you tired `set_caption(caption = "MyCaption", style ="Normal")` with flextable versions prior to 0.6.10?
