### ISSUE TITLE
Exporting in .rtf?

### ISSUE THREAD

**Issue by Pierre-Wallet** [davidgohel/flextable#376]
Hi David,

Is there a way to export the flextable objects into .rtf file?

Thanks,
Pierre.

**Comment by davidgohel** [comment]
Hi Pierre,

No, it is planned, but I still not have find time it. The same applies to plot output (a real one, not a wrapper that screenshots a table). 

In short, there will be "plot" and "RTF" outputs, but it will take some time.

David

**Comment by davidgohel** [comment]
For those who read this, the package now supports RTF and grid graphics (ggplot2, patchwork, etc.)

(RTF starting with flextable `0.8.6`, grid graphics starting with version `0.8.0`)
