### ISSUE TITLE
BUG: flextable > 0.6.8 stops using style: “Table Caption” for the inserted tables in DOCX

### ISSUE THREAD

**Issue by Pindar777** [davidgohel/flextable#377]
In order to verify just knit a rmd via 

```
 bookdown::markdown_document2:
    base_format: officedown::rdocx_document
```

and insert a table.
The table style is simple "standard" and not “Table Caption” anymore.
I noticed the change after upgrading from "flextable 0.6.7" and tested that from "0.6.10" the bug is present.

**Comment by davidgohel** [comment]
<img width="1357" alt="Capture d’écran 2022-02-19 à 14 18 03" src="https://user-images.githubusercontent.com/4331618/154802504-d089c900-0324-4191-95f7-2c521cccc9e4.png">



``````
---
output: officedown::rdocx_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.cap = TRUE)
library(officedown)
library(officer)
library(flextable)
```

```{r tab.cap='test'}
qflextable(head(iris))
```

```{r}
sessionInfo()
```


``````





````
## R version 4.1.2 (2021-11-01)
## Platform: x86_64-apple-darwin17.0 (64-bit)
## Running under: macOS Big Sur 10.16
## 
## Matrix products: default
## BLAS:   /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.0.dylib
## LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib
## 
## locale:
## [1] fr_FR.UTF-8/fr_FR.UTF-8/fr_FR.UTF-8/C/fr_FR.UTF-8/fr_FR.UTF-8
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] flextable_0.7.0.006 officer_0.4.1       officedown_0.2.3   
## 
## loaded via a namespace (and not attached):
##  [1] Rcpp_1.0.8        rstudioapi_0.13   knitr_1.37        xml2_1.3.3       
##  [5] magrittr_2.0.2    locatexec_0.1.1   equatags_0.1.1    xslt_1.4.3       
##  [9] uuid_1.0-3        R6_2.5.1          rlang_1.0.0       fastmap_1.1.0    
## [13] stringr_1.4.0     tools_4.1.2       data.table_1.14.3 xfun_0.29        
## [17] rvg_0.2.5         cli_3.1.1         htmltools_0.5.2   systemfonts_1.0.3
## [21] yaml_2.2.2        digest_0.6.29     zip_2.2.0         base64enc_0.1-3  
## [25] memoise_2.0.1     cachem_1.0.6      evaluate_0.14     rmarkdown_2.11   
## [29] stringi_1.7.6     compiler_4.1.2    gdtools_0.2.4

````



Nest time, follow the guidelines. 

From the guidelines you deleted and did not follow:

-----
When submitting a new issue:

- [ ] Provide the code that is producing the error, it has to be a minimal reproducible example.
Stackoverflow is providing good explanations about it: https://stackoverflow.com/help/mcve. You can use package `reprex` to help you: http://reprex.tidyverse.org/. The most popular R stackoverflow question is about the subject: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

- [ ] Provide the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example. 

- [ ] Make sure you did checked you had the latest version of the package on CRAN (and on github if issue exists with CRAN version).

- [ ] Make sure you searched in the *open* and *closed* issues on the github repository.



--------

**Comment by Pindar777** [comment]
@davidgohel Thank you for your fast response. Now I know how you would produce a reprex and your example helped me in finding the 'bug': There is a breaking change in the behavior of `set_caption(caption = "MyCaption")` 
I used (for some reason I don't remember) `set_caption(caption = "MyCaption", style ="Normal")` which did not effect the styling of lable as such e.g. "Table XXX". Since 0.6.10 the style-parameter affects the whole line and hence it does not show up in the summary. 

Glad that there is now the solution and I can update R!

Have a nice weekend
