### ISSUE TITLE
Newlines are stripped from text

### ISSUE THREAD

**Issue by mattantaliss** [davidgohel/flextable#39]
Any newlines included in text in a flextable (0.3.0; R 3.3.2) are stripped out when printed. For example, the multi-line

Hello
World

is not displayed in the following table:

```
df <- data.frame(A = "Hello World", B = "Hello\nWorld", C = "Hello\r\nWorld")
ft <- flextable(df)
ft <- width(ft, width = 1)
ft
```

The motivation for me here is to dictate the location of a line break in a table cell. I'm working with a date range as text (example: "January 1, 2017 -- November 22, 2017") and tables that have either three or four columns and widths that are set to consume the entire page width (so the four-column table has narrower columns).

In the three-column table, the auto-wrapping breaks the date range after the second month, e.g.,

January 1, 2017 -- November
22, 2017

while everything looks all right in the four-column table, e.g., 

January 1, 2017 --
November 22, 2017

What I would really like to do is dictate the location of the line break by using a date range like "January 1, 2017 --\r\nNovember 22, 2017" (or only "\n" instead of "\r\n" if the "\r" is unnecessary) so it looks correct in all of my tables.

**Comment by davidgohel** [comment]
That is not a feature of `flextable`, one cell can contain only one paragraph in flextable.

Are you having trouble because you can't add paragraph breaks or because you would like to have widths corresponding to the ideal size? 

Function `autofit()` will resize columns so that any content fit perfectly on one line (a single paragraph).

**Comment by mattantaliss** [comment]
I would say my trouble is that I can't add paragraph breaks.

What I'm looking to do is have a table whose width is the same as the text area and whose columns have equal widths. For example, when working with a US Letter sized document (8.5" wide) and 1" margins, I'll have a text area width of 6.5". Then, for my four-column tables, each column will have a width of 1.625", and for my three-column tables, each column will have a width of (approximately) 2.167".

The problem I'm having is that my date range information (for the above example) breaks where I want in the four-column table but not in the three-column table, and I want the break to be consistent between the tables and over all possible date ranges (e.g., it should be the same for "January 1, 2017 -- November 22, 2017" and "April 1, 2017 -- May 1, 2017").

When I use `autofit()`, the overall table width usually ends up being more than the text area width and some times even more than the page width because of long text in another cell, so that's not a viable solution.

All in all, I'm looking for a way to manually specify where a break should occur when wrapping text in a table cell. I thought adding a newline would do it, but that gets stripped, so either being able to do that or passing something to the auto-wrapping functionality to specify where the break should occur would be very helpful.

I did see davidgohel/ReporteRs#20 as a possible work-around, but I'm not sure if that sort of approach will still work (I know the actual code won't work because `flextable` has changed since then).

**Comment by davidgohel** [comment]
Does the last answer helped? Could you provide a feedback?

**Comment by mattantaliss** [comment]
Apologies for responding when you had first posted that work-around. Yeah, that answer does help. I haven't tested it yet, but it does look like a viable work-around so this issue can be closed. Thanks!

**Comment by davidgohel** [comment]
thanks. I will let you know when a less strict version will be implemented

**Comment by cardiomoon** [comment]
I am a big fan of your flextable ! But I also need linefeed in a cell. Please help me with less strict version.

**Comment by davidgohel** [comment]
Thanks @cardiomoon 

I am sorry, I really don't have time for now. Will implement that later.

**Comment by davidgohel** [comment]
@cardiomoon @mattantaliss soft returns `\n` are now available. Note that function `autofit` and `dim_pretty` do not support soft returns, `\n` will be considered as `""`.

**Comment by cardiomoon** [comment]
Daer David,

Thank you very much.

Your packages are really invaluable ! 

I appreciate all the help you’ve given me.
 
Keon-Woong Moon

**Comment by HJAllen** [comment]
Suggestion to handle linefeeds in call to ```optimal_sizes.simple_tabpart```. The idea is to split the cell string on linefeed ``'\n'`` and return the longest string. It isn't perfect because sometimes the width returned from ```m_str_extents``` isn't wide enough.
```
optimal_sizes_simple_tabpart <- function( x ){

  txt_data <- flextable:::get_text_data(x)
  txt_data$type_out <- rep("text", nrow(txt_data))
  txt_data$pos <- rep(1, nrow(txt_data))
  text_fp <- x$styles$text$get_fp()

  sizes <- flextable:::text_metric(data = txt_data, all_fp = text_fp)
  ### START new code
  # Rerun with max strsplit(txt_dat$str, "\n")[[1]]
  txt_data$str <-
    sapply(txt_data$str,
           function(y){
             s_ <- strsplit(y, "\n")[[1]]
             ifelse(length(s_ == 1), s_, s_[which.max(nchar(s_))])
           },
           USE.NAMES = FALSE)
  # Recalc width
  sizes$width <- flextable:::text_metric(data = txt_data, all_fp = text_fp)$width
  ### END new code
  sizes$col_key <- factor(sizes$col_key, levels = x$col_keys)
  sizes <- sizes[order(sizes$col_key, sizes$id ), ]
  widths <- flextable:::as_wide_matrix_(as.data.frame(sizes[, c("col_key", "width", "id")]))
  heights <- flextable:::as_wide_matrix_(as.data.frame(sizes[, c("col_key", "height", "id")]))

  par_dim <- flextable:::dim_paragraphs(x)
  widths <- widths + par_dim$widths
  heights <- heights + par_dim$heights

  widths[x$spans$rows<1] <- 0
  widths[x$spans$columns<1] <- 0
  heights[x$spans$rows<1] <- 0
  heights[x$spans$columns<1] <- 0

  cell_dim <- flextable:::dim_cells(x)
  widths <- widths + cell_dim$widths
  heights <- heights + cell_dim$heights
  list(widths = apply(widths, 2, max, na.rm = TRUE),
       heights = apply(heights, 1, max, na.rm = TRUE)
  )
}
```
