### ISSUE TITLE
autofit is giving an error, then hanging

### ISSUE THREAD

**Issue by bradleymecham** [davidgohel/flextable#392]
The first time I call summary_table <- autofit(summary_table), I get this error:

Error in m_str_extents_(x, fontname, fontsize, bold, italic, fontfile) : 
  function 'Rcpp_previous_remove' not provided by package 'Rcpp'

The next time I call it, the execution hangs and I have to quit R.

My table has 11 columns and 17 rows, all of the entries being text.  It also has three footer lines and a caption.  However, even if I run summary_table <- autofit(summary_table) prior to adding the footer lines and caption, I get the error.

I have RStudio 1.3.959 and R 4.0.2

**Comment by davidgohel** [comment]
you probably need to update your packages
