### ISSUE TITLE
Setting bg color in a flextable that has been subsetted using col_keys arg

### ISSUE THREAD

**Issue by hmeleiro** [davidgohel/flextable#395]
I'm having some trouble setting the background color of cells based on a color scale. When using `scales::col_numeric` in a flextable where I have chosen some col_keys, the j argument does not work properly (or how I think is properly). 

In the following example the bg color is set based on the left cell as if we hadn't selected some of the columns using `col_keys`. 

``` 
library(flextable)

x <- head(iris)

ft_2 <- flextable(x, col_keys = c("Sepal.Width", "Petal.Length", "Petal.Width", "Species"))
colourer <- scales::col_numeric(
  palette = c("wheat", "red"),
  domain = c(0, 2))

ft_2 <- bg(ft_2, j = 2:ncol_keys(ft_2),
           bg = colourer, part = "body")
ft_2

``` 
![image](https://user-images.githubusercontent.com/29704914/166435795-7f9e8643-e6ab-4b3e-8c2a-390a51b9680b.png)

Is this behaviour normal?

Thanks for the package!

**Comment by davidgohel** [comment]
Hi,

There was a bug in flextable, but it's fixed now. 

However, after having updated the package, you may need to adapt your code.

* You may have understood that `j` is refering to original `data.frame` but it refers to `col_keys`. Let me know if unclear.
* Function `colourer` need to be updated with a wider `domain`.
 

```r
library(flextable)

x <- head(iris)

ft_2 <- flextable(
  data = x,
  col_keys = c("Sepal.Width", "Petal.Length", 
               "Petal.Width", "Species"))

colourer <- scales::col_numeric(
  palette = c("wheat", "red"),
  domain = c(0, 4))# changed 2 to 4 to avoid warning

ft_2 <- bg(ft_2,
           # j is relative to colkeys, not the columns of the original dataframe
           j = 1:3,
           bg = colourer)

ft_2
```

<img width="591" alt="Capture d’écran 2022-05-05 à 18 57 23" src="https://user-images.githubusercontent.com/4331618/166974357-97b872bc-f91b-4d23-beff-8f6b3ca01884.png">

**Comment by hmeleiro** [comment]
Great! thanks for the fix.

Yes I understood that `j` is indexing the flextable object `col_keys` not the columns of the underlying `data.frame`. That's actually what bugged me at first. So yes, it is clear. And you are correct about the domain, it should be wider, I just limited the domain for the reprex so that it was obvious that something was wrong.
