### ISSUE TITLE
Allow row to break across pages in Word

### ISSUE THREAD

**Issue by cforne** [davidgohel/flextable#396]
With the version 0.7.0, when rendering in Word, the tables do not allow row to break across pages, although ft.table = TRUE is specified in knitr's chunk options. Until version 0.6.10, tables allowed row to break across pages in Word, even without specifying ft.table = TRUE in chunk options.

Thank you very much for your excellent work!

**Comment by davidgohel** [comment]
I think you are talking about `ft.split` option. 

I had a quick look, and it did not disappear, but I inverted the effect of TRUE/FALSE. 

I'll fix very soon.
