### ISSUE TITLE
save_as_docx crashes R session if word document is open

### ISSUE THREAD

**Issue by Paul-Mee** [davidgohel/flextable#397]
When I create a flextable object (stat_tab)  and then save is as a docx - using the following code 

flextable::save_as_docx(stat_tab,path = paste0(out_dir,out_file))

If the word file is already open the R session is aborted .

It would be useful if the code could capture this and provide a suitable error message.

**Comment by davidgohel** [comment]
Thanks.

I think it already does it. https://github.com/davidgohel/officer/blob/master/R/read_docx.R#L146

* If you think it is not, please follow the guidelines (the text you deleted when you submitted your issue) and I will reopen the issue. I copied them below. Please, add also the name of the edited Word file in your file system (it should start with `~`). 


----

**Not a bug or feature request? If you are looking for help on how to use the 
package correctly, please read the doc first at https://davidgohel.github.io/flextable/. 
You can also visit [Stackoverflow](https://stackoverflow.com/questions/tagged/flextable+r) 
and tag your question with `[flextable]`. We usually read them and answer WHEN possible.**  

When submitting a new issue:

- [ ] Provide the code that is producing the error, it has to be a minimal reproducible example.
Stackoverflow is providing good explanations about it: https://stackoverflow.com/help/mcve. You can use package `reprex` to help you: http://reprex.tidyverse.org/. The most popular R stackoverflow question is about the subject: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

- [ ] Provide the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example. 

- [ ] Make sure you did checked you had the latest version of the package on CRAN (and on github if issue exists with CRAN version).

- [ ] Make sure you searched in the *open* and *closed* issues on the github repository.
