### ISSUE TITLE
Table still splits on page break if ft.keepnext=T

### ISSUE THREAD

**Issue by dwwolfson** [davidgohel/flextable#398]
I'm knitting a .Rmd file to .docx format. One of my flextables is split over a page break. I think the default option was not to allow this? Even if I specify ft.keepnext=T in the chunk option the output is the same.

**Comment by davidgohel** [comment]
cross-posted here: https://community.rstudio.com/t/how-to-prevent-flextable-from-splitting-from-page-break/137106

Thanks for opening this bug report.

> I think the default option was not to allow this? 

I don't think so
