### ISSUE TITLE
merge_v only works in column 1 in header

### ISSUE THREAD

**Issue by andresnecochea** [davidgohel/flextable#409]
Hi I'm trying to make a merge_v on header part but only works in column 1

work:
```
flextable(airquality[sample.int(10),]) |>
  add_header_row(values=names(airquality)) |>
  merge_v(j=1, part="header")
```

dosn't work:
```
flextable(airquality[sample.int(10),]) |>
  add_header_row(values=names(airquality)) |>
  merge_v(j=2, part="header")
```

Maybe I'm doing something wrong but it used to work on previous versions.
I'm using now the github version, but it also does not work in the CRAN version.

**Comment by davidgohel** [comment]
Hello,

Sorry for this bug. The workaround is to use column names or another type of selector (the numeric one is the problematic one).

I'll send a new version on CRAN soon with this fix. Meanwhile, you can use the github version.
