### ISSUE TITLE
Caption lost with save_as_pptx?

### ISSUE THREAD

**Issue by MatthieuStigler** [davidgohel/flextable#412]
I notice that the `caption` output is not reproduced by `save_as_pptx`, at least when I look at the output in LibreOffice? Is that intended/known limitation or unknown one? 

Thanks!

``` r
library(flextable)
packageVersion("flextable")
#> [1] '0.7.2'

tab <- flextable(head(iris)) |>
  set_caption("A title") |>
  add_footer_lines("Note: bla bla ")
  
tab
```

``` r
save_as_pptx(tab, path = "example.pptx")

sessionInfo()
#> R version 4.2.0 (2022-04-22)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 20.04.4 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3
#> LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=de_CH.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=de_CH.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=de_CH.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=de_CH.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] flextable_0.7.2
#> 
#> loaded via a namespace (and not attached):
#>  [1] zip_2.2.0         Rcpp_1.0.8.3      pillar_1.7.0      compiler_4.2.0   
#>  [5] highr_0.9         R.methodsS3_1.8.1 R.utils_2.11.0    base64enc_0.1-3  
#>  [9] tools_4.2.0       uuid_1.1-0        digest_0.6.29     jsonlite_1.8.0   
#> [13] evaluate_0.15     lifecycle_1.0.1   tibble_3.1.7      R.cache_0.15.0   
#> [17] pkgconfig_2.0.3   rlang_1.0.2       reprex_2.0.1      cli_3.3.0        
#> [21] rstudioapi_0.13   yaml_2.3.5        xfun_0.31         fastmap_1.1.0    
#> [25] xml2_1.3.3        officer_0.4.2     withr_2.5.0       styler_1.7.0     
#> [29] stringr_1.4.0     knitr_1.39        systemfonts_1.0.4 gdtools_0.2.4    
#> [33] fs_1.5.2          vctrs_0.4.1       webshot_0.5.3     glue_1.6.2       
#> [37] data.table_1.14.2 R6_2.5.1          processx_3.5.3    fansi_1.0.3      
#> [41] rmarkdown_2.14    callr_3.7.0       purrr_0.3.4       magrittr_2.0.3   
#> [45] ps_1.7.0          ellipsis_0.3.2    htmltools_0.5.2   utf8_1.2.2       
#> [49] stringi_1.7.6     crayon_1.5.1      R.oo_1.24.0
```

<sup>Created on 2022-06-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by davidgohel** [comment]
Hello,

No, caption are not used for PowerPoint output. Deck is not structured and does not behave as HTML document and paginated documents (word, pdf), and it's not possible to clearly know where we should create a shape to contain it, technically it can't be in the shape containing the table.

**Comment by MatthieuStigler** [comment]
My bad, I missed it in those two places. I had looked at ` save_as_pptx`, but didn't find it there, which seems a natural place to look since it is ppt specific?

I am not sure about `flextable::knit_print.flextable()` and `flextable::flextable_to_rmd(), but those seem to render captions? So a warning would not be necessary there

I don't understand well the code for ` save_as_pptx`, but what I have in mind would be something like:

`if(any(sapply(values, function(x) !is.null(x)))) warning("Slot 'caption' will not be preserved by save_as_pptx")`

eventually with a global option to switch it off, for more experienced users?

Anyway, those are just suggestions! having now discussed it here on github already allows for discoverbaility :-)
