### ISSUE TITLE
flextable::color produces corrupt Word doc

### ISSUE THREAD

**Issue by popovs** [davidgohel/flextable#417]
Hello, I've got a strange issue with the flextable `color` function corrupting my Microsoft Word documents. I can create a flextable with colored text with no problem in my R environment. I can even knit an Rmarkdown document successfully -- with no errors -- when calling `flextable::color`. However, when I try to open the Word doc, I get the following error: 

```
Word experienced an error trying to open the file.
Try these suggestions.
* Check the file permissions for the document or drive.
* Make sure there is sufficient free memory and disk space.
* Open the file with the Text Recovery converter.
 (bug_test.docx)
```

A minimal .Rmd doc can reliably reproduce this error on my machine:

`````
---
title: "bug_test"
author: "popovs
date: '2022-06-29'
output: 
  word_document:
    toc: yes
    toc_depth: 2
---

```{r flextable_test}
library(dplyr)
data("airquality")
airquality %>%
  head() %>%
  flextable::flextable() %>%
  flextable::color(j = "Ozone",
                   color = function(x) ifelse(x > 25, "#BD2403", "grey"))
```

`````

The resulting Word document is corrupted regardless of whether I declare the output to be a `word_document`, `bookdown::word_document2`, or `officedown::rdocx_document`.

Finally here's the session info:

```
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] flextable_0.7.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8.3      digest_0.6.29     R6_2.5.1         
 [4] evaluate_0.15     zip_2.2.0         rlang_1.0.3      
 [7] gdtools_0.2.4     cli_3.3.0         uuid_1.1-0       
[10] data.table_1.14.2 rstudioapi_0.13   xml2_1.3.3       
[13] rmarkdown_2.14    tools_4.1.2       officer_0.4.3    
[16] xfun_0.31         yaml_2.3.5        fastmap_1.1.0    
[19] compiler_4.1.2    systemfonts_1.0.4 base64enc_0.1-3  
[22] htmltools_0.5.2   knitr_1.39       
```

**Comment by popovs** [comment]
Somewhat happy update for me: the problem goes away when I go back to flextable version `0.7.0`. So that's my temporary fix for now, in case anybody else has this issue.

**Comment by davidgohel** [comment]
It happens because there are NA in your colors. I have just added a control that prevent using NA. 

It worked in the previous version, but we prefer now to give users an error saying there are NA instead of using the default color (which was what was implemented, but users had no idea of this mechanism)

**Comment by davidgohel** [comment]
Let me know if it's clearer :)
