### ISSUE TITLE
subtotal and grand total

### ISSUE THREAD

**Issue by jic007** [davidgohel/flextable#421]
one of the greatest features of excel is summarising data especially when using pivot tables.
in pivot tables you can create custom calculation fileds per group and also the grand total.

e.g. you have multiple groups and have one column fro value and another for rating. you can create a row or rows to do calculations for that column per group and at the end of the table you have grand calculations.

I am in need of such a thing as I am reporting on more than 100 groups. I hope you can share an idea how to do that

**Comment by davidgohel** [comment]
yes, you can use packages like dplyr or data.table to aggregate your data. They are popular R packages that enable (all possible) data manipulations. Once the data is ready, it's ready to send them to flextable and format them as in the following example:

```r
library(tidyverse)
library(flextable)

z1 <- iris %>% group_by(Species) %>% 
  summarise(across(where(is.numeric), ~ mean(.x)))
z2 <- iris %>% 
  summarise(across(where(is.numeric), ~ mean(.x))) %>% 
  mutate(Species = "Total")

bind_rows(z1, z2) %>% 
  flextable() %>% 
  colformat_double() %>% 
  hline(i = ~ before(Species, "Total"), border = fp_border_default())

```

<img width="638" alt="Capture d’écran 2022-07-12 à 10 05 21" src="https://user-images.githubusercontent.com/4331618/178441179-9ae4ae80-4640-4b4d-8eea-572170a7c8a9.png">
