### ISSUE TITLE
Display problem with `set_table_properties(layout = "autofit")` (in html only)

### ISSUE THREAD

**Issue by rempsyc** [davidgohel/flextable#429]
In the context of `rempsyc::nice_table`, I am usually reporting the 95% CI in one of the columns but I am experiencing some display issues in HTML (e.g., for tutorials) using `set_table_properties(layout = "autofit")` when viewed from internet browsers (though it works fine with `autofit()`). Reprex:

``` r
library(flextable)
#> Warning: package 'flextable' was built under R version 4.2.1

x <- data.frame(x = c("[-0.36, -0.01]", "[0, 0]", 
                      "000, 000", "0000 0000"))

x |> 
  flextable() |> 
  autofit()

x |> 
  flextable() |> 
  set_table_properties(layout = "autofit")
```
<sup>Created on 2022-07-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

When viewed in the RStudio _Viewer_ or the RStudio _Browser_ (rmarkdown), they look fine:

![](https://i.imgur.com/SE2ky0t.png)

When viewed in Word, they also look fine:

![](https://i.imgur.com/atFW9Vq.png)

However, when viewed from any actual browser (e.g., rmarkdown through Google Chrome), the 95% CI column gets squeezed on two lines with `set_table_properties(layout = "autofit")` (though not with `autofit()`):

![](https://i.imgur.com/aMzIR9r.png)

Based on this reprex, it seems that the issue triggers as soon as four characters are separated by a space. Is this behaviour expected? Is there any workaround (while still using `layout = "autofit"`)? For example, is there a way to "soft force" the content to stay on one line (when there is sufficient space)?

Otherwise, best results seem to be with `layout = "fixed"` (in my case with larger tables, even `autofit()` seems to have this problem somehow), though we lose the benefits of autofit.

**Comment by Buedenbender** [comment]
Hi, I was able to replicate the error. It looks fine in the Viewer in Rstudio and Word but fails in the actuall browser.
Tested it in Firefox and Chrome:
![grafik](https://user-images.githubusercontent.com/38650857/181740574-12c8af35-b5cf-4955-ac92-115a2ba6da54.png)

This also affects vignettes created for a `pkgdown` page. You can work around this issue by setting a width
```r
my_ft [%>%](https://magrittr.tidyverse.org/reference/pipe.html)
  # For markdown we additionally need to fix the autofit property, this step is not
  # needed when directly saved to word e.g. with datscience::save_flextable()
  set_table_properties(layout = "autofit", width = 1)
```

**Comment by davidgohel** [comment]
hello,

it should be fixed now

**Comment by rempsyc** [comment]
I can confirm it works beautifully now!
