### ISSUE TITLE
Contingency tables

### ISSUE THREAD

**Issue by sstudent** [davidgohel/flextable#43]
Is there a method to use the flextable to plot contingency tables as generated with table {base} command?

**Comment by davidgohel** [comment]
flextable do not plot, it creates tables. read more here: https://davidgohel.github.io/flextable/

**Comment by davidgohel** [comment]
Do me a favor and read that post: https://github.com/davidgohel/flextable/issues/41

`flextable` and `regulartable` are expecting a data.frame. Maybe that can help: `?as.data.frame`

I will migrate https://cran.r-project.org/web/packages/rtable/ to `flextable`next year (which contains the function you are after).
