### ISSUE TITLE
Feature Request: Save as vector image format?

### ISSUE THREAD

**Issue by N-Accumbens** [davidgohel/flextable#432]
Hello,

Great package, I'm just wondering if it'd be possible to save tables in a vector image format like svg? Having vector format images is great if you want to zoom-in to especially large tables.

**Comment by davidgohel** [comment]
Hello

Not exactly possible right now with a single command. There is one workaround via `save_as_image`:

```
library(flextable)
library(webshot2)

ft <- flextable(head(iris)) |> autofit()
save_as_image(x = ft, path = "ft.pdf", webshot = "webshot2")
```

The result is a vector image PDF.

**Comment by davidgohel** [comment]
It's now implemented thanks to grid graphics! (note it can be slow with large tables)

```
library(flextable)

ft <- flextable(iris) |> autofit()
gr <- gen_grob(ft, scaling = "fixed", fit = "fixed", just = "center")
dims <- dim(gr)
svglite::svglite(filename = "hello-grid-graphics.svg", width = dims$width + .1, height = dims$height + .1)
plot(gr)
dev.off()
```

<img width="618" alt="Capture d’écran 2022-09-06 à 17 41 43" src="https://user-images.githubusercontent.com/4331618/188678110-c511f67f-af31-40fe-90c1-62ab6481df12.png">
