### ISSUE TITLE
First-line or hanging indentation?

### ISSUE THREAD

**Issue by kendonB** [davidgohel/flextable#435]
It would be great to be able to control the type of indentation in flextable. Currently, I believe all cells have no indentation. A journal style I was trying to mimic, however, has first-line indentation in the footer.

The Microsoft Word settings for this are in the Paragraph controls.

![para](https://user-images.githubusercontent.com/5327505/184268843-822523b3-aa22-47c5-bf71-5ce997d9e5c5.png)

**Comment by davidgohel** [comment]
Use function `padding` instead, flextable does not allow 2 paragraphs in a same cell

**Comment by kendonB** [comment]
Even with a single paragraph in a cell, there's still a use case here as the text can wrap. `padding` indents all lines in a cell whereas I'm looking for first-line or hanging indents.
