### ISSUE TITLE
footnote fails in 0.7.3

### ISSUE THREAD

**Issue by vipermcs** [davidgohel/flextable#436]
This reprex doesn't work in flextable 0.7.3 under R 4.2.1 w/tidyverse on Windows 10,
it gives: **Error in `[<-`(`*tmp*`, i, j, value = value) : subscript out of bounds**

require(tidyverse)
g=
	tibble(C1=1:7,C2=LETTERS[1:7],C3=(7:1)+0.321)%>%
	flextable::flextable()%>%
	flextable::footnote(
		i=c(1,3,5),j=c(1,1,1),
		value=flextable::as_paragraph(c("One","Three","Five")),
	)

Same error occurs if require(flextable) first,
It did/does work in flextable 0.7.0 under R 4.2.0 w/tidyverse on Windows 10.

Thanks. Keep up the good work.

**Comment by davidgohel** [comment]
Hello,

Yes, footnote changed with `flextable 0.7.1`. You can have a look at the NEWS here: https://github.com/davidgohel/flextable/blob/fe59ce1436045225c09dfce370d8ad64d5fa8466/NEWS.md?plain=1#L91


You are now forced to specify the symbols as following:

```
require(tibble)
require(flextable)
g <- tibble(C1 = 1:7, C2 = LETTERS[1:7], C3 = (7:1) + 0.321) |>
  flextable::flextable() |>
  flextable::footnote(
    i = c(1, 3, 5), j = c(1, 1, 1),
    ref_symbols = c("A", "B", "C"),
    value = flextable::as_paragraph(c("One", "Three", "Five")),
  )
g
```


<img width="570" alt="Capture d’écran 2022-08-18 à 16 59 15" src="https://user-images.githubusercontent.com/4331618/185427751-5b2f6675-037f-4486-a73d-a3fc6a1b5a95.png">
