### ISSUE TITLE
Easily produce tables using several regression specifications

### ISSUE THREAD

**Issue by kendonB** [davidgohel/flextable#437]
![image](https://user-images.githubusercontent.com/5327505/184563282-be9a51d8-9de7-4200-8aea-6bcdce06169e.png)

Consider the above table, the feature request is to build functionality to create tables like this. Features that I don't believe are available yet but would enable something like this is:

- [ ] A function to replace `as_flextable.lm` that would create the regression output as a single column with standard errors below estimates.
  - [ ] Aligning the decimals between the coefficient-standard error pairs is possible but tedious. In Word and LaTeX, the best solution I know is to create one table environment for each pair, nested inside the larger table environment, then use the standard approach to align on decimal.
  - [ ] The function would allow for replacing groups of variables with a label (e.g. "9 Year-of-birth dummies") and value (e.g. "Yes"). 
- [ ] A function to `bind_cols` two such flextables (possibly could work now with the `merge` functions).
  - [ ] The function would insert the em dash in columns where a variable is missing.

The package that can currently do some of this is `stargazer`. However, one loses the great flexibility and nice grammar of `flextable` when using that.

![image](https://user-images.githubusercontent.com/5327505/184564461-d6c0db28-78ea-4490-8fd6-893006f5583a.png)

I'm quite keen to help out on this if it's something you're interested in but don't know where to start.

**Comment by kendonB** [comment]
related issue https://github.com/davidgohel/flextable/issues/278

**Comment by davidgohel** [comment]
Not sure that I should try that, do you know modelsummary? It seems exactly what you are looking for

https://vincentarelbundock.github.io/modelsummary/
