### ISSUE TITLE
as_grouped_data with date-columns fails

### ISSUE THREAD

**Issue by namarkus** [davidgohel/flextable#438]
I really appreciate the possibility of presenting data grouped row by row in a table. Unfortunately, this does not work if date-formatted columns are present.

Here is a small reproducible example:

```
library(flextable)
library(dplyr)
df = tibble(id = c('1216', '1216', '1217', '1217'),
            beg = as.Date(c('1900-01-01', '2022-08-01', '1900-01-01', '2022-08-01')),
            end = as.Date(c('2022-07-31', '3000-01-01', '2022-07-31', '3000-01-01')),
            name = c('CA 125', 'CA 126', 'CA 15-3', 'CA 15-4'),
            score = c(25L, 14L, 101L, 78L)
            )
```

`df %>% as_grouped_data('id')`

fails with following error-message:

> Error in rbindlist(list_df, use.names = TRUE, fill = TRUE) : 
>   Class attribute on column 2 of item 2 does not match with column 2 of item 1.

A workaround would be to cast Date columns to character columns:

```
df %>% 
  mutate(across(c(beg, end), as.character)) %>% 
  as_grouped_data('id')

```
which works, but I'd prefer to define format of Dates at flextable-level using function colformat_date()

I suspect the problem is caused by a function from data.table:

> data.table::rbindlist

The function can combine boolean (NA) and numeric or integer values but fails to combine boolean (NA) and Date values.
Is it possible to improve this behavior in the flextable package?

Thanks!

**Comment by davidgohel** [comment]
Thanks for reporting this

**Comment by clementinejager** [comment]
Hi, 
It should be fixed now. 
Let us know if not.

**Comment by namarkus** [comment]
perfect, problem solved. Thanks for the quick fix!
