### ISSUE TITLE
Vertical column text alignment not maintained when printing to Powerpoint

### ISSUE THREAD

**Issue by smckearnan** [davidgohel/flextable#444]
Thanks for a fantastic package! I'm encountering an issue with vertical text alignment when printing my flextable to Powerpoint using `officer`. The alignment is as desired when viewing the table in R (the text is centered vertically in the column), but is not maintained when printing to Powerpoint (the text moves to the bottom of the cell). See example and screenshots of the table when viewed in R and Powerpoint below. I've included the flextable defaults I'm using in case those are a contributing factor. 

```{r}
library(flextable)
library(officer)

## Set table defaults
set_flextable_defaults(
  font.size = 8, font.family = "Calibri",
  font.color = "#333333",
  table.layout = "fixed",
  border.color = "black",
  padding.top = 3, padding.bottom = 3)
set_flextable_defaults(na_str = " ")

example_table <- data.frame(chr_col = "label",
  matrix(data = 1:16, nrow = 4))

ft <- flextable(example_table)

## Merge and rotate left column for character column
ft <- merge_v(ft, j = 1)
ft <- rotate(ft, j = 1, rotation = "btlr")
ft <- valign(ft, j = 1, valign = "center", part = "body")

ft
## column text appears appropriately centered

## Output to Powerpoint - column text is no longer centered
tst_pptx <- read_pptx("ppt_blank.pptx")

tst_pptx <- add_slide(tst_pptx, layout = "Title and Content")
tst_pptx <- ph_with(x = tst_pptx,
                    value = ft,
                    location = ph_location_label(ph_label="Content Placeholder 2")) 
print(tst_pptx, target = "test_flextable.pptx")
```
**Table viewed in R:**
<img width="317" alt="ft_Rviewer" src="https://user-images.githubusercontent.com/32182768/185715175-51cef63f-e2ca-41d4-8840-893a26662d26.png">

**Table viewed in Powerpoint:**
<img width="269" alt="ft_ppt" src="https://user-images.githubusercontent.com/32182768/185715182-38b03cfe-76d0-410b-85fc-181bf35ac5f6.png">

**Comment by davidgohel** [comment]
Hello 

I can't reproduce. I think this has been fixed in a recent version. Are you using the latest cran version?

See results (pptx/docx/html) on my environment with latest flextable version:

<img width="1626" alt="Capture d’écran 2022-08-23 à 12 08 06" src="https://user-images.githubusercontent.com/4331618/186132343-65e79a52-108e-487a-b2ae-5de39e9be5d0.png">

**Comment by smckearnan** [comment]
@davidgohel Thank you so much! I updated the version and the issue resolved (apologies for not checking this easy solution!).
