### ISSUE TITLE
Footer lost on pdf output

### ISSUE THREAD

**Issue by mps9506** [davidgohel/flextable#448]
Hi,

With the current dev version of flextable the footer is lost for `as_flextable.gam` objects when using pdf_output. html_output retains the expected footers. This works correctly on the current CRAN version of flextable, so not sure what caused the break. reprex below:

```r
---
title: "flextable_rmd"
output: 
  html_document:
    theme: united
  pdf_document:
    latex_engine: xelatex
    keep_tex: true
---

    ```{r}
    #| echo: false
    library(flextable)
    library(mgcv)
    set.seed(2)
    
    dat <- gamSim(1, n = 400, 
      dist = "normal", scale = 2, verbose = FALSE)
    b <- gam(y ~ s(x0) + s(x1) + s(x2) + s(x3), 
      data = dat)
    
    ft <- as_flextable(b)
    ft
    ```
```  

html output:
![image](https://user-images.githubusercontent.com/11282246/187444298-d017e856-8d6a-4fd0-9eb7-a51181f75952.png)


pdf output:
![image](https://user-images.githubusercontent.com/11282246/187444505-a47a9873-5998-4cd0-b110-74c99ea0295b.png)


I'm not very familiar with .tex but looking at the .tex output I don't see anything resembling the expected footer. I'll note again that it does work on the CRAN version. Session info is below:

```
> sessioninfo::session_info()
- Session info -------------------------------------------------------------------------------------------
 setting  value
 version  R version 4.2.1 (2022-06-23 ucrt)
 os       Windows 10 x64 (build 22000)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.utf8
 ctype    C
 tz       America/Chicago
 date     2022-08-30
 rstudio  2022.02.3+492 Prairie Trillium (desktop)
 pandoc   2.17.1.1 @ C:/Program Files/RStudio/bin/quarto/bin/ (via rmarkdown)

- Packages -----------------------------------------------------------------------------------------------
 package     * version   date (UTC) lib source
 base64enc     0.1-3     2015-07-28 [1] CRAN (R 4.2.0)
 cli           3.3.0     2022-04-25 [1] CRAN (R 4.2.1)
 curl          4.3.2     2021-06-23 [1] CRAN (R 4.2.1)
 data.table    1.14.2    2021-09-27 [1] CRAN (R 4.2.1)
 digest        0.6.29    2021-12-01 [1] CRAN (R 4.2.1)
 evaluate      0.16      2022-08-09 [1] CRAN (R 4.2.1)
 fastmap       1.1.0     2021-01-25 [1] CRAN (R 4.2.1)
 flextable   * 0.7.4.004 2022-08-29 [1] Github (davidgohel/flextable@fe59ce1)
 gdtools       0.2.4     2022-02-14 [1] CRAN (R 4.2.1)
 htmltools     0.5.3     2022-07-18 [1] CRAN (R 4.2.1)
 knitr         1.40      2022-08-24 [1] CRAN (R 4.2.1)
 lattice       0.20-45   2021-09-22 [1] CRAN (R 4.2.1)
 Matrix        1.4-1     2022-03-23 [1] CRAN (R 4.2.1)
 mgcv        * 1.8-40    2022-03-29 [1] CRAN (R 4.2.1)
 nlme        * 3.1-157   2022-03-25 [1] CRAN (R 4.2.1)
 officer       0.4.4.002 2022-08-29 [1] Github (davidgohel/officer@63add4c)
 R6            2.5.1     2021-08-19 [1] CRAN (R 4.2.1)
 Rcpp          1.0.9     2022-07-08 [1] CRAN (R 4.2.1)
 remotes       2.4.2     2021-11-30 [1] CRAN (R 4.2.1)
 rlang         1.0.4     2022-07-12 [1] CRAN (R 4.2.1)
 rmarkdown     2.16      2022-08-24 [1] CRAN (R 4.2.1)
 rstudioapi    0.14      2022-08-22 [1] CRAN (R 4.2.1)
 sessioninfo   1.2.2     2021-12-06 [1] CRAN (R 4.2.1)
 systemfonts   1.0.4     2022-02-11 [1] CRAN (R 4.2.1)
 uuid          1.1-0     2022-04-19 [1] CRAN (R 4.2.0)
 xfun          0.32      2022-08-10 [1] CRAN (R 4.2.1)
 xml2          1.3.3     2021-11-30 [1] CRAN (R 4.2.1)
 yaml          2.3.5     2022-02-21 [1] CRAN (R 4.2.1)
 zip           2.2.0     2021-05-31 [1] CRAN (R 4.2.1)

 [1] C:/Users/michael.schramm/AppData/Local/Programs/R/R-4.2.1/library

----------------------------------------------------------------------------------------------------------
```

**Comment by davidgohel** [comment]
thanks, it should be fixed now
