### ISSUE TITLE
[Question] Is there any plan to make it work on shiny/rmd

### ISSUE THREAD

**Issue by happyshows** [davidgohel/flextable#45]
This package looks really cool, I'm wondering if it could be migrated to the htmlwidget framework so that it can be used in rmd files and shiny as well.

Thanks.

**Comment by davidgohel** [comment]
This is already the case for rmarkdown (as written in the first  two lines of the documentation!)

https://davidgohel.github.io/flextable/index.html

And here: https://davidgohel.github.io/flextable/articles/overview.html#r-markdown-documents


If you read, you will see chunks of code containing what you need, something like that:

    ```
    ft <- regulartable(head(iris))
    ft
    ```

I made a short demo for shiny here: https://davidgohel.github.io/flextable/articles/examples.html#using-within-shiny-applications

I am closing that issue as it is a question.

PS: Next time, please respect the form I have made to collect issues (you probably deleted it without reading it) and make sure you read the documentation :)
