### ISSUE TITLE
First horizontal border missing in Word output

### ISSUE THREAD

**Issue by rempsyc** [davidgohel/flextable#450]
Following commit [7b82521f4c88628aef406ced001e1d2fa7f64a18](https://github.com/davidgohel/flextable/commit/7b82521f4c88628aef406ced001e1d2fa7f64a18), the first horizontal border is missing in Word output, in conjunction with `add_header_lines` and invisible borders. Moving the discussion here from #426.

``` r
library(flextable)
packageVersion("flextable")
#> [1] '0.7.4.8'
invisible.borders <- list("width" = 0, color = "black", style = "solid")
ft_1 <- flextable(head(mtcars)) |> 
  add_header_lines("title") |> 
  border(part = "header", i = 1, border = invisible.borders)
ft_1
```
![](https://i.imgur.com/mzBVYai.png)
``` r
print(ft_1, preview = "docx")
```
![](https://i.imgur.com/lBYzpxw.png)
<sup>Created on 2022-09-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by davidgohel** [comment]
This is because you are using function `border()`. It's documented:

> change borders of selected rows and columns of a flextable. This function is not to be used by end user (it requires careful settings to avoid overlapping borders) but only for programming purposes.

See #322


```
library(flextable)

invisible.borders <- fp_border_default("width" = 0)

ft_1 <- flextable(head(mtcars)) |> 
  add_header_lines("title") |> 
  hline_top(part = "header", border = invisible.borders)
ft_1
print(ft_1, preview = "docx")
print(ft_1, preview = "pptx")
print(ft_1, preview = "pdf")
```

<img width="1391" alt="Capture d’écran 2022-09-04 à 11 52 17" src="https://user-images.githubusercontent.com/4331618/188307779-ccd91720-5f3c-47b2-a482-1d9be05bfcff.png">

**Comment by davidgohel** [comment]
Here is how I would update your `nice_table` code here https://github.com/rempsyc/rempsyc/blob/main/R/nice_table.R#L593: 

```
    table <- table %>%
      add_header_lines(values = rev(title)) %>%
      align(part = "header", i = 1:length(title), align = "left") %>%
      flextable::hline(part = "header", i = seq_len(length(title)-1),
             border = invisible.borders) %>%
      flextable::hline(part = "header", i = length(title),
             border = flextable::fp_border_default()) %>%
      flextable::hline_top(border = invisible.borders, part = "header") %>%
      italic(part = "header", i = italic.lvl) %>%
      bold(., part = "header", i = 1, bold = bold.decision)
```

**Comment by davidgohel** [comment]
Closing the issue. Let me know if I need to re-open it

**Comment by rempsyc** [comment]
Thank you! Your workaround works perfectly! I have updated `nice_table` accordingly.
