### ISSUE TITLE
Caption and crossrefs not working in Quarto (Word output)

### ISSUE THREAD

**Issue by busemorose** [davidgohel/flextable#451]
Hello. First, thank you very much for your work. I've been using `flextable` for more than 1 year and it's awesome. I'm not sure where to post so feel free to delete the issue if not appropriate.

I'm trying to transition from Rmarkdown to Quarto and I'm struggling to have the `flextable` objects working as intended. The tables appear nicely but there is no label neither caption. I had a look at a recent thread about this problem and a potential solution but couldn't manage to make it work (https://github.com/quarto-dev/quarto-cli/issues/1556#issuecomment-1219184451). I (hopefully correctly) updated `flextable`, `quarto`, `office` and `officedown` to the last Github version available, as suggested.

**Reproducible example**
````
---
title: "Untitled"
format: docx
---

```{r include=FALSE}
library(officer)
library(officedown)
knitr::opts_chunk$set(echo = FALSE)
```


blah blah blah `r run_reference(id = "tbl-flextable")`.

```{r}
#| label: tbl-flextable
#| tbl-cap: Caption **strong**
flextable::flextable(mtcars[1:4, 1:4])
```
````

**My output (traduction: Error! Reference Source Not Found)**

![2022-09-04 20_55_18-dddfdfd docx  Lecture seule   Mode de compatibilité  - Word](https://user-images.githubusercontent.com/75677694/188329150-129ac845-0fb2-4fc5-9d74-938d98cb1c07.png)

**sessionInfo**
```
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                   LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] flextable_0.7.4.008  officer_0.4.4.005    officedown_0.2.5.001

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9        digest_0.6.29     R6_2.5.1          grid_4.1.0        evaluate_0.16    
 [6] zip_2.2.0         cachem_1.0.5      rlang_1.0.4       gdtools_0.2.4     cli_3.3.0        
[11] uuid_1.1-0        data.table_1.14.2 rstudioapi_0.13   xml2_1.3.3        rmarkdown_2.16   
[16] tools_4.1.0       yaml_2.3.5        xfun_0.32         fastmap_1.1.0     compiler_4.1.0   
[21] systemfonts_1.0.4 base64enc_0.1-3   rvg_0.2.5         memoise_2.0.1     htmltools_0.5.3  
[26] knitr_1.40      
```

**quarto check install**
```
$ quarto check install

[>] Checking Quarto installation......OK
      Version: 1.2.57
      Path: C:\Users\hsm\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK
```

**quarto check knitr**
```
$ quarto check knitr

[>] Checking R installation...........OK
      Version: 4.1.0
      Path: C:/PROGRA~1/R/R-41~1.0
      LibPaths:
        - C:/Users/hsm/Documents/R/win-library/4.1
        - C:/Program Files/R/R-4.1.0/library
      rmarkdown: 2.16

[>] Checking Knitr engine render......OK
```

**Comment by davidgohel** [comment]
hello, 

Yes, we removed quarto/docx captions from the dev version temporary. 

We are working on it. We will put them back soon, this week probably. :)

**Comment by busemorose** [comment]
Nice to hear! Thank you.

**Comment by davidgohel** [comment]
Hello, 

It should be ok now. Note it's recommended to define the caption with `set_caption` if you want formatted caption!

``````
---
title: "Untitled"
format: docx
---

```{r include=FALSE}
library(flextable)
library(officer)
knitr::opts_chunk$set(echo = FALSE)
```


blah blah blah `r run_reference(id = "tbl-flextable")`.

```{r}
#| label: tbl-flextable
#| tbl-cap: Caption **strong**
flextable(mtcars[1:4, 1:4]) |>
  set_caption(
    caption = as_paragraph(
      "Caption ",
      as_chunk("strong", props = fp_text_default(bold = TRUE))
    )
  )
```

``````



<img width="1104" alt="Capture d’écran 2022-09-06 à 14 43 18" src="https://user-images.githubusercontent.com/4331618/188638138-9177b72d-5a46-444d-80bc-220d7f801ced.png">

**Comment by davidgohel** [comment]
I am closing the issue, let me know if I should reopen if.

**Comment by busemorose** [comment]
Thank you very much. It works perfectly!
