### ISSUE TITLE
Autofit body only not working

### ISSUE THREAD

**Issue by Maschette** [davidgohel/flextable#453]
Hello, 
I have been trying to use the autofit part="body" option and as far as I can tell it is not working as it should 

``` r
library(flextable)
dat <- data.frame("text" = rep("words far apart",4), num=1:4)
names(dat) <- c("Really long annoying text", "oh look some numbers")
tab <- flextable(dat)
tab
```
![image](https://user-images.githubusercontent.com/14663215/189018916-51129995-076c-4e6f-99bf-0026e22f6715.png)
``` r
#auto fit
tab1 <- autofit(tab)
tab1
```
![image](https://user-images.githubusercontent.com/14663215/189018960-5f957952-82b6-4405-a77d-9ceeb594fca9.png)
``` r
#actually I just want the body to auto fit and not the header
tab2 <- autofit(tab, part = "body")
tab2
```
![image](https://user-images.githubusercontent.com/14663215/189018903-bdbf1e3b-1725-42fe-8e1e-820ff52cc823.png)

sessionInfo()
#> R version 4.2.1 (2022-06-23 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19044)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_Australia.utf8  LC_CTYPE=English_Australia.utf8   
#> [3] LC_MONETARY=English_Australia.utf8 LC_NUMERIC=C                      
#> [5] LC_TIME=English_Australia.utf8    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] flextable_0.7.3
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.9        rstudioapi_0.14   xml2_1.3.3        knitr_1.40       
#>  [5] magrittr_2.0.3    uuid_1.1-0        R6_2.5.1          rlang_1.0.4      
#>  [9] fastmap_1.1.0     stringr_1.4.1     highr_0.9         tools_4.2.1      
#> [13] data.table_1.14.2 xfun_0.32         cli_3.3.0         withr_2.5.0      
#> [17] htmltools_0.5.3   systemfonts_1.0.4 yaml_2.3.5        digest_0.6.29    
#> [21] lifecycle_1.0.1   zip_2.2.0         officer_0.4.3     base64enc_0.1-3  
#> [25] fs_1.5.2          glue_1.6.2        evaluate_0.16     rmarkdown_2.16   
#> [29] reprex_2.0.2      stringi_1.7.8     compiler_4.2.1    gdtools_0.2.4
```

<sup>Created on 2022-09-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Maschette** [comment]
I will note that if I switch to knitting to a pdf this does work as it should.

**Comment by davidgohel** [comment]
Thanks it should be fixed now
