### ISSUE TITLE
Freeze the first row and the first column in HTML flextable

### ISSUE THREAD

**Issue by FloBlue** [davidgohel/flextable#461]
Hello
Is there a way to freeze the first row and ideally the first column of a large table in Rmarkdown to HTML?
This option exists in Kableextra for the first row.
That would be really great!

Thanks a lot for any help
```
  library(dplyr)
 library(kableExtra)
  library(flextable); library(knitr)

why <- c(1:20)
wont <- c(1:20)
these <- c(1:20)
headers <- c(1:20)
stay <- c(1:20)
fixed <- c(1:20)

table_data <- data.frame(why, wont, these, headers, stay, fixed)

         table_data %>% 
         kable( format = "html") %>% 
         kable_styling(position = "center", full_width = F, bootstrap_options = c("striped","hover"))%>%        
         scroll_box( width = "1000px", height = "200px", fixed_thead = T)
 
  knit_print(flextable(table_data))   
```

**Comment by davidgohel** [comment]
It is now implemented in the dev version.

To activate this option, use `set_table_properties(opts_html = list(scroll=list(...)))`. See argument `opts_html` in the manual.


`````
---
output: html_document
title: example
---

```{r}
library(flextable)
library(knitr)
library(magrittr)

dat <- lapply(1:30, function(x) rnorm(n = 50)) |> 
  setNames(paste0("colname", 1:30)) |> 
  as.data.frame()

# flextable(dat) |> colformat_double(digits = 2) |>
#   set_table_properties(opts_html = list(scroll=list()))

flextable(dat) |> colformat_double(digits = 2) |>
  bg(bg = "white", part = "header") |> 
  set_table_properties(opts_html = list(scroll=list(height = 300)))
```


`````

<img width="1073" alt="Capture d’écran 2022-10-17 à 18 21 48" src="https://user-images.githubusercontent.com/4331618/196230568-0e228494-3609-40f9-b2f5-8c57618f53ec.png">

**Comment by FloBlue** [comment]
Thanks a lot for this great enhancement! How can I freeze the first column (in addition of the freezing of the 1st row) using the add_css ?

**Comment by davidgohel** [comment]
@FloBlue excellent, I did not succeed freezing the 1st column, happy to get your solution!

Here is how to add it to `add_css`:

```r
library(flextable)
dat <- lapply(1:30, function(x) rnorm(n = 50)) |> 
  setNames(paste0("colname", 1:30)) |> 
  as.data.frame()

ft_1 <- flextable(dat)
ft_1 <- set_table_properties(ft_1, 
                             opts_html = list(
                               extra_css = ".tabwid tbody tr > :first-child {position: sticky;z-index: 1;left: 0;background: #ddd;}",
                               scroll = list(height="500px")))
ft_1
```

Then I can add an element to `opts_html`, something like `scroll = list(height="500px", freeze_first = 2)` and we would be able to freeze the first 1/2/3/... columns. 

I think it would be better for users to have this option instead of using `extra_css`, what's your opinion about that?

**Comment by davidgohel** [comment]
Sorry I could not make it work for more than the first column, it would require knowing the exact column width in HTML...
