### ISSUE TITLE
The caption cannot be

### ISSUE THREAD

**Issue by JTCDCTWB** [davidgohel/flextable#462]
First of all, thank you for your work. I love 'flextable'.
After upgrading flextable from 0.7.3 to 0.8.0, in RMarkdown, generated with officedown::rdocx_document()，it is unable to display when using set_caption() to generate caption.

---
date: "`r Sys.Date()`"
author: "Your Name"
title: "officedown template"
output: 
  officedown::rdocx_document:
    mapstyles:
      Normal: ['First Paragraph']
---

```{r setup, include=FALSE}
library(officedown)
library(tidyverse)
library(officer)
library(flextable)

```

```{r echo=FALSE}
head(mtcars) %>% 
  flextable() %>% 
  set_caption(caption = "mtcars caption")
```

**Comment by davidgohel** [comment]
thanks, it should be fixed now and soon on cran
