### ISSUE TITLE
word_stylename settings in set_caption() not working

### ISSUE THREAD

**Issue by mpmarcaida** [davidgohel/flextable#467]
I am trying to create a Word document in RMarkdown with all of my tables made to look better using the `flextable` package. I recently updated to the latest version of flextable (0.8) and this issue on table captions came up. I have a word template file where I created a new Style format for my table captions. The alignment was set to "justify" but my outputs (for table captions) came out all "centered". I would check the Word output that it was in fact set to the the Style I specified on `word_stylename` but did not follow the actual settings (i.e. "justify" alignment). 

If it would help, here's my code for setting the caption:

```
flextable(my_df) %>%  
  set_caption("My Caption", word_stylename = "my_preferred_caption_settings", autonum = FALSE) %>%
  #and for the rest of the table
  bold(bold = FALSE, part = "header") %>% 
  align(j = 1, align = "left", part = "all") %>%
  align(j = c(2:6), align = "center", part = "all") %>%
  padding(padding = 1.5, part = "all") %>%
  padding(padding.right = 5, padding.left = 5, part = "all")
```

My `knitr` specifications are also as follows: `{r, tab.cap.tnd="", tab.cap.pre="", tab.cap.sep="", results='asis', echo = FALSE, message = FALSE, warning=FALSE}`.

Thanks in advance for addressing my concern.

**Comment by davidgohel** [comment]
Now you need to add an argument `fp_p` when calling `flextable::set_caption(fp_p = fp_par(text.align = "justify"))`

See https://github.com/davidgohel/flextable/issues/425#issuecomment-1191739480 for history

**Comment by mpmarcaida** [comment]
Got it, thanks! The link you sent was helpful. What solved my issue, aside from the `fp_p` argument, was setting `align_with_table = FALSE`!
