### ISSUE TITLE
Repeat header

### ISSUE THREAD

**Issue by cvaldezerea** [davidgohel/flextable#469]
Please allow to repeat headers. It's really needed in the comunity.

Thank you.

When submitting a feature request, please explain the value, describe the situation and be reasonable.

**Not a bug or feature request? If you are looking for help on how to use the 
package correctly, please read the doc first at https://davidgohel.github.io/flextable/. 
You can also visit [Stackoverflow](https://stackoverflow.com/questions/tagged/flextable+r) 
and tag your question with `[flextable]`. We usually read them and answer WHEN possible.**

**Comment by cvaldezerea** [comment]
Here is a small example of a use case 
![image](https://user-images.githubusercontent.com/46382263/192827886-d083edf5-a310-4ff7-ae6f-9375bd1e658f.png)

**Comment by cvaldezerea** [comment]
No needed to resolve. Someone else already did it for you.

Check this our: https://ftextra.atusy.net/

**Comment by davidgohel** [comment]
I still don't understand what it is about but glad you found a solution
