### ISSUE TITLE
Several footers are put in reverse order

### ISSUE THREAD

**Issue by roamdam** [davidgohel/flextable#47]
When adding a footer to a regular table, then another footer, the second one is placed above the first one, which is kind of confusing. I suppose it's because footers are added from the bottom of the body.. wouldn't it be more consistent to have the footers appear in the order they are piped in the code ?

In the below provided example I would like to have 'this a reading instruction' as a second footer, but it appears first.

```
require(flextable)
require(magrittr)
d <- data.frame(label = letters[1:5], x = floor(runif(5, 1, 100)), y = floor(runif(5, 1, 100)))

flext <- d %>% 
  regulartable() %>% 
  add_footer(label = 'This is my tab footnote.') %>% 
  add_footer(label = 'This a reading instruction.') %>% 
  merge_at(i = 2, part = 'footer')
flext
```

**Comment by davidgohel** [comment]
Hi, 

Use argument `top=FALSE`: https://davidgohel.github.io/flextable/reference/add_header.html#arguments

David

**Comment by davidgohel** [comment]
Can you close the issue?

**Comment by roamdam** [comment]
Indeed, a closer look at the documentation would have given the answer... Stupid me. Thanks.

**Comment by davidgohel** [comment]
:)

PR to improve documentation are welcome ;)
