### ISSUE TITLE
Flextable Selectors: Making a function for the i and j arguments

### ISSUE THREAD

**Issue by phargarten2** [davidgohel/flextable#477]
When submitting a feature request, please explain the value, describe the situation and be reasonable.

**Not a bug or feature request? If you are looking for help on how to use the 
package correctly, please read the doc first at https://davidgohel.github.io/flextable/. 
You can also visit [Stackoverflow](https://stackoverflow.com/questions/tagged/flextable+r) 
and tag your question with `[flextable]`. We usually read them and answer WHEN possible.**  

After reading the [documentation] (https://ardata-fr.github.io/flextable-book/design.html#selectors), I wanted to attempt to do more advanced selecting. 

One is to make a function from the selection process. The question and answer here are satisfactory: 
(https://stackoverflow.com/questions/74212389/flextable-selectors-making-a-function-for-the-i-and-j-arguments)
Is using `i = ~ `  or `j = ~ ` a convenient way of creating expressions, so using [documentation from Advanced R](https://adv-r.hadley.nz/expressions.html) is appropriate? 

Another is finding rows that separate a merged column, like `cut` below. I may want to adjust borders around the merged `cut` for all rows. Obviously, I can count the rows and know where the divisions are, but often the data change and are not constant.

```{r}
library(flextable)
library("dplyr")
library(magrittr)
dat <- ggplot2::diamonds %>% group_by(cut) %>% slice_head(n = 3)
ft <- dat %>%
  qflextable() %>%
  merge_v(j = "cut")
ft
```

<img width="1038" alt="Screen Shot 2022-10-26 at 15 18 41" src="https://user-images.githubusercontent.com/17706062/198117045-79b3b757-4cab-4505-b5a4-d260dd7ed208.png">

To add a border where merging occurred, it could be something like `r ft %>% border(i = ~ j %in% "cut")`. Does this idea capture the spirit of what you were envisioning with the `~` notation?

Lastly, would you consider exporting the internal function `get_rowid()`? It may allow users to find row numbers under certain conditions that can be entered in `border()`, `color()`, `bold()`, etc. 

Thanks

**Comment by davidgohel** [comment]
Hello

- yes, the answer given in SO are correct.

> using [documentation from Advanced R](https://adv-r.hadley.nz/expressions.html) is appropriate?

I think so. I am not sure that I understand your question. Use one of the 2 answers you had, either a formula, either a solution with rlang.

> To add a border where merging occurred, it could be something like [...]

yes

> would you consider exporting the internal function get_rowid()?

No a big fan of exporting and documenting this function. Why couldn't you use your data.frame to do specific calculations if you don't want to use formulas in `i`?

**Comment by davidgohel** [comment]
OK closing as no answer to the question

Formatting functions support all argument `j`

**Comment by phargarten2** [comment]
Thank you, and sorry for the slow response.

1. 
> > using [documentation from Advanced R](https://adv-r.hadley.nz/expressions.html) is appropriate?

> I think so. I am not sure that I understand your question. Use one of the 2 answers you had, either a formula, either a solution with rlang.

With respect to the SO answers, what is the mechanism that makes this work?  In other words, does **flextable** use the expressions from **rlang** in a useful and convenient formula fashion so that the bang bang syntax (`!!`) would apply?

2.
> > To add a border where merging occurred, it could be something like r ft %>% border(i = ~ j %in% "cut"). Does this idea capture the spirit of what you were envisioning with the ~ notation?

> Yes

But this idea doesn't work. What I would like to do is to find the row indices of the merged samples and apply a border to them.

```{r}
ft %>% border(i = ~ j %in% "cut")
# Error in j %in% "cut" : object 'j' not found
```

3. I was looking into this function `get_rowid()`. All this work was attempting to fix the formatting after merging the cells, which was described clearly in the vignette.

Thanks.

**Comment by davidgohel** [comment]
1. The rlang package is used to evaluate expression within `as_paragraph()`, `append_chunks()` and `prepend_chunks()`. Not `get_rowid()` (from memory, that's only because the implementation is old!). I don't think it makes a difference, both answers in SO are totally correct.
2. you can use dplyr::lead to compare a row with the next one and place the horizontal border:

````
library(flextable)
library("dplyr")
library(magrittr)
dat <- ggplot2::diamonds %>% group_by(cut) %>% slice_head(n = 3)
ft <- dat %>%
  qflextable() %>%
  merge_v(j = "cut") %>% 
  hline(i = ~ cut != lead(cut), border = fp_border_default(width = 1)) %>% 
  fix_border_issues()
ft

````
<img width="585" alt="Capture d’écran 2022-11-14 à 23 25 51" src="https://user-images.githubusercontent.com/4331618/201781014-d5b21bc9-fd10-4558-8c14-959b8d228a04.png">

**Comment by phargarten2** [comment]
Thank you. I wasn't familiar with `dplyr::lead()`, and this is the exact one I need. I'll add it to my toolkit. I also appreciate knowing some reasons why things work the way they do.
