### ISSUE TITLE
Very large md file with ~500 flextable tables not rendering Word doc with pandoc

### ISSUE THREAD

**Issue by leeroyaus** [davidgohel/flextable#478]
I am creating a very large md file that is produced after knitting an Rmd file with officedown and approx. 500 flextable tables.

After knitting the Rmd file the md file size is 33MB. Once the md file is then parsed to pandoc it does not render (pandoc freezes and nothing happens).

Are there are ways to reduce the size of flextable tables in Word, or is it possible to reduce the size of the md file before it is parsed to pandoc?

I'm happy to provide a reprex but wasn't sure if that was needed.

Thank you

**Comment by davidgohel** [comment]
Sorry

I am not aware of any way to reduce the size of flextable tables in Word, or to reduce the size of the md file before it is parsed to pandoc.

**Comment by davidgohel** [comment]
Closing the issue. It is probably an issue with officedown and the fact it read the XML file in memory. Maybe `block_pour_docx()` could help

**Comment by leeroyaus** [comment]
Thanks @davidgohel  I'll try using `block_pour_docx()` :)

**Comment by leeroyaus** [comment]
Hi @davidgohel thanks again for the advice, using `block_pour_docx()` has fixed the issue. I have a small example below as well:

````
---
title: "Untitled"
format: docx
---

```{r include=FALSE}
library(officer)
library(officedown)
knitr::opts_chunk$set(echo = FALSE)
```

```{r Produce sections, results='asis', include=FALSE}
sections <- 1:100
dir.create("./docs")
for(i in sections){
  render(
    "child.Rmd",
    output_file = file.path("./docs",paste0("section",i,".docx"))
  )
}
```

```{r Pour docs, results='asis'}
secDocs <- list.files("./docs","^section.*\\.docx$",full.names = T) %>% sort()
for(i in secDocs){
  knit_print_block(
    block_pour_docx(i)
  )
}
```
````
