### ISSUE TITLE
Top border error

### ISSUE THREAD

**Issue by derwoman** [davidgohel/flextable#479]
In using the border functions within flextable (i.e. flextable::border, flextable::hline_top, etc) top borders of cells identified are not being updated correctly. This is the case for all functions that manipulate top borders. 

The following lines of code are used to first, get rid of inner horizontal borders with hline (by setting their color to transparent), and then update the borders in the column 'arrow_priority_1' where the values equal 1 or 5. I specifically set border.bottom and border.top to be fp_border(color = 'black').

` megatable <- megatable %>%
      flextable::hline(j = match(megatable$col_keys, x = "arrow_priority_1"), border = fp_border(color = '#ffffff00'), part = "body") %>%
      flextable::border(i = ~ arrow_priority_1 ==1,j = match(megatable$col_keys, x = "arrow_priority_1"),part = "body", 
                        border.top = fp_border(color = 'black'), border.bottom = fp_border(color = 'black')) %>%
      flextable::border(i = ~ arrow_priority_1 ==5,j = match(megatable$col_keys, x = "arrow_priority_1"),part = "body", 
                        border.top = fp_border(color = 'black'), border.bottom = fp_border(color = 'black'))`

No errors are thrown, so it is hard to know why this issue is occuring, but the result of this is that the cells in this column with values of 1 or 5 have bottom rows properly updated, but not top rows. I have played around with the border functions in the flextable package and am seeing this issue across the board, consistently not seeing top borders be udpated.

**Comment by davidgohel** [comment]
We can not reproduce your issue as you did not provide a reproducible example. 

`border()` documentation says 

> This function is not to be used by end user (it requires careful settings to avoid overlapping borders) but only for programming purposes.

Maybe you should instead use the recommended functions?

**Comment by davidgohel** [comment]
Here is a solution: 

```r
library(dplyr)
library(flextable)

fp_bdr <- fp_border_default(color = "red", width = 2)
zz <- head(cars) %>% 
  as_tibble() %>% 
  mutate(arrow_priority_1 = seq_len(6)) %>% 
  relocate(arrow_priority_1) %>% 
  flextable() %>%
  border_remove() %>% 
  surround(
    i = ~ arrow_priority_1 %in% c(1, 5),
    j = "arrow_priority_1",
    border.top = fp_bdr,
    border.bottom = fp_bdr
  ) %>% 
  autofit()

```

```r
print(zz, preview = "docx")
print(zz, preview = "pptx")
print(zz, preview = "html")
print(zz, preview = "pdf")
```

<img width="1592" alt="Capture d’écran 2022-11-01 à 14 14 33" src="https://user-images.githubusercontent.com/4331618/199241670-5b7d6c9b-f5cf-43bc-8fe3-b983745bfdd8.png">
