### ISSUE TITLE
Missing "property" argument when reproducing fp_border example

### ISSUE THREAD

**Issue by ThomasHoussoy** [davidgohel/flextable#483]
Hello,

I'm in the process of deepening my understanding of the workings of the `flextable` package, using the manual.
I reproduced the example in section 5.2 (Formatting functions).

The reproductible code :
```
library(flextable)
library(officer)

dat <- data.frame(wool = c("A", "B"),
                   L = c(44.56, 28.22),
                   M = c(24, 28.77),
                   H = c(24.56, 18.78))

#Using the fp_border_default() function
flextable(dat04) %>%
  style(i = 1,
        pr_c = fp_border_default(color = "red",
                         style = "dotted",
                         width = 1))

#Using the officer::fp_border() function
flextable(dat04) %>%
  style(i = 1,
        pr_c = officer::fp_border(color = "red",
                         style = "dotted",
                         width = 1))
```

Unfortunately, whether I use `fp_border_default()` or `officer::fp_border()`, I obtain the same error message :
```
Erreur dans property %in% names(x) : 
l'argument "property" est manquant, avec aucune valeur par défaut
```

I tried to "debug" it by assuming the `x` is the flextable object, which contains a `properties` element, and changing its name by `property` but it didn't sole the problem in anyway (same error message).
I haven't found any similar issues being post before (whether opened or closed).

**Comment by davidgohel** [comment]
hello, the examples are using `fp_cell`, not `fp_border` with argument `pr_c`. 

The name `pr_c` stands for "properties of cell".
