### ISSUE TITLE
save_as_docx failed in R 4.1.2, ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by living1069** [davidgohel/flextable#486]
R>flextable(mtcars) %>%
  theme_vanilla() %>%
  save_as_docx(path = "mytable.docx")

Error in prop_table(style = NULL, layout = table_layout(type = "fixed"),  :
  unused arguments (word_title = x$properties$word_title, word_description = x$properties$word_description)

I have tried in R --vanilla with no luck. 

Any suggestion? Thanks!

**Comment by davidgohel** [comment]
Yes sure. I would suggest to follow the guidelines you deleted when you opened the issue:


------

- [ ] Provide the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example. 

I can't see the result of `sessionInfo()` as requested. Is that on purpose? 

- [ ] Make sure you did check you had the latest version of the package on CRAN.

Did you make sure you had the latest version? Can you confirm that?

- [ ] Make sure you searched in the *open* and *closed* issues on the github repository.

For example, are you sure this recent issue is not the same than yours? https://github.com/davidgohel/flextable/issues/484
