### ISSUE TITLE
add_footer does not seem to work

### ISSUE THREAD

**Issue by mattantaliss** [davidgohel/flextable#49]
I'm attempting to add a footer to a flextable (version 0.4.2; R 3.4.3), but it is not displaying. It does, however, look like the desired content is in the footer part of the table object.

I have even tried using the example code at https://davidgohel.github.io/flextable/reference/add_header.html:
```r
ft <- flextable( head( iris ),
  col_keys = c("Species", "Sepal.Length", "Petal.Length", "Sepal.Width", "Petal.Width") )
ft <- add_header(x = ft, Sepal.Length = "length",
  Sepal.Width = "width", Petal.Length = "length",
  Petal.Width = "width", Species = "Species", top = FALSE )
ft <- add_header(ft, Sepal.Length = "Inches",
  Sepal.Width = "Inches", Petal.Length = "Inches",
  Petal.Width = "Inches", Species = "Species", top = TRUE )
ft <- merge_h(ft, part = "header")
ft <- add_footer(ft, Species = "This is a footnote" )
ft <- merge_at(ft, j = 1:5, part = "footer")
ft
```

The result of running that code, for me, is the attached image:
![ft](https://user-images.githubusercontent.com/7633746/35879763-37e1dbb4-0b39-11e8-97d0-21277f686425.png)

**Comment by davidgohel** [comment]
Thanks, that's an awful bug. Will fix that this week if not this evening

**Comment by davidgohel** [comment]
It works with `regulartable()` but not `flextable()`

**Comment by davidgohel** [comment]
BTW, why are you using `flextable` and not `regulartable`?

**Comment by davidgohel** [comment]
Should be ok now.

**Comment by mattantaliss** [comment]
To reply to your last couple comments:
1. My use of flextable is most likely out of habit from the ReporteRs days (before officer and flextable as a separate package). I also haven't seen much information about regulartable, so I don't even know what the differences are.
2. Thanks for the quick fix!

**Comment by davidgohel** [comment]
OK

1. I wrote a explanation there: 
https://davidgohel.github.io/flextable/articles/overview.html#introduction

(I was wondering if that was clear... so your feedback is welcome)

2. your are welcome

**Comment by mattantaliss** [comment]
1. That explanation does help, and on a first read-through, it does seem clear. Since I first started using flextable a while ago, if I want to figure out how to do something with it, I'll jump straight to either the [documentation on CRAN](https://cran.r-project.org/web/packages/flextable/flextable.pdf) or the [function reference page](https://davidgohel.github.io/flextable/reference/index.html). It's good to know I should also pay attention to the other pages. Thanks!

**Comment by davidgohel** [comment]
OK, I will add notes in this documents then :) 

Thank you

**Comment by mattantaliss** [comment]
It looks like `body_add_flextable()` is stripping out the footer (with both `flextable()` and `regulartable()`)

**Comment by davidgohel** [comment]
Yes, I noticed that yesterday. I think I made a mistake with git, I am sure it did work (it works with HTML but not with docx/pptx)

**Comment by davidgohel** [comment]
Solved since yesterday :)

**Comment by mattantaliss** [comment]
Confirmed on my end. Thank you for the fix!
