### ISSUE TITLE
Size manipulation

### ISSUE THREAD

**Issue by instantkaffee** [davidgohel/flextable#5]
Is there a mechanism for global (whole table) and/or local text size manipulation via R parameters (rather than css)?

Something like scale or so for global and formula for local ?

**Comment by davidgohel** [comment]
there is function `fontsize`

**Comment by instantkaffee** [comment]
Thx, now I found it in the source. I did not see it your otherwise very comprehensive, excellent documentation.

**Comment by davidgohel** [comment]
thx, I forgot to update the doc...

**Comment by instantkaffee** [comment]
Thank you, for the excellent package.
