### ISSUE TITLE
Flextable does not render a long table properly in pdf in Quarto

### ISSUE THREAD

**Issue by cschwarz-stat-sfu-ca** [davidgohel/flextable#500]
According to the documentation, flextable() is suppose to use the longtable option when generating LaTeX -> PDF. However, the table doesn't seem to break over page boundaries properly when run in Quarto.

MWE. PDF generated attached.

Thanks - great package -- I use it often!

Carl Schwarz

`````
---
title: "Longtable problem with flextable in quarto"
author: "Carl SChwarz"
date: today
date-format: "YYYY-MM-DD"
execute: 
  error: true
format: 
  html:
    toc: true
    number-sections: false
    self-contained: true
  pdf:
    toc: true
    number-sections: false
  docx:
    toc: true
    number-sections: false

---

# Problem with longtables in flextable() with quarto when rendering to pdf.

Here is an example of a long table that doesn't render properly in pdf in quarto when using flextable.

```{r}
library(flextable)

mytable <- data.frame(text=1:100)

ft <-flextable(mytable)
ft

```
`````

[flextable-problem.pdf](https://github.com/davidgohel/flextable/files/10453263/flextable-problem.pdf)
[flextable-problem.pdf](https://github.com/davidgohel/flextable/files/10453266/flextable-problem.pdf)

```{r}

sessionInfo()

```

**Comment by davidgohel** [comment]
thanks, it should be fixed now

**Comment by cschwarz-stat-sfu-ca** [comment]
Thanks... works like a charm now... Carl
