### ISSUE TITLE
More css styling options

### ISSUE THREAD

**Issue by martinzuba** [davidgohel/flextable#51]
Hi David,

I really like your package(s) as they are very useful for automation of generation of Word tables. 

If I understand correctly, `flextable` produces XML tables that are stored in .docx files using `officer`. The style options allow for customisation of table head and body cells. They seem to do so via setting CSS elements of the table. 

My questions are:
• Is there a specific reason why the elements that can be edited are limited to the ones used in fp_par, fp_text and fp_cell? For example, if I wanted to set `line-height = 10 px` (as padding = 0 is not dense enough), would that require a different mechanic in transforming the flextable to an object that can be inserted in Word?
• Is there a way to apply Word styles to the table body or table head, similarly to what can be done in `body_add_par()` with the style parameter? (I know this can be done with "ordinary" tables but it would be cool to do it row-wise with flextables).

**Comment by davidgohel** [comment]
Hi 

Thanks

> They seem to do so via setting CSS elements of the table.

Not really. Each format has corresponding methods.

> My questions are:

1. I don't understand the question and padding is an option.
2. Not in my packages but you can code your function base on existing code.

If you could come with a reproducible example (as explained in the template...) where I could see your issue it would help
