### ISSUE TITLE
Support revealjs format 

### ISSUE THREAD

**Issue by cderv** [davidgohel/flextable#511]
## R Markdown 

````markdown
---
output: revealjs::revealjs_presentation
---

## Test

```{r, echo = FALSE}
library(flextable)
ft <- flextable(airquality[ sample.int(10),])
ft <- add_header_row(ft,
  colwidths = c(4, 2),
  values = c("Air quality", "Time")
)
ft <- theme_vanilla(ft)
ft <- add_footer_lines(ft, "Daily air quality measurements in New York, May to September 1973.")
ft <- color(ft, part = "footer", color = "#666666")
ft <- set_caption(ft, caption = "New York Air Quality Measurements")
ft
```
````

## Quarto 

````markdown
---
format: revealjs
keep-md: true
---

## Test

```{r}
library(flextable)
ft <- flextable(airquality[ sample.int(10),])
ft <- add_header_row(ft,
  colwidths = c(4, 2),
  values = c("Air quality", "Time")
)
ft <- theme_vanilla(ft)
ft <- add_footer_lines(ft, "Daily air quality measurements in New York, May to September 1973.")
ft <- color(ft, part = "footer", color = "#666666")
ft <- set_caption(ft, caption = "New York Air Quality Measurements")
ft
```
````

In both cases, no output is show in slides. 

## Why 

`knit_print.flextable()` uses `flextable_to_md()` which does not support `revealjs` pandoc format explicitely. So the default output will be used (last `else`) 
https://github.com/davidgohel/flextable/blob/2a0310e9dcc4747faac4d1b9d8634bc4b4d521cf/R/printers.R#L224-L243

It is using a screenshot, included using `\includegraphics` LaTeX command. This will only works in LaTeX document. 

More explicitly example: the above examples will show this in the markdown file after knitting as `asis` output for the chunk
````
\includegraphics[width=4.50in,height=3.25in,keepaspectratio]{test2_files/figure-revealjs/unnamed-chunk-1-1.png}
````

This will get picked up as LaTeX by Pandoc, and ignore in non LaTeX output. 

Probably several improvement to make here: 

* Support `revealjs` pandoc format, by simply adding the format name here
https://github.com/davidgohel/flextable/blob/2a0310e9dcc4747faac4d1b9d8634bc4b4d521cf/R/printers.R#L195-L201

* Change the default output to maybe rely on `knitr::include_graphics()` to include an image in a cross format way ? 

Regarding Quarto support, maybe there is other adjustement (`bookdown` and `pandoc2` args used in `flextable_to_rmd()` are probably not needed with Quarto and may interfere). Anyway, if it happens this is other issue. 

Hope it helps

**Comment by cderv** [comment]
What do you mean exactly ? 

`knitr::include_graphics()` return already an object of class `knit_asis` so no need to `results='asis'` in the chunk. The result will already be processed like that by **knitr**. 

Do you have a specific issue in mind ?

**Comment by davidgohel** [comment]
the purpose of `flextable_to_rmd()` is to let people do for loops in R-Markdown, it will work because `results='asis'`. The instruction `includegraphics` was there to let PDF show an image (I remember doing that before latex was an option in flextable) and it was processed and rendered correctly.

If I `cat()` the result of include_graphics, 

```
> cat(knitr::include_graphics("~/Downloads/021500026493036.png"))
```

I get:

```
/Users/davidgohel/Downloads/021500026493036.png
```

If I used `include_graphics` with `results='asis'`, it won't be rendered, is there something else to do when using `results='asis'`?

**Comment by cderv** [comment]
Oh yes if you `cat` such output it will prevent any **knitr** specific handling with `knit_print()` - See more about custom printing in case you don't know well https://cran.r-project.org/web/packages/knitr/vignettes/knit_print.html  

> the purpose of flextable_to_rmd() is to let people do for loops in R-Markdown, it will work because results='asis'.

Does this mean that this function should always return a asis output for **knitr** ? Because in that case you have the `knitr::asis_output` function to indicate **knitr** to treat you output like with `results = "asis"` when knitting. [Example in Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/opts-render.html)

For loops in Rmd with knitting are always tricky. I advice to use `knit_child()` and even template for that, but I understand the need. 
(See an [example ](https://examples.quarto.pub/create-tabsets-panel-from-r-code/) of this with **gt** for Quarto document but applies to Rmd too) 

Do you have a test document you're working with so that I can try see how this all works ? Maybe I am missing something.

**Comment by davidgohel** [comment]
Thank you for the precise instructions!

> Does this mean that this function should always return a asis [...]

Yes and no, when used in `knit_print.flextable()` it is being processed with `asis_output()` https://github.com/davidgohel/flextable/blob/master/R/printers.R#L750

> I advice to use knit_child()

Thanks again for the clear indication and the example. OK, I may need to think about this. There are things to test here...
There are some 'knitr' functions I've discovered lately that I'd like to use (the `meta` argument of `asis_output()` for example).

**Comment by cderv** [comment]
> knit_print.flextable() it is being processed with asis_output() [master/R/printers.R#L750](https://github.com/davidgohel/flextable/blob/master/R/printers.R?rgh-link-date=2023-02-13T21%3A39%3A59Z#L750)

Oh I see. you probably don't need the last call to `knit_print()` and just return a `asis_output()` object. 
I think I would do the `include_graphics()` in there.  What is the non-knitr usage of `flextable_to_rmd()` ?

**Comment by davidgohel** [comment]
Yes, I understand it's time for a cleaning :) I just started and that's not a big deal for now. I agree with your points. 

Somehow related to the cleaning... Has there been a change that would make it possible the processing of the table captions `(\#tab:id)` by 'bookdown' when working with raw HTML (and eventually other formats). For now, the row HTML is split with a simple markdown section where the caption is written; as it is in Markdown, 'bookdown' can process it.

**Comment by cderv** [comment]
> Has there been a change that would make it possible the processing of the table captions (\#tab:id) by 'bookdown' when working with raw HTML (and eventually other formats). For now, the row HTML is split with a simple markdown section where the caption is written; as it is in Markdown, 'bookdown' can process it.

I need to look into that. And maybe make some adjustment in **bookdown**. Quarto should be clever than **bookdown** on that. 

What I know is that in **knitr**
* We process the caption, including for **bookdown** support 
	* https://github.com/yihui/knitr/blob/master/R/table.R#L165-L176
	* https://github.com/yihui/knitr/blob/master/R/utils.R#L855-L864
* Then we include in raw HTML `<caption>`: 
	* https://github.com/yihui/knitr/blob/master/R/table.R#L357

But maybe that is different with **flextable** - I would need to look closer

**Comment by davidgohel** [comment]
That would be great.

[...] How are you writing this in raw html exactly ?

https://github.com/davidgohel/flextable/blob/master/R/captions.R#L176

-----

With flextable, you can set a caption with `set_caption()`, it can be simple or complex (in terms of formatting options). The string value is parsed with the table (https://github.com/davidgohel/flextable/blob/master/R/captions.R#L173). 

It's different with Quarto as the caption is added by Quarto itself, (https://github.com/davidgohel/flextable/blob/master/R/captions.R#L242). The formattings are added and that's it, I can add any caption, it will be replaced by Quarto (with DOCX exception).

**Comment by cderv** [comment]
OK not sure to see what does not work exactly. **bookdown** do regex matching and replacement in HTML table. It is post processing. I probably to see what you want to produce, and what you would expect **bookdown** to replace.  We should probably look at that in another issue 😉

**Comment by davidgohel** [comment]
Closing the issue as it should be now :) Thanks for your help and suggestions, they have been very useful.

I will open a discussion about bookdown and captions later...
