### ISSUE TITLE
headers_flextable_at_bkm does not work 

### ISSUE THREAD

**Issue by martindurian** [davidgohel/flextable#513]
First of all, thank you for officer and flextable. The new versions are great, especially the possibility to define header and footer content within sections and style definitions. 

The function headers_flextable_at_bkm for adding flextables to the header or footer does not work, I have got the error
"Error in header$has_bookmark(bookmark) : attempt to apply non-function"
Most probably, becaue officer dropped the internal $get_at_cursor()

[input.docx](https://github.com/davidgohel/flextable/files/10806610/input.docx)

reprex

```
library(officer)
 library(flextable)
  
 test_docx <- read_docx("input.docx") 
 flx_tbl <- flextable(data.frame(V1 = "A", v2 = "B"))
 test_docx <- headers_flextable_at_bkm(test_docx, bookmark = "hd_summary_tbl", value = flx_tbl)

  x <- print(test_docx , target = tempfile(fileext = ".docx"))
  browseURL(x)
```

**Comment by davidgohel** [comment]
thanks, it should be fixed now

I also did a minor change in officer (on github). With that change, I suggest this code instead, it takes advantage of the new section content feature. I made it simple with only one default header:

```
library(officer)
library(flextable)

test_docx <- read_docx()
flx_tbl <- flextable(data.frame(V1 = "A", v2 = "B"))
header_default <- block_list(flx_tbl)
ps <- prop_section(header_default = header_default)
test_docx <- body_set_default_section(
  test_docx,
  value = ps)
x <- print(test_docx , target = tempfile(fileext = ".docx"))
browseURL(x)
```
