### ISSUE TITLE
Non-breaking space between caption and table using knitr

### ISSUE THREAD

**Issue by acid-bbq** [davidgohel/flextable#516]
When creating a flextable for using it within knitr and adding the option `ft.keepnext=TRUE` it is possible for the caption and the table being on a different page. I am unsure whether there is an option for adding a non-breaking space between the caption and the table. I think for example that in Latex the caption is always bound to the table. Does this option already exist?

**Comment by davidgohel** [comment]
`ft.keepnext=TRUE` only applies to Word output. 

I am not sure if I understood the question, as I can't figure out what exactly you are expecting as a result. I understand you want to add less (or more) padding between the caption and the table. This can be done using `set_caption(..., fp_p = fp_par(padding.bottom = 6)`.

**Comment by davidgohel** [comment]
Or maybe you are after `set_table_properties(opts_pdf=list(float="float"))`?

**Comment by acid-bbq** [comment]
Many thanks for the prompt reply!

My apologies, my question was not well asked... It this to create a Word outpout. I have trouble providing a reproducible example. BTW, my question was related to this one:
https://stackoverflow.com/questions/72789191/table-title-on-a-different-page-when-using-a-flextable-object-in-a-officedown-do

The solution here was to set `ft.keepnext=FALSE`, which I had success with. However when trying to reproduce it, I realise it has effect only when using `officedown::rdocx_document`. It has no effect when using either `bookdown::word_document2` or `word_document`. It is normal?

The initial question is when using `ft.keepnext=TRUE`, given that the second table has enough room to fit in the next, only the table goes to the second page, not the caption. As if the caption is not part of the table. The solution with `ft.keepnext=FALSE` allows to stick the caption with the table but it also allows the table to span over multiple pages, which is not what I am looking for. Ideally the caption should be part of the table. This is what I mean by "non-breaking space", that it should not be possible to separate the table from the caption. So both the caption and table should go on the second page.

Feel free to close the question!

**Comment by davidgohel** [comment]
>  I realise it has effect only when using officedown::rdocx_document. It has no effect when using either bookdown::word_document2 or word_document. It is normal?

Can you provide the `sessionInfo()` and a reproducible example? I am surprised, this is tested visually here: https://github.com/davidgohel/flextable/tree/master/tests/testthat/_snaps/keep-next

> As if the caption is not part of the table.

A caption in Word is a paragraph – not like in HTML or PDF.

You can use that base: https://github.com/davidgohel/flextable/blob/master/tests/testthat/rmd/keep-next.Rmd

> The solution with ft.keepnext=FALSE allows to stick the caption with the table

Not really, it applies to table. The doc states:

> 'keep_with_next': Word option 'keep rows together' is activated when TRUE. It avoids page break within tables. This is handy for small tables, i.e. less than a page height.

The keepnext setting is automatic with caption (set to TRUE if caption is above the table if I remember correctly)

**Comment by acid-bbq** [comment]
My sessionInfo is (I guess important info are below):

```
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

other attached packages:
[1] bookdown_0.33    officedown_0.3.0 flextable_0.8.6 
```

And the example (I've put only two tick marks for the chunks, otherwise it messes it up):

```
---
output: 
  bookdown::word_document2: default
  officedown::rdocx_document: default
  word_document: default
---

``{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
library(flextable)
library(officedown)
library(bookdown)
``

This is some text 1

``{r label3, echo=FALSE, ft.keepnext=TRUE}
ft5 <- flextable(iris[1:15,])
ft5 <- set_caption(ft5, "my caption 5")
ft5
``

This is some text 2

``{r label4, echo=FALSE, ft.keepnext=TRUE}
ft6 <- flextable(iris[1:15,])
ft6 <- set_caption(ft6, "my caption 6")
ft6
``

This is some text 3

``{r label5, echo=FALSE, ft.keepnext=FALSE}
ft7 <- flextable(iris[1:15,])
ft7 <- set_caption(ft7, "my caption 7")
ft7
``

This is some text 4

``{r label6, echo=FALSE, ft.keepnext=FALSE}
ft8 <- flextable(iris[1:15,])
ft8 <- set_caption(ft8, "my caption 8")
ft8
``
```

Actually if I had text between the code chunks, `ft.keepnext=TRUE` has an effect with `bookdown::word_document2`, but let's say you remove `This is some text 2`, then it doesn't.

**Comment by davidgohel** [comment]
I can see the keepwithnext attribute in each version. So it is working. It has an effect when using either bookdown::word_document2 or word_document or rdocx_document. 

If you drop `This is some text 2`, Word do its job as keepwithnext is set to TRUE. Maybe you just need to not use keepwithnext and set it to FALSE? 


``````
---
output: 
  word_document: default
  officedown::rdocx_document: default
  bookdown::word_document2: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
library(flextable)
library(officedown)
library(bookdown)
# set_flextable_defaults(keep_with_next = FALSE)
ft5 <- flextable(iris[1:15,]) |> 
  set_table_properties(opts_word = list(keep_with_next=FALSE))
ft5 <- set_caption(ft5, "my caption")
ft5
```

This is some text 1

```{r label3}
ft5
```

This is some text 2

```{r label4}
ft5
```

This is some text 3

```{r label5}
ft5
```

This is some text 4

```{r label6}
ft5
```

``````

**Comment by acid-bbq** [comment]
Thanks. With your code I get this with `bookdown::word_document2` with `keep_with_next=TRUE`

![bookd](https://user-images.githubusercontent.com/63967066/223436019-7954e26f-f0b1-46b5-9efc-cfbc29a9006c.png)


Whereas with `officedown::rdocx_document` I get this

![off](https://user-images.githubusercontent.com/63967066/223436305-660e786c-d48a-48f2-adc0-7da5597538e6.png)

So with bookdown a table can be split on two pages. And this is not the case with officedown. But with `keep_with_next=FALSE` I get identical results for both as expected.

**Comment by davidgohel** [comment]
you don't get the same results also because the captions styles are different (see the *Details* section of `set_caption()` in bookdown, templates may also be differents. All these details have an impact on the final result. 

Glad it works for you
