### ISSUE TITLE
Providing (a vector of) new column names to flextable without creating look-up or reference tables or vectors

### ISSUE THREAD

**Issue by fthielen** [davidgohel/flextable#517]
I was asked to open a new issue (see [here](https://stackoverflow.com/questions/70355502/is-there-a-way-to-specify-flextable-header-labels-by-just-listing-the-new-header/70355835?noredirect=1#comment133485285_70355835)).

To provide new column labels with `knitr::kable()` we can do:

```
library(flextable)
library(knitr)
library(dplyr)

mtcars %>% 
        knitr::kable(col.names = letters[1:ncol(mtcars)])
```

With flextable it seems that there is a need to construct look-up or references tables or vectors to achieve the same.

```
values <- setNames(letters[1:ncol(mtcars)],
                   colnames(mtcars))

mtcars %>% 
        flextable::flextable() %>% 
        set_header_labels(values = values)
```

This makes it less intuitive and more complex to provide new column names, especially if they are only needed once.

A feature similar to `knitr::kable()` would be very much appreciated.

**Comment by davidgohel** [comment]
Hello,

Thanks, it should be ok now. Could you test the github version?

**Comment by fthielen** [comment]
Hi,

yes, this works for:

```
library(flextable)
library(knitr)
library(dplyr)

mtcars %>% 
    flextable::flextable() %>% 
    set_header_labels(values = letters[1:ncol(mtcars)])
```

It would be nice if this could also work as follows:

```
mtcars %>% 
    flextable::flextable(col_keys = letters[1:ncol(mtcars)])
```

**Comment by davidgohel** [comment]
No, this will not be implemented. `col_keys` is used to choose the visible variables and their order

**Comment by fthielen** [comment]
Clear. As a final suggestion: maybe another parameter like `col_names` could be added to avoid the need for `set_header_labels()` as an additional function.
