### ISSUE TITLE
Usage in Shiny app

### ISSUE THREAD

**Issue by boeinguy2** [davidgohel/flextable#52]
I have a flextable in a shiny app that will not respond to any attribute that changes a column width. I can get height to change, but not width.  I have tried using width(), the tabwid attribute width=, and autofit.  There are three columns in the table, none of which will respond to the width specification. 

      print(results_table1,preview="html") will show in the RStudio the adjustments to columns, so the attributes are actually changed.

but then followed by
     ` output$resultsTable1 <- rendertabwid(tabwid(results_table1))`

and the displayed table in the shiny app makes no adjustments.

the block that builds the table is shown below.  Most is turned off while I try to get the width problem taken care of.

`      observe({
        #browser()
        if(input$qset != ' ' & input$method == 1 & input$submit > 0){
          results_table1 <- flextable(resultTableDF1(),cwidth = 1) %>%
            theme_box() #%>%
        
        ### Column Headers
        #  Add column headers for table
        
        # bold(part = "header") %>%
        # fontsize(part = "header",size = 18) %>%
        # align(part="header",align="center") #%>%
      
      ### Body  
      
        #width(j =  ~ID, width = .1) %>%
        #width(j =  ~Data, width = .4) %>%

              # format general body of table
      
      # for(mm in seq(from=1,to=(nrow(resultTableDF1())-2),by=3)) {
      #   results_table1 <- merge_at(results_table1,i=mm:(mm+2), j = ~ID, part = "body")
      #   results_table1 <- merge_at(results_table1,i=mm:(mm+2), j = ~Rank, part = "body")
      # }
      
      # results_table1 <- fontsize(results_table1,part = "body",size = 18) %>%
      #   align(j = ~ID, align = "center", part = "body") %>%
      #   align(j = ~Data, align = "left", part = "body") %>%
      #   align(j = ~Rank, align = "center", part = "body") %>%
      #   padding( padding = 5, part = "all" ) %>%
      #   style(pr_c = fp_cell(border = fp_border(color="black", width = 2)),part = "all") #%>%
        
     results_table1 <-  width(results_table1, j = ~Data, width = 8) 
        
     #results_table1 <-  autofit(results_table1) 
     
     
           #     
      #     values$likematrix <- results_table1
      #   
      #dim(results_table1)
     
      print(results_table1,preview="html")
     
      output$resultsTable1 <- rendertabwid(tabwid(results_table1))
    }
  })  
`

I will build a simple example, my code is way to involved in the app to copy any more over

**Comment by boeinguy2** [comment]
Okay, here is working example that shows the issue.  I left the print statement in because it shows that in the RStudio Viewer the middle column is changing, but in the displayed Shiny output, it does not change.

server.R:


     `library(shiny)
library(flextable)

ID <- c("C01"," "," ","C02"," "," ","C03"," "," ")
Data <- c("Problem 1","Answer 1","Note 1","Problem 2","Answer 2","Note 2","Problem 3","Answer 3","Note 3")
Rank <- c("L"," "," ","L"," "," ","L"," "," ")
finalResults <- data.frame(ID,Data,Rank)

shinyServer(function(input, output, session) {
  #browser()  

  observe({
    #browser()
      results_table1 <- flextable(finalResults,cwidth = 1) %>%
        theme_box() #%>%

      results_table1 <-  width(results_table1, j = ~Data, width = 8) 

      print(results_table1,preview="html")  
      
      output$resultsTable1 <- rendertabwid(tabwid(results_table1))

  })
  
})`

ui.R:
    
    `library(shiny)
library(shinyjs)

shinyUI(
  fluidRow(
    flextable::tabwidOutput("resultsTable1",width="100%")  )
)`

**Comment by davidgohel** [comment]
Nest time, add your `sessionInfo()` as explained in the guidelines of the template. 

Your code will need to be modified. You are using `tabwidOutput` that has been deprecated (two release ago) and deleted (one release ago). You will first need to update the package.

The documentation is giving an example for shiny usage. 
https://davidgohel.github.io/flextable/articles/examples.html#using-within-shiny-applications

I can't easily reuse your code and I don't see any reactive value in your call to `observe()`. I have adapted the example below to demo a reactive width (but limited to its container size). 

```
library(shiny)
library(dplyr)
library(flextable)


ui <- fluidPage(
  titlePanel("mtcars"),
  sidebarLayout(
    sidebarPanel(
      sliderInput("mpg", "mpg Limit", min = 11, max = 33, value = 20),
      sliderInput("wd", "width...", min = 0.1, max = 8, value = 1)
    ),
    mainPanel(
      uiOutput("mtcars_ft")
    )
  )
)


server <- function(input, output) {
  
  output$mtcars_ft <- renderUI({
    mtcars %>%
      mutate(car = rownames(.)) %>%
      select(car, everything()) %>%
      filter(mpg <= input$mpg) %>%
      regulartable() %>%
      theme_booktabs() %>% 
      width(width = input$wd) %>%
      htmltools_value()
  })
  
}


shinyApp(ui = ui, server = server)
```

**Comment by boeinguy2** [comment]
Okay, I will try this.  However updating the package will force me to
rewrite four other tables that took months to get working.  They have some
unique complexities that could only be solved in flextable and now have to
be revisited.  Hopefully they will not require much change to adapt.

**Comment by boeinguy2** [comment]
I got the example to show the problem, did not think about the lack of a
reactive value in the observe.  In the app, there are reactive values.

**Comment by boeinguy2** [comment]
also, can I still use flextable and not regulartable?

**Comment by davidgohel** [comment]
> can I still use flextable and not regulartable?

yes, difference is explained here https://davidgohel.github.io/flextable/articles/overview.html#introduction
