### ISSUE TITLE
No autonumber unless using a bookmark

### ISSUE THREAD

**Issue by thebioengineer** [davidgohel/flextable#527]
**Not a bug or feature request? If you are looking for help on how to use the 
package correctly, please read the doc first at https://davidgohel.github.io/flextable/. 
You can also visit [Stackoverflow](https://stackoverflow.com/questions/tagged/flextable+r) 
and tag your question with `[flextable]`. We usually read them and answer WHEN possible.**  

When submitting a new issue:

- [x] Provide the code that is producing the error, it has to be a minimal reproducible example.
Stackoverflow is providing good explanations about it: https://stackoverflow.com/help/mcve. You can use package `reprex` to help you: http://reprex.tidyverse.org/. The most popular R stackoverflow question is about the subject: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

``` r
library(officer)
#> Warning: package 'officer' was built under R version 4.1.3
library(flextable)
#> Warning: package 'flextable' was built under R version 4.1.3

doc <- read_docx()

ft <- flextable(head(airquality))
ft1 <- ft |>
  set_caption(
    caption = "airquality dataset", 
    autonum = run_autonum(seq_id = "tab", bkm = "airquality"))

ft2 <- ft |> 
  set_caption(
    caption = "airquality dataset", 
    autonum = run_autonum(seq_id = "tab"))
doc <- doc |> 
  body_add_flextable(ft1) |> 
  body_add_flextable(ft2)

print(doc, target = "Test.docx")

sessionInfo()
#> R version 4.1.1 (2021-08-10)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19044)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] flextable_0.9.0 officer_0.6.1  
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.10             digest_0.6.31           utf8_1.2.2             
#>  [4] mime_0.12               R6_2.5.1                backports_1.4.1        
#>  [7] reprex_2.0.1            evaluate_0.20           highr_0.10             
#> [10] pillar_1.8.1            gdtools_0.3.2           rlang_1.0.6            
#> [13] curl_5.0.0              uuid_1.1-0              rstudioapi_0.13        
#> [16] data.table_1.14.6       R.utils_2.11.0          R.oo_1.24.0            
#> [19] rmarkdown_2.20          styler_1.6.2            textshaping_0.3.5      
#> [22] stringr_1.5.0           shiny_1.7.4             compiler_4.1.1         
#> [25] httpuv_1.6.8            xfun_0.36               pkgconfig_2.0.3        
#> [28] askpass_1.1             systemfonts_1.0.4       gfonts_0.2.0           
#> [31] htmltools_0.5.4         openssl_2.0.5           tibble_3.1.8           
#> [34] fontBitstreamVera_0.1.1 httpcode_0.3.0          fansi_1.0.3            
#> [37] crayon_1.5.2            withr_2.5.0             later_1.3.0            
#> [40] R.methodsS3_1.8.1       crul_1.3                grid_4.1.1             
#> [43] jsonlite_1.8.4          xtable_1.8-4            lifecycle_1.0.3        
#> [46] magrittr_2.0.3          zip_2.2.2               cli_3.6.0              
#> [49] stringi_1.7.12          cachem_1.0.6            fs_1.5.2               
#> [52] promises_1.2.0.1        xml2_1.3.3              ellipsis_0.3.2         
#> [55] ragg_1.1.3              vctrs_0.5.2             tools_4.1.1            
#> [58] R.cache_0.15.0          glue_1.6.2              fontquiver_0.2.1       
#> [61] purrr_1.0.1             fastmap_1.1.0           yaml_2.3.7             
#> [64] fontLiberation_0.1.0    memoise_2.0.1           knitr_1.41
```

<sup>Created on 2023-03-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

- [x] Provide the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example. 

- [x] Make sure you did checked you had the latest version of the package on CRAN (and on github if issue exists with CRAN version).

- [x] Make sure you searched in the *open* and *closed* issues on the github repository.

Issue #497 appears to have returned. Looking at your code, it looks like you are using `has_autonum()` to check for whether numbering exists, but it looks for the existence of a bookmark, as opposed to generally if autonumbering exists: x$caption$autonum$bookmark, Would it be better just to look for x$caption$autonum? it will exist if autnumbering/bookmarking is defined at all:

https://github.com/davidgohel/flextable/blob/cc2a01c2888999ee8aa8e05e3314d11f003cc665/R/captions.R#L306

has_autonum <- function (x) 
{
    has_it <- FALSE
    if (!is.null(x$caption$autonum)) {
        has_it <- TRUE
    }
    has_it
}

**Comment by anon94041** [comment]
I'm getting exactly the same results - autonumbering isn't working for me.  Just wanted to add my support for moving this up the priority list.

I ran the same code as thebioengineer and got the same results.  My session info is:

R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] flextable_0.8.3 officer_0.6.2  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.11       digest_0.6.30     grid_4.2.2        R6_2.5.1         
 [5] evaluate_0.18     zip_2.2.2         gdtools_0.2.4     rlang_1.0.6      
 [9] cli_3.4.1         uuid_1.1-0        data.table_1.14.4 xml2_1.3.3       
[13] ragg_1.2.5        rmarkdown_2.18    textshaping_0.3.6 tools_4.2.2      
[17] xfun_0.34         yaml_2.3.6        fastmap_1.1.0     compiler_4.2.2   
[21] base64enc_0.1-3   askpass_1.2.0     systemfonts_1.0.4 htmltools_0.5.3  
[25] openssl_2.1.1     knitr_1.40

**Comment by davidgohel** [comment]
Thanks, it is now fixed with the proposed solution
