### ISSUE TITLE
Quarto/PDF Output - Unnecessary Lines Above Table when captions

### ISSUE THREAD

**Issue by Louis-Alassane** [davidgohel/flextable#528]
Dear David, 

I have run into a problem a couple times creating simple flextables in Quarto and rendering to pdf. 

When using a subcaption, the table creates unnecessary lines above the headers (see screenshot). This has happened to me both when adding a subcaption and when displaying tables side by side (which creates a subcaption table a/table b by default).  However, the side by side layout may not be problematic anymore as I could not recreate it today. 

![image](https://user-images.githubusercontent.com/124859189/227436788-800e4a02-5b8e-44bc-a860-a5f2e336f994.png)

**Flextable code:** 
```{r}
#| label: tbl-age
#| tbl-cap: "Descriptive Statistics: Age"
#| tbl-subcap: "some subcap"

ft <- flextable(df)
ft <- autofit(ft3)
ft 
```
**Session Info:**

R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044) 

Merci!

**Comment by davidgohel** [comment]
This weird thing is added by Quarto. 

We only inject an empty caption when working with Quarto as the product manages on its own all captions, their placements, etc. So I am afraid we can't do anything.

**Comment by Louis-Alassane** [comment]
Ah good to know, nevermind then! 

It's not a massive problem as you can just do away with subcaptions in general but I thought I'd let you know.

**Comment by davidgohel** [comment]
thanks, all is ok with Quarto except the captions, we are waiting some feature to come in the next release 

See https://github.com/quarto-dev/quarto-cli/issues/1556

**Comment by davidgohel** [comment]
It should be fixed. 

It seems the solution was to only remove caption from flextable output, it works in Quarto for PDF and HTML.
