### ISSUE TITLE
[Enhanecement] Add subtotal capability

### ISSUE THREAD

**Issue by happyshows** [davidgohel/flextable#53]
Hi,

I am assuming the vision of this package is to replace excel pivot reporting (let me know if this is wrong)

In my view, one missing element in this package is subtotal by group in pivoted view. The aggregation method could just be SUM, which I believe most people would use.

People will start to ask question when they see a row header merged but no subtotal shown.

Let me know if you have more questions on use case or this is already implemented but not documented.

**Comment by davidgohel** [comment]
Hi

* [...] is to replace excel pivot reporting

I am afraid not, it is only to make reporting to html/word/pptx easier:

> create tables for reporting and control their formatting properties and their layout

Sorry, there is no motivation to create a pivot reporting in the package.
