### ISSUE TITLE
rotate() align argument is horizontal, not verticle

### ISSUE THREAD

**Issue by jzadra** [davidgohel/flextable#54]
When using rotate(), the align argument is specific to the direction of the text, not the cell.  So if the rotation is "lrtb", then align = "top" / "bottom" moves the text up/down, respectively.  However, if the rotation is "btlr" or "tbrl", then align = "top" / "bottom" moves the text left or right.

**Comment by jzadra** [comment]
I guess it's supposed to be this way.  The `align` function lets you do the other dimension.

**Comment by davidgohel** [comment]
sorry not been available...

Yes, you will probably need to play with rotate and align:

```
library(flextable)

ft <- flextable(iris)
ft <- rotate(ft, rotation = "tbrl", part = "header", align = "center")
ft <- align(ft, align = "center")
max_width <- max(dim_pretty(ft, part = "header")$widths)
ft <- height(ft, height = max_width, part = "header")

print(ft, preview = "docx")
```

**Comment by jzadra** [comment]
Thanks!
