### ISSUE TITLE
Unexpected bold `hlines()`

### ISSUE THREAD

**Issue by DanChaltiel** [davidgohel/flextable#543]
Hi David,

I'm using `hline()` for my crosstables, and it seems that recently some wild bold rows appear somewhat randomly.

For instance, consider the following code and output:
```r
iris %>% flextable() %>% hline()
```
![image](https://github.com/davidgohel/flextable/assets/15105152/ba8b4097-cda9-4aae-ac75-3594ac67a50c)

`fix_border_issues()` is unfortunately not helping and specifying `i` is also randomly making the line bold.

There seems to be a pattern of every 5 and 3 rows.

I'm using flextable 0.9.1 (last on CRAN at this time).

Hope to see you in Avignon in June :-)

Dan

When submitting a new issue:

- [x] Provide the code that is producing the error, it has to be a minimal reproducible example.
Stackoverflow is providing good explanations about it: https://stackoverflow.com/help/mcve. You can use package `reprex` to help you: http://reprex.tidyverse.org/. The most popular R stackoverflow question is about the subject: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

- [x] Provide the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example. 

- [x] Make sure you did checked you had the latest version of the package on CRAN (and on github if issue exists with CRAN version).

- [x] Make sure you searched in the *open* and *closed* issues on the github repository.

**Comment by davidgohel** [comment]
Probably a duplicate of #343, #374 and #535

**Comment by DanChaltiel** [comment]
Oh sorry, I searched through the issues but I missed those ones.

Indeed, this happens in RStudio's viewer pane but not in Chrome and not in MS Word. I guess this is a bug in the Chrome engine inside RStudio.
