### ISSUE TITLE
autofit ignores rotation

### ISSUE THREAD

**Issue by jzadra** [davidgohel/flextable#55]
`autofit()` ignores rotation. So if I have a long string that is vertical, autofit sizes the column as if it's horizontal.  `dim_pretty(myft, part = "body")` seems able to calculate the dims that one would want with a rotated header, but I'm not sure how to use those values to set the heights/widths.  Perhaps the `autofit()` function could have a `part` argument that could reuse the same code as `dim_pretty()` when ignoring the header.

**Comment by davidgohel** [comment]
Yes

Thanks for the questions, that should be documented...

The following code should help:

```
library(flextable)

ft <- flextable(iris)
ft <- rotate(ft, rotation = "tbrl", part = "header", align = "center")
ft <- align(ft, align = "center")

# Here I am computing the max width of columns in the header part :
max_width <- max(dim_pretty(ft, part = "header")$widths)

# And now, I am using that max as an height:
ft <- height(ft, height = max_width, part = "header")

print(ft, preview = "docx")
```

**Comment by davidgohel** [comment]
I am closing the issue, it get documented: https://github.com/davidgohel/flextable/commit/b09605d95bb62b6d6dc7bf10608171ba7bd650bf

Suggestions or comments to improve this explanation are welcome :)
