### ISSUE TITLE
Header showing up with class of variable (integer/numeric)

### ISSUE THREAD

**Issue by wfdefreitas** [davidgohel/flextable#554]
Not sure if I am doing something incorrect or if this is a result of updating Rstudio to 2023.06.0 build 421, but can't seem to get flextable without class of variable printing below the header. 

```
mtcars |> 
  as_flextable()
```

output shows:

![image](https://github.com/davidgohel/flextable/assets/138241985/592a860d-0eff-4146-8aac-3c6d93e7da52)

**How do I get rid of the row with "numeric"?** 

tried to void:

```
mtcars |> 
  as_flextable() |> 
  void(i=2, part="header")
```

but get this error
```
Error in void(as_flextable(mtcars), i = 2, part = "header") : 
  unused argument (i = 2)
```

tried to set as NULL:

```
mtcars$header$dataset[2,] <- NULL
```
but get this error
```
Error in x[[jj]][iseq] <- vjj : replacement has length zero

```

Help?

**Comment by davidgohel** [comment]
See `?as_flextable` and `?flextable()`. I think you only want `flextable()`

**Comment by wfdefreitas** [comment]
Well that was silly! Sorry and thank you!
