### ISSUE TITLE
Super- and subscripts incorrectly rendered in LaTeX

### ISSUE THREAD

**Issue by phgrosjean** [davidgohel/flextable#556]
In an R Markdown document, I have this chunk:

```
library(flextable)
flextable(head(iris)) |>
  add_footer_lines(as_paragraph(as_chunk("Super"), as_sup("script"),
    as_chunk(" and sub"), as_sub("script")))
```

then, I knit to PDF. The super- and subscripts are rendered with same font size as normal text. This is wrong: they should be smaller.

The culprit is (in the .tex file), a call to `\fontsize{}` *after* `\textsuperscript{}`, like: `{\textsuperscript{\fontsize{11}{11}\selectfont{script}}}`. This should be `\fontsize{}` first and `\textsuperscript{}` in second, like: `{\fontsize{11}{11}\selectfont{\textsuperscript{script}}}`. When I do this change manually in the .tex document generated by knitr, the super- and subscripts are correctly rendered in the PDF.

I use R 4.2.3 and {flextable} 0.9.2.

**Comment by davidgohel** [comment]
Thank you for that, your solution has been used!
