### ISSUE TITLE
Proc_freq shows superfluous semicolons when include.row_percent = FALSE

### ISSUE THREAD

**Issue by fkatwix** [davidgohel/flextable#559]
Using the example from the documentation. 

> proc_freq(mtcars, "vs", "gear",
>           include.row_percent = FALSE,
>        include.table_percent = FALSE,
>         include.header_row = FALSE)

<img width="481" alt="Screenshot 2023-08-03 at 13 29 57" src="https://github.com/davidgohel/flextable/assets/124152523/6c0ff6f4-8967-449e-8dbf-2d7c96c67666">

Is there any way to get rid of the semicolons when you're only using the col%? I love the versatility of flextable, particularly for aesthetics, thanks for your work :)

> R version 4.2.2 (2022-10-31)
> 
> Platform: aarch64-apple-darwin20 (64-bit)
> Running under: macOS Ventura 13.2.1
> 
> Matrix products: default
> LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] htmlwidgets_1.6.2   emoji_15.0          plotly_4.10.2       timevis_2.1.0       vistime_1.2.3       pander_0.6.5       
>  [7] EnvStats_2.8.0      sandwich_3.0-2      kableExtra_1.3.4    stargazer_5.2.3     modelsummary_1.4.1  miceadds_3.16-18   
> [13] mice_3.16.0         huxtable_5.5.2      sjPlot_2.8.14       jtools_2.2.2        see_0.8.0           report_0.5.7       
> [19] parameters_0.21.1   performance_0.10.4  modelbased_0.8.6    insight_0.19.3      effectsize_0.8.3    datawizard_0.8.0   
> [25] correlation_0.8.4   bayestestR_0.13.1   easystats_0.6.0     lindia_0.9          ggplotify_0.1.1     car_3.1-2          
> [31] carData_3.0-5       officer_0.6.2       quantreg_5.96       SparseM_1.81        lmtest_0.9-40       zoo_1.8-12         
> [37] overviewR_0.0.13    ggpubr_0.6.0        gtsummary_1.7.2     gtExtras_0.4.5      gt_0.9.0            **flextable_0.9.2**    
> [43] reactablefmtr_2.0.0 reactable_0.4.4     viridis_0.6.4       viridisLite_0.4.2   ghibli_0.3.3        wesanderson_0.3.6  
> [49] addinslist_0.5.0    devtools_2.4.5      usethis_2.2.1       lubridate_1.9.2     forcats_1.0.0       stringr_1.5.0      
> [55] dplyr_1.1.2         purrr_1.0.1         readr_2.1.4         tidyr_1.3.0         tibble_3.2.1        ggplot2_3.4.2      
> [61] tidyverse_2.0.0    
> 
> loaded via a namespace (and not attached):
>   [1] ggvenn_0.1.10              utf8_1.2.3                 tidyselect_1.2.0           lme4_1.1-33               
>   [5] grid_4.2.2                 munsell_0.5.0              codetools_0.2-19           ragg_1.2.5                
>   [9] DT_0.28                    miniUI_0.1.1.1             withr_2.5.0                colorspace_2.1-0          
>  [13] tables_0.9.17              knitr_1.43                 uuid_1.1-0                 rstudioapi_0.14           
>  [17] assertive.base_0.0-9       ggsignif_0.6.4             fontLiberation_0.1.0       emmeans_1.8.7             
>  [21] farver_2.1.1               coda_0.19-4                vctrs_0.6.3                generics_0.1.3            
>  [25] TH.data_1.1-2              xfun_0.39                  timechange_0.2.0           fontquiver_0.2.1          
>  [29] R6_2.5.1                   cachem_1.0.8               gridGraphics_0.5-1         assertthat_0.2.1          
>  [33] promises_1.2.0.1           scales_1.2.1               nnet_7.3-19                multcomp_1.4-25           
>  [37] gtable_0.3.3               processx_3.8.2             rlang_1.1.1                MatrixModels_0.5-1        
>  [41] systemfonts_1.0.4          splines_4.2.2              rstatix_0.7.2              lazyeval_0.2.2            
>  [45] broom_1.0.5                prismatic_1.1.1            modelr_0.1.11              yaml_2.3.7                
>  [49] abind_1.4-5                crosstalk_1.2.0            backports_1.4.1            httpuv_1.6.11             
>  [53] wordcountaddin_0.3.0.9000  tools_4.2.2                ellipsis_0.3.2             sessioninfo_1.2.2         
>  [57] Rcpp_1.0.10                ps_1.7.5                   prettyunits_1.1.1          rpart_4.1.19              
>  [61] openssl_2.0.6              urlchecker_1.0.1           fontawesome_0.5.1          ggrepel_0.9.3             
>  [65] fs_1.6.2                   crul_1.4.0                 magrittr_2.0.3             data.table_1.14.8         
>  [69] mvtnorm_1.2-2              mitml_0.4-5                sjmisc_2.8.9               pkgload_1.3.2             
>  [73] hms_1.1.3                  mime_0.12                  evaluate_0.21              xtable_1.8-4              
>  [77] sjstats_0.18.2             shape_1.4.6                gridExtra_2.3              ggeffects_1.2.3           
>  [81] compiler_4.2.2             fontBitstreamVera_0.1.1    crayon_1.5.2               minqa_1.2.5               
>  [85] koRpus_0.13-8              htmltools_0.5.5            later_1.3.1                tzdb_0.4.0                
>  [89] DBI_1.1.3                  sjlabelled_1.2.0           MASS_7.3-60                broom.helpers_1.13.0      
>  [93] boot_1.3-28.1              Matrix_1.5-4.1             mitools_2.4                cli_3.6.1                 
>  [97] assertive.types_0.0-3      pan_1.8                    pkgconfig_2.0.3            foreach_1.5.2             
> [101] xml2_1.3.4                 paletteer_1.5.0            svglite_2.1.1              sylly_0.1-6               
> [105] webshot_0.5.5              estimability_1.4.1         rvest_1.0.3                yulab.utils_0.0.6         
> [109] callr_3.7.3                digest_0.6.31              httpcode_0.3.0             rmarkdown_2.23            
> [113] gdtools_0.3.3              curl_5.0.1                 jomo_2.7-6                 shiny_1.7.4               
> [117] nloptr_2.0.3               lifecycle_1.0.3            nlme_3.1-162               jsonlite_1.8.7            
> [121] askpass_1.1                fansi_1.0.4                pillar_1.9.0               lattice_0.21-8            
> [125] fastmap_1.1.1              httr_1.4.6                 pkgbuild_1.4.2             survival_3.5-5            
> [129] glue_1.6.2                 remotes_2.4.2              zip_2.3.0                  iterators_1.0.14          
> [133] glmnet_4.1-7               assertive.properties_0.0-5 stringi_1.7.12             sass_0.4.6                
> [137] profvis_0.3.8              rematch2_2.1.2             textshaping_0.3.6          gfonts_0.2.0              
> [141] memoise_2.0.1             

I hope this is everything you need, I haven't reported an issue using GitHub before. Thank you

**Comment by davidgohel** [comment]
thanks for reporting this, this was a stupid mistake in the code
