### ISSUE TITLE
newline (\n) does not work in cell

### ISSUE THREAD

**Issue by renkun-ken** [davidgohel/flextable#56]
It's common in paper to present tables of statistics. Many look like 

<img width="283" alt="image" src="https://user-images.githubusercontent.com/4662568/37904960-e8fda3ee-312f-11e8-82ae-bc6d9c6c80ea.png">

A simple demo is 

```r
library(flextable)
library(officer)
library(magrittr)
table <- data.frame("Col1" = c("1.5\n(0.5)", "2.3\n(-0.1)"), stringsAsFactors = FALSE)
tb1 <- regulartable(table) %>%
  theme_vanilla()
doc <- read_docx()
doc %>%
  body_add_flextable(tb1) %>%
  print(target = "~/data/word-tables.docx")
```

But the line breaks are gone in the resulted table in Word:

<img width="163" alt="image" src="https://user-images.githubusercontent.com/4662568/37905058-35222a06-3130-11e8-875e-0971fc05acba.png">

I'm wondering how to produce multi-line cells with `flextable`?

I've gone through #39, <https://stackoverflow.com/questions/36506787/add-line-break-in-title-in-reporters>, <https://github.com/davidgohel/ReporteRs/issues/20> but no solution seems to work in my case.

My session info:

```
R version 3.4.4 (2018-03-15)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magrittr_1.5    officer_0.2.2   flextable_0.4.3

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16      rprojroot_1.3-2   digest_0.6.15     R.methodsS3_1.7.1 R6_2.2.2          backports_1.1.2   evaluate_0.10.1  
 [8] zip_1.0.0         stringi_1.1.7     gdtools_0.1.7     uuid_0.1-2        R.oo_1.21.0       R.utils_2.6.0     xml2_1.2.0       
[15] rmarkdown_1.9     tools_3.4.4       stringr_1.3.0     yaml_2.1.18       compiler_3.4.4    base64enc_0.1-3   htmltools_0.3.6  
[22] knitr_1.20       
```

**Comment by davidgohel** [comment]
Ideally, new lines are new rows. But the idea does not please users :) To enable the gathering of different informations in one single cell, I will have to provide a less strict implementation that will allow  new lines as explained in #39

(and you will loose ability to *autofit*) 

David

**Comment by davidgohel** [comment]
Soft returns `\n` are now available (in the dev version on github). 

Functions `autofit` and `dim_pretty` do not support soft returns, `\n` will be considered as `""`.

**Comment by renkun-ken** [comment]
Thanks a lot! I'll try it soon.
