### ISSUE TITLE
Updating 0.9.1 to 0.9.2, can't open shared object libtiff.so.5

### ISSUE THREAD

**Issue by SimonDedman** [davidgohel/flextable#560]
Updating in RStudio on Linux, getting:

> unable to load shared object '/home/simon/R/x86_64-pc-linux-gnu-library/4.2/ragg/libs/ragg.so':
>   libtiff.so.5: cannot open shared object file: No such file or directory

I've tried `sudo apt install libtiff5-dev` to no avail; `sudo apt install libtiff5` has no install candidate, `apt-cache search libtiff` returns:

> libtiff-dev - Tag Image File Format library (TIFF), development files
> libtiff-doc - TIFF manipulation and conversion documentation
> libtiff5-dev - Tag Image File Format library (TIFF), development files (transitional package)
> libtiff6 - Tag Image File Format (TIFF) library
> libtiffxx6 - Tag Image File Format (TIFF) library -- C++ interface
> libgraphics-tiff-perl - Perl extension for the libtiff library
> libtiff-opengl - TIFF manipulation and conversion tools
> libtiff-tools - TIFF manipulation and conversion tools
> pngtools - series of tools for PNG (Portable Network Graphics) images
> pylibtiff - wrapper to the libtiff library to Python using ctypes (command line utilities)
> python3-libtiff - wrapper to the libtiff library to Python using ctypes (Python 3 version)
> gem-plugin-tiff - Graphics Environment for Multimedia - TIFF support

Any ideas what I need to install here? 
Xubuntu 23.04.

`sessionInfo()`:

> R version 4.2.2 Patched (2022-11-10 r83330)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 23.04
> 
> Matrix products: default
> BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
> LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.21.so
> 
> locale:
>  [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8
> [12] LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base

Thanks!

**Comment by davidgohel** [comment]
Sorry, I don't have any Xubuntu 23.04 available so it's hard to check. 

From a quick google search, https://askubuntu.com/a/1467229 seems to be a solution to those who met your issue. If that does not fix the issue, sorry, we are not able to help more with 'ragg' update.

'ragg' was already a dependency with flextable `0.9.1` and there is no minimum version required – you don't need to update it to get 'flextable' update.

**Comment by SimonDedman** [comment]
Wonderful stuff. `/usr/lib/x86_64-linux-gnu$ sudo ln -s libtiff.so.6.0.0 libtiff.so.5` did it for me. Thanks!
