### ISSUE TITLE
Repeated footer for long tables

### ISSUE THREAD

**Issue by cwilso6** [davidgohel/flextable#566]
I wondering if it is possible to add a feature for repeating the footer for each page of a long table. Here is a basic example of the challenge.

```
---
title: "Untitled"
format: 
  docx:
    keep-md: false
---
```

```{r include=FALSE}
library(flextable)
library(officer)
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
ft <- flextable(mtcars)
ft |> add_footer_lines("Some additional info about table") |>
  paginate(hdr_ftr = TRUE, init = FALSE) #not complete sure this is need or helpful
```

which produced:
![image](https://github.com/davidgohel/flextable/assets/42617537/78494ac2-752c-401f-821e-c0107fdc2897)

and what I am hoping for is 
![image](https://github.com/davidgohel/flextable/assets/42617537/8db64557-7e72-468c-bbca-c248ce4ee06d)

which was not straightforward I inserted a row below in the second to last row on the first page, merged the new cells, added a border on the top of the new row, and left-aligned the text. I recognize that this can be done manually but my team is hoping to automate the report generation as it will be generated from a shiny app.

**Comment by davidgohel** [comment]
Hello, what you are asking is not possible because MS Word does not come with a table footer concept. It is not feasible. The only workaround would be to add the table in its proper section and to add a section page footer where your content will repeated until the section is closed.
