### ISSUE TITLE
Images as column headers

### ISSUE THREAD

**Issue by cataclysmic** [davidgohel/flextable#568]
Hey maintainers,

I couldn't find a way to replace column headers with images/icons.
It'd be great i you could implement this feature. Or add it to the documentation if already possible.

Thx in advance.

**Comment by davidgohel** [comment]
```

library(flextable)
img.file <- file.path( R.home("doc"),
                       "html", "logo.jpg" )

as_flextable(iris) |> 
  append_chunks(part = "header", as_image(src = img.file),
                j = 2:3, i = 1)
```

<img width="864" alt="Capture d’écran 2023-09-03 à 12 15 25" src="https://github.com/davidgohel/flextable/assets/4331618/31d50ea6-2dcf-4e7a-ace4-417c3a5574c7">

Below an example. I can add a specific section to doc but that's hard to illustrate all questions. The links below shows how it works. A flextable has parts, each part can be modify with `mk_par()` or `append_chunk()`, a chunk can be an image.

https://ardata-fr.github.io/flextable-book/cell-content.html#function-mk_par

https://ardata-fr.github.io/flextable-book/cell-content.html#append-or-prepend-content

https://ardata-fr.github.io/flextable-book/cell-content.html#images

https://ardata-fr.github.io/flextable-book/table-design.html#table-parts

**Comment by cataclysmic** [comment]
Sorry for the fuzz. Thank you so much.
