### ISSUE TITLE
setZebraStyle() is referenced in documentation but is not in package 

### ISSUE THREAD

**Issue by jzadra** [davidgohel/flextable#57]
setZebraStyle() is referenced here, but does not appear to be in v 0.4.4.1

https://davidgohel.github.io/ReporteRs/articles/FlexTable.html#zebra-striped-tables

**Comment by davidgohel** [comment]
`setZebraStyle` is part of `ReporteRs`, not part of `flextable`. 

`officer`/`flextable`/`rvg` are replacing `ReporteRs`.

**Comment by jzadra** [comment]
My mistake.

Thanks, these packages are saving my life this week.

**Comment by davidgohel** [comment]
No problem :) You are looking for function `theme_zebra` in flextable package: 

https://davidgohel.github.io/flextable/reference/index.html#section-flextable-themes
