### ISSUE TITLE
Typo in flextable book?

### ISSUE THREAD

**Issue by iago-pssjd** [davidgohel/flextable#571]
> **Not a bug or feature request? 

No, however...

> If you are looking for help on how to use the 
package correctly, please read the doc first at https://davidgohel.github.io/flextable/. 
You can also visit [Stackoverflow](https://stackoverflow.com/questions/tagged/flextable+r) 
and tag your question with `[flextable]`. We usually read them and answer WHEN possible.**  

No too.

I looked for the Github repository for the flextable book (under ardata-fr user) but I couldn't find, so I post here. Let me know if there is other better place. In https://ardata-fr.github.io/flextable-book/rendering.html#knitr-chunk-options, the first R Markdown document example in [section 4.3](https://ardata-fr.github.io/flextable-book/rendering.html#r-markdown-documents) shows

````r
---
title: blah blah
output: html_document
---

> this is how to print a flextable in a R Markdown document

```{r}
library(flextable)
ft <- flextable(head(mtcars))
ft <- autofit(ft)
ft
```
````

Shouldn't be `word_document` instead of `html_document`?

Thanks!

**Comment by davidgohel** [comment]
Thanks, I will add `in`, sorry for the language errors.

> Shouldn't be word_document instead of html_document?

No, why? flextable manage Word, PowerPoint, grid and ggplot2 outputs, PDF, RTF, HTML. Word is only one option, the default output is HTML

**Comment by iago-pssjd** [comment]
Ok! I just thought the emphasize was for word
