### ISSUE TITLE
Issue when justifying table text: NA placed in text

### ISSUE THREAD

**Issue by aito123** [davidgohel/flextable#573]
Hello,

I use `{flextable}` for creating tables intended for PDF outputs in Quarto (.qmd). This works fine except when I want to justify the text of the table, the `align` function justifies de text but places NA at the beginning of every cell for some reason. Here the regex:

**CODE**

````{rmd}
---
title: "REGEX FLEXTABLE"
format: pdf
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

```{r}
pacman::p_load(flextable, tidyverse)

head(as.data.frame(sentences)) %>% 
  flextable() %>% 
  align(j=1, align = "justify", part = "body") %>% 
  autofit()

```
 ````

**OUTPUT**

<img width="660" alt="image" src="https://github.com/davidgohel/flextable/assets/53672503/a69a3990-a83b-468d-9847-bba9c75beba6">

Thanks very much for the help.

**Comment by davidgohel** [comment]
thank you. The issue was there because 'justified text' is not supported with the latex flextable implementation. I have updated the documentation and changed 'justify' to 'left' for latex output.

**Comment by aito123** [comment]
Ok. Hopefully justified its implemented as an option inside body cells in a future update.

Cheers,
Santiago
