### ISSUE TITLE
[docs] update add_footer's documentation

### ISSUE THREAD

**Issue by jhk0530** [davidgohel/flextable#575]
Hi, thanks for nice work. 

Recently I'm develop some package with flextable. and trying to add `Footer` like below's image (from [function reference](https://davidgohel.github.io/flextable/reference/add_footer.html))

![](https://www.ardata.fr/img/flextable-imgs/flextable-016.png)

but I think this result can build with `footnote` function instead of `add_footer`. (also examples code generates another table)

here's `add_footer`'s result with example code. 

![image](https://github.com/davidgohel/flextable/assets/6457691/64c62454-4681-4220-b09f-fa3ade8a0a62)

So here's my suggestion.

1. Add note for `footnote` function below that image. (like `See Also`)

or

2. Move that image to `footnote`'s documentation. and update code for that. 

If this make sence, I'd like to make PR for this. 

Thanks. 

Kim

**Comment by davidgohel** [comment]
hello, good catch, thank you

I did the update because it was a quick update, but thanks for volunteering for a PR. 

Thanks,
David
