### ISSUE TITLE
Flextables objects do not land in the second column in column containers in powerpoint

### ISSUE THREAD

**Issue by sjkiss** [davidgohel/flextable#580]
Hi: I'm using RMarkdown to create a powerpoint presentation. 

When I create a flextable object for inclusion in the second column of a two-column slide, the flextable only ever appears in the first column. 

This code reproduces the problem.

Thank you.

```
---
title: "Test"
author: "author"
date: "2023-10-18"
output: powerpoint_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=F, message=F)
```

## R Markdown

:::::::::::::: {.columns}
::: {.column width="50%"}
- Some text talkinga bout the column on the right
:::
::: {.column width="50%"}
```{r table}
#install.packages("flextable")
library(flextable)
library(dplyr)
data("mtcars")
mtcars %>% 
  group_by(cyl) %>% 
  summarize(avg=mean(mpg)) %>% 
  flextable()
```

:::
::::::::::::::
```

**Comment by davidgohel** [comment]
hello

See https://davidgohel.github.io/flextable/reference/knit_print.flextable.html#chunk-options and the subchapter "PowerPoint only".

<img width="910" alt="Capture d’écran 2023-10-18 à 16 08 30" src="https://github.com/davidgohel/flextable/assets/4331618/548e17a0-9df9-42f4-b794-6ed8abc7cc9c">

**Comment by sjkiss** [comment]
That is tremendous. Thank you.
