### ISSUE TITLE
Use NFD Unicode normalization form to fix accented characters in Word

### ISSUE THREAD

**Issue by uhkeller** [davidgohel/flextable#586]
When writing accented (combined) characters to a table with `body_add_flextable()`, combined characters using NFC Unicode normalization are displayed by Word in Arial/Helvetica instead of the font specified in `set_flextable_defaults()`. For example:

```R
library(flextable)
library(officer)
set_flextable_defaults(font.family = "Cambria")
read_docx() |>
  body_add_flextable(qflextable(data.frame(a = "eé"))) |>
  print(target = "accent_test_bad.docx")
```

When opening the generated file in MS Word for macOS, the accented "é" is displayed using Helvetica instead of Cambria. On Windows, it's Arial.

![image](https://github.com/davidgohel/flextable/assets/2323704/ee2e0d09-7dc6-4cd6-8bb4-503ee9da9e7c)

In LibreOffice it is displayed correctly.

![image](https://github.com/davidgohel/flextable/assets/2323704/051baefd-a0b1-4a1e-9ed8-296a944d26c0)

When typed into RStudio, the "é" is encoded using NFC. However, if it's converted to NFD using `stringi::stri_trans_nfd()`, the problem disappears and the table looks as intended in both Word and LibreOffice:

```R
library(flextable)
library(officer)
set_flextable_defaults(font.family = "Cambria")
read_docx() |>
  body_add_flextable(qflextable(data.frame(a = stringr::stri_trans_nfd("eé")))) |>
  print(target = "accent_test_good.docx")
```

![image](https://github.com/davidgohel/flextable/assets/2323704/b1a85948-baf2-4e3b-b2ef-4ba70f4dce02)

It took us several hours to figure out what's going on there. To spare others the trouble, it would be very helpful if the documentation on `body_add_flextable()` could mention this. Or maybe non-NFD Unicode strings could be converted automatically?

Edit: flextable 0.9.4, Word for Mac 16.78.3, Word for Windows version 2302

**Comment by davidgohel** [comment]
Hello,

See this thread #383 

This can be easily solved by specifying the same font for 'hansi.family' and without using 'stringi' by using `set_flextable_defaults(font.family = "Cambria", hansi.family = "Cambria")`: 

````
library(flextable)
library(officer)
set_flextable_defaults(font.family = "Cambria", hansi.family = "Cambria")
read_docx() |>
  body_add_flextable(qflextable(data.frame(a = "eé"))) |> 
  print(target = "accent_test_bad.docx") 
````

<img width="321" alt="Capture d’écran 2023-12-10 à 21 28 31" src="https://github.com/davidgohel/flextable/assets/4331618/82e5b72e-67da-4f21-8e90-dc98032ee0bc">

I understand it's not easy to guess that `hansi.family` exists but I prefer to follow advice given in the manual of `stringi::stri_trans_nfd()`

> [...] you will rather not use these functions in typical string processing activities [...]

**Comment by uhkeller** [comment]
Thanks a lot for pointing this out, and sorry I missed it. Maybe an additional sentence in the help for `body_help_flextable()` and/or `set_flextable_default()` would be helpful? Then people wouldn't have to guess.

**Comment by davidgohel** [comment]
@uhkeller sure, you're right

**Comment by davidgohel** [comment]
- [ ] highlight the need for a value for `hansi.family` in `set_flextable_default()` and maybe `body_help_flextable()` and other Word related functions
