### ISSUE TITLE
Splitting up a flextable from a flextable object

### ISSUE THREAD

**Issue by phargarten2** [davidgohel/flextable#590]
Thank you for creating the flextable package. I find it great to use in reports and presentations. Situations arise where a flextable that works in a report does not work on a slide because the table is too big. Consider this example:
 
```{r}
library(flextable)
library(magrittr)
ft <- flextable::flextable(
  iris[c(1:8, 50:58), ]
)
ft
```
![image](https://github.com/davidgohel/flextable/assets/17706062/49b546dd-56a2-412a-81d9-a045d71dc94b)

This table would be fine for a report, but on a slide it is way too big.  I would need to split it on different slides.

```{r}
ft %>%
  flextable::set_caption("") %>%   # No captions in presentation
  fontsize(size = 14, part = "all")   #Text needs to be bigger in presentation
```
![image](https://github.com/davidgohel/flextable/assets/17706062/88b6f081-98b9-4302-8bd2-2bcda9915e5a)

Is there a way to split up the flextable (ft), say by Species? Or even specify that I would want the first 8 rows one slide and the last 8 rows on the next? Or, according to  #95,  I would need to do all this in the dataset, like iris, before producing a flextable.

```{r}
flextable::flextable(
  iris[c(1:8), ]
)%>%
  flextable::set_caption("") %>%   # No captions in presentation
  fontsize(size = 14, part = "all")   #Text needs to be bigger in presentation


flextable::flextable(
  iris[c(50:58), ]
)%>%
  flextable::set_caption("") %>%   # No captions in presentation
  fontsize(size = 14, part = "all")   #Text needs to be bigger in presentation
```
![image](https://github.com/davidgohel/flextable/assets/17706062/64ebbc31-b3ad-4960-9555-bce83ae88ab5)
![image](https://github.com/davidgohel/flextable/assets/17706062/4b7220fc-5480-4bbe-a47c-778b8b9c8e58)

===============================================================================
**Not a bug or feature request? If you are looking for help using the 
package correctly, please read the doc first at https://davidgohel.github.io/flextable/. 
You can also visit [Stackoverflow](https://stackoverflow.com/questions/tagged/flextable+r) 
and tag your question with `[flextable]`. We usually read them and answer WHEN possible.**

**Comment by davidgohel** [comment]
For that, you can play with `delete_rows()` and maybe `flextable_dim(ft)` that return the whole width and height or `dim(ft)` that return the widths and the heights.

```
library(flextable)
x <- iris
rownum <- seq_len(nrow(x))
z <- flextable(x) |> autofit()

z1 <- delete_rows(z, i = setdiff(rownum, 1L:40L))
flextable_dim(z1)$heights
z2 <- delete_rows(z, i = setdiff(rownum, 41:80))
flextable_dim(z2)$heights
z3 <- delete_rows(z, i = setdiff(rownum, 81:120))
z4 <- delete_rows(z, i = setdiff(rownum, 121:150))
```

**Comment by phargarten2** [comment]
Thank you, David! The inclusion of `delete_rows()` is a great addition to v. 0.9.4. Even better, I can use the row selectors to delete the rows not needed as well, which totally answers the question. 

```{r}
library(flextable)
x <- iris
rownum <- seq_len(nrow(x))
z <- flextable(x) |> autofit()
delete_rows(ft, ~ Species == "setosa", part = "body")
delete_rows(ft, ~ Species == "versicolor", part = "body")

```
