### ISSUE TITLE
Crossref in table caption not being resolved when using Quarto

### ISSUE THREAD

**Issue by cschwarz-stat-sfu-ca** [davidgohel/flextable#592]
I can use @tbl-tablename or @fig-figname in a figure caption and they are resolved properly.
However, if I try and crossreference in a table caption, it is not resolved.

MWE and output attached

Thanks.
Carl Schwarz

---
title: "test"
author: "Carl James Schwarz"
date: today
date-format: "YYYY-MM-DD"
execute: 
  error: true
format: 
  html:
    toc: true
    number-sections: true
    self-contained: true
  pdf:
    toc: true
    number-sections: true
    fig-pos: ht
  docx:
    toc: true
    number-sections: true
format-links: false
fig-cap-location: top
---

## Cross references in tables and figures

This is a standard xref to @tbl-map-unit-strata which works fine.

```{r}
#| echo: false
#| warning: false
#| message: false

library(ggplot2)

map.unit.stratum.csv <- textConnection(
"Sample..Map.Unit, Stratum
19,	L
18,	M
17,	L
")
map.unit.stratum <- read.csv(map.unit.stratum.csv, header=TRUE, as.is=TRUE, strip.white=TRUE)

```

```{r}
#| echo: false
#| warning: false
#| message: false
#| tbl-cap: "Map unit strata"
#| label: tbl-map-unit-strata

ft <- flextable::flextable(map.unit.stratum)
ft

```

We can reference the table in a caption for a figure as shown below
```{r}
#| echo: false
#| warning: false
#| message: false
#| fig-cap: Reference to @tbl-map-unit-strata in a figure caption works fine.
#| label: figl-map-unit-strata

df <- data.frame(x=1:10, y=1:10)
ggplot(data=df, aes(x=x, y=y))+
   geom_point()


```

The following doesn't seem to work since the cross reference is not resolved in the captions.

```{r}
#| echo: false
#| warning: false
#| message: false
#| tbl-cap: Map unit strata 2 wich references  @tbl-map-unit-strata
#| label: tbl-map-unit-strata2


ft <- flextable::flextable(map.unit.stratum[1:5,])
ft

```

```{r}
#| echo: false
#| warning: false
#| message: false

sessionInfo()
```

[test.pdf](https://github.com/davidgohel/flextable/files/13461557/test.pdf)

**Comment by davidgohel** [comment]
Thanks,

Quarto is managing captions on its own. We can't do anything about the way it manages them. As you can see here https://github.com/davidgohel/flextable/blob/master/R/printers.R#L350 and here https://github.com/davidgohel/flextable/blob/master/R/latex_str.R#L219, there is no code in flextable that manage captions for quarto! 

I think quarto team made improvements with the latest versions of quarto. I have no idea what version of quarto you are using but I recommend updating it regularly as it is in active development.

**Comment by cschwarz-stat-sfu-ca** [comment]
Thanks for your quick reply... I'm running the current release of quarto...
I'll submit this issue to quarto.
Thanks.

Carl.

**Comment by cschwarz-stat-sfu-ca** [comment]
BTW, it is possible to include a crossref in a footnote? If you have @ref
in a string it is not resolved. There must be some settings in the
as_paragraph() that would allow it to be resolved?
Thanks
Carl

**Comment by cschwarz-stat-sfu-ca** [comment]
BTW again... this issue of xref in table captions seems to be fixed in the
development version (pre-release) version of quarto...Next trying to figure
out crossref in footnotes.
Carl
