### ISSUE TITLE
The border style of a cell is not taken into account when exporting to PPT with officer.

### ISSUE THREAD

**Issue by dominiqueemmanuel** [davidgohel/flextable#598]
I have  simple flextable with a border (with `fp_par`) :
```
library(flextable)
library(officer)
d <- data.frame(x=1:2,y=1:2)

myft <- flextable(d) %>% style(i=1,j=1,pr_p = fp_par(
  border =fp_border(color="red"))
  
)
print(myft)
```
It looks fine a Rstudio Viewer (the 1 is bordered with a red line) :
![image](https://github.com/davidgohel/flextable/assets/4983353/efc1c3c8-c6bb-4db3-bfe0-dc4a05baaff3)

But when I want to export in PPT,
```
my_pres <- read_pptx()
my_pres <- add_slide(my_pres,
                     layout = "Two Content", master = "Office Theme"
)
my_pres<-ph_with(my_pres,value=myft,location = ph_location_left())
print(my_pres, target = "test.pptx")
```

the border disappear : 
![image](https://github.com/davidgohel/flextable/assets/4983353/2b936ab5-4ec8-4e56-954d-1303c7f79472)

Is it a bug ?

**Comment by davidgohel** [comment]
Not really (I did not remember I implemented borders for paragraphs). 

There is a dedicated function for your need:

```
library(flextable)
library(officer)
d <- data.frame(x=1:2,y=1:2)

myft <- flextable(d)
myft <- surround(myft, i = 1, j = 1, border = fp_border(color = "red"))
print(myft, preview = "pptx")
```

<img width="505" alt="Capture d’écran 2024-01-18 à 19 34 11" src="https://github.com/davidgohel/flextable/assets/4331618/902d8a05-39e9-497c-aca6-ae806994fa4c">
