### ISSUE TITLE
Width of bottom line theme_booktabs() 

### ISSUE THREAD

**Issue by instantkaffee** [davidgohel/flextable#6]
The code rendering the bottom line in theme_booktabs() needs some correction for cases where columns are merged (see red part, width):

```
flextable(mpg[1:20,]) %>%
  flextable::merge_v(~ manufacturer + model) %>%
  bold(part = "header", bold = T) %>%
  fontsize(part= "body", size = 7) %>%
  autofit() %>%
  theme_booktabs() %>%
  height(part= "body", height = 0.2) 
```

![rplot](https://cloud.githubusercontent.com/assets/3050723/23830583/9cbe6726-070e-11e7-8115-9151ee01b1dc.png)

**Comment by davidgohel** [comment]
Sorry for the delay. It's fixed now. 

From now, functions `hline()` and `vline()` should be preferred to `border()`.
