### ISSUE TITLE
padding(padding=0) not shrinking the cells vertically

### ISSUE THREAD

**Issue by TomasHovorka** [davidgohel/flextable#60]
Hi David,
I am not sure this is a bug, or if just my expectation of the padding() function are wrong.
Following code
```
library(flextable)
library(officer)
ft <- flextable(head(mtcars[,1:3]),cwidth = 0, cheight = 0)
ft<-border_inner_v(ft,fp_border(width = 1))
ft<-fontsize(ft,size=6,part = "all")
ft
```
produces:
![image](https://user-images.githubusercontent.com/15159067/39034006-00932e0e-4475-11e8-8c59-159ad1b78923.png)

when I use 
```
padding(ft,padding=0)
```

It shrinks the table horizontaly but not vertically:
![image](https://user-images.githubusercontent.com/15159067/39034055-3a8dc45c-4475-11e8-9252-a748ab241855.png)
(it shows the same in browser).
I would like also to shrink the table vertically.
Thank you

```
sessionInfo()
```

R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Czech_Czech Republic.1250  LC_CTYPE=Czech_Czech Republic.1250    LC_MONETARY=Czech_Czech Republic.1250 LC_NUMERIC=C                         
[5] LC_TIME=Czech_Czech Republic.1250    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] flextable_0.4.4   officer_0.2.3.101

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16    digest_0.6.15   rprojroot_1.1   R6_2.2.2        backports_1.1.2 magrittr_1.5    evaluate_0.10   zip_1.0.0       stringi_1.1.7  
[10] gdtools_0.1.7   uuid_0.1-2      xml2_1.2.0      rmarkdown_1.9   tools_3.3.1     stringr_1.3.0   base64enc_0.1-3 htmltools_0.3.6 knitr_1.20     
>

**Comment by davidgohel** [comment]
I recommand you to read the documentation here : https://davidgohel.github.io/flextable/articles/overview.html#flextable-keypoints

```
library(flextable)
library(officer)
ft <- flextable(head(mtcars[,1:3]),cwidth = 0, cheight = 0)
ft<-border_inner_v(ft,fp_border(width = 1))
ft<-fontsize(ft,size=6,part = "all")
print(ft, preview = "html")

ft <- padding(ft,padding=0)
print(ft, preview = "html")

print(autofit(ft), preview = "html")
```

**Comment by TomasHovorka** [comment]
Hi David, I was trying to reduce the height of the cells in the above example (I think I understand the documentation in this aspect). I think its not a problem with padding() as it works for bigger fonts and for small fonts it is rendered fine in MS Word. Just the html (also in browser) has some redundant vertical space in the case above, but that might be caused by the way how the html is rendered not that the content would be wrong. Thanks

**Comment by davidgohel** [comment]
maybe an issue with `line-height`... I will keep that in mind for the next devel run :)
