### ISSUE TITLE
[flextable] delete_column print 

### ISSUE THREAD

**Issue by dar143** [davidgohel/flextable#613]
`> ft <- flextable(head(iris))
> ft
> ft <- delete_columns(ft, j = "Species")
> ft
Error in data.frame(col_id = rep(x$col_keys, each = nr), ft_row_id = rep(seq_len(nr),  : 
  arguments imply differing number of rows: 30, 24`

**Comment by davidgohel** [comment]
Update

**Comment by dar143** [comment]
Doh!.  Apologies. Thanks
________________________________
