### ISSUE TITLE
unknown export from flextable: `flextable_to_rmd()` with @importFrom

### ISSUE THREAD

**Issue by TimBMK** [davidgohel/flextable#614]
This is probably just a minor issue, but when importing `flextable_to_rmd()` in function documentations with devtools/roxygen2, such as
`#' @importFrom flextable flextable_to_rmd()`

Calling `devtools::document()` gives the following problem: 
`@importFrom Excluding unknown export from flextable: flextable_to_rmd().`

I'm not sure what's causing this, and in most cases it should not be a problem, but may make it harder to use this particular function in packages down the road.

I'm running flextable v0.9.5 on R 4.2.2 under Ubuntu 20.04.5 LTS

**Comment by davidgohel** [comment]
Hi
Sorry, it should have been written, don't import `flextable_to_rmd` (and not `flextable_to_rmd()`) in your package but prefer posit recommendation: https://ardata-fr.github.io/flextable-book/rendering.html#looping-in-r-mardown-documents

I will add a note to `flextable_to_rmd` and deprecate it if I am not able to substitute its code with something compliant with posit recommendation

**Comment by davidgohel** [comment]
`flextable_to_rmd()` is now using `knit_child()` for safer usage from `for` loops or `if` statements now. It's safier and therefore will not be deprecated :)

**Comment by TimBMK** [comment]
Awesome! Will check downstream compability, but it looks like this is gonna save me from changing the code in my own packages/functions, haha. Thanks for the update and the great package!
