### ISSUE TITLE
Missing Texts in choose.file or choose.dir

### ISSUE THREAD

**Issue by DustInTheWind22** [davidgohel/flextable#626]
Hi,

I just updated R and installed the latest version of the package.

Every time I include Flextable commands (like library(flextable) or flextable::command) in my code, even without running them, and then attempt to open a file using choose.file or any other command that opens the file explorer, I encounter an explorer window with blank text.

However, when I remove the Flextable commands and restart R, the explorer window displays the text properly again.

I would love to get this fixed.

![Unbenannt](https://github.com/davidgohel/flextable/assets/167428730/8ae68270-4fe2-4475-8bc7-b82d961ba08f)

**Comment by davidgohel** [comment]
I am sorry, but there is no reproducible code here. You can update your issue, please follow the guidelines that are written when you open an issue

**Comment by davidgohel** [comment]
To be clear: 


```r
library(flextable)
choose.file()
```

```
> choose.file()
Error in choose.file() : could not find function "choose.file"
```

**Comment by DustInTheWind22** [comment]
Sorry. I just retried it with those simple lines and got the issue again:

setwd(choose.dir(default = getwd(), caption = "Arbeitsverzeichnis"))

flextable::get_flextable_defaults()

flextable::set_flextable_defaults(table.layout = "autofit")

**Comment by davidgohel** [comment]
thanks to @eli-daniels, your issue is more probably due to https://github.com/rstudio/rstudio/issues/13078 than to anything related to flextable
