### ISSUE TITLE
flextable issue after upgrading to R 4.4

### ISSUE THREAD

**Issue by dar143** [davidgohel/flextable#628]
Quarto script has a rendering issue with flextable after I upgraded to R 4.4
Example script below
flextable package is version 0.9.6.007
quarto is version 1.4
R is 4.4 (puppy cup)

`---
title: "Flextable"
format: docx
---

```{r}
#| label: tbl-flextable-example
#| tbl-cap: Problems after updating to 4.4
library(flextable)
cbind(Make = rownames(mtcars), mtcars[, 1:3]) |> flextable() |>
  autofit()

```

**Comment by dar143** [comment]
Sorry eerror is 
processing file: Flextable.qmd
  |...............................               |  67% [tbl-flextable-example]
Quitting from lines  at lines 7-13 [tbl-flextable-example] (Flextable.qmd)
Error in `.make_numeric_version()`:
! invalid non-character version specification 'x' (type: double)
Backtrace:
  1. global .main()
  2. execute(...)
  3. rmarkdown::render(...)
  4. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  5. knitr:::process_file(text, output)
     ...
 26. flextable:::is_in_quarto()
 28. base::Ops.numeric_version(...)
 29. base::as.numeric_version(e1)
 30. base::numeric_version(x)
 31. base::.make_numeric_version(x, strict, .standard_regexps()$valid_numeric_version)
                                                                                                                  
Execution halted

**Comment by davidgohel** [comment]
Try with flextable 0.9.6.008 the latest version

**Comment by dar143** [comment]
[like]  Darnell, Ross (Data61, Dutton ... reacted to your message:
________________________________
