### ISSUE TITLE
flextable not available for webR due to its gdtools/curl dependency

### ISSUE THREAD

**Issue by maek-ies** [davidgohel/flextable#637]
More a question than a bug.

[WebR](https://docs.r-wasm.org/webr/latest/) allows to run R code in the browser without the need for an R server to execute the code. For packages to work in webR they need to be compiled to WebAssembly format, but due to technical limitations this is not possible for some packages (the issue is that opening raw network sockets is not permitted from the WebAssembly sandbox so prominently curl package is affected). I'd love to use flextable for shinylive apps built on webR. 

My question is whether it would be possible (and not time consuming) to create a lightweight version of flextable that would not be dependent on gdtools/curl? If yes, it should be then easy to compile it to wasm and use in webR. If gdtools package is so essential that it is not so easy to do so and it would take a lot work, then feel free to close the issue. While flextable would be my preference, there are alternative table packages that are compiled for webR already (e.g. gt), and they could be used instead.

![2024-06-06_09-51-01](https://github.com/davidgohel/flextable/assets/151060752/63a967b9-2ce9-4e2a-ab3c-6ee9b50b22e9)

**Comment by davidgohel** [comment]
hello,

I know. I don't think it's hard. gdtools has to be updated with a suggest instead of import instructions for curl and maybe gfonts

**Comment by maek-ies** [comment]
Thanks a lot! This is so useful! I checked now and when using "https://davidgohel.r-universe.dev" as repo during flextable installation in webR it works already now.

**Comment by davidgohel** [comment]
it now also works without using r-universe

**Comment by maek-ies** [comment]
Thank you, David!
