### ISSUE TITLE
Having NAs as cell values produces a hard to understand error.

### ISSUE THREAD

**Issue by Dulani** [davidgohel/flextable#64]
@davidgohel This is a very helpful package (and has been needed for a while).  Thanks for your work on it!

Here's the issue I'm experiencing (I think it is a bug, or if not, then a better error message might be helpful).

If you create a data frame with NAs: 
```
     fooTableNA <- data_frame(col1 = letters[1:5], col2 = NA)
     regulartable(fooTableNA)
```
The result is: `Error in rep(value[[k]], length.out = n) : attempt to replicate an object of type 'closure'`

This does not happen if col2 is not NA: 
```
fooTable <- data_frame(col1 = letters[1:5], col2 = 1:5)
regulartable(fooTable)
```
The result is: 
![flextable image](https://user-images.githubusercontent.com/2193516/39715961-eafa37f0-51fc-11e8-8a8e-fe4a585b71a3.png)

Abbreviated sessionInfo():
```
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

other attached packages:
 [1] forcats_0.2.0       stringr_1.2.0       dplyr_0.7.4         purrr_0.2.4         readr_1.1.1        
 [6] tidyr_0.8.0         tibble_1.4.2        ggplot2_2.2.1.9000  tidyverse_1.2.1     flextable_0.4.5.001
```
Other requested answers: 
- Checked the latest version of the package on CRAN: yes (I reinstalled and it occurred with flextable_0.4.3)
- And on GitHub if issue exists with CRAN version): yes (0.4.5.001)
- Searched in the *open* and *closed* issues on the GitHub repository: yes

**Comment by davidgohel** [comment]
@Dulani Many thanks for reporting that.

**Comment by davidgohel** [comment]
This was a bug and should be fixed in the github version, let me know if not and i will reopen the issue.
