### ISSUE TITLE
Different result from the example

### ISSUE THREAD

**Issue by alireza5969** [davidgohel/flextable#642]
The code that you provided for example for footnotes on this [page](https://davidgohel.github.io/flextable/reference/footnote.html) returns a different output than the one that is on the webpage:

```r
ft_3 <- flextable(head(iris))
ft_3 <- autofit(ft_3)
ft_3 <- footnote(
    x = ft_3, i = 1:3, j = 1:3,
    ref_symbols = "a",
    value = as_paragraph("This is footnote one")
)
ft_3
``` 
The output has 3 <sup>**`a`**</sup>s in the footnote:
![image](https://github.com/davidgohel/flextable/assets/57384423/1821bbea-becb-4698-80eb-550f7487bcbc)

I'm not sure why!

**Comment by davidgohel** [comment]
I have the same output. You are probably using an old version or another code (for ex, your table has a black background color)
