### ISSUE TITLE
Unexpected output using set_header_df() in R v3.5

### ISSUE THREAD

**Issue by kstierhoff** [davidgohel/flextable#65]
Hi,
I was running some old code that used flextable::set_header_df(), but it returned a bunch of numeric column headers (indices, I presume) rather than their text values. When I reverted back to an earlier version of R (3.4.3), I got the expected result. Here is a toy example that demonstrates the behavior that I'm getting:

```
library(tidyverse)
library(flextable)

# Make a toy data frame
df <- select(mtcars, mpg, cyl, disp)[1:5, ]
# Make a data frame for the headers
hdr.df <- data.frame("col_keys" = c("mpg","cyl","disp"),
                     "colA" = c("MPG","CYL","DISP"))
# Create the flextable
regulartable(df, col_keys = names(df)) %>%
  set_header_df(mapping = hdr.df, key = "col_keys")
```
The code above generates the following output for me in R v3.5 and flextable v0.4.5.004:

![image](https://user-images.githubusercontent.com/2256746/40379023-f42f8646-5da9-11e8-89c7-0458c82e4f30.png)

Using R v3.4.3 and flextable v0.4.2, I get the following (the expected output):

![good](https://user-images.githubusercontent.com/2256746/40378916-adcbd6dc-5da9-11e8-98e1-92a16fb9432c.PNG)

Worth noting that I recently had some issues installing some R packages, which may have broken my v3.5.0 installation, and I don't have another machine to test on at the moment, but I was hoping you could confirm this behavior and perhaps suggest why it's not working?

Thanks,
Kevin

**Comment by davidgohel** [comment]
Hi, 

This is probably because I drop dplyr dependancy. Before it was using tibble, now data.frame. The `hdr.df` is made only of factor and the flextable display its underlying values. Using `tibble` or adding `stringsAsFactors = FALSE` will solve the issue.

```
library(tidyverse)
library(flextable)

# Make a toy data frame
df <- select(mtcars, mpg, cyl, disp)[1:5, ]
# Make a data frame for the headers
hdr.df <- data.frame("col_keys" = c("mpg","cyl","disp"),
                     "colA" = c("MPG","CYL","DISP"), 
                     stringsAsFactors = FALSE)
# Create the flextable
regulartable(df, col_keys = names(df)) %>%
  set_header_df(mapping = hdr.df, key = "col_keys")
```

**Comment by kstierhoff** [comment]
Hi David,
Yes, that indeed fixes the problem, either using `tibble()` or `data.frame(stringsAsFactors = F).` Thank you for the quick reply. I would not have solved that on my own.
Kevin
