### ISSUE TITLE
Outer Border in SVG Export (flextable 0.9.7.004)

### ISSUE THREAD

**Issue by mbrunner23** [davidgohel/flextable#650]
Hi,

I'm encountering an issue with the flextable package (version 0.9.7.004) when exporting tables to SVG format. Setting the outer border does not apply to all sides of the table.

Below is a reproducible example to demonstrate the issue:

```
library(flextable)
library(officer)

data <- data.frame(
  Header1 = c("A", "B", "C"),
  Header2 = c(1, 2, 3)
)

ft <- flextable(data)

ft <- border_outer(ft, border = fp_border(color = "black", width = 2), part = "all")

save_as_image(x = ft, path = "test_flextable.svg")
```
<img width="408" alt="Screenshot 2024-08-07 at 21 13 17" src="https://github.com/user-attachments/assets/d9b04716-8c27-4fe4-8d70-2ab46ac7b589">

Steps to reproduce:
1. Run the provided code.
2. Open the generated SVG file (test_flextable.svg).
3. Notice that the outer border does not surround the entire table.

**Comment by davidgohel** [comment]
thanks, it should be fixed now
