### ISSUE TITLE
Outer Border with merge_h() in SVG Export (flextable 0.9.7.8)

### ISSUE THREAD

**Issue by mbrunner23** [davidgohel/flextable#658]
Hi,

I'm encountering an issue with the flextable package (version 0.9.7.8) when exporting tables with merged cells to SVG format. If the function merge_h() is used, the outer border does not apply to the right side of the table in the affected rows.

Below is a reproducible example to demonstrate the issue:
```
library(flextable)
library(officer)

data <- data.frame(
  Col1 = c("A", "B", "C"),
  Col2 = c("1", "G", "G"),
  Col3 = c("E", "G", "G")
)

ft <- flextable(data)

ft <- set_header_labels(ft,
                        Col1 = "Header1",
                        Col2 = "Header2",
                        Col3 = "Header2")

ft <- merge_h(ft, i = 1, part = "header")
ft <- merge_h(ft, i = 2, part = "body")

ft <- border_outer(ft, border = fp_border(color = "black", width = 2), part = "all")

save_as_image(x = ft, path = "test_flextable.svg")
```
<img width="487" alt="Screenshot 2024-09-04 at 17 07 13" src="https://github.com/user-attachments/assets/8b923fa3-09f1-407b-92f6-4214b40518f7">

Steps to reproduce:

1. Run the provided code.
2. Open the generated SVG file (test_flextable.svg).
3. Notice that the outer border does not surround the entire table.

**Comment by davidgohel** [comment]
Did you try dev version ?

See https://github.com/davidgohel/flextable/issues/650

**Comment by davidgohel** [comment]
note version 0.9.7.8 never existed

**Comment by mbrunner23** [comment]
I’ve just updated the package to the latest version from GitHub. Now, `packageVersion("flextable")` returns 0.9.7.12. However, the issue still persists with this version.

**Comment by davidgohel** [comment]
ok, I was not aware of `packageVersion()`, it drops the `0`... so you add (to me) `0.9.7.008`, sorry, it's a dev version.

Can you try `fix_border_issues()`: https://davidgohel.github.io/flextable/reference/fix_border_issues.html

It seems it fix your issue. I guess I should drop it and force its execution to all tables.

**Comment by mbrunner23** [comment]
`fix_border_issues()` fixes the issue. Thank you!

**Comment by davidgohel** [comment]
The `fix_border_issues` function should be useless for users now, as it is now called automatically before printing.
