### ISSUE TITLE
bring back shadow-dom for pagedown

### ISSUE THREAD

**Issue by davidgohel** [davidgohel/flextable#666]
And this search lead me to this commit
- https://github.com/davidgohel/flextable/commit/439d93c55339b0d1ff7929fbfa80d470adf75308

I think that **flextable** now always output shadow dom, and #216 still applies because the `ft.shadow` option is not existing anymore in **flextable**  (https://github.com/davidgohel/flextable/commit/439d93c55339b0d1ff7929fbfa80d470adf75308#diff-f0c168982bc3b1afb5f98bd5e0230be9a96126d723db777bfde5b3dfeacf9b00L1012) 

@davidgohel I'll see what I can do in **pagedown** but if there is a way to still not use shadow dom in paged.js context, it would be cool. 

Otherwise, it will need to wait for an update in Paged.js inside pagedown but I am not sure that paged.js really support shadow dom
- https://gitlab.coko.foundation/pagedjs/pagedjs/-/issues/148
- https://gitlab.coko.foundation/pagedjs/pagedjs/-/issues/120

So we may be blocked here. 🤔

_Originally posted by @cderv in https://github.com/rstudio/pagedown/issues/332#issuecomment-2399912716_

**Comment by yihui** [comment]
You are welcome! I'll make a new CRAN release of **pagedown** soon.

**Comment by cderv** [comment]
> the evil 666 issue

😆 I have not seen one... Bring back the shadows for the evil issue 😈

**Comment by yihui** [comment]
FYI **pagedown** 0.21 is on CRAN now.

**Comment by davidgohel** [comment]
Thank you @yihui
