### ISSUE TITLE
flextable creates an image instead of a table in RTF documents produced by R Markdown

### ISSUE THREAD

**Issue by daattali** [davidgohel/flextable#667]
When I create an RTF document with a flextable in it, the table is converted to an image instead of being a table. This has two major drawbacks: (1) if the table has many rows, then the image simply gets cut off at the end of the page, whereas a table would naturally continue on the following page; (2) the resulting table is un-editable

For example, create a `test.Rmd` file with the following content:

````
---
output: word_document
---

```{r}
flextable::flextable(head(cars))
```
````

After knitting this document, you'll get a Word file with a real table in it. But if you replace `word_document` with `rtf_document`, then the resulting output file has an image of a table.

**Comment by davidgohel** [comment]
yes, sorry, there is no plan to implement RTF output for 'R Markdown' (as I don't know exactly how to manipulate the font table and other details - from memory, it's not possible)

**Comment by davidgohel** [comment]
depending on your tables, some can be produced/expressed with 'rtables' or 'tables' and these packages allow you to split the table into many tables that then can be transformed into flextables with `as_flextable()`

**Comment by daattali** [comment]
Those other packges are for specific types of tables - I was using {flextable} because it allows me to display the exact contents of a dataframe easily and with a lot of visual customizations. It's true that RTF is a weird format to write, so I understand if you don't want to support it with "native" tables. Perhaps this could be mentioned somewhere in some documentation.

**Comment by davidgohel** [comment]
I didn't say we don't support RTF, I said:

- we don't support RTF with “R Markdown”. 
- You can generate flextable in RTF documents using the 'officer' package.

-----

As for the documentation, I don't understand what I could add and where. 

1. If you consult the book which is provided as the first URL https://ardata-fr.github.io/flextable-book/ in the suggested help, it's written in the very first chapter.

<img width="852" alt="Capture d’écran 2024-10-19 à 08 28 56" src="https://github.com/user-attachments/assets/65c3ce7e-4b4a-406a-9d5c-25ec90bd2fb9">


2. If you prefer to read the manual, the `flextable()` manual says :
 
<img width="888" alt="Capture d’écran 2024-10-19 à 08 30 22" src="https://github.com/user-attachments/assets/1dd7c0cd-4b9c-4c16-b4ac-c9c00e32e4b5">

3. And the knit_print manual says:

<img width="879" alt="Capture d’écran 2024-10-19 à 08 29 33" src="https://github.com/user-attachments/assets/e9d00b5c-f6b4-4cf8-b6c3-74528fe6ae53">

**Comment by daattali** [comment]
The documentation is clearly very thorough (which is one of the reasons I love using this over other packages)! The only "improvement" I meant is that there is no mention of what happens to RTF in Rmd -- that it gets converted to tables and isn't fully supported. It's true that RTF is not listed as a supported format with Rmd, but because it does work to some extent, it's a bit ambiguous. I thought it would be more clear to state that it has limited support, rather than omit discussing it entirely. But I won't push for this, it was just a comment. You can close this issue if there's no plans to support rtf in rmd.
