### ISSUE TITLE
Unable to load library(flextable) due to systemfonts

### ISSUE THREAD

**Issue by DiqiZeng** [davidgohel/flextable#668]
I successfully install the package but run into issue when loading the package through library(flextable)

Error message: 
> library(flextable) 
Error: package or namespace load failed for ‘flextable’:
 object ‘match_fonts’ is not exported by 'namespace:systemfonts'

I tried 
1. reintsall R studio
2. reinstall systemfonts
3. intall flextable from github source

**Comment by davidgohel** [comment]
I think you should update gdtools

**Comment by DrChar614** [comment]
Greetings...

Upon updating gdtools, I received the same message our peer in the initial comment received regarding 'flextable'. I too can no longer use this phenomenal package. Any insight into how to fix this would be appreciated.  Error message: Error: package or namespace load failed for ‘gdtools’:
 object ‘match_fonts’ is not exported by 'namespace:systemfonts'

**Comment by davidgohel** [comment]
Yes, please try:

````
install.packages("systemfonts")
install.packages("gdtools")
````

**Comment by DrChar614** [comment]
Appreciated...upon attempts to load the flextable package and gdtools, I receive the following errors:

Error: package or namespace load failed for ‘gdtools’:
 object ‘match_fonts’ is not exported by 'namespace:systemfonts'

Error: package or namespace load failed for ‘flextable’:
 object ‘match_fonts’ is not exported by 'namespace:systemfonts'

I am running R version 4.4.2

**Comment by davidgohel** [comment]
Did you follow the instructions I provided ?

**Comment by DrChar614** [comment]
Yes, just as you listed above. Tomorrow I will try this from a different computer and see what results I get. I will follow-up. Your time is appreciated!

**Comment by DiqiZeng** [comment]
> I think you should update gdtools

Thanks! my problem is solved after updating gdtools.
