### ISSUE TITLE
flextable : the use of logical type field 

### ISSUE THREAD

**Issue by FrancoisRidremont** [davidgohel/flextable#67]
Hi,

Trying to convert a dataframe with the flextable function (flextable package), I got an error message from the rbind underlying function. After some tests to fix the issue, it seems that the flextable function does not support the use of "logical type field ". Is it normal or not ? 

The r script and the error message were : 

> library(flextable)
>data=cbind(head(iris),origin=rep(TRUE,6))
>flextable(data)
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match

Thanks a lot,

François

**Comment by davidgohel** [comment]
Thanks for reporting that!

It should be fixed now. Please let me know if not and I will reopen the issue. 

David

**Comment by FrancoisRidremont** [comment]
Dear David,

Thanks a lot for your responsiveness to fix this "bug".

I tried to re-install the flextable package this morning using "_install.packages("flextable")_" , but the package version is the 0.4.4 version on the CRAN Repository. The newest version seems to be the 0.4.5 like seen through the link here after : https://github.com/davidgohel/flextable/commit/74f4ef6bf4b6a7d7eb03af987774066ee02fae32 

How can I have access to this newest version ?

In any case, thanks again for your precious package !

François
