### ISSUE TITLE
Word document created with quarto gives the error that is illegible.

### ISSUE THREAD

**Issue by lvazdela** [davidgohel/flextable#671]
Hi,
after rendering a word document, when opening the created file, a message appears stating thes there is illegible content, when accepting the option to open the file anyway, the file looks fine. 
here is the info session:
[infosesion.txt](https://github.com/user-attachments/files/17782864/infosesion.txt)

Here is the reprex:
[reprex.txt](https://github.com/user-attachments/files/17782950/reprex.txt)

Thanks

**Comment by davidgohel** [comment]
``````
---
title: "reprex"
lang: es
format:
  docx
crossref:
  fig-prefix: Figura
  tbl-prefix: Tabla
  ref-hyperlink: false
echo: FALSE
---


```{r}
#| echo: false
#| include: false

knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

Results in @tbl-cars

```{r}
#| label: tbl-cars
#| tbl-cap: 'Cars'

library(flextable)
flextable(head(cars))
```

``````

**Comment by davidgohel** [comment]
It seems the caption management has an issue when using `label` in the chunk option. I don't have a clear diagnostic.

'flextable' does not manage captions if renderer is 'quarto', I am afraid there is nothing we can do. 

Quarto is in active development and they will probably fix the issue. From a quick search, I think it may be related to https://github.com/quarto-dev/quarto-cli/issues/10587

**Comment by lvazdela** [comment]
Thank you
