### ISSUE TITLE
Unwanted padding when text columns as processed by xtable_to_flextable

### ISSUE THREAD

**Issue by stefanvaldimarsson** [davidgohel/flextable#69]
Let me first say that flextable is a fantastic package. Thank you very much for it.

I ran into one issue. When I knit the following chunk to word, the outcome has several spaces before the "a" in the cell containing "a".

```
df = data.frame(str=c("a", "bbbbbbbbbbb"), num=c(1,2))
xf = xtable(df)
xtable_to_flextable(xf)
```

The cause of the problem seems to be that the vector `c("a", "bbbbbbbbbbb")` is passed to `formatC_with_na` which results in 

```
[1] "          a" "bbbbbbbbbbb"
```

I seem to be able to get around the problem with the following.

```
assignInNamespace("formatC_with_na", function (x, digits, format, na_string, ...)
{
    if (is.character(x)) {
      x
    } else {
      ifelse(is.na(x), na_string, formatC(x, digits = digits, format = format,
        ...))
    }
}, ns="flextable")
```

which prevents character vectors from being padded by formatC.

**Comment by davidgohel** [comment]
Thanks, I can reproduce. Yes it seems something is not working as expected.

Thanks for the function suggestion.

David

**Comment by davidgohel** [comment]
Thanks, it should be fixed in the Github version.
