### ISSUE TITLE
rotation() align=center will not center in merged cells

### ISSUE THREAD

**Issue by caston60** [davidgohel/flextable#70]
I have a regulartable in which I have merged the cells in the first column of the body.
I wish to rotate the text in this merged-cell and center it. I entered the command as:
  yx_table <- flextable::rotate(yx_table, part = "body", j = 1, rotation = "btlr", align = "center")
where the text("Education") is in body[i=1,j=1]
The result (in Word) is:
![image](https://user-images.githubusercontent.com/30416190/41512768-b88ea13e-7254-11e8-9ccd-b4787b9a2f7c.png)
Am I miscoding the parameters?  Or am I asking too much of flextable?

**Comment by caston60** [comment]
Argh!  Those headings are all comments within the R code. And I failed to get that traditional grey background for the code.  Clearly, I have yet to get the hang of this.

**Comment by davidgohel** [comment]
Dear @caston60 

This is not a minimal reproducible example but it works ;)

You need to add an align instruction:

```
yx_table <- rotate(yx_table, part = "body", j = 1, rotation = "btlr", align = "center")
yx_table <- align(yx_table, j = 1, align = "center")
```

---

Not related to your question but here you are looping a lot while it is not necessary. For example this: 

```
for (k in 1:n_col) {
  yx_table <- flextable::vline(yx_table, part="body", j=(2+2*k), border=fp_border(style="solid"))
  yx_table <- flextable::vline(yx_table, part="body", j=(1+2*k), border=fp_border(style="dotted"))
}
```

Can be replaced with:

```
yx_table <- vline(yx_table, part="body", j=(2+2*(1:n_col)), border=fp_border(style="solid"))
yx_table <- vline(yx_table, part="body", j=(1+2*(1:n_col)), border=fp_border(style="dotted"))
```


Also you are not using provided API, instead you are modifying internal values (which is dangerous, I can garantee the API will not change, but internal code may change one day). This:

```
# modify table header
yx_table <- flextable::add_header(yx_table, top=TRUE, "X3" = "Gender")  
yx_table$header$dataset$X1[2] = " "
yx_table$header$dataset$X2[2] = " "
yx_table$header$dataset$X3[2] = "Male"
yx_table$header$dataset$X4[2] = " "
yx_table$header$dataset$X5[2] = "Female"
yx_table$header$dataset$X6[2] = " "
yx_table$header$dataset$X7[1] = "Total"
```

Should be replaced by:

```
yx_table <- add_header(yx_table, top=TRUE, "X3" = "Gender")  
yx_table <- set_header_labels(yx_table, X1 = "", X2 = "", 
  "X3" = "Male", X4 = "", X5 = "Female", X6 = "", X7 = "Total")  
```

---

I like your example, this is a perfect illustration of what flextable is supposed to produce. I will try to find time next week to write this as an example in the doc.

**Comment by caston60** [comment]
Thank you for both the alignment fix and the suggestions for efficient code.  

I am curious; what does the align="center"  parameter in the rotation function do, or why did it not achieve the centering in this case?

An aside: Ideally I would like to rotate the corner percentages by 45 degree so they are diagonal. I suspect it cannot be done because you cannot diagonalize the text in Word but being optimistic I thought I would ask. Any suggestions on how to do this?

Again, thank you for your attention and fix for my centering problem.

**Comment by davidgohel** [comment]
> what does the align="center" parameter in the rotation function do

It is used to control vertical alignment of paragraph within cell. It must be one of "center", "top" or "bottom". 

As you rotated the paragraph within the cell, the horizontal alignment remain the same (right align per default for characters) and has to be changed:

    yx_table <- align(yx_table, j = 1, align = "center")

> Ideally I would like to rotate the corner percentages by 45 degree [...] you cannot diagonalize the text in Word

Exactly, that's the issue. No, unless to create an image containing rotated text but that's lot of work for little gain and it's ugly. 

Note also the rotation in HTML is not perfect (I decided to not spend time on that as it is a navigator issue, waiting for improvments from navigators :)).

**Comment by davidgohel** [comment]
I have updated the doc :)
