### ISSUE TITLE
Tables wrapped into multiple columns in Word do not align properly

### ISSUE THREAD

**Issue by ksnap28** [davidgohel/flextable#71]
I recently updated to the newest version of R/flextable/officer. I'm now having trouble with tables that are added to word docs via body_add_flextable no longer aligning in the document properly. This is only an issue when the table is wrapped across more than one column.

**Here's an example of what I'm trying:**

```
library(flextable)
library(officer)
library(magrittr)
my_df = data.frame(col_a = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
                   col_b = c('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'))
my_tb = regulartable(my_df)
my_doc =
    read_docx() %>%
    body_add_par('One Column Table', style = "centered") %>%
    body_add_flextable(my_tb, align = "center") %>%
    body_add_par('') %>%
    body_add_par('') %>%
    body_add_par('Two Column Table', style = "centered") %>%
    body_end_section_continuous() %>%
    body_add_flextable(my_tb, align = "center") %>%
    body_end_section_columns(widths = rep(1.5, 2),
                             space = .5)
print(my_doc, target = 'test.docx')
```

**Here's my session info:**
```
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
magrittr_1.5    officer_0.3.1   flextable_0.4.4
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] magrittr_1.5    officer_0.3.1   flextable_0.4.4
```

**Comment by davidgohel** [comment]
Hi,

Thanks for the reproducible example.

Is the following code solving your issue? 

```
library(flextable)
library(officer)
library(magrittr)
my_df = data.frame(col_a = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
                   col_b = c('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'))
my_tb = regulartable(my_df)
my_doc =
  read_docx() %>%
  body_end_section_continuous() %>%
  body_add_par('One Column Table', style = "centered") %>%
  body_add_flextable(my_tb, align = "center") %>%
  body_add_par('Two Column Table', style = "centered") %>%
  slip_in_column_break( pos = "before") %>%# before the current paragraph written by the line above
 # slip_in is working on current paragraph and will add a break column at the beginning of it.
 # if pos = "after", the break column will be written at the end of the current paragraph
  body_add_flextable(my_tb, align = "center") %>%
  body_end_section_columns(widths = rep(1.5, 2), space = .5)
print(my_doc, target = 'test.docx')
```

**Comment by ksnap28** [comment]
Hi David,

Thanks so much for your reply. That doesn't quite solve my problem.

I'm generating a report for people who would like one table wrapped in to two columns to save space in their report. This table wrapping portion of my code is working, but the table does not center align in the document. In case it is helpful: I just upgraded from R 3.4.3 / flextable 0.4.3 / officer 0.2.2 where the code was working.

I think my example code may have been confusing (I included the first table to show how the second table should be aligning) - I've updated it to be more clear:
library(flextable)
library(officer)
library(magrittr)
my_df = data.frame(col_a = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
                   col_b = c('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'))
my_tb = regulartable(my_df)
my_doc =
    read_docx() %>%
    body_add_par('Two Column Table', style = "centered") %>%
    body_end_section_continuous() %>%
    body_add_flextable(my_tb, align = "center") %>%
    body_end_section_columns(widths = rep(1.5, 2),
                             space = .5)
print(my_doc, target = 'test.docx')

Thanks again for looking at this!
Katie

**Comment by davidgohel** [comment]
OK, it does not align properly because you defined a section smaller than the page width.

```
library(flextable)
library(officer)
library(magrittr)
my_df = data.frame(col_a = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
                   col_b = c('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'))
my_tb = regulartable(my_df)
my_doc =
  read_docx() %>%
  body_add_par('Two Column Table', style = "centered") %>%
  body_end_section_continuous() %>%
  body_add_flextable(my_tb, align = "center") %>%
  body_end_section_columns(widths = rep(2.9, 2), space = .5)
print(my_doc, target = 'test.docx') %>% browseURL()
```
