### ISSUE TITLE
allow caption in Rmd 

### ISSUE THREAD

**Issue by davidgohel** [davidgohel/flextable#72]
Find a solution to add caption to flextable/regulartable

**Comment by sybrnorox** [comment]
I use the very nice packager `captioner` for this purpose, by simply using it to add a aption in an additional header row. It actually works so well and simple that I do not think an additional mechanism is needed for this.

**Comment by ahmadzai** [comment]
> I use the very nice packag `captioner` for this purpose, by simply using it to add a aption in an additional header row. It actually works so well and simple that I do not think an additional mechanism is needed for this.
> 
> Should you be interested to hear it, I can gladly elaborate on how exactly I use the package.
> 
> Cheers
> Jan

Hi Jan, 

Could you please let me know, how did you add caption to flextable using captioner. 

Thanks in advance, 
Wazir

**Comment by sybrnorox** [comment]
Hi Wazir,

in Captioner you define a function, that  creates a caption string according to your needs including the table number when you call it. [https://cran.r-project.org/web/packages/captioner/vignettes/using_captioner.html](url)

` tab_nums <- captioner::captioner(prefix = "Tab.\\ ", auto_space = FALSE, levels = 2)`

When calling the captioner function, you give the table a unique identifer so later you can call your captioner function again, giving that name, to cite the respective table, with the correct number.

What I simply did, is to write this caption string into the header of a flextable. Works a charm.


 ```
library(dplyr)

  caption <- tab_nums(name = 'table_name', caption = 'This is a table.')

  t <- flextable(df)

  header.df <- data.frame(col_keys = t$col_keys,
                                           caption = rep(caption, (ncol(df)),
                              stringsAsFactors = FALSE)
  
  
  
  t  <- t %>%  set_header_df(mapping = header.df) %>% merge_at(i=1, part='header')

```

Cannot test the code right now. But something like this should work.

Cheers, Jan

**Comment by dmenne** [comment]
Above link is mal-formatted.

https://cran.r-project.org/web/packages/captioner/vignettes/using_captioner.html

**Comment by davidgohel** [comment]
There is now a `set_caption()` function but it will only have an effect when output is HTML. 

For PowerPoint output, there is no such concept available. 

For Word output, you can add captions but not in the table - a Word document is expecting the caption to be a paragraph located not in the table but just before or after the table.
