### ISSUE TITLE
as_image in combination with knitr/rmarkdown results in corrupted docx

### ISSUE THREAD

**Issue by sybrnorox** [davidgohel/flextable#74]
Hi,
so any attempt I have made so far of creating a docx via knitr that includes a image embedded in a flextable via `display()` and `as_image()` results in a corrupted docx.

The tables (including the image) work fine when using `print(table, preview  'docx')` as well as using the RStudio viewer.

Example:

```
df <- data.frame(x_Tst = c(1,2,3,4,5,6,7,8,9),
                 y_fsd = c(11,12,13,14,15,16,17,18,19),
                 z_Fsd = c(1,2,3,4,5,6,7,8,9))

download.file('https://www.r-project.org/logo/Rlogo.svg', destfile = "Rlogo.svg")

t <- flextable(df)

 t <-  display(t, col_key = t$col_keys[3],
                i = 6,
                pattern = "{{test}}",
                formatters = list(test ~ as_image(z_Fsd,
                                                  src = 'Rlogo.svg',
                                                  width = 1,
                                                  height = 1)))
t
```

Cheers

**Comment by davidgohel** [comment]
Hi,

Yes, that's a known limitation. 

This package: https://github.com/davidgohel/worded support that feature. 

Can you test it?

**Comment by sybrnorox** [comment]
I have just tried this. However, the kitting process now fails at 100% with

```
Fehler in rdoc$doc_obj$package_dirname() : 
  Versuch eine Nicht-Funktion anzuwenden
Ruft auf: <Anonymous> -> <Anonymous> -> process_images -> file.path
Ausführung angehalten
```

Sorry I couldn't figure out how to get the error message in english. 

First line ist `Error in...`
Second line is basically saying `Trying to run a non-function`
Third line is `Calling...`
And fourth is `Stopping execution.`

**Comment by sybrnorox** [comment]
Ok, so I was able to make it work after all. The solution seems a little bit hacky to me, but at least now I finally found a reason to use officeR as well :D It only works for PNG, which is ok though. I saw you have another package for svg, haven't looked at it yet though. 

```

library(worded)
library(flextable)
library(officer)
```
```
doc = read_docx('mystyles_numsec.docx')
```
```
df <- data.frame(x_Tst = c(1,2,3,4,5,6,7,8,9),
                 y_fsd = c(11,12,13,14,15,16,17,18,19),
                 z_Fsd = c(1,2,3,4,5,6,7,8,9))

download.file('https://www.r-project.org/logo/Rlogo.png', destfile = "Rlogo.png")

t <- flextable(df)

t <-  display(t, col_key = t$col_keys[3],
                i = 6,
                pattern = "{{test}}",
                formatters = list(test ~ as_image(z_Fsd,
                                                  src = 'Rlogo.png',
                                                  width = 1,
                                                  height = 1)))
```
```
doc = body_add_flextable(doc , t)


print(doc, target = 'temp.docx')
```

and then insert the whole thing into your Rmd by:

`<!---BLOCK_POUR_DOCX{docx_file: 'temp.docx'}--->`

Important note: there needs to be a space between the `docx_file:` flag and the file name. Otherwise knitting will fail.

It doesn't appear to be possible to use `block_pour_docx()` to insert the block from within a code chunk.

Cheers, 
Jan

**Comment by davidgohel** [comment]
Sorry for the delay.

I have updated worded, there was a bug (I could reproduce your issue), sorry for that - I was working on officer in the same time... With the dev version on github, it should work now as expected (you should no more need the trick with `BLOCK_POUR_DOCX`).

Below a slightly modified version of your code. Images location should be available in the original data.frame (I will try to improve that part later):

```
library(flextable)
download.file('https://www.r-project.org/logo/Rlogo.svg', destfile = "Rlogo.svg")
rsvg::rsvg_png("Rlogo.svg", "Rlogo.png")
df <- data.frame(x_Tst = c(1,2,3,4,5,6,7,8,9),
                 y_fsd = c(11,12,13,14,15,16,17,18,19),
                 z_Fsd = c(1,2,3,4,5,6,7,8,9))
df$img <- "Rlogo.png"

t <- flextable(df, col_keys = c("x_Tst", "y_fsd", "z_Fsd"))

t <-  display(t, col_key = "z_Fsd", i = 6, pattern = "{{test}}",
              formatters = list(test ~ as_image(z_Fsd, src = img, width = 1, height = 1)))
t
```

Below my `sessionInfo()` results:

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] fr_FR.UTF-8/fr_FR.UTF-8/fr_FR.UTF-8/C/fr_FR.UTF-8/fr_FR.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] worded_0.0.2.990

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17    digest_0.6.15   rprojroot_1.3-2 R6_2.2.2        backports_1.1.2 magrittr_1.5   
 [7] evaluate_0.11   zip_1.0.0       stringi_1.2.3   uuid_0.1-2      xml2_1.2.0      rmarkdown_1.10 
[13] tools_3.5.1     stringr_1.3.1   officer_0.3.2   yaml_2.1.19     compiler_3.5.1  base64enc_0.1-3
[19] htmltools_0.3.6 knitr_1.20
```

**Comment by sybrnorox** [comment]
I can confirm this is now working with the current dev versions of `worded` and `officer` (the latter appeared to be needed for `worded` compilation).

Many thanks for the quick fix!

Now I just need flextables to stop splitting at page ends ;)

Cheers
