### ISSUE TITLE
Using £ signs in Flextable

### ISSUE THREAD

**Issue by Bozo1979** [davidgohel/flextable#78]
Issues are a great way to keep track of tasks, enhancements, and bugs for your projects (https://guides.github.com/features/issues/). When submitting, you need to provide the following elements:

### If you are reporting a bug:

- [ ] The code that is producing the error, it has to be a minimal reproducible example.
Stackoverflow is providing good explanations about it: https://stackoverflow.com/help/mcve. You can use package `reprex` to help you: http://reprex.tidyverse.org/. The most popular R stackoverflow question is about the subject: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

- [ ] the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example. 

- [ ] you did checked you had the latest version of the package on CRAN (and on github if issue exists with CRAN version).

- [ ] you searched in the *open* and *closed* issues on the github repository.

### If you are asking an enhancement or a new function

Explain the value, describe the situation.

Avoid beeing anonymous, it's not pleasant for me not knowing who talked to me.

Any suggestions to make the documentation better is really appriciated.

### If you are asking a question

Don't, this is not the place where to put questions. If you are looking for help on how to use the package correctly, please visit Stackoverflow and tag your question with `[r]` and `[flextable]`. I usually read them and answer when possible.

**Comment by davidgohel** [comment]
please don't crosspost (https://stackoverflow.com/questions/52313310/adding-%C2%A3-signs-in-r-flextables-without-the-%C3%82) and follow the guidelines (read the text you post :))

KR
David

**Comment by Bozo1979** [comment]
I’ve no idea what crossposting is

On 13 Sep 2018, at 13:10, David Gohel <notifications@github.com<mailto:notifications@github.com>> wrote:


please don't crosspost (https://stackoverflow.com/questions/52313310/adding-%C2%A3-signs-in-r-flextables-without-the-%C3%82) and follow the guidelines (read the text you post :))

KR
David

**Comment by davidgohel** [comment]
https://en.wikipedia.org/wiki/Crossposting

Please describe the issue, provide a reproducible example and `sessionInfo()` result.

**Comment by Bozo1979** [comment]
Ok thanks, duly noted.

Kind regards

Adam

On 13 Sep 2018, at 14:03, David Gohel <notifications@github.com<mailto:notifications@github.com>> wrote:


https://en.wikipedia.org/wiki/Crossposting

Please describe the issue, provide a reproducible example and sessionInfo() result.

**Comment by Bozo1979** [comment]
Sorry just read the description, not sure I did crosspost. It was posted once to one forum and tagged accordingly.

Apologies if I have missed something.


On 13 Sep 2018, at 14:03, David Gohel <notifications@github.com<mailto:notifications@github.com>> wrote:


https://en.wikipedia.org/wiki/Crossposting

Please describe the issue, provide a reproducible example and sessionInfo() result.

**Comment by Bozo1979** [comment]
Apologies, ignore that!

**Comment by davidgohel** [comment]
no problem, I will need to answer also 

https://stackoverflow.com/questions/52264208/how-to-insert-greek-letter-delta-%E2%88%86-into-header-of-flextable-object

It seems closed to your need.
