### ISSUE TITLE
Feature Request: Export docx_str function

### ISSUE THREAD

**Issue by pierre-ange** [davidgohel/flextable#79]
Hi David,

Very cool package, and with the future shipment of pandoc2 into RStudio, I think that it will get even more traction (for inserting flextables into Word documents).

**Would you consider making the docx_str methods available to users, by adding them to the NAMESPACE file (through @export tag)?**

I see for example that the html equivalent, htmltools_value, is exported. But docx_str is not.

I think this would be useful to many. For example, my use case is the following: it is frequent that I need to arrange a couple of flextables inside Word, side-by-side. To do so with rmarkdown, I insert a few openxml commands before, after and possibly in-between the flextable prints (to manage the layout). It becomes very quickly cumbersome, repetitive and prone to errors.
Instead, a better way would be to create a function which would call docx_str(), directly manage the openxml layout commands from user input, and knit_print it. (Kind of a knit_print for grids of flextables). However this would only be possible if docx_str was exported.

Hope this is clear,
Thanks!
Pierre-Ange

**Comment by davidgohel** [comment]
Well exporting that mean provide support for it ;)

as a first answer, I would suggest https://github.com/davidgohel/worded

You can arrange tables within columns of a section and make the comparison easier. Would it be a solution for you?

**Comment by pierre-ange** [comment]
I didn't know about worded, looks great! 
I think that would definitely help indeed :)
Thanks

**Comment by davidgohel** [comment]
Hi @pierre-ange 

I have documented `format.flextable`. It was already exported and I did not think about it when you opened the issue. You can use this function to get the html, pptx and docx code of your flextable objects.

**Comment by pierre-ange** [comment]
Thank you @davidgohel, great!
