### ISSUE TITLE
Feature Request modify columns to currency

### ISSUE THREAD

**Issue by UTexas80** [davidgohel/flextable#80]

**Comment by davidgohel** [comment]
Hi Glen

I am going to make that easier (later)... This is already possible by using `set_formatter`. Below an illustration.

```
library(flextable)
library(magrittr)

ft <- regulartable(iris)

# format function:
fun_ <- function(x) paste0("$", formatC(x, format="f", big.mark=",", digits = 2) )
# columns to be formatted:
colnames_ <- Filter(is.numeric, iris ) %>% names()

# prepare args for `set_formatter` call
sf_args <- rep(c(fun_), length(colnames_)) %>% 
  setNames(colnames_)
sf_args$x <- ft

# call exec
ft <- do.call(set_formatter, sf_args) 

autofit(ft) %>% print()
```

**Comment by UTexas80** [comment]
David,
OMG. Wow. That looks GREAT! Thank you!!!

![image](https://user-images.githubusercontent.com/16102161/45700206-ebe54000-bb39-11e8-907a-bc9b087fd0be.png)
Do you have any suggestions on how to clear those nasty bugger NA's? 
My code
`pdf.tbl[is.na(pdf.tbl)] <- ""`
seems to be ignored.

Also, how do I reference the` autofit(ft) %>% print()` so that it will print in my word doc?

Thanks so much. This is awesome!

Glen

**Comment by UTexas80** [comment]
David - 

Thank you so much for taking the time to provide me with a quick response (My boss appreciates it too 👍 )

The updated table looks perfect.

Have a good one.

Glen

**Comment by davidgohel** [comment]
Hi

I have implemented new functions to make this more easy: `colformat_char`, `colformat_int` and `colformat_num`. 

```
dat <- iris
dat[1:4, 1] <- NA
dat[, 2] <- dat[, 2] * 1000000

ft <- regulartable(dat)
colkeys = c("Sepal.Length", "Sepal.Width",
            "Petal.Length", "Petal.Width")
ft <- colformat_num(
  x = ft, col_keys = colkeys,
  big.mark=",", digits = 2, na_str = "N/A", prefix = "$")
autofit(ft)
```


<img width="501" alt="capture d ecran 2018-10-27 a 15 41 14" src="https://user-images.githubusercontent.com/4331618/47604807-cc75e880-d9fe-11e8-9e6c-1fe62c8faee9.png">
