### ISSUE TITLE
Remove "NA" from Flextable output in MS Word

### ISSUE THREAD

**Issue by sdas1983** [davidgohel/flextable#83]
Hi David,

I am working in creating reports in word format from R in Flextable. Here I am facing a strange issue.

While trying to display the numeric columns in flextable MS Word output, I am getting "NA" in the cells where there is no value or if it is blank.

My original flextable:

![image](https://user-images.githubusercontent.com/12120392/46567703-e880ef80-c954-11e8-8acb-1e31f970af0a.png)

Applying the below R Code:
Here I am trying to remove the ZEROs after decimal and applying the COMMA format.

`my_flextable<- display(my_flextable, 
                                             col_key = "col3",
                                             pattern = "{{col3}}",
                                             formatters = list(col3 ~ format(col3,big.mark=",")))`

Below is the output:
![image](https://user-images.githubusercontent.com/12120392/46567718-44e40f00-c955-11e8-9537-dc12e7bf0a60.png)

How to remove the "NA" from flextable. I want them to remain as blank in the output.
Please help.

Regards,
Sumanta

**Comment by cderv** [comment]
Hello, 

just in case, can you check which version you are using ? 
There is a fix from a related issue with displaying NA from version 0.4.2.3 (see [NEWS](https://github.com/davidgohel/flextable/blob/d1bbbf6729100d06e0b35574911372391148ab99/NEWS#L45))

Also, if you can provide a reproductible example, it will help us help you. Thank you.

**Comment by cderv** [comment]
> format(col3,big.mark=",") 
when using this, `NA` in col3 is converted to character. And I think it is why you have the results with NA
``` r
format(c(26,NA,2010),big.mark=",") 
#> [1] "   26" "   NA" "2,010"
```
If you modify your formatter function to remove NA, it should work. 
```r
display(z1_flextable, col_key = "col3",
        pattern = "{{col3}}",
        formatters = list(col3 ~ ifelse(is.na(col3), "", format(col3,big.mark=",")))
)
```
I am not an expert of flextable and there may be another way. Will see if someone else answer. 
However, for this kind of question, you should ask in Stacktoverflow, as the issue template mentioned, using [[r][flextable] tags](https://stackoverflow.com/questions/tagged/r+flextable). There may already be an answer there.

**Comment by davidgohel** [comment]
The NA can be removed, the code below shows how to : 

```
# This function format data with "" as NA
format_nona <- function(x) {
  ifelse(is.na(x), "", format(x, big.mark = ","))
}

library(flextable)
z1 <- data.frame(Product = c("BF", "Clacium", "Gypsum"), col3 = c(26, NA, 2010))

z1_flextable <- flextable(z1, col_keys = c("Product", "col3"))

z1_flextable <- display(z1_flextable,
  col_key = "col3",
  pattern = "{{col3}}",
  formatters = list(col3 ~ format_nona(col3))
)
z1_flextable
```

<img width="141" alt="capture d ecran 2018-10-06 a 11 56 03" src="https://user-images.githubusercontent.com/4331618/46570057-e1f77580-c95e-11e8-9a7e-c98e21e0284f.png">


Note that using xtable is also an option you can explore:

```
xtable_to_flextable(xtable::xtable(z1), include.rownames = FALSE)
```

<img width="125" alt="capture d ecran 2018-10-06 a 11 56 14" src="https://user-images.githubusercontent.com/4331618/46570061-e7ed5680-c95e-11e8-9602-537e183266a0.png">

**Comment by davidgohel** [comment]
@cderv tohh! we cross flows. We should never: ![](https://media.giphy.com/media/11jGtzDu7Nh89a/giphy.gif). Many thanks for you help!

**Comment by sdas1983** [comment]
Thanks David,

The function works well @davidgohel .

Thanks to Christophe @cderv as well. 

You all are great. Thank you again.

Regards,
Sumanta
