### ISSUE TITLE
flextable for datatable

### ISSUE THREAD

**Issue by overmar** [davidgohel/flextable#86]
Any thoughts on creating a DT_to_flextable set of functions? We needed word documents for work, so I've been working on some helper functions which I could contribute, if they would be useful.

**Comment by davidgohel** [comment]
I try to keep the outputs identical for html, docx and pptx... I never thought about it as it seems to me DT is for interactive usage.

Can you share examples?

**Comment by overmar** [comment]
DT is useful for that, but I also found it was one of the few packages that would allow me to indent columns, so in that case its very similar to xtable, but their structure (containers, formatted values, etc...) are different. Basically its a good deal of code that builds off of your xtable function and applies it to DT objects

**Comment by davidgohel** [comment]
I had to google for *indent columns*. Do you mean you are generating flextable with indented columns?  

If you want me to spend time on integrating something you did, that would be good to show me that thing! Can you share examples?

**Comment by davidgohel** [comment]
Sorry, I am closing that issue for lack of answer.
