### ISSUE TITLE
Request - Add PowerPoint to rendering

### ISSUE THREAD

**Issue by MCM-Math** [davidgohel/flextable#88]
I am wondering if the ability to render flextables in PowerPoint from R Markdown is currently being considered.  It would be very helpful, as R Markdown doesn't generate tables in PowerPoint very well with kable or pander.

**Comment by davidgohel** [comment]
Agree, it's planned but will require `pandoc >= 2.4`

**Comment by davidgohel** [comment]
This has just been implemented. :)

````
---
output: powerpoint_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flextable)
library(magrittr)
library(knitr)
```

## Including flextable

```{r echo=FALSE, ft.top = 2, ft.left = 1}
cars %>% 
  head() %>% 
  regulartable() %>% 
  autofit()
```
````

<img width="1125" alt="capture d ecran 2018-11-22 a 22 38 51" src="https://user-images.githubusercontent.com/4331618/48922513-7c782d80-eea7-11e8-90e2-617f327d2bc7.png">

**Comment by davidgohel** [comment]
> Please make sure to upload this update to the CRAN repository. 

Please test it.

> what version of pandoc does this require specifically?

https://github.com/davidgohel/flextable/issues/88#issuecomment-438664221

**Comment by MCM-Math** [comment]
I tested the version of flextable I have, after updating Pandoc, and I still got the unsupported error.

**Comment by MCM-Math** [comment]
I have the most recent version, as far as RStudio can tell.

**Comment by davidgohel** [comment]
I understand. You need to update the package from github: 

```
devtools::install_github("davidgohel/flextable")
```

You need to install pandoc 2.4 and to configure properly your environment so that Rstudio use the 2.4 version and not the default one. 


If you reporting an error, please show the error. Please read and follow instructions written in the template issue (you deleted them when you created that issue).

**Comment by MCM-Math** [comment]
The github package seems to work, but not the current CRAN version, which is the only version I can access at work (I get access errors trying to install the github version).  Please make sure to update the CRAN version as soon as you are comfortable enough with the newer version.

Side note: When creating a PowerPoint from R Markdown using a reference PowerPoint for formatting, there is a bit of a placement error with where the flextable is placed (I managed to test your code at home, away from work stuff).  Not a major thing, and probably not explicitly an issue with flextable, but I thought I should mention it.

**Comment by MCM-Math** [comment]
Is this latest version ready for CRAN, or is it still being developed?
