### ISSUE TITLE
More accurate merging option

### ISSUE THREAD

**Issue by eusebe** [davidgohel/flextable#9]
Hi, 
I'm playing around with these new functions similar to those of the ReporteRs package. Very, very good job, thanks !

I have a issue with the "merge_v" (and "merge_h") functions. In brief, sometimes, all consecutive cells that have identical values should not be merged together.

I have this use case:

```r
library(flextable)
df <- data.frame(variable = c("A", "A", "B", "B", "C", "C"), value1 = c(1, 2, 3, 4, 5, 6), value2 = c(1, 2, 3, 4, 5, 6), p = c("0.43", "0.43", "<0.01", "<0.01", "<0.01", "<0.01"))
ft <- flextable(df)
merge_v(ft, c("variable", "p"))
```

In the resulting table, all "<0.01" in the last column are merged together (this is expected), but this not corresponds to "structure" of this table. I wish to have the possibility to indicate more precisely which cells should be merged together, so that, in this example, merged cells of the last column would have the same layout than in the first column (maybe I'm not clear here).

David

**Comment by davidgohel** [comment]
You are clear. I already faced similar issues... 

It will be implemented soon.

**Comment by davidgohel** [comment]
You can now use new function `merge_at`.

David
