### ISSUE TITLE
Issues with flextable and dates

### ISSUE THREAD

**Issue by matiasandina** [davidgohel/flextable#90]
I am having problems with `flextable()` and columns of class `Date`. Moreover `regulartable()` seems to be working. I have 2 examples.

```
df <- data.frame(x = 1:3, today = lubridate::today())
df <- dplyr::mutate(df, tomorrow = today + 1)
```
Calling `flextable(df)`  produces an *empty(?)* table

`flextable(df)
`
![image](https://user-images.githubusercontent.com/7494967/49198590-d96d5b00-f361-11e8-8bf1-72ad7d30531c.png)

Calling `regulartable(df)` works as expected.

![image](https://user-images.githubusercontent.com/7494967/49198579-c9ee1200-f361-11e8-9bee-8c604fa5b9b4.png)

A very similar one with my real data, as you can see, I could coerce my dates to character and it would work (`pairing_date` column).

```
dput(df)
structure(list(female_id = c("F112", "F112", "F112"), pairing_date = c("2018-11-26", 
"2018-11-26", "2018-11-26"), separate_date = structure(c(17876, 
17876, 17876), class = "Date")), class = "data.frame", row.names = c(NA, 
-3L))
str(df)
'data.frame':	3 obs. of  3 variables:
 $ female_id    : chr  "F112" "F112" "F112"
 $ pairing_date : chr  "2018-11-26" "2018-11-26" "2018-11-26"
 $ separate_date: Date, format: "2018-12-11" ...
```

Calling `flextable(df)` converts the `Date` column into numbers much like Excel

```
flextable(df)
```
![image](https://user-images.githubusercontent.com/7494967/49198607-eab66780-f361-11e8-9ae4-94c6e6a13507.png)

However, `regulartable(df)` works as expected.

![image](https://user-images.githubusercontent.com/7494967/49198614-f4d86600-f361-11e8-8555-be2baeb1e593.png)

**Comment by davidgohel** [comment]
Thanks for reporting this!

There are two different issues there:

* The first one occurs because of usage of `x`, if you use another variable name, i.e. `xx` it will be ok. I will try to fix that soon
* The second one was a stupid `if-else` issue and should be fixed with the latest commit

**Comment by davidgohel** [comment]
hi, it is fixed now.
