### ISSUE TITLE
Please upload 0.4.7.* to CRAN

### ISSUE THREAD

**Issue by MCM-Math** [davidgohel/flextable#94]
Please upload 0.4.7.* to CRAN.  I am designing R Markdown code for my office, and while I am able to install the GitHub version of this package to my system, there are others who would use my code that would not be able to use the GitHub installation.  I am sure there are others in similar circumstances.

**Comment by qfazille** [comment]
Hello,

Before updating the package to CRAN we have to perform some more tests.
As soon as we will get more time, we will work on that.

But as a workaround for the moment you can do :

1. Clone the project `git clone https://github.com/davidgohel/flextable.git`
2. Build source `devtools::build()`
3. Your collegues can use command `install.packages("flextable_0.4.7.003.tar.gz", type="source", repos=NULL)`

Happy new year !

**Comment by davidgohel** [comment]
We are planning to submit the new version this week.
