### ISSUE TITLE
merge_h no longer works properly after update

### ISSUE THREAD

**Issue by MCM-Math** [davidgohel/flextable#97]
merge_h doesn't seem to do anything in version 0.5.0, when it did in the previous version (4.7.*).  Horizontally adjacent identical cells don't merge.

**Comment by davidgohel** [comment]
Can you provide a reproducible example?

**Comment by MCM-Math** [comment]
I've found a workaround for now (merge_at).  If this becomes an issue later, I'll come back.

**Comment by Cortex85** [comment]
I have the same problem, my code worked before updating. I built in easy example:

library(flextable)
library(dplyr)

column1 <- c("male","female","total")
values1 <- c(1,2,3)
values2 <- c(4,5,9)

df1 <- as.data.frame(cbind(Sex = column1, Sum1 = values1, Sum2 =values2))
df1

flextable(df1) %>% 
  set_header_labels(Sex= "Sex", Sum1= "Sum", Sum2="Sum") %>% 
  merge_h(part="header", i = 1)

**Comment by davidgohel** [comment]
Thanks for providing a reproducible example, it let me understand what the issue was and to to help users.

The data.frame names are `Sum1` and `Sum2`, they are not identical. The old version was containing an issue by comparing the displayed values and not the internal one. 

In your case, I would implement that as : 

```
library(flextable)
library(dplyr)

column1 <- c("male","female","total")
values1 <- c(1,2,3)
values2 <- c(4,5,9)

df1 <- as.data.frame(cbind(Sex = column1, Sum1 = values1, Sum2 =values2))

flextable(df1) %>%
  set_header_labels(Sex= "Sex", Sum1= "Sum") %>%
  merge_at(part="header", i = 1, j = 2:3)
```

Or 

```
flextable(df1) %>%
  set_header_df(data.frame(col_keys = c("Sex", "Sum1", "Sum2"), 
                           disp = c("Sex", "Sum", "Sum"), stringsAsFactors = FALSE
                           )) %>% 
  merge_h(part="header", i = 1) %>% 
  theme_booktabs()
```

But this solution will be better when many columns and header rows.

**Comment by Cortex85** [comment]
Thanks for your quick answer! I prefer the second solution, because I indeed have a lot of header rows. I registered another issue, which worked before the update, but I will open another issue for it.
